### ISSUE TITLE
Spell System Revamp

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1]
Spells could have:

- Level
- Mana Cost
- Cooldown

Example: Escape Teleport
- Level: 4
- Mana Cost: 1
- Cooldown: 180 turns

Level determines Casting Success %. Mana Cost is the Power Cost to cast the spell. Cooldown is the time the caster must wait before he or she can cast the spell again.

**Comment by janne-hmp** [comment]
Done.
