### ISSUE TITLE
Autopickup missiles of wielded (or alternate) missile weapon

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1004]
Maybe also could be extended to thrown weapons if readied.

Is this already possible?

**Comment by janne-hmp** [comment]
Possibly by some autopickup configuration, but it might be possible to make a separate option for autopickup all items that are mergeable with quivered weapon. Not sure if there is already such an option.

**Comment by janne-hmp** [comment]
It seems to work when you put autopickup on, pick_thrown on (by default), and autopickupexceptions are all (.*. seems to work).

**Comment by TommiGustafsson-HMP** [comment]
Does it pickup unknown gray stones, when wielding a sling? It should not. Only flint stones.

**Comment by janne-hmp** [comment]
I changed pick_thrown option so that it also activates autopickup alone, but only for items that you have fired or thrown.
