### ISSUE TITLE
Curses Interface and Status Lines: Auto

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1005]
Create a curses interface option for statuslines, which divides automatically the available vertical space between extra info lines and statuslines in the bottom. This can be used, because we do not know how many vertical lines every user has. The user can still set the minimum number of status lines with `OPTIONS=statuslines:3`, for example.

It can be 

`OPTIONS=autostatuslines`

or something similar. It only works in the curses interface.

We do  not need option to limit the maximum number of statuslines, because the user can turn `autostatuslines` off for that.

I think it would work like this:
- If extra vertical space available is 3 lines, use 1 info text line and 2 status lines
- If 4, use 2 info text lines and 2 status lines
- If 5, use 2 info text lines and 3 status lines
- If 6, use 3 info text lines and 3 status lines
- If 7, use 3 info text lines and 4 status lines
- If 8, use 4 info text lines and 4 status lines
- If 9, use 4 info text lines and 5 status lines
- If 10, use 5 info text lines and 5 status lines
- And so on.
- If 15, use 7 info text lines and 8 status lines
- If 16, use 8 info text lines and 8 status lines
- If 17, use 9 info text lines and 8 status lines
- If 18, use 10 info text lines and 8 status lines
- And so on.

**Comment by janne-hmp** [comment]
Done.
