### ISSUE TITLE
Level 30 skeleton lord does very little damage

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1008]
![image](https://user-images.githubusercontent.com/16661034/80097063-53b00800-8573-11ea-9fe7-eecce9f7eb36.png)

**Comment by TommiGustafsson-HMP** [comment]
This one hits more:

![image](https://user-images.githubusercontent.com/16661034/80097170-85c16a00-8573-11ea-9eb0-a250b1b8a4ea.png)

**Comment by janne-hmp** [comment]
Obsolete.
