### ISSUE TITLE
Primus summonable on Secret Modron Level

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1012]
There should be a Modronite Altar guarded by Modron Secundus. If you defeat him, you can perform a Primus summoning ritual to fight him. So that's optional.

**Comment by janne-hmp** [comment]
Ok, modron level needs to be improved a lot for the patch following 4.0.22e.

**Comment by TommiGustafsson-HMP** [comment]
Maybe there could be 4 smaller bosses:
- Modron Quinton: Keeper of Modron Decahedron (or Dodekahedron)
- Modron Quarton: Keeper of Modron Octahedron
- Modron Tertian: Keeper of Modron Cube
- Modron Secundus: Keeper of Modron Tetrahedron

These four items are needed to perform the ritual to summon Primus.

**Comment by TommiGustafsson-HMP** [comment]
Obsolete
