### ISSUE TITLE
There was only 1 normal dungeon level between medusa and castle

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1016]
Should not there have been some special levels and maze levels with minotaurs? Or is my memory not right?

**Comment by TommiGustafsson-HMP** [comment]
I think some of the missing levels came after entering Gehennom.

**Comment by janne-hmp** [comment]
There is 1/6 chance of the level being normal. There can be even 0 or 1 level between castle and medusa.
