### ISSUE TITLE
Rust Traps do not rust

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1025]
![image](https://user-images.githubusercontent.com/16661034/80281320-f0f57280-8712-11ea-94f3-a699481958df.png)

![image](https://user-images.githubusercontent.com/16661034/80281326-f9e64400-8712-11ea-86ce-24129b069b23.png)

**Comment by TommiGustafsson-HMP** [comment]
Both were rustproof.

**Comment by janne-hmp** [comment]
Ok,  closed.
