### ISSUE TITLE
Dogs grow up in max hit points by every kill

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1027]
What is the system?

**Comment by janne-hmp** [comment]
The system is that the dog gains base hit points equal to 1 ... monster level +1 until it has 8 hit points per level. Then, it levels up (to dog or large dog). So hit points act as some sort of an experience counter for dogs. Alternative would be to set up an experience level system for them.

**Comment by janne-hmp** [comment]
Keeping this so far. Standard NetHack.
