### ISSUE TITLE
Player base to-hit bonus dependant on weapon skill

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1028]
- Unskilled: +1 to hit / 4 levels
- Basic: +1 to hit / 2 levels
- Skilled +3 to hit / 4 levels (+0,75 to hit / level)
- Expert: +1 to hit / level
- Master – Grand Master: +1 to hit/level (capped at this)

**Comment by janne-hmp** [comment]
Done.
