### ISSUE TITLE
Give low level liches summon monsters spell

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1029]
Summon Monsters
Requires Level 8
Summons 1 nasty for Lich (Level 11) 
Summons 1.5 nasties for Demi-Lich (Level 13)
Summons 2 nasties for Master-Lich (Level 17)
Summons 3 nasties for Arch-Lich (Level 25)
Summons 3.5 nasties for Wizard of Yendor (Level 30)

Level 8 – 1 monster
Level 12 – 1d2 (1.5) monsters
Level 16 – 2 monsters
Level 20 – 1d2+1 (2.5) monsters
Level 24 – 1d3+1 (3) monsters
Level 28 – 1d2+2 (3.5) monsters
Level 32 – 1d3+2 (4) monsters (capped)

**Comment by janne-hmp** [comment]
Done, but they got the summon level appropriate monsters spell instead. Summon nasties summons things like ancient dragons.
