### ISSUE TITLE
Balance Monster AC

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1030]
Here's average AC per monster level:

Monster Level | Average AC (50% hit chance)
0 | 8
1 | 6
2 | 4
3 | 2
4 | 0
5 | -2
6 | -4
7 | -6
8 | -8
9 | -10
10 | -12
11 | -14
12 | -16
13 | -18
14 | -20
15 | -21
16 | -22
17 | -23
18 | -24
19 | -25
20 | -26
21 | -27
22 | -28
23 | -29
24 | -30
25 | -30
26 | -30
27 | -30
28 | -31
29 | -31
30 | -31
31 | -31
32 | -32
33 | -32
34 | -32
35 | -32
36 | -33
37 | -33
38 | -33
39 | -33
40 | -34
41 | -34
42 | -34
43 | -34
44 | -35
45 | -35
46 | -35
47 | -35
48 | -35
49 | -35
50 | -35
51 | -35
52 | -36
53 | -36
54 | -36
55 | -36
56 | -36
57 | -36
58 | -36
59 | -36
60 | -37
61 | -37
62 | -37
63 | -37
64 | -37
65 | -37
66 | -37
67 | -37
68 | -38
69 | -38
70 | -38
71 | -38
72 | -38
73 | -38
74 | -38
75 | -38
76 | -39
77 | -39
78 | -39
79 | -39
80 | -39
81 | -39
82 | -39
83 | -39
84 | -40
85 | -40
86 | -40
87 | -40
88 | -40
89 | -40
90 | -40
91 | -40
92 | -41
93 | -41
94 | -41
95 | -41
96 | -41
97 | -41
98 | -41
99 | -41
100 | -42
101 | -42
102 | -42
103 | -42
104 | -42
105 | -42
106 | -42
107 | -42
108 | -43
109 | -43
110 | -43

**Comment by TommiGustafsson-HMP** [comment]
We should also make monster innate AC and AC from armors not stackable, so that if you polymorph into a monster, you do not get double AC, once from monster and once from your equipment, doubling the final AC.

**Comment by TommiGustafsson-HMP** [comment]
Some figures:

### 50% Hit Chances

Unskilled:
- hits AC 0 at 50% at level 10
- hits AC -10 at 50% at level 20
- hits AC -20 at 50% at level 34

Basic:
- hits AC 0 at 50% at level 5
- hits AC -10 at 50% at level 14
- hits AC -20 at 50% at level 24

Skilled
- hits AC 0 at 50% at level 4
- hits AC -10 at 50% at level 10
- hits AC -20 at 50% at level 19
- hits AC -30 at 50% at level 24

Expert
- hits AC 0 at 50% at level 3
- hits AC -10 at 50% at level 8
- hits AC -20 at 50% at level 12
- hits AC -30 at 50% at level 19


### 95% hit chances

Unskilled:
- AC 0: Level 20
- AC -10: Level 34

Basic:
- AC 0: Level 13
- AC -10: Level 22
- AC -20: Level 34

Skilled:
- AC 0: Level 8
- AC -10: Level 16
- AC -20: Level 25
- AC -30: Level 34

Expert:
- AC 0: Level 7
- AC -10: Level 13
- AC -20: Level 19
- AC -30: Level 26

### Conclusions
- AC 0 is safe for basic Level 5, since you hit it with 50% with Basic.
- AC 0 is very safe for basic Level 10 monsters, since you can hit it with 50% with Unskilled.
- AC -10 is safe for basic Level 14 monsters, since you hit it with Basic at 50% and 95% with Skilled.
- AC -10 is very safe for Level 20 monsters, since you can hit it with 50% with Unskilled.
- AC -20 is safe for basic Level 24 monsters, since you hit it with Basic at 50% chance and 95% chance with Skilled.
- AC -20 is very safe for high level boss monsters, since you can hit it with 50% with Unskilled at level 36.
- AC -30 is safe only for special high level boss monsters. Basic can hit them at 50% at level 36, Skilled can hit them at 95% at level 34 and Expert at level 26. Skilled can hit it with 50% at level 24 and expert at level 19.

**Comment by janne-hmp** [comment]
Probably obsolete.
