### ISSUE TITLE
Bare-handed and martial arts effect on to-hit

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1032]
Bare-handed Combat
- Unskilled: +1/4 levels
- Basic:: +1/2 levels
- Skilled: +1/2 levels
- Expert: +3/4 levels

Martial Arts
- Basic: +3/4 levels
- Skilled: +1/level
- Expert: +1/level
- Master: +5/4 levels
- Grand Master: +5/4 levels

Armor or shield reduces these bonuses to Unskilled: +1/4 levels.

**Comment by janne-hmp** [comment]
Done using 1/8 increments: 

Bare-handed Combat
- Unskilled: +1/3 levels
- Basic:: +1/2 levels
- Skilled: +5/8 levels
- Expert: +3/4 levels

Martial Arts
- Basic: +7/8 levels
- Skilled: +1/level
- Expert: +9/8/level
- Master: +5/4 levels
- Grand Master: +11/8 levels
