### ISSUE TITLE
Mummies could be more dangerous

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1034]
Now they are too similar to zombies. I think that they should be considerably more dangerous.

And vampires are then more dangerous than mummies.

**Comment by janne-hmp** [comment]
Mummy rot?

**Comment by TommiGustafsson-HMP** [comment]
Sounds cool. Is it like terminal illness?

**Comment by janne-hmp** [comment]
Similar to AD&D, it stops you from regenerating and, unless you have regeneration, you start losing hit points at a rate of maxhp / 900 per round.

**Comment by janne-hmp** [comment]
Done. They have now a mummy rot attack.
