### ISSUE TITLE
Encounter levels are seriously wrong

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1041]
Current encounter levels do not take into account that the player becomes more proficient on higher levels and therefore low level monsters are easier for him. I made an analysis what is the true encounter level, when the player proficiency is taken into account.

**Monster/Number | 1 | 2 | 3 | 4 | 5 | 6**
Killer Bee | 3 | 3 | 3 | 2 | 2 | 2
Soldier Ant | 9 | 4 | 2 | 2 | 2 | 2
Uruk-Hai | 6 | 6 | 7 | 6 | 7 | 5

We can see that the encounter difficulty actually reduces when there are more monsters. The reason is that the player is at higher level, because the encounter difficulty is calculated to be quite high. It is `SQRT(n)*monster_difficulty` at least. So, it can be very high, so that the game thinks that the encounter is appropriate for, for example, 18th level character. But at that level, the encounter difficulty is 2, which means that it's super easy.

The problem is that when you add monsters to the encounter, you increase the encounter level, which makes the encounter appear later in the game, but at that point player is even more proficient and the encounter is actually easier with an additional monster, not harder.

We need to revise how encounters are generated, since using `monster_difficulty_level` is no good, because it is not a constant but heavily depends on the player level. For example, a single soldier ant is an appropriate challenge for a 7 level player but 4 soldier ants may be only worth of level 9 encounter and 6 soldier ants a level 10 encounter, since the player is more proficient.

Here's an analysis:

**Monster | Number | Difficulty | Multiplier | Total |   | Orig Level | Multiplier**
Soldier Ant | 1 | 7 | 1 | 7 |   | 7,0 | 1,00
Soldier Ant | 2 | 6 | 1,414 | 8,49 |   | 12,73 | 0,67
Soldier Ant | 3 | 5 | 1,732 | 8,66 |   | 15,59 | 0,56
Soldier Ant | 4 | 4 | 2,000 | 8,00 |   | 18,00 | 0,44
Soldier Ant | 5 | 4 | 2,236 | 8,94 |   | 20,12 | 0,44
Soldier Ant | 6 | 4 | 2,449 | 9,80 |   | 22,05 | 0,44

So, the final difficulty levels for soldier ants should be 7, 9 , 9 , 8, 9, 10, which we might put as 7, 9, 9, 9, 10, 10, or so. This can be compared to difficulty levels that are now 7, 13, 16, 18, 20, 22.

This is the reason that all encounters are always too easy in GnollHack.

Very interestingly, the multiplier `new_difficulty_level/old_difficulty_level` for 4+ soldier ants is always 0.44444.

**Comment by TommiGustafsson-HMP** [comment]
Trying to find an exact number for the monster difficulty level is an iterative task. However, I think the following might be a good approximation:

**Encounter min level (one monster can attack at a time):**
`monster_difficulty_level * monster_number^(1/3)`

**Encounter max level (all monsters can attack):**
`monster_difficulty_level * monster_number^(2/3)`

This way, soldier ant encounters at min level, would be:

1: 7,00
2: 9,00
3: 10,00
4: 11,00
5: 12,00
6: 13,00

**Gray dragons at min level:**
Number | Encounter level
1 | 17,00
2 | 21,00
3 | 24,00
4 | 27,00
5 | 29,00
6 | 31,00

**Gray dragons at max level:**
Number | Encounter level
1 | 17,00
2 | 27,00
3 | 35,00
4 | 43,00
5 | 50,00
6 | 56,00

**Comment by TommiGustafsson-HMP** [comment]
An encounter with different types of monsters can be be calculated as follows:

Min Encounter Level:
`(number_of_monster1 x monster1_difficulty_level^3 + number of monster2 x monster2_difficulty_level^3 + ...)^(1/3)`

Max encounter level similarly but with 2/3 and 3/2 powers:
`(number_of_monster1 x monster1_difficulty_level^(3/2) + number of monster2 x monster2_difficulty_level* (3/2) + ... )^(2/3)`

Encounter difficulty levels with 2-7 hitters at a time can probably be approximated by dividing the range of powers 1/3 to 2/3 to 8 points (including the border points). So, the powers would be:

**Number of hitters | Power**
1 | 0,3333
2 | 0,3810
3 | 0,4286
4 | 0,4762
5 | 0,5238
6 | 0,5714
7 | 0,6190
8 | 0,6667

**Comment by janne-hmp** [comment]
Ok, will have a look.

**Comment by janne-hmp** [comment]
Done. No of hitters is limited to the maximum number of monsters in the encounter (then, the encounter difficulty will be at max).
