### ISSUE TITLE
Add to hit and damage information to ')' 

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1042]
With current weapon
- AC, which has 50% hit chance
- AC, which has 95% hit chance
- AC, which has 5% hit chance
- Average total damage (small, large)
- Range, if thrown
- Multishot information 
- Average damage with multishot

**Comment by janne-hmp** [comment]
That's a simple command showing the wielded weapon in the inventory. You cannot add much information to it. Maybe one should use examine instead, or one needs to make a new weapon analysis command.

**Comment by janne-hmp** [comment]
Done. Added this to examine. Shown when the weapon enchantment has been identified.
