### ISSUE TITLE
Missile weapon and missile enchantment bonus to give only 1/2 of normal effect

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1043]
Together they add to normal bonus.

**Comment by janne-hmp** [comment]
How about if launcher gives only to-hit and missile itself only damage bonus?

**Comment by TommiGustafsson-HMP** [comment]
Could work like that too.

**Comment by TommiGustafsson-HMP** [comment]
How about thrown weapons?

I think that daggers would get half of to-hit and damage bonus when thrown and full to-hit and damage bonus, when used in melee.

So, I think it is best to just halve the enchantment effects for ranged weapons.

**Comment by janne-hmp** [comment]
Ok, but in this case +1 bow and +1 arrow give +0 in total, because both are rounded down to 0? You cannot give half values to-hit and bow and arrow plusses are calculated separately.

**Comment by TommiGustafsson-HMP** [comment]
Ok. Sounds ok. So bow needs to be +2 at least.

**Comment by janne-hmp** [comment]
I think it is not a good idea to make +0 and +1 weapons the same, or +2 and +3 weapons.

**Comment by TommiGustafsson-HMP** [comment]
Any idea to solve the problem?

**Comment by janne-hmp** [comment]
Maybe so that +1 arrow gives +0/+1, +2 arrow gives +1/+1, +3 arrow +1/+2, and so on. +1 bow gives +1/+0, +2 bow +1/+1, +3 bow +2/+1, and so on.

**Comment by janne-hmp** [comment]
Done, as per above.
