### ISSUE TITLE
Juiblex is too easy

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1048]
I think he does not do so much damage at all. His hit points are ok, though.

**Comment by janne-hmp** [comment]
Double the speed from 3 to 6, and added the damage of his attacks a little. Increased difficulty from 30 to 40.

**Comment by TommiGustafsson-HMP** [comment]
Juiblex could move at speed 20. Baalzebub too.
