### ISSUE TITLE
Archaeologist starts with too few quarrels

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1049]
Should be 20 or so.

**Comment by janne-hmp** [comment]
Done. Added 5 more normal quarrels, and 6 lightning-enchanted quarrels for emergency. Also changed bullwhip to be +3 and added a wand of petrification (very powerful for emergencies) to starting items.

**Comment by TommiGustafsson-HMP** [comment]
I think wand of digging would be better. It can also be used as a means of escape.
