### ISSUE TITLE
Game feels pretty tough with Tourist or Archaeologist on Hard

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1050]
May be it should feel so, too. But it really does. Dying all the time.

One time to hill orc with potion of paralysis. The other time to cancelled Quantum Mechanic. He could not teleport, but instead killed the character.

**Comment by janne-hmp** [comment]
Archeologist starts now with 6 electrified crossbow bolts and a wand of petrification for emergency.

**Comment by janne-hmp** [comment]
Also, starting weapons are now +3, and leather jacket and Hawaiian T-shirt are now +2. And tourist now starts wand of teleportation, ring of teleport control, and a powerful new golem-like pet called small luggage (white 'm'), which can grow up to medium luggage and large luggage. (From Discworld.)
