### ISSUE TITLE
Weapon to-hit chance could use some colors

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1051]
It could say: "You have [Green]95%[/Green]/[Orange]50%[/Orange]/[Red]5%[/Red] chance to hit AC [Green]5[/Green]/[Orange]-4[/Orange]/[Red]-13[/Red]."

**Comment by janne-hmp** [comment]
Unfortunately, NetHack does not support coloring like that. Status line can be colored by small areas, and menus on a line-by-line basis, but you cannot put select areas in different colors in data windows or menus. Weapon to-hit chance uses a data window.

**Comment by janne-hmp** [comment]
Done on mobile.
