### ISSUE TITLE
Hand crossbow to use strength 13-14.

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1052]
It deals quite small damage. I think it should use strength 13-14 for damage bonuses.

**Comment by janne-hmp** [comment]
Changed damage bonuses to be +3 for hand crossbow (STR 11, up from STR 5), +6 (STR 17) for crossbow, and +9 (STR 19) for heavy crossbow. Repeating crossbows are now at +4 for normal (STR 15) and +7 for heavy (STR 18/50).
