### ISSUE TITLE
Angel is level 11 monster, even though it is very dangerous

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1059]
I think it should be at least level 30 or so. Probably not, but with armors yes.

**Comment by TommiGustafsson-HMP** [comment]
AC -21!!

![image](https://user-images.githubusercontent.com/16661034/80947667-51fb0580-8df9-11ea-901a-8d79e9a41209.png)

**Comment by TommiGustafsson-HMP** [comment]
Because armor stacks: 

![image](https://user-images.githubusercontent.com/16661034/80947749-73f48800-8df9-11ea-8065-675267bbc24d.png)

**Comment by janne-hmp** [comment]
I suppose then we should decide whether the armor should stack, and adjust the level appropriately. It would be odd if wearing armor did not help the angel at all. Maybe the natural AC does not stack with a suit and robe (and perhaps with t-shirt)? Or some other system, like a suit gives just a maximum of -1 AC bonus after accounting for natural AC, or something like that.

**Comment by janne-hmp** [comment]
Fixed. Raised angel levels and armor and natural AC do not stack directly anymore. Armor gives 1/3 of AC on the top of natural AC and natural AC gives 1/3 on the top of armor AC, and a better number of these is chosen.
