### ISSUE TITLE
Angel picks up ammunition and does not do anything

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1061]
If you fire flint stones at an angel, the angel only picks up ammunition until he is dead.

**Comment by janne-hmp** [comment]
My test angel seems to ignore the fired flint stones instead.

**Comment by TommiGustafsson-HMP** [comment]
Angel needs to be a long away in the corridor:

![image](https://user-images.githubusercontent.com/16661034/81001954-24da4180-8e51-11ea-8e2f-9d84e7099626.png)

![image](https://user-images.githubusercontent.com/16661034/81001968-2c014f80-8e51-11ea-9102-49c9fbb7b76a.png)

**Comment by janne-hmp** [comment]
Angel was most likely 9 or more squares away. The threat distance was 8. Increased it to 18 now. Hopefully works better now.
