### ISSUE TITLE
Change "deathly" to "deadly"

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1063]
Deadly is better english. Deathly sounds like an error.

**Comment by janne-hmp** [comment]
It is a real English word, like in Harry Potter and Deathly Hallows. See [deathly](https://www.merriam-webster.com/dictionary/deathly). Deadly means something a bit different.

**Comment by janne-hmp** [comment]
Maybe it could be changed to something. Deathly means ”related to death”.

**Comment by janne-hmp** [comment]
Looks like ”mortiferous” has the right meaning. It means ”brings death”.

**Comment by janne-hmp** [comment]
Changed 'deathly' into 'mortific' which seems to be the shortest special word with the right meaning.

**Comment by janne-hmp** [comment]
Changed this now to "death-magical". Nobody probably knows what "mortific" means.
