### ISSUE TITLE
Garden rooms with bugbears can appear quite early and are very dangerous

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1068]
There can be several angry bugbears.

I think there should be mostly hobgoblins early on.

**Comment by TommiGustafsson-HMP** [comment]
Probably make it so that the difficulty level also has an effect on the difficulty of monsters generated.

**Comment by janne-hmp** [comment]
Fixed. There was actually a bug there.
