### ISSUE TITLE
Guidebooks

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1069]
Add in-game Guidebooks to the game.
- Ranger starts with Guidebook to Ranged Combat.
- Spell-casters start with Guidebook to Spell Casting.
- Tourists start with Guidebook to Photography.

Reading a Guidebook results in a short written tutorial of the specified topic.

They are pretty light, around 0.4 lbs and sell for a few gold pieces.

**Comment by janne-hmp** [comment]
Done in a bit different way through manuals.
