### ISSUE TITLE
New Item: Robe of Blessedness

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#107]
Robe that grants protection from curses of your inventory items.

Cannot be cursed. If Robe of Blessedness is to become cursed, it becomes uncursed instead.

As Blessed, the robe grants 95% protection against curses.
As Uncursed, the robe grants 90% protection against curses.

**Comment by janne-hmp** [comment]
Done, and called Gown of the Archbishops. Gives Curse Resistance (as well as death resistance and drain resistance).
