### ISSUE TITLE
Change priest donation

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1071]
It should be a new chat option: Donate for divine protection. It should always cost 500 x experience level, adjusted by charisma. Other useless donation effects can be removed.

**Comment by TommiGustafsson-HMP** [comment]
Luxidream used Stormbringer to drain himself to level 1 and then donate all money for protection and clairvoicance. So, clairvoiyance could be an option for donation too.

**Comment by janne-hmp** [comment]
Done. Now major donation costs 2500 + 150 per level (divine protection) and minor donation 500 + 25 per level (Clairvoyance). In comparison, enchant armor with smith costs 400 + 25 per level.
