### ISSUE TITLE
Missing Corpse Icon reads Giant Ant in the pickup menu

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1072]
![image](https://user-images.githubusercontent.com/16661034/82648125-e64dd080-9c1f-11ea-8e8e-865556362348.png)

It's also red like being a monster.

**Comment by janne-hmp** [comment]
Fixed. Menu did not support flipped tilse (the corpse was facing right).

**Comment by TommiGustafsson-HMP** [comment]
But it was a gnoll corpse?
