### ISSUE TITLE
Main Tile Marker

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1074]
![image](https://user-images.githubusercontent.com/16661034/82661901-937f1380-9c35-11ea-8e1a-cbaa305ad616.png)

Here is a 16x16 version (it's actually 12x16):
![image](https://user-images.githubusercontent.com/16661034/82661946-af82b500-9c35-11ea-9209-a3c3a0922e15.png)

**Comment by janne-hmp** [comment]
Done.
