### ISSUE TITLE
Teleportation trap is invisible

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1076]
![image](https://user-images.githubusercontent.com/16661034/82730515-04433000-9d09-11ea-859f-901f17c99426.png)

**Comment by TommiGustafsson-HMP** [comment]
Boulder too:
![image](https://user-images.githubusercontent.com/16661034/82730601-9fd4a080-9d09-11ea-97e3-ae7a42ed83e4.png)

**Comment by janne-hmp** [comment]
Fixed
