### ISSUE TITLE
New Spells: Guardian Angel, Angelic Mount, Angelic Army

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#108]
Guardian Angel
Clerical Level 4
Summons a tame angel. Has ((Level of Caster) - 10) % chance of summoning Archon, otherwise Aleax. Lasts 300 turns. Cooldown 300 turns. Has Material Component.

Angelic Mount
Clerical Level 6
Summons a tame Ki-Rin. Lasts 300 turns. Cooldown 300 turns. Has Material Component.

Angelic Army
Clerical Level 9
Summons 2d4 angels. Each angel has 10% chance of being Archon, otherwise Aleax. Angels last for 150 turns. Cooldown 150 turns. Has Material Component.

**Comment by janne-hmp** [comment]
Implemented, with names changed to Divine Mount and Heavenly Army.
