### ISSUE TITLE
List number of used inventory slots / max inventory slots

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1080]
Many variants list these on the first row when viewing the inventory.

xNetHack:
![image](https://user-images.githubusercontent.com/16661034/82749430-dd8d0400-9db1-11ea-94c2-3376e397bb00.png)

This shows in both normal inventory and permanent inventory.

**Comment by janne-hmp** [comment]
Added slots/52 and weight/unencumbered max weight to the title row.
