### ISSUE TITLE
Cursor in GUI could be as clear as in TTY/Curses

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1082]
Especially in minimap view, cursor is not well visible.

This is how it looks like in TTY/Curses:

![image](https://user-images.githubusercontent.com/16661034/83143027-fe2ec400-a0f9-11ea-8d63-6d13aa2aa90b.png)

Maybe change its color to green and add some breadth?

**Comment by janne-hmp** [comment]
The artists can update the bitmaps. The current ones are for test only.

**Comment by TommiGustafsson-HMP** [comment]
This was for the very old cursor, not for the new ones.

**Comment by janne-hmp** [comment]
Ok. Closed due to new cursors.
