### ISSUE TITLE
Add weapon damage to large and small targets to examine

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1083]
![image](https://user-images.githubusercontent.com/16661034/83143417-962cad80-a0fa-11ea-9d03-3a6e361cc881.png)

Now, it does not seem to list them separately.

**Comment by janne-hmp** [comment]
It takes the average of the two.

**Comment by janne-hmp** [comment]
Ok as is.
