### ISSUE TITLE
[From SpliceHack] More info about monsters

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1085]
Maybe something like this?

![image](https://user-images.githubusercontent.com/16661034/83333202-10e6fb80-a2a8-11ea-989e-726d86b7a9d9.png)

![image](https://user-images.githubusercontent.com/16661034/83333213-1a706380-a2a8-11ea-8ed1-180fdbf9f39f.png)

**Comment by janne-hmp** [comment]
Better info in probing already.
