### ISSUE TITLE
[From NetHack 3.7?]Auto-unlock

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1086]
In most new NetHack variants (including SpliceHack):

![image](https://user-images.githubusercontent.com/16661034/83333371-daf64700-a2a8-11ea-9244-c976bb44b606.png)

**Comment by TommiGustafsson-HMP** [comment]
This is also implemented in Dynahack.

**Comment by janne-hmp** [comment]
Done.
