### ISSUE TITLE
[From NetHack Fourk] textunicode tileset

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1091]
Unicode supporting ASCII text tileset.

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp UTF8graphics symset is available in some NetHack variants:

https://nethackwiki.com/wiki/UTF8graphics

For example, Raisse on eu.hardfought.org uses it:
[Raisse.nh343rc.txt](https://github.com/hyvanmielenpelit/GnollHack/files/4818547/Raisse.nh343rc.txt)

There is !cursesgraphics and UTF8graphics options set.

And he can play NetHack 3.4.3 with PuTTY using UTF8 remote character set.

**Comment by janne-hmp** [comment]
Done a long time ago.
