### ISSUE TITLE
Investigate if it is possible to make inventory management easier in GnollHack

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#1096]
It has more worn items than NetHack, and free space to manage non-worn items is less.

**Comment by TommiGustafsson-HMP** [comment]
Probably made easier, if people would learn to use new container commands, such as 'd', 'p', 'm', and 'g'.

**Comment by TommiGustafsson-HMP** [comment]
Probably is ok, since you don't have old blessed scroll of identify.
