### ISSUE TITLE
Blessed potion of enlightenment adds 1 to Int and Wis

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1099]
Should not be too common. I think fountain of power creates potions of enlightenment?

**Comment by TommiGustafsson-HMP** [comment]
Well, I tried it and it did not add any attributes.

**Comment by TommiGustafsson-HMP** [comment]
I think Int and Wis were at maximum already.

**Comment by janne-hmp** [comment]
Closed.
