### ISSUE TITLE
Summoned creatures and their items

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#110]
Summoned creatures should drop all picked up items on death/unsummon or they cannot pick up items at all. For example, Ki-rin would drop all items that it picked up but not its Saddle. They won't drop any generated items, such saddles, weapons, shields, etc. Maybe easiest is to prevent them from picking up any items at all and prevent them from dropping any items on death/unsummon.

**Comment by janne-hmp** [comment]
Done, summoned monsters do not pick up any items, and do not drop any generated items when they vanish.
