### ISSUE TITLE
Object polymorphing could have a maximum number of items it affects

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1107]
Like 1–3 items. A wand of polymorph could still polymorph about 8–24 items with 8 charges.

Mass polypiling is a super strong strategy.

Maybe cursed polymorph could affect 1 item, uncursed 2 items, and blessed 3 items.

**Comment by janne-hmp** [comment]
Done at 1/2/3.
