### ISSUE TITLE
Elemental damage resistances to 50% (from 100%)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1112]
Resistances are 50%. Players can get these.

Immunities are 100%. Monsters can have these. Like Fire Elemental has Fire Immunity.

**Comment by TommiGustafsson-HMP** [comment]
Dragons should have only 50% elemental resistances, since dragon scale mails give 50% resistance as well.

**Comment by janne-hmp** [comment]
Done.
