### ISSUE TITLE
Infernal weapons

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1113]
Late-game weapon-using demons and devils need infernal weapons, with high damage, up to at least 3d12.

Yeenoghu's triple flail can be two-handed, dealing 3 x 3d6.

**Comment by janne-hmp** [comment]
Updated for Yeenoghu

**Comment by janne-hmp** [comment]
Done. Infernal weapons do now 4x normal base damage.
