### ISSUE TITLE
New Spells: Cold-Enchant Item, Fire-Enchant Item, Lightning-Enchant Item, Death-Enchant Item

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#112]
Cold-Enchant Item
Enchantment Level 1
Cold-Enchants an item. Has Material Component.

Fire-Enchant Item
Enchantment Level 2
Fire-Enchants an item. Has Material Component.

Lightning-Enchant Item
Echantment Level 3
Lightning-Echants an item. Has Material Component.

Death-Enchant Item
Enchantment Level 8
Death-Enchants an item. Has Material Component.

**Comment by janne-hmp** [comment]
Done
