### ISSUE TITLE
Remove adjustment of randomly generated monsters

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1120]
On very easy, it is very difficult to get high enough level monsters to sacrifice, making the game harder.

Also, on very hard difficulty, it generates higher level monsters, which give out more experience, making the game easier.

After removal, we should also balance monster generation so that high level monsters can be generated. The highest monster level should be around 36–40, which can be achieved by being 1) level 22 on dungeon level 50 or 2) level 28 on dungeon level 52.

**Comment by janne-hmp** [comment]
Fixed. Now always generates monsters of normal difficulty.
