### ISSUE TITLE
Maximum damage reduction?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1121]
Damage reduction should probably be capped at 1d20 at AC -20. Higher damage reduction values effectively reduce damage to 1 from all attacks. This is to nerf super low AC.

**Comment by janne-hmp** [comment]
So how AC -20 and AC -21 are then different?

**Comment by TommiGustafsson-HMP** [comment]
-21 gives 1d21 random AC.

**Comment by janne-hmp** [comment]
Fixed.
