### ISSUE TITLE
[From Discord] Sentient Pets stepping over cursed items

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1124]
I'm finding that sentient pets (ie, hired bugbears and so on) as well as the Tourist's starting luggage aren't reluctant to step over cursed items.

**Comment by janne-hmp** [comment]
I think pets need to be animals to be reluctant to step on cursed items. But should all pets be reluctant about stepping on cursed items?

**Comment by TommiGustafsson-HMP** [comment]
Yes, because you usually hire low-level monsters for that. Another option is to implement can-detect-curse property for monsters.

**Comment by janne-hmp** [comment]
Fixed.
