### ISSUE TITLE
[From Discord] Spears should not notify you about hitting in melee 

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1126]
Are spears coded as melee weapons? I'm getting the message "you begin bashing monsters with your dwarven spear." Playing as a knight, if that helps.

**Comment by janne-hmp** [comment]
Fixed. Took the spears out of bashing messages, since they have a minimum range of 1. Bashing messages work now also better for two-weapon combat.
