### ISSUE TITLE
You cannot see yourself when invisible

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1131]
![image](https://user-images.githubusercontent.com/16661034/87223584-e7c98880-c386-11ea-80e8-4916eef4d73e.png)

**Comment by janne-hmp** [comment]
There is no cursor, you cannot see yourself in ascii mode either. Suggestions to fix this?

**Comment by TommiGustafsson-HMP** [comment]
Ultima 5 had this kind of a generic invisibility icon:
![image](https://user-images.githubusercontent.com/16661034/87225793-0b48ff00-c398-11ea-9f89-a76438825929.png)
(Source: http://wiki.ultimacodex.com/wiki/File:Ultima_5_-_Tiles-pc.png)

Maybe something like this?

**Comment by janne-hmp** [comment]
Done. Added invisibility cursor in the suggested general style.
