### ISSUE TITLE
You cannot zoom the screen while detecting monsters etc.

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1132]
It aborts.

**Comment by janne-hmp** [comment]
You can use Ctrl+Mouse scroll. That works. But keyboard commands are normal GnollHack commands which cannot be used there.

**Comment by janne-hmp** [comment]
Added auto-zoomout to detection. Should fix the problem mostly. After detection, the zoom reverts back to what it was before.
