### ISSUE TITLE
Increase number of riding attempts, reduce fumble damage

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#114]
Increase the number of riding attempts to 50 (from 5) before the mount goes wild. (This does not apply to knights; they can already mount unlimited times.)

Decrease riding fumble damage to 1d8+1 from 1d6+9.

**Comment by janne-hmp** [comment]
Done. P_RIDING expert has also unlimited times, others have 50 (unskilled), 100 (basic) or 250 (skilled) times to try.
