### ISSUE TITLE
New potions

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1161]
- Potion of Fire Immunity
- Potion of Heroism (double damage)
- Potion of Super Heroism (quad damage)
- Potion of Titan Strength
- Potion of Greater Speed (36 move, 120 turns)
- Potion of Lightning Speed (48 move, 120 turns)
- Potion of Lesser Regeneration (Regenerates 10 hp/round for 45 rounds)
- Potion of Regeneration (Regenerates 20 hp/round for 45 rounds)
- Potion of Greater Regeneration (Regenerates 40 hp/round for 45 rounds)
- Potion of Lesser Rejuvenation (Regenerates 5 hp + 5 mana/round for 45 rounds)
- Potion of Rejuvenation (Regenerates 10 hp + 10 mana/round for 45 rounds)
- Potion of Greater Rejuvenation (Regenerates 20 hp + 20 mana/round for 45 rounds)

Old Potions Improved
- Potion of Speed (24 move, 120 turns)
- Potion of Healing (12d6 healing)
- Potion of Extra Healing (24d6 healing)
- Potion of Greater Healing (48d6 healing)
- Potion of Full Healing (800 HPs)

**Comment by janne-hmp** [comment]
Done.
