### ISSUE TITLE
New Item: Ring of Kings +X, plus some other rings

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#117]
Ring of Kings +X
Adds +X to all ability scores. X is 1d2.
Enchantment can be altered by charging.

Ring of Gain Dexterity +X
Adds +X to dexterity. X is 1d5.
Enchantment can be altered by charging.

Ring of Gain Intelligence +X
Adds +X to intelligence. X is 1d5.
Enchantment can be altered by charging.

Ring of Gain Wisdom +X
Adds +X to wisdom. X is 1d5.
Enchantment can be altered by charging.

Ring of Gain Charisma +X
Adds +X to charisma. X is 1d5.
Enchantment can be altered by charging.

Also, balance rings of gain strength and constitution likewise.

**Comment by janne-hmp** [comment]
Done. The all-attributes-ring is call Ring of Power.
