### ISSUE TITLE
Master and Grand Master skill levels for classes without magic skills

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1179]
Master: 4 skill lots, 50% chance of critical strike = 2x damage.
Grand Master: 5 skill lots, 50% chance of of critical strike = 4x damage.

**Comment by TommiGustafsson-HMP** [comment]
Or it could be Master 40% chance of 2x damage (= average 140% damage)
And Grand Master 50% chance of 3x damage (= average 200% damage)

**Comment by TommiGustafsson-HMP** [comment]
Or the critical strike chance could be 1%/5%/10%/20%/40%/80% per skill level (starting from unskilled).

**Comment by janne-hmp** [comment]
Done.
