### ISSUE TITLE
Extrinsic fire resistance etc. could be 75%

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1183]
It could be called greater fire resistance.

For example, ring of fire resistance could grant it.

**Comment by janne-hmp** [comment]
How about weak fire resistance => 50%, strong fire resistance => 75%, full fire resistance => 100%? Fire immunity will be full fire resistance.

**Comment by janne-hmp** [comment]
Done.
