### ISSUE TITLE
Set level-based to-hit bonus to 0.5 per level for players on all skill levels

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1184]
It was too hard to balance to-hit on high levels, if it was different.

Monsters can have 1 per level as they do not have skills and many don't have weapons.

**Comment by TommiGustafsson-HMP** [comment]
Or it might be as low as 0-0.33, if we do not increase monster AC. However, increasing monster AC might be ok that monsters and players had similar ACs. Now a high level character can have -40 AC.

**Comment by janne-hmp** [comment]
Done.
