### ISSUE TITLE
Fit to screen: Ctrl-0, and Reset to 1x Zoom: Ctrl-1

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1197]
It seems that many programs have:

- Ctrl-1: Reset to 1x Zoom
- Ctrl-0: Fit to screen

We could use these in GnollHackW as well.

**Comment by janne-hmp** [comment]
Done. Also Ctrl-+ is zoom in and Ctrl-- is zoom out. Alternatively, you can still use Alt-. Alt-, Alt-+ and Alt-- just in case.
