### ISSUE TITLE
Cancellation to affect for 2d4 turns

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1200]
Cancellation should last for 2d4 turns on a target.

It does not affect items in inventory, except if you zap a wand of cancellation at yourself.

Beholders could also cancel you for 2d4 turns.

There is 10 round immunity to further cancellations (counted at the start of cancellation, so the minimum is 2 rounds of non-cancellation).

There is no saving throw for cancellation. Reflection does not help (as it does not help against Umber Hulk) nor does magic resistance.

Works the same way for monsters and players alike.

**Comment by janne-hmp** [comment]
Done.
