### ISSUE TITLE
Gnome lord escapes upstairs but is nowhere to be seen

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1204]
![image](https://user-images.githubusercontent.com/16661034/90315822-1e1a9a80-df27-11ea-94f4-b3564bdb0223.png)

**Comment by janne-hmp** [comment]
Fixed. This was a bug especially occurring in gnomish mines (a very big room)., as there was no distance limitation within the room.
