### ISSUE TITLE
The game crashes when you try to view a corpse in the '/' view, which does not exist anymore but is still known and marked on the map

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1211]
[tommi-wizard.zip](https://github.com/hyvanmielenpelit/GnollHack/files/5082713/tommi-wizard.zip)

The saved game attached. When you move the look cursor right and look at all the corpses, it will crash at one of them.

**Comment by janne-hmp** [comment]
Potentially fixed. It did not check memory objects. However, not sure why it crashed. It should have generated a fakeobj if it didn't find anything.

**Comment by janne-hmp** [comment]
Fixed the root problem.
