### ISSUE TITLE
Orb of Detection in GnollHack is different than in NetHack

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1212]
![image](https://user-images.githubusercontent.com/16661034/90411733-e04b7c80-e0b4-11ea-9139-f63738eba584.png)

https://nethackwiki.com/wiki/The_Orb_of_Detection

GnollHack version confers searching, which is more or less useless, because archeologist gets searching from role.
It also misses magic resistance, which is very useful.
Toggleable invisibility is also gone, replaced with monster detection, which is useless, because Crystal Ball can anyways be used for monster detection.
Also, half spell damage is gone, which would be quite useful some times.

GnollHack version confers Clairvoyance, which is somewhat useful.

**Comment by janne-hmp** [comment]
Fixed back to original.
