### ISSUE TITLE
Charisma has too big effect on service costs

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1215]
![image](https://user-images.githubusercontent.com/16661034/90486891-55b15e80-e142-11ea-845f-653dd252ffff.png)

Cha 24, armor enchantment 189 gold.

I think charisma effect could be halved or so.

**Comment by TommiGustafsson-HMP** [comment]
I think Enchant Armor/Weapon on XL 18: 
- Cha 25 should cost something like 1000 gold.
- Charisma 18 could be like 1500 gold
- Charisma 11 could be 2250 gold
- Charisma 4 could be 3375 gold.

**Comment by janne-hmp** [comment]
Done.
