### ISSUE TITLE
MC 38!

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1216]
![image](https://user-images.githubusercontent.com/16661034/90487246-e0925900-e142-11ea-8cba-983f81fef3cb.png)

No innate protection yet. So, MC40 is very easy to achieve.

Also, in my version (18, not newest) smith services are all the way too cheap.

**Comment by TommiGustafsson-HMP** [comment]
So, there are a few ways to deal with it:
- Reduce max protection to 98%, so it would not be a super-immunity
- Give higher level monsters up to -30 to MC
- Raise max level of MC to 30 or so.

**Comment by TommiGustafsson-HMP** [comment]
Perhaps it is enough to reduce max protection to 98% at MC 25. So the level formula would be:


MC | %
0 | 0
1 | 10
2 | 20
3 | 30
4 | 40
5 | 50
6 | 55
7 | 60
8 | 65
9 | 70
10 | 75
11 | 78
12 | 80
13 | 82
14 | 84
15 | 86
16 | 88
17 | 90
18 | 91
19 | 92
20 | 93
21 | 94
22 | 95
23 | 96
24 | 97
25 | 98

**Comment by janne-hmp** [comment]
Probably fixed due to fixing a bug that gave MC equal to enchantment / 2 instead of enchantment / 3.
