### ISSUE TITLE
Enchanting a group of items to take more than one charge / casting for big groups

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#122]
Cold/lightning/fire/death enchanting a group of items should take 1 charge of a wand for each 5 items in the group. Similarly, 1 casting of a spell for each 5 items in the group. This would prevent abuse like death-enchanting 200 arrows with one charge.

**Comment by janne-hmp** [comment]
Done. One charge enchants only a small number of items.
