### ISSUE TITLE
How do you find traps in chests?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1225]
Search did not do it...

**Comment by TommiGustafsson-HMP** [comment]
https://nethackwiki.com/wiki/Container_trap

Seems to be #untrap. Maybe also search could work?

**Comment by TommiGustafsson-HMP** [comment]
> If a trap exists on a container, the chance of actually finding it is 10/(31 − Xlvl).

@janne-hmp This will probably throw division by zero on level 31.

**Comment by janne-hmp** [comment]
Not really, it was 10/(MAXULEVEL +1 - Xlvl). I changed it now to (MAXULEVEL/3)/(MAXULEVEL + 1- Xlvl).
