### ISSUE TITLE
New Monsters: High Level Mummies

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1228]
Mummy Pharaoh (named, such as Tutankhamon, MC-15 on Mummy Rot)
Mummy Priest/Priestess (MC -8 on Mummy Rot, casts clerical spells)
Mummy High Priest/Priestess (casts clerical spells, can cast Touch of Death, named, MC-12 on Mummy Rot)
Mummy Lord (MC-10 on Mummy Rot)

**Comment by janne-hmp** [comment]
Done.
