### ISSUE TITLE
To Hit AC:s are pretty low 

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1229]
![image](https://user-images.githubusercontent.com/16661034/90665485-c3e64600-e254-11ea-8adb-22b602d0602a.png)

With +20 Kusanagi and XL 28, Swords skilled:
-38 AC: 50%
-29 AC: 95%

Hmm...

1) Maybe per level attack bonus (+14) could be removed:
-24 AC: 50%
-15 AC: 95%

2) Or reduced to +1 / 4 levels
-31 AC: 50%
-22 AC: 95%

We need to remember that no monster has very low AC at the moment.

**Comment by janne-hmp** [comment]
Changed to 1/4 per level.
