### ISSUE TITLE
New alliance aspect: Controlled

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#125]
"Controlled" would be the same as conjured/summoned/animated. This would replace "tamed" for summoned and animated monsters.

**Comment by janne-hmp** [comment]
issummoned flag is used for making sure summoned (timed) monsters do not pick up anything, but it does not do anything else.

**Comment by TommiGustafsson-HMP** [comment]
Not impelemented.
