### ISSUE TITLE
Need some more items to enchant weapon and armor

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1253]
You need about 60x enchant weapon
- 21x for main two-handed weapon
- 6x for bow
- 6x for arrows
- 21x for polearm
- Total: 54 Enchant Weapon

You need about 28 enchant armor, 4 for each slot.

Total 82 Enchants.
Smith can probably do 25 or so.
So that's down to 57.

One possibility is to make a stash somewhere with 10 enchant weapon/armor scrolls. Or make a wand that has 5–8 charges of enchantments.

Also, Demon lords could drop huge amount of cash, with which you could enchant your weapons more. How about 8000–16000 gold per demon lord? That would be 4–8 enchantments if one costs about 2000 gold at smith. Or it could be in a box in their room, protected by the Gilthoniel rune word.

**Comment by janne-hmp** [comment]
Done. Demon lords have chests now with a new power word Morgoth underneath them.
