### ISSUE TITLE
When there are items in a pile, the game reports the dog stepping reluctantly on a wrong item

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1254]
![image](https://user-images.githubusercontent.com/16661034/92114209-23b62280-edf9-11ea-9c67-2ee3d4ffd0f9.png)

**Comment by janne-hmp** [comment]
Fixed. This was intended behavior in NetHack (the top pile item was reported), but now the game reports always the right item.
