### ISSUE TITLE
Two-weapon combat skill could cost 1/1/2/2/3 per level

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1255]
So, that's 9 points total.

> When fighting with two weapons, your effective two-weapon skill level for each hand is the lesser of your two-weapon combat skill level and the relevant weapon skill level.

> Because the two-weapon to-hit bonus and damage bonus calculations always use the lesser of the two-weapon combat skill level and the appropriate weapon skill level, there is no point raising your two-weapon skill higher than those of the weapons you actually intend to use.

If would understand this so that the weapon skill is limited to the two-weapon skill level. Thus, to fight with two weapons at Grand Master Level costs 15 skill points in the weapon skill (if both are of the same type) and then 9 points in Two-weaponing (total 24 skill points).

**Comment by janne-hmp** [comment]
Done.
