### ISSUE TITLE
If you use '/' + '/' and mouse click on an altar, the more info is pretty useless

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1260]
![image](https://user-images.githubusercontent.com/16661034/92359606-392a9580-f0f4-11ea-9f0a-67352cc3df0a.png)

The same probably goes to other things, as well.

**Comment by janne-hmp** [comment]
Most such info is useless in NetHack.

**Comment by janne-hmp** [comment]
This is the same as normal extra info. Closed.
