### ISSUE TITLE
Chosen Font is not monospace

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1266]
![image](https://user-images.githubusercontent.com/16661034/92693871-e13b9b00-f34e-11ea-8427-98e5d209fc1b.png)

**Comment by janne-hmp** [comment]
Yes, maybe have to find a better one.

**Comment by TommiGustafsson-HMP** [comment]
How about Fantasque Sans Mono:
https://github.com/belluzj/fantasque-sans/releases/tag/v1.8.0

Normal:
![image](https://user-images.githubusercontent.com/16661034/93071580-f8e58d00-f688-11ea-9082-afffdef4ae74.png)

NoLoopK:
![image](https://user-images.githubusercontent.com/16661034/93071637-0c90f380-f689-11ea-9a2f-e2f5ea91eac3.png)

I think the NoLoopK looks better.  Here's a pic of it in action (16pt):
![image](https://user-images.githubusercontent.com/16661034/93071970-78735c00-f689-11ea-9afb-5fec942fbef0.png)

**Comment by TommiGustafsson-HMP** [comment]
The original font seems to be monospace, but the problem is probably with the skills window.

**Comment by janne-hmp** [comment]
Changed this so that bolded texts should now be aligned properly.
