### ISSUE TITLE
I got extra CON but HP did not increase

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1268]
![image](https://user-images.githubusercontent.com/16661034/92699008-bdc81e80-f355-11ea-986d-6a6a63c4aa1b.png)

It stayed at 101.

Second time it worked.

![image](https://user-images.githubusercontent.com/16661034/92699436-3f1fb100-f356-11ea-9f22-14512b3c51e8.png)

I had a shuddering from polymorph earlier. Would that be the cause?

**Comment by TommiGustafsson-HMP** [comment]
Probably HP comes only each other CON point?

![image](https://user-images.githubusercontent.com/16661034/92699705-97ef4980-f356-11ea-9d61-6e6d8ecaa98a.png)

**Comment by janne-hmp** [comment]
Yes. The formula is max(-2, (min(25, con) - 7) / 2). Should HP be increased at every CON-point?

**Comment by TommiGustafsson-HMP** [comment]
Not necessarily. But I expected to get more hp when I got more Con.

**Comment by janne-hmp** [comment]
Changed the per-level bonus to double, so you will now benefit from fractionals.
