### ISSUE TITLE
New monster: Phase Spider + configure amounts of thread of spider silk 

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#127]
Phase Spider
- a nasty poisonous spider that appears in the end game
- drops 1d6+2 threads of spider silk on death
- presented by light blue s

Giant Spider drops 1d4+1 threads of spider silk on death

Cave Spider drops 1d2 threads of spider silk on death

**Comment by janne-hmp** [comment]
Done
