### ISSUE TITLE
Exceptional and elite weapons

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1279]
Exceptional: Double Base Damage
Elite: Triple Base Damage
Celestial/?/Infernal?: Quadruple Base Damage (aligned to Lawful/Neutral/Chaotic)

This property can be on all weapons, including special weapons, such as sword of wounding.

Artifacts might be excluded.

**Comment by TommiGustafsson-HMP** [comment]
Chance of appearing:
- Celestial, etc: 2%
- Elite: 7%
- Exceptional: 21%

Celestial etc. weapons blast you like artifacts. They cannot be used by a character of wrong alignment.

**Comment by janne-hmp** [comment]
Done.
