### ISSUE TITLE
Wishes for exceptional and elite weapons

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1282]
Celestial etc. weapons have a 75% chance of becoming normal instead, when wished for. 

Elite weapon wishes have a 20% chance to become normal instead.

Exceptional weapon wishes have a 0% chance to become normal (wish is always 100% successful).

If the fail happens, there should be some comment about it, so that the player understands that it was too difficult a wish.

**Comment by janne-hmp** [comment]
Fixed, but a proper message is difficult to implement.
