### ISSUE TITLE
Balancing ranged weapons

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1283]
1. Ranged weapons could get the same damage to-hit and to-damage bonus from DEX as melee weapons get from STR.

2. Ranged classes should be balanced to have high DEX. Now, they may have 10 or so. Also, half-ranged classes could have DEX of 14-15 or so.

3. Thrown weapons would use the average of STR and DEX for determining the to-hit and to-damage bonus.

4. Add items that give you high DEX, as there are items that give you high STR. There could be a special bow that gives you DEX 19 when wielded, for example.

5. Bracers of Archery could give you +3/+3 to ranged damage when +0. Each additional + would give you +1/+1. So, it would be really good from ranged combat.

**Comment by janne-hmp** [comment]
The system is already quite complicated. Here's what's been done:
1. Melee got both STR and DEX bonuses to hit, while ranged only DEX. Now ranged gets double normal DEX bonus to hit. Damage STR bonuses are as before. DEX does not give more damage at the moment, but STR does similar to melee weapons.
2. Added DEX to Archeologist, Ranger, and Rogue.
3. Both use double normal DEX bonus to hit. Thrown uses half STR bonus to damage and fired full STR bonus to damage.
4. Added Galadhrim bow (DEX 19) and Galadhrim boots (DEX 20 + enchantment), both elven items.
5. Done, up from +2/+2.
