### ISSUE TITLE
New missile weapon enchantment system 

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1284]
We could return missile weapon enchantments to be normal, so +1/+1 per enchantment, but limit them by max enchantment. That would be clearer.

- Arrows and other missiles: max +5
- Two-handed launchers, such as bow: max +7
- Single-handed launchers, such as sling: max +5
- Thrown weapons, such as darts: max +10
- Daggers and other single-handed melee/thrown weapons: max +10
- Two-handed melee/thrown weapons, if any: max +15

**Comment by janne-hmp** [comment]
Done.
