### ISSUE TITLE
FIreball and other AoE spells to use only directions like rays

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#129]
No more targeting by cursor. Use targeting by direction (N,W,E,S,NW,NE,SW,SE). Hits the first target and then explodes.

Can hit walls?

**Comment by janne-hmp** [comment]
Done. It was already implemented but not used in NetHack, so just required reactivation. Stinking Cloud is now the only "targeted" spell.
