### ISSUE TITLE
Giants standing over a boulder are not visible

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1295]
If the boulder and giant are in the same square.

**Comment by janne-hmp** [comment]
Most monster currently appear under the boulder. Should some monsters like giants, or monsters in general, appear on the top of the boulders?

**Comment by TommiGustafsson-HMP** [comment]
The problem is that giants can enter boulder squares and attack you. Now you do not know when a giant is in the boulder square.

**Comment by janne-hmp** [comment]
Fixed now so that only the square where you are is showing boulders on the top and monsters appear on the top of boulders.
