### ISSUE TITLE
Can dwarven geologists appear in dungeon?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1299]
They should, at least 1 or 2 times, I was able to get all money from one in Mine Town.

**Comment by janne-hmp** [comment]
Yes, each level has c. 16% probability to have an NPC, and there is 50% chance it is a geologist. Orcus town also has a geologist.

**Comment by janne-hmp** [comment]
Ok for the time being.
