### ISSUE TITLE
Limit level of random G's and h's in Gnomish Mines?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#130]
Now, it is possible that in the mines it appears:
- mind flayer (h)
- master mind flayer (h)
- flind (G)
- flindlord (G)

Should be limited perhaps? They are out of difficulty for early players.

**Comment by TommiGustafsson-HMP** [comment]
Just played a game and a flind was instadeath.

**Comment by janne-hmp** [comment]
Gnomes moved to 'g', so only gnomes, gremlins, and gargoyles will generate. In addition, in mines, the appearance of mind flayers and winged gargoyles has been restricted.

**Comment by janne-hmp** [comment]
Also gremlins and gargoyles do not generate in gnomish mines
