### ISSUE TITLE
Special arrows to be permanent

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1303]
For example, arrow of dragon slaying, like normal arrow but:
- 15% chance of slaying dragon on hit
- 4d6 extra damage against dragons otherwise
- appears in normal stacks of 10-20
- can be exceptional etc.
- has a 5% chance of breaking when uncursed, 0% when blessed

**Comment by janne-hmp** [comment]
Obsolete with mythic properties.
