### ISSUE TITLE
Dracolich pet status line reads SpecUnav, after it has used its breath weapon

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1310]

**Comment by janne-hmp** [comment]
This is as intended. It means that the dracolich cannot use its breath weapon while SpecUnav is on.

**Comment by TommiGustafsson-HMP** [comment]
It could be clearer, like "Cooldown". SpecUnav sounds like a bug.

**Comment by janne-hmp** [comment]
Changed to Cooldown.
