### ISSUE TITLE
Big monster targeting graphics

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1316]
Could be something like this:

![image](https://user-images.githubusercontent.com/16661034/93770635-1a182180-fc25-11ea-9c04-9a8c251bb689.png)

May be a different color, like orange or red.

**Comment by TommiGustafsson-HMP** [comment]
Here's the orange one:

![image](https://user-images.githubusercontent.com/16661034/93993597-9d598480-fd97-11ea-8323-c7bc0dd97e58.png)

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp How about a key, which hou press flashes the target square targetting graphics.

**Comment by janne-hmp** [comment]
Done. It works now from Alt-*, Alt-4 (no numpad), and Alt-:, since all the other, more practical keys are taken.
