### ISSUE TITLE
Leather hat should be enchantable to +7 as in NetHack, but can be enchanted to +3 only

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1318]
![image](https://user-images.githubusercontent.com/16661034/93856656-0242ab00-fcc2-11ea-9ae5-9efcf2390ed9.png)

**Comment by TommiGustafsson-HMP** [comment]
I guess generally all leather items should be enchantable to +7. So, the enchantable level would be +6 (double normal).

**Comment by janne-hmp** [comment]
Already so.
