### ISSUE TITLE
Adventuring advice is useless

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1324]
It's just plain wrong:

![image](https://user-images.githubusercontent.com/16661034/93879801-1055f300-fce5-11ea-9d1f-424a02b13a54.png)

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp How about
- each advice giver has 25% chance of not having advice
- otherwise, he or she has advice
- the 25% not-having-chance will be checked each time you talk to him or her, if he or she had advice previously
- if he or she has advice
  - 10% chance of major divination
  - 40% chance of minor divination
  - 40% chance of true rumor (is this different from minor divination?)
  - 10% chance of false rumor

**Comment by janne-hmp** [comment]
Almost all NPCs including shopkeepers, priests and smiths, but excluding hermits, now have always true advice. Hermits tend to be a bit deranged, and are not reliable. Demons and priests/angels of Moloch have false advice. Others may have true or false advice.
