### ISSUE TITLE
After Dispater is killed, Dungeon overview does not show Dis (level 32)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1328]
![image](https://user-images.githubusercontent.com/16661034/94111255-77da8280-fe4c-11ea-8025-492b00db3a7f.png)

**Comment by janne-hmp** [comment]
Fixed. The game now shows the level names in Gehennom by default, and all special levels in Hell are treated as special. The problem with level names is that it is difficult to know when to display them, i.e., when the player knows that he/she is on the special level.
