### ISSUE TITLE
Firetraps still remove max hit points

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1330]
![image](https://user-images.githubusercontent.com/16661034/94112637-698d6600-fe4e-11ea-8b9e-89024537de2f.png)

**Comment by TommiGustafsson-HMP** [comment]
And restore ability does not restore lost hit points.

**Comment by TommiGustafsson-HMP** [comment]
Maybe they should do some serious damage, like 20d6 instead. 10d6 with 50% fire resistance.

**Comment by janne-hmp** [comment]
Fixed.
