### ISSUE TITLE
Up ladder cmap is missing

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1336]
![image](https://user-images.githubusercontent.com/16661034/94138349-a8ccae80-fe70-11ea-94f2-f079ed00cadf.png)

**Comment by TommiGustafsson-HMP** [comment]
And dows ladder:

![image](https://user-images.githubusercontent.com/16661034/94138535-f47f5800-fe70-11ea-899c-0f8c5dcebfd0.png)

**Comment by janne-hmp** [comment]
Yes, nobody has drawn them so far, but let me see.

**Comment by janne-hmp** [comment]
Fixed.
