### ISSUE TITLE
New wand: Wand of Stone to Flesh

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1340]
It would allow destoning of pets after a cockatrice or gorgon encounter. You usually never have enough time to feed the pet a dragon fruit. About 8 charges.

Also, wand of resurrection could be changed to have 5–8 charges as well. It won't help against disintegration, though.

**Comment by janne-hmp** [comment]
Done. It is now a jar of basilisk blood, which cures petrification and in fact works as Stone to Flesh spell. You can also drink from the jar. It has only a range of 1 currently, though, so pets cannot be cured from an extended range.
