### ISSUE TITLE
Wand of Orcus started empty (0:0)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1343]
And recharging with the artificer gave it only one charge.

![image](https://user-images.githubusercontent.com/16661034/94335996-439bc900-ffe8-11ea-97f2-12d2d0ccb1f1.png)

Shouldn't it get something like 5 charges?

**Comment by janne-hmp** [comment]
Fixed. Two different bugs. The artificer now gives 1d4+3 charges, and Orcus gets a wand with 7 charges to start.
