### ISSUE TITLE
Your teleportation is restricted when going up in Gehennom

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1349]
![image](https://user-images.githubusercontent.com/16661034/94341616-727b6480-0013-11eb-81ae-4a3ced036b7c.png)

**Comment by janne-hmp** [comment]
Just press 'n'. The message can come because of many reasons. It is just a wizard mode override.

**Comment by janne-hmp** [comment]
Closed.
