### ISSUE TITLE
Skill screen could tell how many skill points is needed for advancement of a skill

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1354]
For example, weapon skills cost 2 skill points to improve them from Basic to Skilled.
However, two-weapon fighting costs only 1 skill point to improve it from Basic to Skilled.
I think it does not read anywhere.
This is especially important when you are about to increase a skill but would be nice to know also at other times so that you know how many skill points you need to reserve for the next increase.

**Comment by janne-hmp** [comment]
Done.
