### ISSUE TITLE
Modron level drops

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1357]
## Level 1
5 Quintons (Difficulty Level 30)
- Key to the teleportation chamber
- 1d3 dilithium crystals (1 can be used to activate the Li2 power generator)
- Cubic Gate
- Repeating Heavy Crossbow, 50 crossbow bolts
- Wand of Identify

## Level 2
4 Quartons (Difficulty Level 40)
- Key to the teleportation chamber
- 1d3+1 dilithium crystals
- Ring of Teleport Control
- Ring of Free Action

## Level 3
3 Tertians (Difficulty Level 50)
- Key to the Teleportation Chamber
- 1d3+2 dilithium crystals
- Wings of Flying

## Level 4
2 Secundi (Difficulty Level 60)
- Key to the Teleportation Chamber
- 1d3+1 Blessed Scrolls of Charging, 1 random artifact

In a storeroom:
- 1d3+3 dilithium crystals

## Level 5
Primus (Difficulty Level 80–100)
- 1d3+1 Blessed Scrolls of Conflict, 2 random artifacts

In a storeroom:
- 1d3+4 dilithium crystals
- Magic marker

**Comment by janne-hmp** [comment]
Done.
