### ISSUE TITLE
Some monsters are too high level, etc.

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1360]
- Killer bee: 5 → 3
- Beholder 30 → 22
- Elder Orb 50 → 35
- Death Tyrant 55 → 44
- Archon 45 → 30
- Ancient Dragons: 35 → 30
- Dracolich: 30 → 25
- Elder Dracolich: 55 → 44
- Ancient Gold Dragon: 50 → 40
- Juggernaut: 55 → 45
- Wizard of Yendor: 50 → 32
- Death, Famine, Pestilence: 40 → 55
- Tarrasque: 81 → 60

Giant Luggage could also be nerfed. It is now worth Difficulty Level 26, while large Luggage is 7.

Too low level:
- Phoenix: 18 → 25
- Dwarven Geologist: 24 → 37
- Archmage: 28 → 37
- Greater Mummy Pharaoh: 27 → 40
- Greater Dwarven Mummy Geologist: 27 → 40

Vlad could be buffed, since he is only level 35–39.

**Comment by janne-hmp** [comment]
Fixed. Put killer bee to level 4 instead, just in case. Vlad has now 2 weapon attacks, and a bit more strength and dexterity.
