### ISSUE TITLE
High priest of Moloch in the sanctum could have better equipment

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1363]
- Infernal or elite mace or equivalent, maybe even an artifact weapon (some mace)
- Some good armor (mithril full plate mail, or orichalcum full plate mail, or orange dragon scale mail, or yellow dragon scale mail +3/+4?)
- No shield
- Some robe (magic resistance or starry wisdom?)
- Cloak (protection?)
- Amulet of bracers of reflection?

Plus
- 9 points of divine protection

Total AC could be something like -22 – -25.

**Comment by janne-hmp** [comment]
Done.
