### ISSUE TITLE
Add good potions etc. to secret areas in the Modron level

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1367]
They could help to fight against the bosses.
- potions of heroism
- potions of super heroism
- potions of greater speed
- potions of lightning speed
- potions of full healing
- potions of full energy
- wand of cancellation
- wand of death
- scrolls of conflict
- scrolls of taming
- scrolls of genocide
- potions of paralysis
- magic markers
- horn of chaos
- scrolls of charging (to charge more)

These would be found (at least partly) in secret areas, to encourage area exploration.

**Comment by janne-hmp** [comment]
Done. Added a shop that has most of these.
