### ISSUE TITLE
Basic Modrons could be redesigned so that they are about the same difficulty level

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1373]
Monodrone could have 1 very damaging attack like Primus, etc.

Their base levels could be:
- Monodrone: 20
- Duodrone: 21
- Tridrone: 22
- Quadrone: 23
- Pentadrone: 24

Example in MonsterStats-v23

**Comment by janne-hmp** [comment]
Monodrone does now 9d4+9, is level 12, duodrone 2 x 4d4+4, is level 14, tridrone 3x 3d4+3, is level 16, quadrone 4x 2d4+4, is level 18, and pentadron 5x 2d4+1, is level 20. Sum is always 9 or 8.

**Comment by janne-hmp** [comment]
HD:s are 15, 18, 21, 24 and 27.
