### ISSUE TITLE
Use 'b' and 'v' keys to zoom in and out

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1376]
For example,

- b = Zoom 100%
- B = Zoom Scaling Value %, e.g. 250% (acquired from the OS)
- v = Zoom out, fit to screen
- V = Zoom Scaling Value % / 2, e.g. 125%
- Ctrl-v = Zoom 50%

**Comment by janne-hmp** [comment]
What’s the problem with Alt- or Ctrl- , and . ?

**Comment by TommiGustafsson-HMP** [comment]
Maybe these are easier to find for new players.

**Comment by TommiGustafsson-HMP** [comment]
Also, you could anyways add at least "Zoom Scaling Value %, e.g. 250% (acquired from the OS)."

**Comment by TommiGustafsson-HMP** [comment]
Probably not needed no with menu zoom commands.
