### ISSUE TITLE
Starting Zoom

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1377]
How about the game starting with Zoom:

`FLOOR((ScreenScalingValue - 100) / 50) * 25 + 100`

That is,
- Scaling Value 125% → 100% Zoom
- Scaling Value 150% → 125% Zoom
- Scaling Value 175% → 125% Zoom
- Scaling Value 200% → 150% Zoom
- Scaling Value 250% → 175% Zoom
- Scaling Value 300% → 200% Zoom

This would be the Zoom for Alt+.

Zoom for Ctrl+, would be half of that:
- Scaling Value 125% → 50% Zoom
- Scaling Value 150% → 62.5% Zoom
- Scaling Value 175% → 62.5% Zoom
- Scaling Value 200% → 75% Zoom
- Scaling Value 250% → 87.5% Zoom
- Scaling Value 300% → 100% Zoom

Another possibility for Zooms would be that there would be no steps, but it would be straight

`(ScreenScalingValue - 100) / 2 + 100`

That is,
- Scaling Value 125% → 112.5% Zoom
- Scaling Value 150% → 125% Zoom
- Scaling Value 175% → 137.5% Zoom
- Scaling Value 200% → 150% Zoom
- Scaling Value 250% → 175% Zoom
- Scaling Value 300% → 200% Zoom

**Comment by janne-hmp** [comment]
Done, but something a bit different.
