### ISSUE TITLE
Cockatrices, chickatrices, couatls, Aleaxes, and Archons to drop feathers on death

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#138]
Chickatrice: 1d3 feathers
Cockatrice: 1d4 feathers
Couatl: 1d4+1 feathers
Aleax: 1d5+1 feathers
Archon: 1d10+4 feathers

Roc could be 1d8+3 feathers.

**Comment by janne-hmp** [comment]
Done
