### ISSUE TITLE
Reveal weapon enchantment after use

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1380]
Weapon enchantment could be revealed after you hit with it successfully.

Includes arrows and launchers as well as thrown weapons.

**Comment by TommiGustafsson-HMP** [comment]
Even easier would be, revealing the enchantment upon wielding. Non-wieldable weapons could reveal their enchantment after use.

**Comment by janne-hmp** [comment]
Not planned as impractical.
