### ISSUE TITLE
Wand skill could give +4/+8/+12/+16/+20 to hit and give +5%/+10%/+20%/+40%/+70% Critical Strike

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1382]
And cost 1/1/2/2/3 per level. It could be trained to Grand Master level.

## Max Levels
Archaeologist: Expert
Barbarian: Basic
Caveman: Master
Healer: Expert
Knight: Skilled
Monk: Expert
Priest: Grand Master
Ranger: Expert
Rogue: Master
Samurai: Basic
Tourist: Expert
Valkyrie: Skilled
Wizard: Grand Master

## Summary
Basic: 2 roles
Skilled: 2 roles
Expert: 5 roles
Master: 2 roles
Grand Master: 2 roles

## Zaps required

Unskilled: 0
Basic: 10
Skilled: 40
Expert: 90
Master: 160
Grand Master: 250

**Comment by janne-hmp** [comment]
Done.
