### ISSUE TITLE
Zorbus style keyboard command help page

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1385]
![image](https://user-images.githubusercontent.com/16661034/104020643-32a54b00-51c6-11eb-928d-4876614bf619.png)

Probably best if the image can change depending on whether you hold down ALT, SHIFT, or CTRL. Just like in Final Cut Pro X. Actually Zorbus does this too.

The problem with this setup is, of course, national keyboard layouts. For example, > and < keys are in different places etc.

**Comment by janne-hmp** [comment]
Not planned.
