### ISSUE TITLE
master branch doesn't compile

### ISSUE THREAD

**Issue by gebulmer** [hyvanmielenpelit/GnollHack#1388]
Hello!

This doesn't currently compile in Linux due to a link-time error from multiple definitions of WIN_STATUS in src/windows.c and src/decl.c

I suspect you meant for the windows.c one to be extern'd

Additionally the first time you compile from a completely clean repository with parallel make (make -j) it can fail, but that's not particularly important as it will succeed after that

**Comment by janne-hmp** [comment]
Hi, 
For me the Linux version compiles just fine, at least on Ubuntu 20. Here are the steps that should work:

1. Create a directory for GnollHack repository (e.g., 'mkdir GnollHack'), and then go into that directory ('cd GnollHack')
2. a. If this is a new repository with no files yet, type `git clone https://github.com/hyvanmielenpelit/GnollHack.git` 
2. b. If you have already created a GnollHack directory with old GnollHack files, type `git stash` and then type `git pull` to get all the (new) stuff from repository
3. Then `sudo chmod a+rwx ./sys/unix/setup.sh` to make setup.sh readable and executable
4. Then run it by `sudo ./sys/unix/setup.sh ./sys/unix/hints/linux-debug` to create a makefile in the main GnollHack directory
5. Then compile GnollHack with `sudo make install -B`. This compiles GnollHack into /gnh directory (under the root directory).
6. Finally 'cd /gnh' and type 'sudo chmod -R a+rw *' to have all necessary read and write permissions
7. You should be now able to play GnollHack by typing './gnollhack'

You need to have normal NetHack compilation tools installed, such as gcc, bison, and flex for this to work.

**Comment by gebulmer** [comment]
Heya,

The difference between our setups is that I'm using a later version of gcc which defaults to including -fno-common

If I add -fcommon (the default before gcc 10) to the CFLAGS, it compiles fine

It might be worth correcting the declaration of WIN_STATUS though instead, as it's the only instance the changed default in gcc affects

**Comment by janne-hmp** [comment]
Thanks, I'll look into that. Sounds like the issue should be easy to replicate by adding that CFLAG.

**Comment by janne-hmp** [comment]
Hi, this was inherited to my understanding from NetHack. The declaration of WIN_STATUS in windows.c was completely unnecessary, since windows.c includes hack.h, which in turn includes decl.h where extern of WIN_STATUS is. I just commented WIN_STATUS out from windows.c, and this did not affect the building on Windows at all. I trust that it should be now fine with Linux gcc with -fno-common flag as well (but I didn't have time to test this yet).

**Comment by gebulmer** [comment]
looks good to me :+1: compiles fine

**Comment by janne-hmp** [comment]
Great stuff. This can be closed now.
