### ISSUE TITLE
Add difficulty modifiers to difficulty menu (to make effect clearer)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1399]
Very Easy (10% combat difficulty)
Easy (18% combat difficulty)
Medium (31% combat difficulty)
Hard (56% combat difficulty)
Expert (100% combat difficulty)
Master (178% combat difficulty)
Grand Master (317% combat difficulty)

or

Very Easy (1/10 combat difficulty)
Easy (1/6 combat difficulty)
Medium (1/3 combat difficulty)
Hard (1/2 combat difficulty)
Expert (normal combat difficulty)
Master (1.8x combat difficulty)
Grand Master (3.2x combat difficulty)

**Comment by janne-hmp** [comment]
Done.
