### ISSUE TITLE
Bracers or robe which confers MC3

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#141]
Bracers of protection
Robe of protection

Confers MC3. Or maybe confers MC2 + enchantment bonus.

**Comment by janne-hmp** [comment]
Robe of protection and Cloak of protection give MC3 + protection = MC3. Bracers of defense give MC2 + protection = MC3. The whole MC-concept is rather odd; it gives implicit cancellation effect at 30%, 60% or 90% chance, which prevents monsters from using magical attack types (or their special effects).
