### ISSUE TITLE
New celestial spells that deal huge damage to undead and demons

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1431]
For example,

Level 2 touch spell: 6d10 + 1d10 / level to undead and demons
Level 3 ray spell: 6d6 + 1d6 / level to undead and demons
Level 4 circle spell: 6d6 + 1d6 / level to undead and demons
Level 5 explosion spell: 6d10 + 1d10 / level to undead and demons
Level 6 touch spell: 24d10 + 4d10 / level to undead and demons
Level 7 ray spell: 24d6 + 4d6 / level to undead and demons
Level 8 circle spell: 24d6 + 4d6 / level to undead and demons
Level 9 explosion spell: 24d10 + 4d10 / level to undead and demons

**Comment by janne-hmp** [comment]
Done.
