### ISSUE TITLE
Add new arcane spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1432]
Flaming Touch
Fire touch spell level 6: 12d10 + 2d10 / level
Sulphurous Ash
20 Castings

Shock touch spell level 7: 24d6 + 4d6 / level
Cold touch spell level 8: 24d10 + 4d10 / level

Fire ray spell level 7: 24d6 + 4d6 / level
Shock ray spell level 8: 24d10 + 4d10 / level
Cold ray spell level 9: 48d6 + 8d6 / level

**Comment by janne-hmp** [comment]
Done.
