### ISSUE TITLE
New conjuration spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1433]
Greater Animate Water
Level 5
Summons Elder Water Elemental
Potion of Water
1 Casting

Greater Animate Earth
Level 6
Summons Elder Earth Elemental
4 Stone Pebbles
1 Casting

Greater Animate Fire
Level 7
Summons Elder Fire Elemental
2 Sulphurous Ash
1 Casting

Greater Animate Air
Level 8
Summons Elder Air Elemental
2 Feathers
1 Casting

Summon Dragon
Level 5
Summons random dragon
Gold Ore
1 Casting

Summon Ancient Dragon
Level 8
Summons random ancient dragon
1 Fluorite Stone
1 Casting

**Comment by janne-hmp** [comment]
Done.
