### ISSUE TITLE
Make chances of getting elite/celestial/primordial/infernal weapons from a wish better

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1434]
Elite weapon -> 100% (up from 80%)
Celestial/primordial/infernal -> 2/3 = 67% (up from 25%)

Reasoning: Actually, you want to use a wish for a weapon you do not find normally. Celestial/primordial/infernal weapons are a good candidate for a wish, especially if you combine it with a special weapon, such as a staff of frost or a flindbar.

**Comment by janne-hmp** [comment]
Fixed.
