### ISSUE TITLE
Weapons to show damage, armors to show AC and MC

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#144]
Weapons and armors should show their stats, when looked at or in inventory.

**Comment by TommiGustafsson-HMP** [comment]
Ranged weapons could also show their range.

**Comment by janne-hmp** [comment]
Now in new command M('x'), examine. It gives all kinds of data on items. Calculation of range of ranged weapons is a bit difficult, as it depends on STR, etc.

**Comment by janne-hmp** [comment]
The new Examine (M('x')) command shows now throw and fire ranges, as well as wand damage and range. It shows most relevant stats for most items.
