### ISSUE TITLE
Dwarven geologists could have ores and gems in inventory, which they sell

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1441]
Reasoning: Geologists are useless for wizards, who need all the ores and gems.

Ore prices could be relative to their rarity:
- Iron Ore: 90
- Copper Ore: 100
- Silver Ore: 180
- Gold Ore: 225
- Platinum Ore: 300
- Orichalcum Ore: 450
- Mithril Ore: 450
- Adamantium Ore: 450

**Comment by janne-hmp** [comment]
Done.
