### ISSUE TITLE
GnollHack Scoring Algorithm

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1443]
Score is calculated as follows:

**Score = Base_Score * Ascension_Multiplier * Difficulty_Multiplier**

**Base Score** = (Deepest_Dungeon_Level - 1) * 5000 + Achievements_Score * 10000 + Conduct_Score * 20000
**Deepest_Dungeon_Level** is the max dungeon depth the charcter reached.
**Achievements_Score** = Sum of Achievements (each has value of 1)

## Conduct_Score
If Ascension failed: 0

If Ascension succeeded, the sum of following:
Foodless = 5
Vegan = 3
Vegetarian = 2
Atheist = 2
Pacifist = 5
Never hit with a wielded weapon = 2
Illiterate = 3
Never polymorphed an object = 2
Never change a form = 1
Genocideless = 2
Wishless = 3
Artifact Wishless = 2
Zen = 5
Nudist = 5
Elberethless* = 1

## Ascension_Multiplier

If Ascension failed: 1
If Ascension succeeded: 4 * Turn_Count_Multiplier, with maximum of 16 and minimum of 2.

## Turn_Count_Multiplier

SQRT(50000) / SQRT(Turn_Count)

This is 1, when Turn_Count = 50000. Effectively, minimum multiplier is 0.5 and maximum multiplier is 4 (see min and max above).

## Difficulty_Multiplier

10^(1/4)^Difficulty_Level^2
or more consicely
SQRT(10)^Difficulty_Level

Difficulty_Level for Very Easy is -4, Easy -3, Medium -2, Hard -1, Expert 0, Master 1, and Grand Master 2.

This is, for example, on Very Easy = 1% and on Grand Master = 1000%.

Note that 10^(1/4) (=1.7783) is a good approximate for the real difficulty level, which is SQRT(2)*2^(1/3) (=1.7818).

**Comment by janne-hmp** [comment]
Lisäksi luckstoneista voisi saada pisteitä. Tämän päälle voisi olla hahmoluokka-spesifiä tavoitteita: Rogue - raha + timantit, Wizard opitut spellit jne. Tässä olisi jokin cap, niin, että kaikki saavuttavat maksimimäärän jollain sopivalla / yhtä vaikealla tavoite määrällä

**Comment by TommiGustafsson-HMP** [comment]
## Conduct Values from TNNT

Foodless | 50
Vegan | 30
Vegetarian | 10
Atheist | 15
Pacifist | 60
Never hit with a wielded weapon | 15
Illiterate | 30
Never polymorphed an object | 2
Never change a form | 2
Genocideless | 10
Wishless | 10
Artifact Wishless | 2
Zen | 80
Nudist | 60
Elberethless* | 10

These could use Conduct Multiplier 5000.

**Comment by janne-hmp** [comment]
Done.
