### ISSUE TITLE
Frost Horn damage could be 12d6 instead of 6d6

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1449]
Fire Horn, too.

All horns could be much better than wands.

Horns could also gain +1 to hit per level, since there is no skill associated with them.

Maybe horns could also get +1d6 per 2 levels to their damage? Then they could be 6d6 + 1d6 per two levels. That is, 12d6 at level 12.

**Comment by janne-hmp** [comment]
Changed to 12d6 now first.

**Comment by janne-hmp** [comment]
This is probably ok now. Horn damage is also influenced by wand skill.
