### ISSUE TITLE
Should a long bow have a larger range than a short bow?

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#145]
Now they both have range equal to STR.

**Comment by TommiGustafsson-HMP** [comment]
Maybe shortbow could be 2/3 * STR. So 12 with strength 18 and 6 with strength 9.

**Comment by janne-hmp** [comment]
Now all items can be specified a fixed range and a range as % of STR. If it is a launcher (bow, or crossbow), this applies to firing projectiles. If not a launcher, this applies to overriding normal throwing range (like with javelin).
