### ISSUE TITLE
In front of the shopkeepers door, there's no text "Closed for Inventory", when the door is locked

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1456]
![image](https://user-images.githubusercontent.com/16661034/112833718-cab52100-909f-11eb-8bd9-b871c063199d.png)

**Comment by janne-hmp** [comment]
Normally there should always be if the door is locked. Not sure what happened there.

**Comment by janne-hmp** [comment]
The engraving there is now non-smudging.
