### ISSUE TITLE
The game stopped responding when wriggling free of bear trap

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1460]
ACTUALLY it hangs after a while on staying on the Treasure Island level.

![image](https://user-images.githubusercontent.com/16661034/112839694-2505b000-90a7-11eb-8671-442a584ba186.png)

**Comment by janne-hmp** [comment]
Fixed. This was a very special case of a buried chest with an artifact rotted away. A NetHack bug that hadn't considered such a situation.
