### ISSUE TITLE
Warning on level 1 character shows easy monsters as 5

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1464]
I mean they are not as difficult as 5 should let you understand.

**Comment by janne-hmp** [comment]
Fixed. A new system developed, where there it at least 1 monster level difference between all levels, giving highest amount of information. 

At player levels 1 and 2, monsters of difficulties 0-6 give warnings of 0-6. 

At player level 3, monsters of levels 0-1 give warning level 0, dif 2 => wl 1, dif 3 => wl 2, dif 4-5 => wl 3, dif 6 => wl 5, dif 7+ => wl 6.  

At player level 4, dif 0-1 => wl 0, dif 2 => wl 1, dif 3 => wl 2, dif 4-5 => wl 3, dif 6-7 => wl 4, dif 7-8 => wl 5, dif 9+ => wl 6.   

At player level 5, dif 0-2 => wl 0, dif 3 => wl 1, dif 4 => wl 2, dif 5-6 => wl 3, dif 7-8 => wl 4, dif 9-11 => wl 5, dif 12+ => wl 6. 

At player level 6, dif 0-2 => wl 0, dif 3 => wl 1, dif 4 => wl 2, dif 5-7 => wl 3, dif 8- => wl 4, dif 11-13 => wl 5, dif 14+ => wl 6.
