### ISSUE TITLE
Examine to show spell casting penalty of armors

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#148]
Examine should show the spell casting penalty of armors. Maybe first the base penalty of the armor, and then specific penalty for your class (for example, if you are a priest, which can wear armor while casting spells).

Possibly also it could show specific penalties for casting Int, Wis, Cha spells, if they are different from the base penalty.

So there could be many lines for spell casting penalties.

**Comment by janne-hmp** [comment]
Showing now basic penalty. This penalty can now be specified item by item, and negative numbers give spell casting bonuses.
