### ISSUE TITLE
Evaporating water at the castle moat looks strange

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1480]
![image](https://user-images.githubusercontent.com/16661034/114020140-ec6c9000-9877-11eb-9abb-b895bdd77657.png)

**Comment by janne-hmp** [comment]
Sure. It is a floor with pit. Maybe a graphics change / a variation is need there. In general, putting a pit on the ground where the moat used to be looks like that. Maybe a better system would be needed, but that would change the game mechanics.

**Comment by janne-hmp** [comment]
Fixed. It was a bug with wand of evaporation and drawbridges in fact.
