### ISSUE TITLE
Attack Wands and Wand Skill revamp

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1483]
Attack Wand base damage:
- Magic Missile: 2d6
- Striking: 3d6
- Fire: 4d6
- Lightning: 5d6
- Cold: 6d6

Wand skill:
- Unskilled: Normal damage
- Basic: 2x damage
- Skilled: 3x damage
- Expert: 4x damage

Skill cost:
- Unskilled -> Basic: 1 skill slot
- Basic -> Skilled: 2 skill slots
- Skilled -> Expert: 3 skill slots

Master and Grand Master levels do not exist.

**Comment by janne-hmp** [comment]
Done.

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp Wand of cold base damage should be 8d6 and wand of magic missile 3d5, if we follow corresponding spells.

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp 
- Basic 1x
- Skilled 1.5x
- Expert 2x
- Master 3x
- Grand Master 4x

**Comment by TommiGustafsson-HMP** [comment]
So, wand of cold on grand master level does 32d6 damage, for average of 112 points of damage.

**Comment by janne-hmp** [comment]
Fixed.
