### ISSUE TITLE
Examine to show Magic Cancellation % in addition to the integer

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#149]
Examine's Magic Cancellation info could also show the % chance of cancellation (like 30%), so that it would be clear what it does.

**Comment by TommiGustafsson-HMP** [comment]
This probably does not need to be implemented if #151 and #150 are implemented, because MC>3 is not linear.

**Comment by janne-hmp** [comment]
Impossible, since each item gives separately MC and only the total matters. MC% is not item specific.
