### ISSUE TITLE
There are too many scrolls of conflict on the modron level

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1493]
Should be 2-4 in total, counting the shop.

Now I found 8 and a ring of conflict with 7 charges = 15 conflict. Plus horn of chaos 19 charges.

Horn of chaos could have fewer charges, like 5-8.

**Comment by janne-hmp** [comment]
Removed them all, and replaced them with random contents. Fixed horn of chaos charges.
