### ISSUE TITLE
Wand of Trap Detection

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1498]
Has about 10–15 charges.

Detects trap in the vicinity of the player. Let's say 15 squares.

Is not too uncommon.

**Comment by janne-hmp** [comment]
Done. But made it a standard trap detection (whole map), similar to detect traps spell, as it would have been very confusing otherwise (when an item detects the whole map and when not). Therefore 5-8 charges only. Does not work non-magic-mappable maps, similar to detect traps spell.
