### ISSUE TITLE
New Magic Skill Opening Levels (Simplified)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1505]
**Starting Skill / Level Opened for:  Basic | Skilled | Expert | Master | Grand Master**
Unskilled:  3 | 7 | 13 | 21 | 31
Basic:  N/A | 4 | 9 | 16 | 25
Skilled: N/A | N/A | 5 | 11 | 19

For example:
- If skill starts at Unskilled, Basic level is opened at level 3
- If skill starts at Basic, Skilled level is opened at level 4
- If skill starts at Skilled, Expert level is opened at level 5

**Comment by janne-hmp** [comment]
Done.
