### ISSUE TITLE
Make special weapons effects more like special attributes to a weapon

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1506]
For example,
- wounding
- troll slaying
- defense

Could be attributes on a weapon.

Each weapon could have one or more magical attributes.

For example, 
- exceptional long sword of troll slaying
- elite morning star of wounding and defense

The number of attributes could be shown on the unidentified item.
- uncommon: 1 magical property
- rare: 2 magical properties
- mythic: 3 magical properties

 For example,
- uncommon exceptional long sword
- mythic elite axe

The system would be implemented first for weapons only, because you can just wield one or two of them.

**Comment by janne-hmp** [comment]
Maybe terms could be enchanted/mythic/legendary.

**Comment by TommiGustafsson-HMP** [comment]
Chances of appearing on item could be:

Legendary 1%
Mythic 3%
Enchanted 9%
Normal 87%

Legendary items can appear only at dungeon level 16 and below. Before they revert to mythic items.
Mythic items can appear only at dungeon level 8 and below. Before they revert to enchanted items.

So, about every 8th weapon is enchanted somehow. Is it ok?

**Comment by janne-hmp** [comment]
More or less done now.
