### ISSUE TITLE
MC4 95%, MC5 98%, MC6 99%, MC7 100% cancellation

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#151]
MCs over 3 as follows:
- MC4 95%
- MC5 98%
- MC6 99%
- MC7 100%

**Comment by janne-hmp** [comment]
MC is now 0% at MC0, 25% at MC1, and after that 100% - 100%/MC, so at MC10 chance is 90%. All MC benefits are added together from all items. Protection spell adds 1 level and protection items another 1 level.
