### ISSUE TITLE
Gargantuan mimic on DL 6?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1511]
![image](https://user-images.githubusercontent.com/16661034/114851659-be90c980-9dea-11eb-9185-0c9df820190f.png)

Should be much later, no?

**Comment by janne-hmp** [comment]
It comes 1 level after Oracle, but can be moved later. Maybe level 8 minimum?

**Comment by janne-hmp** [comment]
Looks like it difficulty 17, so maybe much higher than that?

**Comment by janne-hmp** [comment]
Moved it to appear between levels 11 and 20.
