### ISSUE TITLE
Program in disorder

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1512]
![image](https://user-images.githubusercontent.com/16661034/114856092-5b556600-9def-11eb-8392-762aa6a69d48.png)

![image](https://user-images.githubusercontent.com/16661034/114856213-8475f680-9def-11eb-882a-8609a312edf8.png)

Attached save game:

[tommi-wizard.zip](https://github.com/hyvanmielenpelit/GnollHack/files/6317183/tommi-wizard.zip)

**Comment by janne-hmp** [comment]
Which test version?

**Comment by TommiGustafsson-HMP** [comment]
4.1.0-Test18

**Comment by janne-hmp** [comment]
Fixed.
