### ISSUE TITLE
Disintegrate could be transmutation spell

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1519]
Sphere of annihilation conjuration
Black blade of disaster conjuration

In arcane, there should be only the normal attack damage spells.

**Comment by janne-hmp** [comment]
How about power word kill / stun / blind?

**Comment by janne-hmp** [comment]
Maybe enchantment?

**Comment by janne-hmp** [comment]
Done. Power words and mirror image moved to enchantment. Shield moved to abjuration.
