### ISSUE TITLE
Game froze up

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1523]
![image](https://user-images.githubusercontent.com/16661034/115111192-c9349580-9f87-11eb-9a39-3307343a92ba.png)

After the dragon breathed fire. The fire sound is playing indefinitely. Then, after 1 minute the game resumes and executes all commands that are in queue. Of course I had clicked arrow keys several times.

Save file here:

[tommi-wizard.zip](https://github.com/hyvanmielenpelit/GnollHack/files/6329126/tommi-wizard.zip)

4.1.0-Test18

**Comment by janne-hmp** [comment]
Fixed.
