### ISSUE TITLE
Winter wolf seems not have cold resistance

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1524]

**Comment by janne-hmp** [comment]
In test game they get half damage, which is about 22 or so on master. Maybe a different monster, hallucination or something else. Scrrenshot would have helped.

**Comment by TommiGustafsson-HMP** [comment]
Still no cold resistance.

![image](https://user-images.githubusercontent.com/16661034/115756337-c6320e80-a3a6-11eb-8441-5b557c5f6a1c.png)

**Comment by janne-hmp** [comment]
Fixed.
