### ISSUE TITLE
Game Crashed: You begin to bash monsters with your bare hands

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#153]
![image](https://user-images.githubusercontent.com/16661034/65372983-ac3ac200-dc7f-11e9-8911-a610f21a07f6.png)

Like this picture and then it crashes if you bash monsters with your bare hands!

**Comment by janne-hmp** [comment]
Fixed. This was a bug due to checking if the object wielded would shatter.
