### ISSUE TITLE
Hint books

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1530]
Each characters starts with a hint book.

Each hint book gives you a random short hint how to play the game, when you read it. The hints could be numbered.

For example:

**GnollHack Beginner Hints** (appears on Very Easy, Easy, and Medium)
**GnollHack Intermediate Hints** (appears on Hard and Expert)

Hints could be like this:

_Tip 15: You can have two sets of weapons and change between them with 'x'. Doing this does not cost you a turn.
Tip 33: You need to mix spells from material components before you can cast them. You do this with 'X'._

Hints could be lines from the tutorials in the wiki.

There could be also a starting hint, when you start a game with a hint book like this:

_Hint - You can press 'r' to read a hint book in your inventory. You can press 'i' to view your inventory._ (Appears on Very Easy to Medium difficulties)

**Comment by janne-hmp** [comment]
Done.
