### ISSUE TITLE
Slowness in game

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1534]
Trying to cast flame burst. Zip file included. 4.1.0-Test18.

[tommi-wizard.zip](https://github.com/hyvanmielenpelit/GnollHack/files/6356589/tommi-wizard.zip)

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp Finally, game crashed after being slow for a long time.

**Comment by janne-hmp** [comment]
shieldeffect and some trap animations do not play anymore if you do not see the trap.

**Comment by janne-hmp** [comment]
The game is pretty fast now with user input cancelling all delay_out / wait commands until the command is processed. Fixed.
