### ISSUE TITLE
Grid bug seems to do no damage

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1536]
![image](https://user-images.githubusercontent.com/16661034/115703402-c2849480-a372-11eb-879a-e38f8b463766.png)

**Comment by TommiGustafsson-HMP** [comment]
They do damage, but very little?

**Comment by janne-hmp** [comment]
Did the character have shock resistance, e.g., from ring?

**Comment by janne-hmp** [comment]
Fixed. Magic cancellation reduced the damage to zero. Removed cancellation and MC resistance from fire, cold, shock attacks.
