### ISSUE TITLE
New Spell Casting Penalty System

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1545]
The Spell Casting Penalty on armor could be subtracted from bonuses this way:

**_Spell Casting Bonuses - Spell Casting Penalty_**

Now it is somehow like this:

_Spell Casting Bonuses * (100% - Spell Casting Penalty)_

We would need to adjust Spell Casting Penalties like this:

_New Spell Casting Penalty = Old Spell Casting Penalty * 6_

That is, an armor that had previously -5% Spell Casting Penalty would have -30% Spell Casting Penalty in the new system.

**Comment by janne-hmp** [comment]
Done.
