### ISSUE TITLE
Rot in curses interface could have red color (font or backround)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1552]
Now it is gray.

**Comment by janne-hmp** [comment]
Following should be added to server default .gnollhackrc file:

## Skill
OPTIONS=hilite_status:skill-availability/skill/green

## Two-weapon fighting
OPTIONS=hilite_status:two-weapon-fighting/2weap/yellow

## Grabbed
OPTIONS=hilite_status:condition/grab/yellow

## Mental
OPTIONS=hilite_status:condition/hallu/yellow
OPTIONS=hilite_status:condition/conf/orange
OPTIONS=hilite_status:condition/stun/red&bold
OPTIONS=hilite_status:condition/slow/yellow
OPTIONS=hilite_status:condition/fear/yellow
OPTIONS=hilite_status:condition/cancl/yellow
OPTIONS=hilite_status:condition/silent/yellow
OPTIONS=hilite_status:condition/blind/yellow

## Health
OPTIONS=hilite_status:condition/termill/red&inverse
OPTIONS=hilite_status:condition/foodpois/red&inverse
OPTIONS=hilite_status:condition/slime/red&inverse
OPTIONS=hilite_status:condition/stone/red&inverse
OPTIONS=hilite_status:condition/suffoc/red&inverse
OPTIONS=hilite_status:condition/strngl/red&inverse
OPTIONS=hilite_status:condition/paral/red&inverse
OPTIONS=hilite_status:condition/sleep/red&inverse
OPTIONS=hilite_status:condition/rot/red
OPTIONS=hilite_status:condition/lyca/red

**Comment by janne-hmp** [comment]
Done, and updated on servers.
