### ISSUE TITLE
Large kobold is not poisonous?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1554]
![image](https://user-images.githubusercontent.com/16661034/116868415-6c87da80-ac17-11eb-8896-fa7f6add5388.png)

**Comment by TommiGustafsson-HMP** [comment]
Playing human male wizard.

**Comment by TommiGustafsson-HMP** [comment]
I think there is something strange with poison. My another character was shot with a poisoned arrow and it did not do anything. I had no poison resistance.

**Comment by janne-hmp** [comment]
Looks like there is a 20% chance that it is not poisonous.
