### ISSUE TITLE
Can dart and arrow traps produce death-enchanted projectiles?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#156]
Hopefully not. But they seem to be able to produce lightning-enchanted projectiles. That's ok, since it's only 4d6 (=14) damage. But death-enchanted projectiles would be too bad.

**Comment by janne-hmp** [comment]
No, it cannot, since only bone and glass items can be death-enchanted, and the traps shoot normal arrows and darts. However, removed the chance of such projectiles being special-enchanted in the first place.
