### ISSUE TITLE
Monk martial arts damage

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1569]
Skills: +to hit/+to damage/critical strike%/second strike%/str bonus%

Bare Handed Combat
- Unskilled +0/+0/0%/0%/50%
- Basic +3/+2/5%/0%/50%
- Skilled +6/+4/5%/0%/50%
- Expert +9/+6/5%/0%/50%

Martial arts
- Basic +12/+8/5%/0%/100%
- Skilled +16/+11/10%/10%/100%
- Expert  +20/+14/20%/20%/100%
- Master +24/+17/40%/30%/100%
- Grand Master +28/+20/70%/40%/100%

Something like this. Must test in game.

Critical strike is the same as with weapons. To be easy to remember.

+4/+3 per skill level to hit/to damage in martial arts is the same as with weapons.

Second strike is an added bonus.

**Comment by janne-hmp** [comment]
Done.
