### ISSUE TITLE
Sometimes no lighting store in mine town

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#157]
There is not always a lighting store in mine town. There should be guaranteed a place where you can buy/find 7 candles.

**Comment by janne-hmp** [comment]
Maybe also fix this by adding Oracle granting wishes? Or another place where candles can be found for sure?

**Comment by TommiGustafsson-HMP** [comment]
No more wish-dependance. Should be found in the game for certain. One place could be Vlad's tower, where the candelabrum is found.

**Comment by TommiGustafsson-HMP** [comment]
Fixed by kobolds carrying candles #199 .
