### ISSUE TITLE
Add achieveX and conductX fields to xlogfile

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1574]
AchieveX and ConductX list achievements and conducts in a comma-separated list. Example:

version=3.7.0	points=9549	deathdnum=2	deathlev=11	maxlvl=11	hp=0	maxhp=74	deaths=1	deathdate=20210527	birthdate=20210527	uid=5	role=Bar	race=Hum	gender=Fem	align=Neu	name=StatueSurfer	death=killed by a forest centaur	while=sleeping off a magical draught	conduct=0xf80	turns=5539	achieve=0x3c200	<span style="color:green;">**achieveX=attained_the_rank_of_pillager,entered_the_gnomish_mines,attained_the_rank_of_bandit,entered_mine_town,entered_a_shop,entered_a_temple,obtained_the_luckstone_from_the_mines**</span>	**conductX=polyless,polyselfless,wishless,artiwishless,genocideless**	realtime=6455	starttime=1622088854	endtime=1622099542	gender0=Fem	align0=Neu	flags=0x4	gold=350	wish_cnt=0	arti_wish_cnt=0	bones=0

Here's how to do it (from NetHack):
https://github.com/NetHack/NetHack/commit/0e4ff07cef

**Comment by TommiGustafsson-HMP** [comment]
Apparently there is more code than that commit to achievements, since **attained_the_rank_of_bandit** is not listed in that commit.

**Comment by janne-hmp** [comment]
Done. Implemented something similar.
