### ISSUE TITLE
Longbow of diana could have multishot like elven bows.

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1578]
Now it does not do very much anything.

![image](https://user-images.githubusercontent.com/16661034/120078936-71c33280-c0ba-11eb-8075-f3d0d63eeec1.png)

Or does it do double normal damage? = Equal to multishot 2?

Does it double arrow damage too?

**Comment by janne-hmp** [comment]
Added multishot. The Longbow deals double normal elite damage = 6x base damage. It does not influence arrow damage currently.
