### ISSUE TITLE
Level 15 looks strange

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1581]
![image](https://user-images.githubusercontent.com/16661034/120080313-f3b65a00-c0c0-11eb-9fad-b9b322655229.png)

On curses interface.

**Comment by TommiGustafsson-HMP** [comment]
Staircases are %

![image](https://user-images.githubusercontent.com/16661034/120080370-455ee480-c0c1-11eb-91f7-9bfe281e3edd.png)

**Comment by janne-hmp** [comment]
It is the rogue level.

**Comment by TommiGustafsson-HMP** [comment]
Shouldn't rogue level look something like this instead?

![image](https://user-images.githubusercontent.com/16661034/120110570-9f6db180-c176-11eb-8159-e2025548012d.png)

**Comment by TommiGustafsson-HMP** [comment]
It really seems to like this in Curses.
