### ISSUE TITLE
Segfault in wizard mode when using #terrain

### ISSUE THREAD

**Issue by gebulmer** [hyvanmielenpelit/GnollHack#1585]
Start a game in wizard mode and call the #terrain extended command

If you select the 6th option, `legend of base-36 levl[][].typ codes`, you get a segmentation fault

That's because some of the entries in levltyp are null pointers and it attempts to dereference them immediately - perhaps the `!*dsc` check should also check `dsc` is truthy

**Comment by janne-hmp** [comment]
Fixed. The levltyp list was missing two new location types.
