### ISSUE TITLE
Mjollnir to return 100% to Valkyrie's hand

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#159]
Mjollnir should return 100% to Valkyrie's hand, regardless whether it hits or misses. Valkyrie should be able to receive Mjollnir with 100% chance. Now, 99% is very dangerous. 1% of time it will ruin your game, so throwing Mjollnir is never preferred. Mjollnir should never stay on ground, regardless, where it lands (on walls, water, lava, or whatever).

**Comment by janne-hmp** [comment]
Done, it should always return.
