### ISSUE TITLE
Some Junethack achievements are surely not counted

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1590]
I don't believe these work:
- read a Discworld novel
- consulted the Oracle
-  entered a shop
-  entered a temple
-  entered Sokoban
-  entered the Gnomish Mines
-  entered Mine Town
-  entered the Big Room

They are listed in Junethack
https://junethack.net/trophies/gnollhack
but probably not implemented?

Anyways, these achievements should not score the full achievement score, but should be 1/2, 1/3 or 1/4 of normal achievement score.

**Comment by janne-hmp** [comment]
Fixed.
