### ISSUE TITLE
Disarm traps chance to grant an item

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1596]
Unskilled:
- Normal Traps: 1/3 chance to disarm, 1/3 chance to grant an item on disarm
- Magical Traps: 0% chance to disarm

Basic:
- Normal Traps: 2/3 chance to disarm, 2/3 chance to grant an item on disarm
- Magical Traps: 1/3 chance to disarm, 1/3 chance to grant an item on disarm

Skilled:
- Normal Traps: 5/6 chance to disarm, 5/6 chance to grant an item on disarm
- Magical Traps: 2/3 chance to disarm, 2/3 chance to grant an item on disarm

Expert:
- Normal Traps: 11/12 chance to disarm, 11/12 chance to grant an item on disarm
- Magical Traps: 5/6 chance to disarm, 5/6 chance to grant an item on disarm

**Comment by janne-hmp** [comment]
Done.
