### ISSUE TITLE
[From NetHackFourk] Indicate your weapon mode in the status bar

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1597]
Modes are:
- Melee
- Ranged
- Unarmed
- Non-Weapon

Color is yellow or green. So, if you are wielding a bow, it reads ranged. If you are wielding an axe, it reads melee.

We could add also polearms:
- Reach

**Comment by janne-hmp** [comment]
Done.
