### ISSUE TITLE
Early special room/quest with reward as scrolls of identify

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#160]
Somewhere in dungeon level 3–5 there should be a special quest with reward of 1d3+1 scrolls of identify. One semi-dangerous special monster? Should not be too dangerous...

**Comment by TommiGustafsson-HMP** [comment]
Maybe a deserted shop with lots of mimics? A couple of small mimics, a couple of large mimics, and one giant mimic. Somewhere in the shop could be a large box with all the scrolls of identify.

**Comment by TommiGustafsson-HMP** [comment]
Giant mimic might be too dangerous for early game, so maybe just small mimics and one large mimic.

**Comment by TommiGustafsson-HMP** [comment]
The shop could be similar as ones in Orcus town...

**Comment by TommiGustafsson-HMP** [comment]
Maybe one small or large mimic would suffice.

**Comment by TommiGustafsson-HMP** [comment]
The reward would be the wand of identify ( #161 ).

**Comment by janne-hmp** [comment]
There is one scroll of identify in the starting stash. A deserted shop sounds cool for additional identify items.

**Comment by janne-hmp** [comment]
The deserted shop is now located somewhere between Oracle and Medusa levels. The shop has a lot of mimics. The special giant mimic carries a wand of identify.
