### ISSUE TITLE
Descrption of items what they do

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1603]
Like in Shattered Pixel Dungeon.

For example, unicorn horn:

Unicorn horn is known for its powers to cure ailments. It is a charged item.

If an item has charges, it could be noted somewhere, even if unidentified. Has charges: Yes.

But how to balance discovery vs. descriptions?

**Comment by janne-hmp** [comment]
Done for unicorn horn. Added also note of an item having charges.

**Comment by janne-hmp** [comment]
Done for many items now.
