### ISSUE TITLE
Nerf monk innate protection

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1618]
AC: Level/3
MC: Level/9

So, at level 30: +10 AC, +3 MC
At level 50: +16 AC, +5 MC

**Comment by janne-hmp** [comment]
Done.

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp This could be further nerfed to AC -1/6 levels and MC +1/18 levels.

This is equal to monk having Enchant Armor each 6 levels, which is still very good. At level 36: -6 AC, +2 MC.

**Comment by janne-hmp** [comment]
Maybe -1/4 AC, +1/12 MC would be make more sense: At level 36 -9 AC, +3 MC. At level 48: -12 AC, -4 MC.

**Comment by TommiGustafsson-HMP** [comment]
12 free enchant armor seems quite a lot.

**Comment by janne-hmp** [comment]
Let's try this first. Otherwise the innate protection becomes quite meaningless. At 1/4 AC and 1/12 MC it is already half of what it was before.

**Comment by TommiGustafsson-HMP** [comment]
Ok.
