### ISSUE TITLE
Monk deals a bit of too much damage

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1622]
I think FIQ dealt 70 damage / 140 damage (crit.) per hit, so two hits 140-280 damage per round.

I think we could nerf second strike to be 0%/10%/20%/30%/40% per martial arts level to tone this down.

**Comment by janne-hmp** [comment]
Toned it down to half of before (10% at basic and 50% at grand master).
