### ISSUE TITLE
Quivered darts do not fire

### ISSUE THREAD

**Issue by Graznop** [hyvanmielenpelit/GnollHack#1627]
With darts quivered ('at the ready' in the inventory), pressing 'f' doesn't throw one.
This is a minor annoyance if you are used to vanilla Nethack.

**Comment by janne-hmp** [comment]
This was actually a deliberate design to restrict "f" to fire a launcher (like a bow) to make the command more logical (you do not exactly "fire" darts), but it obviously makes quivering darts useless. Ideally, making darts "at the ready" and quivering arrows would be two different types of actions (so you could "quiver" both, and use bow with quivered arrows and readied darts at the same time), but currently there is no free bit in the worn mask to do that, nor a command to throw a readied dart (if "f" is reserved for firing one's bow). But in any case, we'll think of how to resolve this, or if it makes sense to revert the behavior to vanilla. For the time being, one can use throw and then repeat.

**Comment by janne-hmp** [comment]
We decided to revert the behavior back to vanilla. The plan is to have another quiver for daggers & thrown weapons in addition to quiver for ammo (such as arrows), which are used just with launchers (such as bows), but since there are no free worn bits, nothing's implemented yet.
