### ISSUE TITLE
A way/tool to disarm magical traps

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#164]
You cannot disarm magical traps with #untrap command.

**Comment by janne-hmp** [comment]
How about wand of cancellation? Could do also a wand of untrapping, which would also remove poisoning from all poisoned items and disarm trapped chests, or something like that...

**Comment by TommiGustafsson-HMP** [comment]
Maybe make disarm a trap a skill?

Unskilled: Can disable non-magical traps with 1/3 chance
Basic: Can disable non-magical traps with 5/6 chance, magical traps with 1/3 chance
Skilled: Can disable non-magical traps with 19/20 chance and magical traps with 5/6 chance
Expert: Can disable non-magical traps with 99/100 chance and magical traps with 19/20 chance

Unskilled → Basic: 4 successful disarms
Basic → Skilled: 8 successful disarms
Skilled → Expert: 16 successful disarms

Archaeologist, Monk, Ranger, and Rogue could start with Basic Disarm Traps skill. 
Rogue and Ranger can be Expert in Disarm Traps
Archaeologist and Monk can be Skilled in Disarm Traps

Barbarian, Caveman, Knight, Samurai, Tourist, Valkyrie, and Wizard can be Basic in Disarm Traps.

**Comment by janne-hmp** [comment]
Can be done, too

**Comment by TommiGustafsson-HMP** [comment]
Disarming traps would produce items. For example, disarming a polymorph trap would grant a wand of polymorph.

**Comment by janne-hmp** [comment]
Done
