### ISSUE TITLE
Stairs are drawn wrong on Android

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1642]
It does not cover objects behind.

![Screenshot (28 Oct 2021 15 07 53)](https://user-images.githubusercontent.com/16661034/139252765-62007f0c-c501-4cdf-b6c9-a9589cd78954.png)

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp We could try to think of a solution to this problem...

**Comment by janne-hmp** [comment]
Fixed.
