### ISSUE TITLE
Possible Spell Mana Cost System

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#165]
Idea: Spell mana cost would double when the level increases by two. Essentially, the mana cost would increase by √2 each level. Thus, the mana cost of a spell that is **two levels** higher than another spell would have a double mana cost. However, we will start counting at level 1 as 10 mana and level 2 as 15 mana, applying the same procedure to both levels, so we actually never need to multiply values with √2.

- Level 1: 10 mana
- Level 2: 15 mana
- Level 3: 20 mana (2 times 10)
- Level 4: 30 mana (2 times 15)
- Level 5: 40 mana (2 times 20)
- Level 6: 60 mana (2 times 30)
- Level 7: 80 mana (etc.)
- Level 8: 120 mana
- Level 9: 160 mana
- Level 10: 240 mana
- Level 11: 320 mana
- Level 12: 480 mana

Level -1 would then be 5 mana and level 0 7 mana (since 7.5 mana is impossible).

**Comment by janne-hmp** [comment]
Sound like a possibility. 160 mana for a 9th level spell is not much, though. Also, relative increase from level 2 to level 3 (33%) is less than from 1 to 2 (50%). Here's a system where each level is multiplied by 1.5x and rounded up to the nearest 5 in levels 7 and below, and to the nearest 100 mana from there on (50 will be rounded up). 

Level 1: 10 mana
Level 2: 15 mana (5 diff, 50% increase)
Level 3: 25 mana (2.5 times 10, 10 diff to previous, 66% increase)
Level 4: 40 mana (2.66 times 15, 15 diff to previous, 60% increase)
Level 5: 60 mana (2,4 times 25, 20 diff to previous, 50% increase)
Level 6: 90 mana (2,25 times 40, to previous: 30 diff, 50% increase)
Level 7: 135 mana
Level 8: 200 mana
Level 9: 300 mana
Level 10: 500 mana
Level 11: 800 mana
Level 12: 1200 mana

**Comment by TommiGustafsson-HMP** [comment]
I think the lower mana cost is better, or characters can never cast high level spells. Also, there is a clear system to determine mana costs per level in the original system.

**Comment by janne-hmp** [comment]
It is actually possible to use both systems, since you can specify mana costs separately for each spell.

**Comment by janne-hmp** [comment]
Will close this now. Spells will be investigated on a spell on spell basis.
