### ISSUE TITLE
Travel to Downstairs and Travel to Upstairs could be triggered from '>' and '<' when not standing on stairs

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1654]
And when not asking for a direction.

"So, you can't go down here" could be replaced with "Do you want to travel to downstairs?" or something like that.

**Comment by TommiGustafsson-HMP** [comment]
There could be a contextual Next button on the left side of screen with which you could cycle stairs.

**Comment by janne-hmp** [comment]
Done the contextual button.
