### ISSUE TITLE
Pets can spawn at strange places while going up and down

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1656]
![Screenshot_20211103-104725](https://user-images.githubusercontent.com/16661034/140031329-987ac3fb-49b4-4faa-88b4-68f3b41da588.png)

Is a NetHack issue. Probably does not need fixing.

**Comment by janne-hmp** [comment]
Fixed instead an issue where pets sometimes appeared at the stairs spot instead of you. (Was intentional in NetHack, but felt like a bug.) Hostile monsters can still do that. Avoiding the above would require checking pathing connection, which is difficult for the time being.
