### ISSUE TITLE
New MC system needed?

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#166]
MC is now cumulative, which is more sensible. Each item can give it. Is 1-1/Level system good here (certainly better than the previous system, though)? You get 50% MC almost immediately with a few items. Or should it be more linear at low levels? At high levels, the system works now so that you get at least 1% of MC-% at each MC level (levels 11-20). Level 20 gives 100% MC.

**Comment by TommiGustafsson-HMP** [comment]
One possibility would be the following:

In the beginning 25%:

- MC1: 25%
- MC2: 50%
- MC3: 75%

After that 5%:

- MC4: 80%
- MC5; 85%
- MC6: 90%
- MC7: 95%

After that 1%:

- MC8: 96%
- MC9: 97%
- MC10: 98%
- MC11: 99%

After that total immunity 100%:

- MC12: 100%

**Comment by janne-hmp** [comment]
Made the following compromise with 15 levels (MC10 = 95% and you gain 1% thereafter):

MC0: 0%
MC1: 25%
MC2: 50%
MC3: 66%
MC4: 75%
MC5: 80%
MC6: 84%
MC7: 87%
MC8: 90%
MC9: 93%
MC10: 95%
MC11: 96%
MC12: 97%
MC13: 98%
MC14: 99%
MC15+: 100%
