### ISSUE TITLE
Take off many (Remove many) caused a disorder, when taking of all armor

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1660]
![Screenshot_20211103-123052](https://user-images.githubusercontent.com/16661034/140045217-2dd9f3c4-afeb-45e1-bc91-675e46c68a82.png)

Inventory:
![Screenshot_20211103-123224](https://user-images.githubusercontent.com/16661034/140045235-1afb7966-bddf-40b1-a302-dd6be9be1d5e.png)

Was not wearing: faded pall, hard hat, set of silver dragon scales. Wore all others.

**Comment by janne-hmp** [comment]
Fixed.
