### ISSUE TITLE
Wish able to generate up to 20 thrown weapons and missiles

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1663]
Non-artifict thrown weapons and missiles, such as:
- darts
- shurikens
- arrows
- crossbow bolts

So, wishing for _20 blessed fixed +2 elite darts_ would be a valid wish.

Don't know what the limit is now.

**Comment by janne-hmp** [comment]
It is already exactly at 20 for missiles and ammo (by coincidence).
