### ISSUE TITLE
Sleep spell/wand fails too often

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1679]
Even normal monsters, like dwarf, very often resist it.

**Comment by TommiGustafsson-HMP** [comment]
This should be changed to use Magic Resistance instead of Wisdom-based saving throw.

**Magic Resistance - (Skill Level - 1) * 10%**

So, the modifiers per skill level (Enchantment spells or Wand skill):
- Unskilled: +10%
- Basic: +0%
- Skilled: -10%
- Expert: -20%
- Master: -30%
- Grand Master: -40%

The same thing should apply to other echantment spells, and hold spells, etc., which now use Wisdom-based saving throw.

**Comment by janne-hmp** [comment]
Fixed it now so that one gets -2 per skill level beyond unskilled to WIS saving throw. Still uses WIS.
