### ISSUE TITLE
Game crashed after reading spellbook of confuse monster

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#168]
The game crashes about 50% of time when you read spellbook of confuse monster as Valkyrie level 1 (dwarf). Just wish for the spellbook at the start of the game, and it crashes sometimes. Sometimes it does not.

![image](https://user-images.githubusercontent.com/16661034/65439935-a59f7c80-de30-11e9-816b-d30181e382b8.png)

**Comment by janne-hmp** [comment]
Bug fixed. The spellbook was cursed. Caused by level being < 1.
