### ISSUE TITLE
New artifact: Gnollbane

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#169]
Deals double damage to gnolls and flinds and grants lightning resistance. If a gnoll character touches the Gnollbane, it deals 12d6 damage.

Grants +1d5 to hit, +1d12 to damage.

Alignment: lawful.
Type: Club

**Comment by janne-hmp** [comment]
Did a hammer of gnoll slaying instead. It is not an artifact, though. Gnollbane could possibly be an artifact weapon of that type.

**Comment by janne-hmp** [comment]
Done. War hammer of gnoll slaying gives 2d6 extra damage against gnolls, grants warning of gnolls, and gives +1 to damage and hit compared to normal war hammer against all opponents. Gnollbane is an artifact war hammer of gnoll slaying that adds on the top 1d20 artifact damage and 1d5 artifact to-hit bonus, and grants shock resistance (supposedly against flinds).
