### ISSUE TITLE
The Eye of the Aethiopica could give +200 to spell casting when worn

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1691]
Similarly, other spell caster quest artifacts:
- Staff of Aesculapius +150: #1688 
- Mitre of Holiness: +180 to spell casting

**Comment by TommiGustafsson-HMP** [comment]
Maybe these are too high. +120 for each item would be ok.

**Comment by TommiGustafsson-HMP** [comment]
+80 for staff of Aesculapius seems ok, but it can be enchanted to provide more. Eye cannot be enchanted, so +120 for it is ok.

**Comment by janne-hmp** [comment]
Staff gets already plusses from Staff of Life. Eye now grants +120. Mitre is based on Helm of Brilliance, which now gives plusses to INT, WIS, and all spell casting (5% per plus) equal to its enchantment.
