### ISSUE TITLE
After completing the quest, Hippocrates line comes twice

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1693]
Line is: ""You have again returned to us, adventurer. We have done well in your absence..."

It comes each time you do something close to Hippocrates.

**Comment by janne-hmp** [comment]
Removed automatic lines after completing the quest, since they play always when you are next to the leader. Before that they less distracting. You can still play the lines by chatting to the leader.
