### ISSUE TITLE
Sometimes Grayswandir deals very small amount of damage like 3-4

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#170]
Maybe it is right, since the damage is 2d8 + STR bonus?

**Comment by janne-hmp** [comment]
If you are unskilled in silver saber, you get -2 to damage. So it  deals 2d8 - 2 without STR bonus, which is 7 on average, and can vary from 0 to 14. Not sure if the skill-based weapon damage adjustment is a good idea, but that's how it works now.
