### ISSUE TITLE
Add grey, slightly transparent background behind status row

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1707]
It's difficult to see white text on white background. 

The same could be behind the buttons in the bottom

![Screenshot (16 Nov 2021 11 36 57)](https://user-images.githubusercontent.com/16661034/141967957-20ee61a5-0f48-4425-ad03-a8a27e32d7ce.png)
.

**Comment by janne-hmp** [comment]
Added behind buttons.

**Comment by janne-hmp** [comment]
Done also for new modern status bar.
