### ISSUE TITLE
Large monster invisibility seems to have some problems rendering correctly

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1710]
![Screenshot (17 Nov 2021 12 00 03)](https://user-images.githubusercontent.com/16661034/142179445-8db20324-f4f6-4a44-9a5f-a90bbfd81c7c.png)

**Comment by janne-hmp** [comment]
It most likely renders correctly. The background is so different between the tiles, but the monster is equally transparent in each.
