### ISSUE TITLE
High level monsters should not use low-level wands

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#173]
Unless we want them to be really easy. Like Marilith with a wand of magic missile is laughable, but a marilith without any wands is really dangerous.

**Comment by TommiGustafsson-HMP** [comment]
Alternatively, there could be a delay between the uses of a wand, such as 3-4 turns.

**Comment by janne-hmp** [comment]
Fixed. Marilith now checks whether the wand is any good.
