### ISSUE TITLE
Non-phasing monsters can walk in the outer wall of the wizard's tower (bottom floor)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1730]
Or is it special floor?

![Screenshot (26 Nov 2021 11 06 04)](https://user-images.githubusercontent.com/16661034/143555696-43b41fe0-31ef-42b5-a97b-68c2fd1f7557.png)

**Comment by janne-hmp** [comment]
It's not wall, it is floor.
