### ISSUE TITLE
Wizard of Yendor oddities

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1737]
Wizard of Yendor title text came twice (may be because he teleported, or because he summoned double trouble?).

Wizard of Yendor awoke when I was in the first room in the last level of his tower. That is, too early.

**Comment by janne-hmp** [comment]
It was double trouble. This is fixed. The Wizard of Yendor woke up, because somebody cast the aggravate spell.

**Comment by janne-hmp** [comment]
Aggrave spell does not influence Wizard of Yendor anymore.
