### ISSUE TITLE
Make spell casting easier for non-spell-casting classes

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#174]
High number of spell books is now quite good, but for "non-spellcasting" classes it is still usually 100% fail chance for every spell, which makes the game a bit uninteresting. You find a nice spell, which you can never use. I think it would be nice, if every character could cast spells, so that the spellbooks would not be in vain. Likewise, every character can use the same potions and scrolls. There is no difference.

Some things that could alleviate the problem:
- remove armor penalty for casting spells
- reduce the effect of intelligence/wisdom/charisma to 10% from 20%
- reduce the effect of skills to +30%/level

Otherwise all armor using classes can almost never cast spells. I think the spell casting should be more limited by mana and components than other things. Wizard should have lots more mana than a barbarian. Both should be able to cast spells with some chance.

Maybe reduce the chance of casting spells by intelligence/wisdom/charisma point to 10% from 20%. If not, low intelligence/wisdom/charisma characters do not have a chance to cast any spells ever. And casting some low level spells in late game is useless.

We should focus on that all classes have a chance of casting some basic spells in the beginning and some awesome spells in the end. Wizard and priests and other spell casting classes would only have some edge, like more mana and slightly better chance of casting. I think we should reimagine casting spells not to be limited to some "wizard" classes but to be a priviledge of every class. It would make the game more fun.

**Comment by TommiGustafsson-HMP** [comment]
Tested out some parameters and I think following is good for success %:
-70
+20 x Caster Level
-40 x Spell Level
+10 x Stat (Int/Wis/Cha)
+40 x Skill Level

**Comment by janne-hmp** [comment]
Done. Armors still give penalties, but it is possible to set the penalty on an armor-by-armor basis, so it is possible to create special armors that do not have spell-casting penalty. Some dragon armors (all but gray, silver, and black) have very low spell-casting penalties to encourage their use. Yellow dragon scale mail gives +10% bonus to spell casting (negative penalty).
