### ISSUE TITLE
Far look does not tell the color of the altar nor the deity of the high priest on Astral Plane

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1743]
When you see the guys.

**Comment by janne-hmp** [comment]
In NetHack, you can only see it when next to the altar or high priest. Maybe a very small symbol somewhere?

**Comment by janne-hmp** [comment]
Perhaps unnecessary consideration, since the gameplay needs to be similar to NetHack.
