### ISSUE TITLE
Charm spells could be 2 levels higher

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1745]
1 level lower than dominate spells. They are almost the same in practice.

E.g.
- Charm monster: Level 4 → Level 6.
- Mass Charm: Level 8 → Level 10

Increase mana cost accordingly and reduce castings accordingly.

Also, **charm and dominate** spells could have 30% less castings. This assumes that charm and dominate spells work almost always. Otherwise, the castings should not be reduced.
E.g.,
- Dominate monster: 10 castings -> 7 castings

**Comment by janne-hmp** [comment]
Fixed. Severely reduced castings from charm spells due to higher level and general casting reduction.
