### ISSUE TITLE
Add Interface Tutorial to the Mobile Game

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1748]
Something like this:

![MobileUITutorial](https://user-images.githubusercontent.com/16661034/145679841-2c094d3b-7e00-4834-8f1b-5cfdfe3c555a.png)

There should be Previous, Next, and Close buttons somewhere. These will tell what different icons do. This is especially important for icons, which do not have text.

This happens only the first time, you start the game. So, it should be saved in preferences.

In the settings, there could be Show UI Tutorial button, if you want review it.

It could show also invisible buttons like this:

![MobileUITutorial2](https://user-images.githubusercontent.com/16661034/145680562-5d7c8c33-f04a-4d79-8092-183aab613a09.png)

Hint background is (#800000), and there are 10-pixel red borders (circle) or 5-pixel red borders (text box) in this example.

**Comment by janne-hmp** [comment]
Done.
