### ISSUE TITLE
Send crash report functionality

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1749]
If a crash occurs, and the app is restarted, it could zip all the relevant files and save it to some public location. Then, it could open a share file menu. I believe it could be implemented with this:

https://docs.microsoft.com/en-us/xamarin/essentials/share?tabs=android

It would be good if it adviced the user to write how and when the crash happened. The crash file could be sent to gnollhack@hyvanmielenpelit.fi by default, if possible.

**Comment by janne-hmp** [comment]
Done.
