### ISSUE TITLE
Summon monster to create only 1 monster

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#175]
Summon monster spell (summon nasties) should summon only 1 monster, with maximum number of level/8 monsters. Level 16 lich can summon maximum of 2 monsters, level 24 lich 3, level 32 4 and so on. This is equivalent of having level/8 summon monster spells prepared.

This would alleviate the summon problem until the monster spell system is completely revamped.

Summon nasties is also now more dangerous since the lich can gate in ancient dragons, which are REALLY dangerous.

**Comment by janne-hmp** [comment]
Done

**Comment by janne-hmp** [comment]
Now works properly by summoning only one monster, but maximum number is not limited yet.
