### ISSUE TITLE
Mobile game could tell at startup to Disable Auto-Update

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1753]
Something like this:

Updating GnollHack may cause your save games to become invalid. Therefore, we recommend that you turn off Auto-Update from Google Play Store for GnollHack and manually apply updates, when you have no saved games.

About-valikossa voisi olla nappi, jolla vinkin saa uudestaan. Muuten se tulee vain ensimmäisellä kerralla käynnistettäessä.

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp It could be better if the notice would come when exiting the program through the Exit button. It could have a check box: "Do not show again." This way it would not interfere with the game experience at startup.

**Comment by janne-hmp** [comment]
Done.
