### ISSUE TITLE
Blessed potion of full healing not restoring all hit points

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#176]
![image](https://user-images.githubusercontent.com/16661034/65528280-c0d7be00-defc-11e9-816c-934f1c18e501.png)

![image](https://user-images.githubusercontent.com/16661034/65528307-caf9bc80-defc-11e9-9c95-ef0174b3ea45.png)

It seems that when potion of any healing gives more than maximum hit points it goes down to 200-200 something.

**Comment by janne-hmp** [comment]
Fixed. Healing up was done a bit oddly before.
