### ISSUE TITLE
If there is a bag with gold coins in a store, the number of gold coins is not added to the price of the bag

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1763]
It was a bag of holding.

**Comment by janne-hmp** [comment]
Apparently this is intended behavior in NetHack. The amount of gold is added to one's credit when money is dropped to shop. If the money is picked up in shop (including a in bag) it is added to debit. That's why it is not included in the bag's price.
