### ISSUE TITLE
Skill action page could open in any case and the "advance to level" option could be greyed out

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1769]
If the skill cannot be advanced, Advance to Level could be greyed out.
If possible, it could have a third line, which tells the reason:
- Not enough skill slots

If there are enough skills slots, it tells one or both of the following:
- Not enough training
- Not high level enough

**Comment by janne-hmp** [comment]
Done.
