### ISSUE TITLE
GnollHack: Some sort of a crash happens after turning off "Show Pets" in settings

### ISSUE THREAD

**Issue by robsan85** [hyvanmielenpelit/GnollHack#1773]
I turned off Show Pets once in the settings, and now it has started partly crashing afterwards every time i start to play the game from the main menu, even after turning the same setting back on. Also when i tried to send the archive as a result of the crash, it failed to make the crash archive, there should be a screenshot attached to this message showing the archive error
![archievefail](https://user-images.githubusercontent.com/103635746/163357192-42cb16e7-4686-453d-8686-aa7014bdd89f.jpg)
.

**Comment by janne-hmp** [comment]
I cannot replicate this. Show Pets seems to work fine. Would it be possible that the phone run out of disk space at that point?

**Comment by janne-hmp** [comment]
Most likely now fixed with dialogues being streamed.
