### ISSUE TITLE
Related to earlier crash report with "Show Pets" setting

### ISSUE THREAD

**Issue by robsan85** [hyvanmielenpelit/GnollHack#1774]
After the crashes related to the earlier issue, i finished the current character (went upstairs in the 1st floor), and when i started playing the game again, another crash was detected, and now there was this message in the in-game chat:
![image](https://user-images.githubusercontent.com/103635746/163358423-19f87bcf-dd6e-4148-b2e1-50748a81f384.png)

**Comment by janne-hmp** [comment]
CLosed with the previous issue.
