### ISSUE TITLE
Bug with using a name already in use for a new character.

### ISSUE THREAD

**Issue by robsan85** [hyvanmielenpelit/GnollHack#1783]
Naming a new character with the same name as what an already existing/saved character is already called makes you play as the saved character instead of creating a new one.

For example i had a character called "rob" saved, and then i created a new character, called him "rob" too and then the game instead of going through character creation process, it goes into me playing with my saved character.

**Comment by janne-hmp** [comment]
Fixed. The game now asks if you want to delete the existing character if you type a name for which a saved game exists.
