### ISSUE TITLE
View Whole Map mode should be non-static

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1787]
Now part of the map is under icons:

![Screenshot_20220522-132832](https://user-images.githubusercontent.com/16661034/169691010-1e2b740c-5ff5-4c9d-a2e6-c470f4032ba0.jpg)

You should be able to adjust the map (either by panning or by zooming) so that all the map is visible.

This is a problem in the landscape mode.

In the whole map mode, auto-center is of course disabled.

**Comment by janne-hmp** [comment]
Fixed.
