### ISSUE TITLE
Add smaller achievements (for Junethack)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1796]
Following achievements:
- Entered Big Room
- Entered Mine Town
- Entered Gnomish Mines
- Entered Sokoban
- Entered a Temple (with priest I guess)
- Entered a Shop
- Consulted the Oracle
- Read a Discworld Novel

Reference:
https://discord.com/channels/205277826788622337/585121163794186242/985162337734508545

They were accidentally added by Bhaak for GnollHack for Junethack. But we could also implement them.

They probably should give out some score, but not as much as more important achievements. Probably 1/2 of normal achivement score, so multiplier of 5000. So, the Base Score would be:

**Base Score** = (Deepest_Dungeon_Level - 1) * 5000 + Small_Achievements_Score * 5000 + Achievements_Score * 10000 + Conduct_Score * 20000

**Small_Achievements_Score** = Sum of Small Achievements (each has value of 1)
**Achievements_Score** = Sum of Achievements (each has value of 1)

Code can be probably copied from some other variant that does it (probably UnNetHack?). The info needs to be output to the AchieveX field, I think.

Also, it probably should not output the text "Achievement Earned". Not in the ASCII version and not in the mobile UI.

So, these should be invisible, smaller achievements.

**Comment by janne-hmp** [comment]
Done.
