### ISSUE TITLE
Some items auto-id when bought?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1800]
I bought an unid's robe from the shop and after that it showed up as "robe" so that it's item type was known. What happened?

**Comment by janne-hmp** [comment]
Cannot replicate the situation.

**Comment by TommiGustafsson-HMP** [comment]
This seems to be problem with item "robe". How to reproduce:

1. Go to a general shop in mine town view wizlevelport
2. Wish for robe, until you get the normal robe (you cannot wish for a normal robe, but it gives you a random robe, maybe could be fixed too?)
3. Sell the normal robe to the shop
4. It will be identified after sold.

The same happens if you buy the robe.

**Comment by janne-hmp** [comment]
This NetHack feature has been deactivated.
