### ISSUE TITLE
Character selection screen's character icons don't scale on iPad

### ISSUE THREAD

**Issue by robsan85** [hyvanmielenpelit/GnollHack#1802]
![Unscaled_Character_Select](https://user-images.githubusercontent.com/103635746/174045458-acaff6f5-d310-46c9-8b04-374a3dfabf54.png)

**Comment by robsan85** [comment]
![Unscaled_Spell_Select](https://user-images.githubusercontent.com/103635746/174046772-ed25fa2e-50f3-4d99-84cf-2889b2ea183e.png)
![Unscaled_Inventory_Select](https://user-images.githubusercontent.com/103635746/174046810-15ccfea2-0d59-4d07-b6a4-f35a6cee77fc.png)

Same with Inventory and Spell -menus.

**Comment by janne-hmp** [comment]
Now they scale up a little bit on player selection, where they might have been too small previously, but not on other screens. On other screens there might be a lot of spells / items, and scaling is not necessarily preferable.
