### ISSUE TITLE
If you try to wield Mjollnir alone in 2-weapon fighting as ranged weapon in set 2, it goes to the left hand and cannot be thrown

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1805]
When you already have two weapons in two hands in set 1.

I had strength 23 to throw the weapon.

**Comment by janne-hmp** [comment]
I believe Mjollnir was readied as a left hand alternate weapon. This should have been fixed now.
