### ISSUE TITLE
Allow pets to drink potions when feeding them

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1806]
Such as blessed potion of healing or a potion of extra-healing to cure mummy rot.

Of course, other potions as well, which have been implemented. (Some monsters can already drink potions, so these effects have already been implemented.)

Pets could refuse to drink potions with non-implemented effects.

**Comment by janne-hmp** [comment]
Done. Pets can now drink most potions.

**Comment by TommiGustafsson-HMP** [comment]
Cool. @demogorgon22 had also shown interest in this  feature on Discord.
