### ISSUE TITLE
When naming a potion (after it is thrown and crashes on your head), also show the effect text in the popup dialog

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1808]
Now it only says: "What do you want to call this potion?"

But you need to look at the effect in the message lines.

**Comment by janne-hmp** [comment]
Added some texts to the popup. It is difficult to add many of them, but perhaps it helps enough.

**Comment by janne-hmp** [comment]
Done.
