### ISSUE TITLE
Yellow text in the Skill screen could be more golden

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1815]
Yellow is too bright.

![Screenshot_20220628-151835](https://user-images.githubusercontent.com/16661034/176177002-e056a4ed-38c3-479f-a179-c53be9834891.jpg)

**Comment by janne-hmp** [comment]
Fixed. Should appear gold in mobile and brown in other windowing systems.
