### ISSUE TITLE
New geologist service: Sling stone cutting

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1818]
- Makes 5 iron sling bullets from an iron ore.
- Makes 10 exceptional iron sling bullets from 2 iron ores and a gold ore.
- Makes 10 elite iron sling bullets from 2 iron ores and and an adamantium ore.

Silver sling bullets:
- Makes 5 silver sling bullets from a silver ore.
- Makes 10 exceptional silver sling bullets from 2 silver ores and a gold ore.
- Makes 10 elite silver sling bullets from 2 silver ores and and an adamantium ore.

**Comment by janne-hmp** [comment]
Done.
