### ISSUE TITLE
Forging armor is too expensive

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1822]
New prices:
- Orichalcum full plate mail: 4 orichalcum ore
- Mithril full plate mail: 4 mithril ore
- Adamantium full plate mail: 4 adamantium ore
- Crystal plate mail: 1 dilithium crystal + 3 platinum ore
- Shield of reflection: 8 silver ore
- Full plate mail: 8 iron ore
- Field plate mail: 6 iron ore
- Bronze plate mail: 4 copper ore
- Plate mail: 4 iron ore

**Comment by janne-hmp** [comment]
Fixed.
