### ISSUE TITLE
Game crashed some time after being reborn having died to food poisoning

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1826]
Modern mode. On iOS (2 GB RAM). Sami clicked ESC continually (thought to be Main menu.)

Out of memory?

Crash report:
[crash_report.zip](https://github.com/hyvanmielenpelit/GnollHack/files/9018153/crash_report.zip)

**Comment by janne-hmp** [comment]
Most likely fixed now with most dialogues being streamed.
