### ISSUE TITLE
Weapon mode status sometimes does not display Shield

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1828]
It should be M/S, but sometimes it reads M. This is immediately after loading the save game.

![Screenshot_20220630-125242](https://user-images.githubusercontent.com/16661034/176649334-4ba74122-5a63-4211-8a44-2a1f197498c6.jpg)

![Screenshot_20220630-125328](https://user-images.githubusercontent.com/16661034/176649375-a97c5581-7a26-4b08-96e7-9c505d6eb39f.jpg)

It resets to normal M/S when you swap weapons two times.

**Comment by janne-hmp** [comment]
Fixed. Now updates upon loading.
