### ISSUE TITLE
Summon demon spell did not summon tame demon

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1838]
It appeared and vanished.

![Screenshot_20220702-205728](https://user-images.githubusercontent.com/16661034/177011454-1b60ab6b-2eda-4ad7-8f5a-6301a914c408.jpg)
.

**Comment by janne-hmp** [comment]
Fixed. It summoned a demon with 0 duration, instead of a permanent one.
