### ISSUE TITLE
On tablet, clicking arrow north-east is too small and often results in clicking arrow east

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1843]
![Screenshot_20220705-125854](https://user-images.githubusercontent.com/16661034/177305720-9c6193d3-f10e-4291-a104-08f0a87cae13.jpg)

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp Is it possible to have a debug mode that shows the clicking area of the buttons and arrows in 50% transparent red? Might be good for debugging these issues.

**Comment by janne-hmp** [comment]
A suspect device problem. Omitted.
