### ISSUE TITLE
Full fire resistance did not protect potions from being destroyed

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1844]
![Screenshot_20220705-132355](https://user-images.githubusercontent.com/16661034/177307772-47bd3058-d369-4731-93e6-7fec74b79e06.jpg)

**Comment by janne-hmp** [comment]
Where did you get the full fire resistance from?

**Comment by TommiGustafsson-HMP** [comment]
Mitre of Holiness, priest quest artiffact.
