### ISSUE TITLE
Gehennom could still be less tedious

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1847]
Like this:
- Castle (30)
- Valley of the Dead (31)
- Dis (Dispater) (32) 
- 0-1 mid levels (32-33)
- Maladomini (Baalzebub) (33-34)
- 0-1 mid levels (33-35)
- Jubilex (34-36)
- 0-1 mid levels (34-37)
- Orcus Town (35-38)
- Wizard's Tower (3 levels) (36,37,38-39,40,41)
- Lair of Tarrasque (39-42)
- Wizard's Tower Portal 1 (Fake/real) (40-43)
- Yeenaghu (41-44)
- Wizard's Tower Portal 2 (Fake/real) (42-45)
- Vibrating Square (43-46)
- Moloch's Sanctum (44-47)

Mid levels are all cavernous. 

Total of 0-3 midlevels. 15 special levels (counting Castle and Moloch's Sanctum).

Average deepest depth 45.5 floors, when 0-1 mid levels have 50% being 0 and 50% being 1.

There are no random mazes or wide mazes in Gehennom.

**Comment by janne-hmp** [comment]
Quite did not there completely in order to retain some more randomness, but now Gehennom is 2 to 5 levels shorter than before, and has no mazes. Depending on the depth of the dungeon, there will be 3-5 cavernous fill levels.
