### ISSUE TITLE
Iron veins, silver veins, and mithril veins randomly generated in the rock

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#185]
You can then find them by digging there.

Potion of object detection will reveal these veins. There could also be some low level spell to spot these veins. Also, there might be a ring, amulet, or a helm that would reveal the veins when you draw near them.

When you dig into vein, it will give you iron, silver, or mithril instead of rocks. These can be used in blacksmithing and in creation of golems.

**Comment by TommiGustafsson-HMP** [comment]
We could add the scroll of ore detection, and the spell book of ore detection, to detect ores in the rock.

**Comment by janne-hmp** [comment]
There are now lots of different kinds of ores instead of gold: iron, copper, silver, gold, platinum, and mithril ores. A unit of ore is called a nugget of ore, e.g. a nugget of gold ore, unless a better name can be found.
