### ISSUE TITLE
Crash after dying many times (crash)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1853]
Sami's game crashed after he was hallucinating and died many times. Crash report:

[crash_report (1).zip](https://github.com/hyvanmielenpelit/GnollHack/files/9061634/crash_report.1.zip)

Maybe out of memory crash? Can such crashes be caught or identified? Would make life easier.

**Comment by janne-hmp** [comment]
Most likely now fixed with dialogues being streamed.
