### ISSUE TITLE
New nature spells: Summon cockatrice et al

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1870]
**Summon Cockatrice**
Level 3 nature spell
2 Feathers, 1 stone pebble, 1 bat guano
1 casting per mixing

**Summon Giant Cockatrice**
Level 6 nature spell
2 feathers, 1 stone pebble, 1 bat guano, 1 jet stone
1 casting per mixing

**Summon Gargantuan Cockatrice**
Level 9 nature spell
4 feathers, 4 stone pebble, 4 bat guano, 2 jet stones
1 casting per mixing

**Summon Giant Spider**
Level 3 nature spell
3 threads of spider silk
1 casting per mixing

**Summon Phase Spider**
Level 5 nature spell
3 threads of spider silk, 1 mithril ore
1 casting per mixing

**Summon Purple Worm**
Level 8 nature spell
3 oracular toadstools
1 casting per mixing

**Stick to Giant Anaconda**
Level 8 nature spell
4 wood, 1 Amber Stone
1 casting per mixing

**Summon Gargantuan Beetle**
Level 4 nature spell
3 bat guanos, 1 iron ore
1 casting per mixing

**Summon Raven**
Level 0 nature spell
1 feather
1 casting per mixing

**Summon Winter Wolf**
Level 1 nature spell
1 iron ore
1 casting per mixing

**Comment by janne-hmp** [comment]
Done.
