### ISSUE TITLE
Fainting not shown on status bar (shadowrider38 - ttyrecs included)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1874]
## Description

The status bar stopped working in turn 47596, when shadowrider38 wielded the **rustproof +11 Howling Flail**. After reloading, the turn was 47642. He was fighting an invisible stalker with it when it stopped working. The boa constrictor showed up later on.

## Screenshot 1

<pre>                 Message History
                 
       <font color="#C4A000"><b>*</b></font>         Never mind.
       <font color="#06989A">*</font>         What do you want to use or apply?
         *       What do you want to use or apply?
      *          You faint from lack of food.  You&apos;re gasping for air.  You are being strangled!  You regain consciousness.
                 You are being strangled!
      ---------- You are being strangled!  The boa constrictor bites for 25 damage!  The boa constrictor is constricting you to death!  You find it hard to breathe.
      |<font color="#2E3436"><b>...</b></font>&lt;<font color="#2E3436"><b>.....</b></font> You hit the boa constrictor critically for 77 damage!  The boa constrictor bites for 1 damage!  The boa constrictor is constricting you to death!
      |<font color="#06989A">)</font><font color="#2E3436"><b>........</b></font> The boa constrictor is constricting you to death!
      |<font color="#2E3436"><b>.........</b></font> You hit the boa constrictor for 38 damage!  The boa constrictor bites for 1 damage!  The boa constrictor swings itself around you. You sustain 1 damage!
      |<font color="#2E3436"><b>.........</b></font> a - the rustproof +11 Howling Flail (weapon in hand).
      |#<font color="#2E3436"><b>........</b></font> What do you want to wield?
      |<font color="#2E3436"><b>.........</b></font> The boa constrictor turns to flee.
      ------.--- What do you want to write in the dust here? ELbereth
            <font color="#D3D7CF"><b>%</b></font>    You write in the dust with your fingertip.
           #<span style="background-color:#C4A000"><font color="#300A24">*</font></span>    What do you want to write with?
           <font color="#06989A">*</font>     You stop digging.  The boa constrictor brushes against your leg.
                 You continue digging.  You hit the rock with all your might.  A boa constrictor was hidden under a stalker corpse!  The boa constrictor bites for 11 damage!
                 You start digging.  You hit the rock with all your might.  You stop digging.
           *     You start digging.  You hit the rock with all your might.  You succeed in cutting away some rock.
                 In what direction do you want to dig? [hyulnjb&gt;] h
Shadowrider38 th --More--
g DL:25 <font color="#4E9A06"><b>HP:246</b></font><font color="#4E9A06">(305)</font> MP:220(220) AC:-34 MC:22/96% MS:9 W:M XL:15/13254 T:47596 S:1
<font color="#4E9A06">Skill</font> <font color="#CC0000"><b>Hungry</b></font> <font color="#C4A000"><b>Burdened</b></font>                                                                                                                                                                     
</pre>

## Screenshot 2

<pre>
                                                                           
       <font color="#C4A000"><b>*</b></font>              -----------           *  ------------       ----     
       <font color="#06989A">*</font>              |<font color="#2E3436"><b>..</b></font><font color="#3465A4"><b>{</b></font><font color="#2E3436"><b>^.....</b></font>|              |...........<font color="#D3D7CF"><b>##</b></font>#####.<font color="#2E3436"><b>..</b></font>|     
         *            |<font color="#2E3436"><b>.........</b></font>|             #<font color="#C4A000">-</font>..&gt;.......|       |<font color="#2E3436"><b>..</b></font>|     
      *               |<font color="#2E3436"><b>.</b></font><font color="#3465A4">^</font><font color="#2E3436"><b>.....</b></font><font color="#C4A000">^</font><font color="#2E3436"><b>.</b></font>|             #|......<font color="#D3D7CF"><b>@</b></font>..*|     <font color="#06989A">*</font> ----     
                    ##<font color="#C4A000">-</font><font color="#2E3436"><b>.........</b></font>|             #|.<font color="#CC0000"><u style="text-decoration-style:single">O</u></font>........|                 
      -----------   # -<font color="#4E9A06">%</font>------<font color="#C4A000">|</font>--             #|..........|    <span style="background-color:#75507B"><font color="#300A24">*</font></span>             
      |<font color="#2E3436"><b>...</b></font>&lt;<font color="#2E3436"><b>.....</b></font>|####  #### ##<span style="background-color:#75507B"><font color="#300A24">%</font></span>               [---<font color="#C4A000">|</font>--------             *     
      |<font color="#06989A">)</font><font color="#2E3436"><b>........</b></font>|#        #######             #   <font color="#D3D7CF"><b>###</b></font>                          
      |<font color="#2E3436"><b>.........</b></font>|#          #   #########     #     <font color="#D3D7CF"><b>##</b></font>                         
      |<font color="#2E3436"><b>.........</b></font><font color="#C4A000">-</font>#    * #<font color="#3465A4"><b>%</b></font>### *         ####<font color="#3465A4">%</font>####0##<font color="#D3D7CF"><b>#####</b></font>###############0      
      |#<font color="#2E3436"><b>........</b></font>|       #                     #         #          -----.--    
      |<font color="#2E3436"><b>.........</b></font>|  <font color="#C4A000"><b>*</b></font>    #    ############################# # #     |<font color="#2E3436"><b>......</b></font>|    
      ------.----   * --.--                   #       -.-.-<font color="#C4A000">+</font>-.-    |<font color="#2E3436"><b>......</b></font>|    
            <font color="#D3D7CF"><b>%</b></font>         |<font color="#2E3436"><b>,</b></font><font color="#D3D7CF"><b>|</b></font><font color="#2E3436"><b>,</b></font>|##########      #  #       |<font color="#2E3436"><b>.......</b></font>.####.<font color="#2E3436"><b>......</b></font>|    
           #<span style="background-color:#C4A000"><font color="#300A24">*</font></span>    <font color="#C4A000"><b>*</b></font>    |<font color="#D3D7CF"><b>|</b></font><font color="#2E3436"><b>,,</b></font>|#     ---.------<font color="#C4A000">+</font>--#   <font color="#C4A000"><b>*</b></font>   |<font color="#2E3436"><b>.......</b></font>|    |<font color="#2E3436"><b>......</b></font>|    
           <font color="#06989A">*</font>    <font color="#06989A">*</font>     |<font color="#C4A000">((</font><font color="#2E3436"><b>,</b></font><font color="#C4A000">-</font>###   |<font color="#2E3436"><b>...........</b></font>|#       |<font color="#2E3436"><b>...*...</b></font>|    --------    
                 <font color="#C4A000"><b>*</b></font>    |<font color="#2E3436"><b>,,,</b></font>|# ##  |<font color="#2E3436"><b>...........</b></font>|#       ---------                
                      -----#  ###.<font color="#2E3436"><b>.........*.</b></font><font color="#C4A000">-</font>#                                
           *              ##     -------------                                
                                                                            
Shadowrider38 t
g DL:25 <font color="#4E9A06"><b>HP:246</b></font><font color="#4E9A06">(305)</font> MP:220(220) AC:-34 MC:22/96% MS:9 W:M XL:15/13254 T:47596 S:1
<font color="#4E9A06">Skill</font> <font color="#CC0000"><b>Hungry</b></font> <font color="#C4A000"><b>Burdened</b></font>                                                                                                                                                                     </pre>

## Screenshot 3

<pre>
                                                                           
       <font color="#C4A000"><b>*</b></font>              -----------           *  ------------       ----     
       <font color="#06989A">*</font>              |<font color="#2E3436"><b>..</b></font><font color="#3465A4"><b>{</b></font><font color="#2E3436"><b>^.....</b></font>|              |<font color="#2E3436"><b>.</b></font>..........<font color="#D3D7CF"><b>#</b></font>######.<font color="#2E3436"><b>..</b></font>|     
         *            |<font color="#2E3436"><b>.........</b></font>|             #<font color="#C4A000">-</font>..&gt;.......|       |<font color="#2E3436"><b>..</b></font>|     
      *               |<font color="#2E3436"><b>.</b></font><font color="#3465A4">^</font><font color="#2E3436"><b>.....</b></font><font color="#C4A000">^</font><font color="#2E3436"><b>.</b></font>|             #|.........*|     <font color="#06989A">*</font> ----     
                    ##<font color="#C4A000">-</font><font color="#2E3436"><b>.........</b></font>|             #|......<font color="#D3D7CF"><b>@</b></font>...|                 
      -----------   # -<font color="#4E9A06">%</font>------<font color="#C4A000">|</font>--             #|..<font color="#CC0000"><u style="text-decoration-style:single">O</u></font>.......|    <span style="background-color:#75507B"><font color="#300A24">*</font></span>             
      |<font color="#2E3436"><b>...</b></font>&lt;<font color="#2E3436"><b>.....</b></font>|####  #### ##<span style="background-color:#75507B"><font color="#300A24">%</font></span>               [---<font color="#C4A000">|</font>--------             *     
      |<font color="#06989A">)</font><font color="#2E3436"><b>........</b></font>|#        #######             #   <font color="#D3D7CF"><b>###</b></font>                          
      |<font color="#2E3436"><b>.........</b></font>|#          #   #########     #     <font color="#D3D7CF"><b>##</b></font>                         
      |<font color="#2E3436"><b>.........</b></font><font color="#C4A000">-</font>#    * #<font color="#3465A4"><b>%</b></font>### *         ####<font color="#3465A4">%</font>####0<font color="#D3D7CF"><b>#########</b></font>#############0      
      |#<font color="#2E3436"><b>........</b></font>|       #                     #         <font color="#D3D7CF"><b>#</b></font>          -----.--    
      |<font color="#2E3436"><b>.........</b></font>|  <font color="#C4A000"><b>*</b></font>    #    ############################# # #     |<font color="#2E3436"><b>......</b></font>|    
      ------.----   * --.--                   #       -.-.-<font color="#C4A000">+</font>-.-    |<font color="#2E3436"><b>......</b></font>|    
            <font color="#D3D7CF"><b>%</b></font>         |<font color="#2E3436"><b>,</b></font><font color="#D3D7CF"><b>|</b></font><font color="#2E3436"><b>,</b></font>|##########      #  #       |<font color="#2E3436"><b>.......</b></font>.####.<font color="#2E3436"><b>......</b></font>|    
           #<span style="background-color:#C4A000"><font color="#300A24">*</font></span>    <font color="#C4A000"><b>*</b></font>    |<font color="#D3D7CF"><b>|</b></font><font color="#2E3436"><b>,,</b></font>|#     ---.------<font color="#C4A000">+</font>--#   <font color="#C4A000"><b>*</b></font>   |<font color="#2E3436"><b>.......</b></font>|    |<font color="#2E3436"><b>......</b></font>|    
           <font color="#06989A">*</font>    <font color="#06989A">*</font>     |<font color="#C4A000">((</font><font color="#2E3436"><b>,</b></font><font color="#C4A000">-</font>###   |<font color="#2E3436"><b>...........</b></font>|#       |<font color="#2E3436"><b>...*...</b></font>|    --------    
                 <font color="#C4A000"><b>*</b></font>    |<font color="#2E3436"><b>,,,</b></font>|# ##  |<font color="#2E3436"><b>...........</b></font>|#       ---------                
                      -----#  ###.<font color="#2E3436"><b>.........*.</b></font><font color="#C4A000">-</font>#                                
           *              ##     -------------                                
                                                                            
Shadowrider38 the Scout        St:14 Dx:19 Co:17 In:21 Wi:11 Ch:25 $:16
g DL:25 <font color="#4E9A06"><b>HP:268</b></font><font color="#4E9A06">(305)</font> MP:199(220) AC:-34 MC:22/96% MS:9 W:M XL:15/13374 T:47642 S:1600000
<font color="#4E9A06">Skill</font> <span style="background-color:#CC0000"><font color="#300A24">Fainting</font></span> <font color="#C4A000"><b>Burdened</b></font>
</pre>

## Zip File with TTYRECs

[fainting-ttyrec.zip](https://github.com/hyvanmielenpelit/GnollHack/files/9103486/fainting-ttyrec.zip)

**Comment by janne-hmp** [comment]
Potentially fixed. Let's monitor this forward.
