### ISSUE TITLE
Howling Flail has strange field Extra Damage that has average calculated wrong

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1875]
It shows 2d4 (avg. 15.0)

![image](https://user-images.githubusercontent.com/16661034/179297166-2b9a7de9-7e99-44b2-9e14-7d2917a22f46.png)

**Comment by janne-hmp** [comment]
Fixed. It had an extra multiplier, and did not specify that the extra damage is granted when wielded by a gnoll. Also removed the double 25 CHA (now comes just from artifact properties), and increased the repowering time to 300.
