### ISSUE TITLE
Target MC Adjustment seems to be wrong with staff of withering and other items

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1876]
The staff seems to give +X adjustment to MC, where X is enchantment bonus. I would guess that it should be -X instead of +X.

![image](https://user-images.githubusercontent.com/16661034/179354700-564f3f00-666c-4f91-8d28-a084bfefa8a7.png)

**Comment by janne-hmp** [comment]
Fixed.
