### ISSUE TITLE
Pouch of endless bolts does not have description

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1881]
![image](https://user-images.githubusercontent.com/16661034/179733946-4d81c9cc-b914-4e99-b82e-e7b9de201372.png)

The same for Bag of infinite sling bullets:

![image](https://user-images.githubusercontent.com/16661034/179734329-6259c120-f54b-4b88-838a-34f33d63cddb.png)

And the same for Quiver of infinite arrows:

![image](https://user-images.githubusercontent.com/16661034/179734641-e3af58f6-91c8-46e9-8f7a-536edbbab3ba.png)

**Comment by janne-hmp** [comment]
Fixed.
