### ISSUE TITLE
Dragon scale mails to confer MC 2-4

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#189]
Gray dragon scale mail and silver dragon scale mail should confer MC 2. Yellow dragon scale mail should have MC3 (acid resistance cannot be gained as intrinsic but is rather weak). All other dragon scale mails should confer MC 4 (their resistances can be gained as intrinsics). This is to make them better. In vanilla NetHack, they do not confer any MC.

**Comment by janne-hmp** [comment]
Done.
