### ISSUE TITLE
Unidentified and identified the same item has different price in a shop

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1896]
![Screenshot_20220722-203903](https://user-images.githubusercontent.com/16661034/180495231-854cc139-49d9-4e14-8173-ebb821a3be01.jpg)

**Comment by janne-hmp** [comment]
Fixed. The price now adjusts automatically downwards if there is an extra cost attached to the item at a 25% chance.
