### ISSUE TITLE
Potion of Extra Energy

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1897]
Mana potion equal to potion of extra healing.

Fountain alchemy goes:

## Fountain of Healing
- Potion of gain energy: potion of extra healing
- Potion of extra energy: potion of greater healing
- Potion of greater energy: potion of full healing

## Fountain of mana
- Potion of healing: potion of Extra energy
- Potion of Extra healing: potion of greater energy 
- Potion of greater healung: potion of full energy

**Comment by janne-hmp** [comment]
Done.
