### ISSUE TITLE
More Armor MCs

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#190]
All shirts: MC1
All robes: MC2 (or MC3 if big robe, MC4 if robe of protection)
Mithril coats: MC2
Plate mail: MC3
Crystal plate mail: MC2
Bronze plate mail: MC3
Banded mail: MC2
Splint mail: MC1
Chain mail: MC2
Orcish chain mail: MC2
Scale mail: MC1
Ring mail: MC2
Orcish ring mail: MC2
Studded leather armor: MC1
Leather armor: MC1
Leather jacket: MC1

Cloaks:
- Dwarven cloak: MC2 (gives AC 0 though)

Rings:
- **Ring of protection: Adds enchantment bonus (should be +1d5) to MC!**

Bracers:
- Bracers of Defense: MC 2

**Comment by janne-hmp** [comment]
Done
