### ISSUE TITLE
If you fire sling bullets at a hobgoblin, it stops moving (but does not pick up sling bullets)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1935]
Should not stop moving.

The same thing happens with rothe.

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp Happened again to me. When it starts, it seems to affect all creatures. At one point, I was able to shoot sling bullets at a fleeing leprechaun, and it stopped fleeing as well. What could cause such a global problem with monster AI?

I haven't been able to reproduce it in the wizard mode.

**Comment by janne-hmp** [comment]
Let me investigate that scenario and fix this.JanneLähetetty iPhonestaTommi Gustafsson ***@***.***> kirjoitti 27.10.2022 kello 15.23:﻿
@janne-hmp Happened again to me. When it starts, it seems to affect all creatures. At one point, I was able to shoot sling bullets at a fleeing leprechaun, and it stopped fleeing as well. What could cause such a global problem with monster AI?
I haven't been able to reproduce it in the wizard mode.

**Comment by TommiGustafsson-HMP** [comment]
Here's a saved game from Android:

[1Tommi5.zip](https://github.com/hyvanmielenpelit/GnollHack/files/9888264/1Tommi5.zip)

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp This seems to be still happening. Now with my monk and a staff-sling.

**Comment by janne-hmp** [comment]
Fixed.
