### ISSUE TITLE
Do not automatically delete incompatible save games, but instead show a confirmation dialog

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1936]
In the case the game was automatically updated and the user wants to downgrade to previous version and keep the old save game files.

Maybe also allow exporting and importing saved games, if they are lost while rolling back? Some cheat prevention for this would be good, too.

**Comment by janne-hmp** [comment]
Done. Not exporting and importing, though.
