### ISSUE TITLE
Magic marker recharging to cost about 1/4 of wand of wishing recharging.

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1938]
If not so already.

Also, recharging price should probably be capped for artifacts and other costly items at the level of wand of wishing.

**Comment by janne-hmp** [comment]
At the moment, it costs 1/10 to charge with an NPC, since magic marker's cost is 50 and wand of wishing's 500; recharging price is scaled accordingly.

**Comment by TommiGustafsson-HMP** [comment]
This is what I feared. It should be more expensive.

Also, item price should be capped at 500, so that artifacts can be recharged.

**Comment by TommiGustafsson-HMP** [comment]
I think the best solution is to increase magic marker's price to 125.

**Comment by janne-hmp** [comment]
Done.
