### ISSUE TITLE
Game crashes when exiting

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1940]
From K2:

When exiting a game while in curses mode: 

```
curses_get_nhwin: wid -1 out of range. Not a main window.  Program in disorder!
```

Doesnt matter if i died or just saved/quit. And a segfault when i do the same in tty mode.

**Comment by janne-hmp** [comment]
Ok, I suppose this is Beta 13?

**Comment by janne-hmp** [comment]
I cannot replicate this. I tried this on our servers and otherwise. Is it possible to get a call stack / back trace on the segmentation fault?

**Comment by TommiGustafsson-HMP** [comment]
Need to ask K2 on Discord or IRC.

**Comment by k21971** [comment]
Backtrace of the segfault when exiting the game (tty mode) - https://termbin.com/ju6vf

OS is Ubuntu 22.04.1 x86_64, version: as of commit 2d75fb8.

**Comment by gebulmer** [comment]
IIRC from last time this was spotted, it mattered what you responded to the end-of-game prompts with

It was something like one of:
* press n at all the prompts to get the crash (tty) or panic (curses)
* press q at one of the prompts (can't remember which) to get the crash (tty) or panic (curses)

**Comment by janne-hmp** [comment]
This should have happened only in wizard mode, and is now fixed.

**Comment by TommiGustafsson-HMP** [comment]
According to K2's log, he was indeed running ./gnollhack -D
