### ISSUE TITLE
Make a new hints file for a common xlogfile

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1941]
## EDIT

This needs more work, since we do not want to move saved games. There needs to be two variables:

SAVEDIR = $(HACKDIR)/var/save
LOGDIR = /logfiles

## ORIGINAL

Create a new hints file `linux-debug` or change the old one as follows:

Line 19 `VARDIR = $(HACKDIR)/var`  (https://github.com/hyvanmielenpelit/GnollHack/blob/ad13d9b0099cc7b941dba1b4d325b440d28be36e/sys/unix/hints/linux-debug#L19)

should be changed to `VARDIR = /logfiles`

And recompile the program on public servers.

**Comment by janne-hmp** [comment]
No works if compiled with -DNOCWD_ASSUMPTIONS cflag (in hints file) and SCOREDIR=/logfiles statement in sysconf. Did not make a new hints file yet, since also sysconf needs to be changed.
