### ISSUE TITLE
Tarrasque upgrades and Tooth of Tarrasque artifact dagger

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1944]
Tarrasque can be improved to have a 10% vorpal bite attack that beheads the target.

When killed the first time, Tarrasque drops **Tooth of Tarrasque,** a non-wishable, mythic artifact dagger.

### Melee Weapon: Dagger - Artifact

- Material: Bone
- Hands to use: Single-handed
- Skill: Dagger
- Quality: Elite (triple base damage)
- Mythic: Cyclopean
- Safe enchantable level: +15 or below

### Artifact properties

- Alignment is neutral
- Artifact damage type is physical damage
- Artifact to-hit bonus is 1d10
- Artifact damage bonus is 1d10
- Has a 10% chance to behead target on hit

**Comment by janne-hmp** [comment]
Done, but keeping Tarrasque having sharpness for the time being.
