### ISSUE TITLE
Simple UI mode for beginners

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1947]
### Less top right buttons
- No alternative zoom button
- No walk mode button
- No targeting mode button *(debatable)*

### Less buttons in more commands
Remove:
- Killed
- Genocided
- Wear
- Put On
- Quiver
- Fight
- Take Off
- Remove
- Take Off Many
- Light
- Jump
- Tip
- Wipe
- What is
- Look Far
- Break
- Force Lock

## Expert UI Mode

The current mode could called "expert".

## Toggle UI Mode

- Toggle UI Mode button could be in the settings or in more commands

**Comment by janne-hmp** [comment]
Done.
