### ISSUE TITLE
Requirements for switching to MAUI from Xamarin.Forms

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1950]
- [x] SkiaSharp cross-platform GPU acceleration'
    - At the moment, SKGLView does not work on Mac Catalyst, since OpenGL is not supported on Mac. There is no cross-platform solution for SkiaSharp GPU acceleration.
    - OpenGL works on iOS, though. So, it is possible to implement all platforms except Mac.
    - OpenGL/ANGLE support in WinUI 3 is a question mark. There are reports that ANGLE does not work with WinUI 3, at least not yet.
    - ANGLE converts Open GL ES commands to native APIs, such as Metal, so it is possible to use native APIs through ANGLE, while supporting only OpenGL ES APIs in the app.
    - **Of course, it is possible to use CPU rendering on desktop systems and GPU (OpenGL) on mobile systems.**
    - **It's possible to use CPU rendering on iOS, too, because it's fast enough on iPhones.**

- [x] SkiaSharp performance equal to or better than in Xamarin.Forms
    - Currently, there are reports that SkiaSharp performance in MAUI is 7x–8x slower than in Xamarin.Forms.
    - Also, SkiaSharp 2.88.0 did not work with GnollHack. We need to see if 2.88.3 (latest) works or not.

- [x] FMOD support for all platforms
    - Android, iOS, Mac Catalyst, WinUI 3
    - **Working for Android and iOS at the moment. Haven't tested others.**

- [x] MAUI native control performance better than or equal to that of Xamarin.Forms
    - **Probably working OK.** 

- [x] Support for Play Asset Delivery (asset bundles for Android)
    - Does it work the same way as in Xamarin.Forms or not (=add the zip file to AndroidAppBundleModules)?
    - **Apparently AndroidAppBundleModules works, so this working is confirmed.**

- [x] .NET LTS release support
    - Practically .NET 8
    - **Now working on .NET 7. Can upgrade to .NET 8 when it's released.**

**Comment by janne-hmp** [comment]
All requirements complete.
