### ISSUE TITLE
Fireplace generated in the door

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1955]
This is in Mine Town:

![Screenshot_20230418-202409](https://user-images.githubusercontent.com/16661034/232856374-93d4670d-0f8f-4c86-b916-da41abec129c.png)

![Screenshot_20230418-202419](https://user-images.githubusercontent.com/16661034/232856425-f293fc23-f60e-49d5-81da-79321feeb952.png)

**Comment by janne-hmp** [comment]
Fixed.
