### ISSUE TITLE
Dog breed graphics

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1959]
New dog graphics for different breeds.

Plus some way to choose the dog breed in the settings or somewhere else.

Possible breeds:
- Rottweiler
- Welsh springer spaniel
- Welsh corgi (Pembrooke and Cardigan)
- German shepherd
- Shiba Inu
- etc.

**Comment by janne-hmp** [comment]
Done a few of them.
