### ISSUE TITLE
Translate inventory-based action commands into action-based commands for repeat command

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1966]
Now, especially rubbing a magic lamp is difficult, because you can't repeat rubbing. Is it possible that when you first rub the magic lamp through the inventory and then press Repeat that it actually works? Now it just opens the inventory! I was thinking that is it possible that the game would translate the inventory-based Rub command into an action-based Rub command so that it actually could be repeated by pressing the Repeat command?

**Comment by janne-hmp** [comment]
Done.
