### ISSUE TITLE
Detect if Animations are disabled on Android and show a popup to the user

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1967]
## Edit

**The problem here is that the setting is specific to Samsung Galaxy phones and tablets and not part of Android.** Not sure how one detects vendor-specific settings.

## Original Text

Is it possible to detect if animations are disabled using this toggle:

**Settings → Accessibility → Visibility Enhancements → Remove Animations**

If it is, show a popup for user to disable it on startup:

**Title:** Game Won't Load Because Animations Are Disabled
**Message:** To fix the issue, please go to Android's Settings → Accessibility → Visibility Enhancements → Remove Animations and disable it.

We could also include a link to the right page in settings using this code:
https://stackoverflow.com/questions/61232523/how-to-launch-android-settings-app-to-your-apps-settings-with-xamarin-essential

**Comment by TommiGustafsson-HMP** [comment]
Maybe just make a text that is hidden via animation, but stays visible if animations do not work.

**Comment by janne-hmp** [comment]
There is now a popup. I can also confirm that the game / normal Xamarin animations hang up if animations are off (instead, they should immediately finish).
