### ISSUE TITLE
Crossbows can be cold-enchanted? 

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#197]
What does it do?

**Comment by TommiGustafsson-HMP** [comment]
Maybe enchanting a non-stackable item would produce the same effect as with stackable items, but chance of wearing of would be 1/3 of stackable items. So,

- lightning-enchanted: 1/3
- fire-enchanted: 1/9
- cold-enchanted: 1/30

**Comment by janne-hmp** [comment]
At the moment, a cold-enchanted crossbow adds damage if you swing it at the monster, rather than firing with it...

**Comment by janne-hmp** [comment]
Removed the possibility cold-enchant them. Should be restricted to actually weapons that are meant to hit monsters.
