### ISSUE TITLE
Gauntlets of Ying and Yang could not be enchanted above +9 even though in the Examine, it reads +10 safe enchantable level

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1970]
![Screenshot_20230517_165213](https://github.com/hyvanmielenpelit/GnollHack/assets/16661034/b4cd6a73-0893-427f-af65-9c858fb0ad16)

![Screenshot_20230517_165225](https://github.com/hyvanmielenpelit/GnollHack/assets/16661034/a87d9118-4aaa-4267-9d4d-b596842d3003)

**Comment by janne-hmp** [comment]
Fixed.
