### ISSUE TITLE
Entering portal on Plane of Earth crashes game (Android)

### ISSUE THREAD

**Issue by Democcollab** [hyvanmielenpelit/GnollHack#1978]
Entering the portal on the Plane of Earth instacrashes the game on Android. 

Running 4.1.1 and occurs with or without GPU acceleration enabled. Cache cleared / system restarted with no effect. Crash dump [here](https://we.tl/t-6JOa45Cy9l).

![Screenshot_20230601-104802](https://github.com/hyvanmielenpelit/GnollHack/assets/112494622/5b2a0a02-44f1-4c8c-af22-750f18fb63d0)

**Comment by TommiGustafsson-HMP** [comment]
Confirmed. It quickly enters the plane of air and crashes. ASCII version does not crash, so it is something related to the Android version.

**Comment by janne-hmp** [comment]
Fixed. A text string handling bug on mobile. Will issue a hot fix to Android soon.

**Comment by janne-hmp** [comment]
Hotfix is available now on Android.
