### ISSUE TITLE
Semantic Versioning Based on Save Game Compatibility

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1980]
Let's say

[major].[minor1].[minor2], e.g. 4.1.2

Save game compatible changes increase [minor2]. Save game breaking changes increase [minor1] and set [minor2] to zero.

This way, it's easy to know just based pn the version number, which game versions are save game compatible.

[major] can increase when there's a major rewrite of the code. Or something else major.

**Comment by janne-hmp** [comment]
Can be done so that the build number increases with save game compatible changes and minor2 increases with non-compatible changes. Major and minor1 can be reserved for larger structural changes.
