### ISSUE TITLE
"Brushes against your leg" attack does not inform the player of the attack damage

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1982]
k2 reported that it is probably AT_HUGS, AD_WRAP attack types.

Source: https://discord.com/channels/205277826788622337/384784727774724121/1114323339318677605

Also, k2 said:

> there's a bug - mhitu.c line 2493, damage is supposed to be zeroed out when a monster brushes up against your leg. that's not happening this is version 4.1.1

**Comment by janne-hmp** [comment]
Didn't find anything here.
