### ISSUE TITLE
Some dumplogs still look weird

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1988]
https://www.hardfought.org/userdata/m/murgatroid99/gnollhack/dumplog/1686281750.gnoll.txt

Here's the rc file:
https://www.hardfought.org/userdata/m/murgatroid99/gnollhack/murgatroid99.gnollrc

**Comment by janne-hmp** [comment]
Fixed. That was DECgraphics (or something similar), even though the options rc file does not say so. Perhaps the player changed it during the game.
