### ISSUE TITLE
Adamantium Full Plate Mail of Lightness does not weigh less than normal weight

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1989]
>  I found an adamantium full plate mail of lightness, which says it's supposed to be 1/8 weight, but it's still 60 pounds.

Source: https://discord.com/channels/205277826788622337/384784727774724121/1116851777678086196

**Comment by janne-hmp** [comment]
Fixed. weight() function had not been called after changing the mythic status (in special levels).
