### ISSUE TITLE
Kobolds to drop candles

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#199]
In WoW, they have candles on the head.

- Kobold: Drops a candle
- Large Kobold: Drops 1d2 candles
- Kobold Lord: Drops 1d4 candles
- Kobold Shaman drops 1d3 candles, spellbooks, reagents with some chance

These should be in their inventory. They can perhaps light them in dark areas...

**Comment by janne-hmp** [comment]
Done
