### ISSUE TITLE
GUI version game crash just upon knight riding a horse

### ISSUE THREAD

**Issue by transcendreamer** [hyvanmielenpelit/GnollHack#1992]
Latest windows release version 4.1.1.
Crash happens only with tiles version (GnollHackW.exe) while ascii version loads this save file normally (GnollHack.exe).
Save file attached.
[admin-xor.GnollHack-saved-game.zip](https://github.com/hyvanmielenpelit/GnollHack/files/11728227/admin-xor.GnollHack-saved-game.zip)
Config attached.
[gnollhack-config.zip](https://github.com/hyvanmielenpelit/GnollHack/files/11728261/gnollhack-config.zip)

**Comment by transcendreamer** [comment]
last build Mon May 22 23:38:20 2023 (x64).

**Comment by transcendreamer** [comment]
Strangely... after made my knight jump off the steed and saved the game (in ascii version) and the loaded it again (in GUI version) it's all okay again (no game crash). Then I used ride command again and saved (in GUI version) - and it crashes immediately. So it seems it's problem is with riding in GUI version.

**Comment by janne-hmp** [comment]
Fixed. Caused by a new system of showing a saddle on a horse or not. The system will work a bit better in a future release. Just issued a hot fix that should enable you to continue playing with your old save game.
