### ISSUE TITLE
Demon lords to spawn with reflection with a small chance

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#1993]
There could be a small chance, such as 1/3, that a demon lord in Gehennom will spawn with an amulet of reflection or another similar item. This is to make them harder and not so easy to kill with a wand of disintegration.

Jubilex could be excluded and have intrinsic disintegration resistance.

**Comment by janne-hmp** [comment]
Done.
