### ISSUE TITLE
It does not seem possible to give items to party (team) members inside a shop

### ISSUE THREAD

**Issue by cssdixieland** [hyvanmielenpelit/GnollHack#1999]
Distinguished Gentlemen, in the most recent version of Gnollhack for Apple IPad, which seems to be version 4.1.2 build 4 as of 2023 July 20, the hero is inside a general store in Mine Town, together with some pets and three dwarfs who have joined the team, the exploring party. When trying to give items to the members of the team (arrows of various types) the shop keeper exclaims "Drop that, now !" and only one item (one group of arrows) can be given at a time. Then it becomes necessary to activate again the line that reads 'Give items to [name of dwarf]', but the same problem happens, with the shop attendant repeating "Drop that, now !", and the items given seem to disappear, because afterwards they are not listed in the inventory of the allied dwarf. The items do not seem to be on the floor either, and the shop has not paid for buying them. A minor problem that of course can be avoided by giving items to allied team members outside shops, but if not knowing that detail, there is risk of simply losing the items. In spite of minor problems like that, Gnollhack is in my view THE VERY BEST variety of Nethack that I know. Gnollhack is not 'one of the best', it is downright THE BEST ONE. Few hours ago the Nethack Wiki in this repository has more than DOUBLED the number of pages documenting the game in detail, with an impressive 1369 pages of excellent documentation available now. Keep doing the EXCELLENT work that You are doing. Dixieland for ever ! CSS Dixieland @cssdixieland

**Comment by janne-hmp** [comment]
Thanks for lighting this. This is now fixed and will be part of 4.1.2 Build 6 when it is released (perhaps in a few weeks).
