### ISSUE TITLE
In spell casting menu, the name is too short for long spell names

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#200]
![image](https://user-images.githubusercontent.com/16661034/65963618-d2244b80-e463-11e9-84d1-cb5074575ddc.png)

Protection from lightning does not show up.

**Comment by janne-hmp** [comment]
The length is now variable length to allow maximum length for long spell names (and not to look bad with very short spell names only).
