### ISSUE TITLE
Gnollhack Report

### ISSUE THREAD

**Issue by cssdixieland** [hyvanmielenpelit/GnollHack#2000]
This is not really 'an issue', it is a report prepared by CSS Dixieland and sent by this medium as perhaps the best manner for reaching the head programmer, Fru Janne Gustafsson. Whether closing the 'issue' or keeping it open for other persons who might wish to read the report, is a decision entirely to be made by Lady Janne Gustafsson. Also at her discretion any information published in the report can be freely copied and re-published. Care has been taken for providing exact details, but some mistake may have crept into the report. If so, please be free to correct whatever necessary and to insert verified or updated data, and free to erase irrelevant data. Gnollhack is an excellent project, and this is our manner of helping it. Gnollhack Report, in Adobe Portable Document Format:
https://e.pcloud.link/publink/show?code=XZEGLBZvGjBNxsVetQYLx1LC9mmCzIh5yK7

**Comment by janne-hmp** [comment]
Thanks for the report.

**Comment by TommiGustafsson-HMP** [comment]
I am closing this, since the report is also on NetHack Reddit.
