### ISSUE TITLE
You cannot loot chest

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#201]
![image](https://user-images.githubusercontent.com/16661034/65964496-cb96d380-e465-11e9-8ccc-f947a07883dc.png)

Loot ('l') does not work on a chest. Seems to be different from large chest.

**Comment by TommiGustafsson-HMP** [comment]
Cannot loot bag either.

![image](https://user-images.githubusercontent.com/16661034/65965693-b58a1280-e467-11e9-984a-4bda70bc4301.png)

**Comment by TommiGustafsson-HMP** [comment]
However, you can open them when inventory by using apply ('a').

**Comment by janne-hmp** [comment]
Fixed
