### ISSUE TITLE
Weapon/armor compare screen

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#2017]
Compare option appears for unequipped weapons and armor when you click it in the inventory. It is under Examine. It compares the unequipped item to the equipped weapon or armor. The option appears only if the same kind of a weapon/armor is equipped.

It compares all weapon/armor stats in Examine and shows the difference in color.
- If a stat is better: the new stat is in green
- If a stat is worse: the new stat is in red
- If a stat is the same: not shown at all
 
If all is the same:
- Show a line telling this (CQ2: "I have just like this.")

There should be a table with the equipped weapon or armor on the left and the new weapon armor on the right. On each row there is an item stat. There should be a colored up/down arrow or triangle between the items on the stat rows.

**Comment by janne-hmp** [comment]
Done as an extra section in examine command.
