### ISSUE TITLE
Customizable command bar

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#2018]
Commands in the command bar could be chosen by the user.

This could be possible to do if the commands bar is drawn with SkiaSharp. This could be part of moving towards MAUI, if it is faster to draw all buttons with SkiaSharp.

The command choosing UI can be a bit difficult to do, but it probably could be like this:
1. User click some button to customize the commands bar.
2. The game shows the command bar as selectable. For example, the commands can shake, or whatever is appropriate for mobile.
3. User clicks on the command they want to customize.
4. The game opens a more commands-like menu, which includes all commands.
5. User selects the command they want to bind to the command bar.
6. User clicks "Finish customize commands bar".

Note: Commands in the commands bar are not shown in more commands.

**Comment by janne-hmp** [comment]
Done with 6 dropdown lists in settings for simple layout.
