### ISSUE TITLE
Lit candle does not show as lit

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#202]
![image](https://user-images.githubusercontent.com/16661034/65965192-e0279b80-e466-11e9-9c68-b345f2512745.png)

One of the candles should be lit. But it does not show up like that in the inventory. The lit candle is the first one. It also does not show as partly-consumed.

**Comment by janne-hmp** [comment]
The same boolean cast bug as in the other case. To cast a bitwise operator to a boolean value use either !!(X & Y) or (X & Y) != 0.
