### ISSUE TITLE
When creating a new game, if character of that name exists, warn the user instead of loading the game

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#2022]
On mobile, if a character of the chosen name exists warn user instead of starting the game. "Character of this name already exists!"

On Linux, it's probably ok to load the game, since it's the only way to "load game" there.

**Comment by janne-hmp** [comment]
It should do so already, but except when changing the name in "Not yet; choose another name" option.
