### ISSUE TITLE
Yeenaghu apparently dropped his flail

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#2024]
As on orc, I offered hobgoblin on an altar, and it summoned peaceful Yeenaghu. I think this is bug, since orcs should be able to do same-race sacrifice unless I am mistaken.

Then Yee'Naghu disappeared and later another hobgoblin came carrying his flail. See screenshot below:

![Screenshot_20230920_230419](https://github.com/hyvanmielenpelit/GnollHack/assets/16661034/3dcc478a-c201-433f-bde1-a6557915a0b0)

What has happened?

**Comment by janne-hmp** [comment]
Fixed: Hobgoblin is no longer an orc; own race sacrifice description is more accurate; and Yeenaghu can now take his indestructible flail with him.
