### ISSUE TITLE
Eliminate the need to tap OK on menus where appropriate (iOS)

### ISSUE THREAD

**Issue by vbmark** [hyvanmielenpelit/GnollHack#2026]
Having to tap OK after every selection seems like an unnecessary step.  Could there be an option to enable tapping on the selection to be enough to automatically OK it?  I understand that there are some screens where this is not possible because multiple selections are allowed.  But on screens where only one option can be selected then let the tap be enough.

Only tested on iOS.

**Comment by janne-hmp** [comment]
Done for certain single-selection menus where auto-click does not create unnecessary hazard and speeds up the game.
