### ISSUE TITLE
Giant slaying arrows do not seem to do any significant extra damage to giants

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#2028]
Setup:
- 24 str
- +7 longbow of Diana
- +3 Bracers of Archery
- +0 arrows of giant slaying
- vs. -1 elite orcish arrows
- Grand master in bows
- Tested against Titan

**Comment by janne-hmp** [comment]
Fixed. Titan was missing M2_GIANT flag. Also increased slaying weapon multiplier to 3x for melee weapon and 6x for arrows.
