### ISSUE TITLE
Trap Disarming Update

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#2030]
## Traps are 4 levels:
- Level 0 — Easy non-magical: Arrow and Dart Traps, etc. 
- Level 1 — Hard non-magical: Sleep Gas Trap, Rust Trap, etc.
- Level 2 — Easy magical: Teleport trap, Level Teleporter, Anti-magic Field
- Level 3 — Hard magical: Magic Trap, Polymorph Trap, Fire Trap

## Disarm Traps Skill is 6 levels:
Unskilled 0 — Grand Master 5.

## Chance to Disarm:
- **Check Difficulty = Skill Level - Trap Level**
- **Level -2 and below:** 100% Fumble
- **Level -1:** 0% Success, 50% Fail, 50 % Fumble
- **Level 0:** 33% Success, 33% Fail, 33% Fumble
- **Level 1:** 66% Success, 17% Fail, 17% Fumble
- **Level 2 and above:** 100% Success, 0% Fail, 0% Fumble

**Comment by janne-hmp** [comment]
Done.
