### ISSUE TITLE
Cloudy potions never summoning djinn if they are one of the new types

### ISSUE THREAD

**Issue by theothersteve7** [hyvanmielenpelit/GnollHack#2042]
The non-vanilla random cloudy potions never summon a djinn.  Tested in wizard mode with ~150 potions to confirm.  If cloudy potions happen to be one of the vanilla potions they can summon djinn as normal.

**Comment by janne-hmp** [comment]
It is **smoky** potions that summon a djinni; cloudy potions never do.

**Comment by theothersteve7** [comment]
Oops, no wonder my luck seemed to be so bad!  Sorry.
