### ISSUE TITLE
Minor wiki fixes

### ISSUE THREAD

**Issue by theothersteve7** [hyvanmielenpelit/GnollHack#2043]
Three tiny things I'd suggest:

Edit the prefix "Witch King's" to be "Witch-King's" - that's what it is in the code.  Caused me some confusion when experimenting with the mythic system to figure out what to wish for.  Just need to add the hyphen in the docs.

Mark the artifact "The Ark of the Covenant" as either removed or not yet implemented.  I was really curious so I dug around and found that it's currently commented out; the wiki doesn't really explain that.  Really cool concept by the way.  I love these sorts of utility items.

The artifact "The Mattock of the Titans" is not listed on the wiki, and it's shown up in my game.  It's an artifact mattock as the name suggests.

Those are all of the discrepancies I've found so far.  The documentation is pretty great!  Thanks!

**Comment by janne-hmp** [comment]
Wiki fixed.
