### ISSUE TITLE
goodpos() can place flying breathing monsters in water on the Plane of Water

### ISSUE THREAD

**Issue by Ardub23** [hyvanmielenpelit/GnollHack#2044]
This results in pets drowning when entering the plane or using a magic whistle there. Pretty anticlimactic end for Bahamut.

`goodpos()` considers flight, levitation, water-walking, or clinging sufficient to allow placement on a tile for which `is_pool()` returns true. That includes the water on the Plane of Water, which can't be flown over.

This was fixed in NetHack 3.6.3 (with further refinement in the 3.7 development version), so it should be possible to just backport the fix from there.

**Comment by janne-hmp** [comment]
Fixed. Added consideration of Plane of Water to goodpos.
