### ISSUE TITLE
Tournament Eligibility Checks

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#2049]
For JunetHack and Nethack Scoreboard.

## Setting in the Settings
- Check Tournament Eligibility

## 1. When Clicking Play Game in the Main Screen
- Checks if the Classic Mode is on
- Checks if the Casual Mode is off
- Checks if the Wizard Mode is off
- Checks if the user has registered a GnollHack account
- Checks if Post Top Scores is on
- Checks if Record Game is on
- Checks if Auto-Upload to Cloud is on

If one or more checks fail, it shows a popup. For example, "X must be on/off for GnollHack games to be eligible for tournaments."

## 2. Hides or Grays out Difficulty Levels below Expert
- If still chosen, tells "This difficulty level is not eligible for tournament play."

**Comment by janne-hmp** [comment]
Done by adding a new Tournament Mode setting.
