### ISSUE TITLE
Spell desc not working

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#205]
![image](https://user-images.githubusercontent.com/16661034/65983179-a3b76800-e485-11e9-949a-82a72cfbccf0.png)

![image](https://user-images.githubusercontent.com/16661034/65983533-630c1e80-e486-11e9-994c-5d29baefe218.png)

**Comment by janne-hmp** [comment]
These are in a static object array. Not sure how they can get scrambled. The bug must be reproduced successfully.

**Comment by TommiGustafsson-HMP** [comment]
Seems to be working now.
