### ISSUE TITLE
Add a switch between Defense Value (DV, 0 base, goes bigger), Armor Class (AC, 10 base, goes smaller)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#2064]
AC is a bit confusing for new players, who do not know AD&D.

This change only affects how things are displayed, not internal mechanics.

So, AC -1 and DV 11 still both give -1 damage reduction, while AC 0 and greater and DV 10 and less do not give damage reduction at all.

**Comment by janne-hmp** [comment]
Not planned currently.
