### ISSUE TITLE
Skill slot system improvement ideas

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#207]
Now, you get one skill slot every level you level up. And it takes following slots to level up your skills:

Weapon skills:
- Unskilled → Basic: 1 slot
- Basic → Skilled: 2 slots
- Skilled → Expert 3 slots

Other skills:
- Unskilled → Basic: 1 slot
- Basic → Skilled: 1 slot
- Skilled → Expert: 2 slots
- Expert → Master: 2 slots
- Master → Grand Master: 3 slots

However, the number of skills have increased, especially when we add crafting skills.

I was thinking that may be the character could gain **2 skill slots per level**.

#enhance should also indicate **how many skill slots you require to advance any particular skill**. Like 1, 2, or 3. There should be a column of "Cost" for each skill that you can advance. Cost would be empty for all skills that you cannot advance. Or there could be "Slots Required for Next Level" always showing up but that's a long expression. Maybe short could be "Up". Up 1, 2, 3 would be quite clear.

**Comment by TommiGustafsson-HMP** [comment]
### 1 skill slot / level

Essentially, people have about 19 skill slots throughout the game. Most classes start with 3 skills at basic, so that's 22 skill slots. Main melee weapon 6 slots, main ranged weapon 6 slots, alternate weapons 3 slots (all at basic), 5 skill slots remain for other/crafting skills (too few). 68%/32% 

### 1 skill slot / level & weapon skills cheaper

_Weapon skills at 1/1/2 cost (like other skills)_

22 skill slots: 4 main weapon, 4 main ranged weapon, 3 alternate weapons, in 11 other/crafting skills. This seems to be fair 11 in weapon skills. 50%/50%

### 2 skill slots / level

3 + 38 skill slots = 41 skill slots

15 in weapons, 26 in other skills. This is too much!

So I guess the best thing is to use **1 skill slot / level & weapon skills cheaper**. That's to lower the cost of weapon skills to the same as other skills. Other skills must be equally good with weapon skills, then though.

**Comment by TommiGustafsson-HMP** [comment]
### Wizard (normal system)

- expert in quarterstaff 6
- expert in dagger 6
- basic in sword 1
- expert in 3 magic schools 3x4 = 12
- basic in 3 magic schools 3x1 = 3
- expert in 2 other/crafting skills = 4
- basic in 1 other/crafting skill 1

Total: 13 weapon, 15 magic, 5 crafting = 33 skill points (needs level 28 – too high)

### Wizard (cheaper weapons system)

- expert in quarterstaff 4
- expert in dagger 4
- basic in sword 1
- expert in 3 magic schools 3x4 = 12
- basic in 3 magic schools 3x1 = 3
- expert in 2 other/crafting skills = 4
- basic in 1 other/crafting skill 1

Total: 9 weapon, 15 magic, 5 crafting = 29 skill points (needs level 24 – a bit high but doable)

### Wizard (2 slot system)

- expert in quarterstaff 6
- expert in dagger 6
- basic in sword 1
- expert in 3 magic schools 3x4 = 12
- basic in 3 magic schools 3x1 = 3
- expert in 2 other/crafting skills = 4
- basic in 1 other/crafting skill 1

Total: 13 weapon, 15 magic, 5 crafting = 33 skill points (needs level 15 – a bit too low)

### Wizard (2 slot system, more expensive other skills)

_Other skills at 1/2/3 like weapon skills_

- expert in quarterstaff 6
- expert in dagger 6
- basic in sword 1
- expert in 3 magic schools 3x6 = 18
- basic in 3 magic schools 3x1 = 3
- expert in 2 other/crafting skills 2x6 = 12
- basic in 1 other/crafting skill 1

Total: 13 weapon, 21 magic, 13 crafting = 47 skill points (needs level 21/22 – seems to be right)

So another option to lowering weapon skill cost and having 1 skill slot per level is to

- have 2 skill slots per level and 
- use 1/2/3 system for other skills as well

**Comment by TommiGustafsson-HMP** [comment]
Second analysis Knight

### 2 skill slot system, other skills at 1/2/3

- Expert in Sword 6
- Expert in Spear 6
- Expert in Riding 6 
- Skilled in Two-weapon combat 3
- Skilled in Crossbow 3
- Basic in Bow 1
- Skilled in Arcane spells 3
- Skilled in Healing spells 3
- Skilled in Clerical spells 3
- Basic in 3 spell schools 3
- Expert in 1 crafting school 6
- Skilled in 1 crafting school 3
- Basic in 1 crafting school 1

= 25 in weapons, 12 in magic, 10 in crafting = 47 skill slots

Starts with 6 skill slots, 41 from levels (21 levels needed) = Level 22 knight, that is, everything is on spot!

**Comment by janne-hmp** [comment]
I think this is obsolete by now. Closed.
