### ISSUE TITLE
Spell "Mass Create Dracolich" does not work

### ISSUE THREAD

**Issue by NeroOneTrueKing** [hyvanmielenpelit/GnollHack#2072]
All the `obj->corpsenm` (which is referencing the spellbook) should be `sobj->corpsenm` (referencing the item in the fobj chain)

https://github.com/hyvanmielenpelit/GnollHack/blob/4764c7d2b6d3ebb3efd823943b5110108a835f46/src/zap.c#L5535-L5567

**Comment by janne-hmp** [comment]
Fixed.
