### ISSUE TITLE
Cold enchant item spell has material component as yeti corpse?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#208]
Should be something much easier. It is level 1 spell and yetis do not appear at dungeon level 1–3.

**Comment by TommiGustafsson-HMP** [comment]
I suggest the material component for cold-enchanting be nugget of iron. Gives 5 castings.

For fire-enchanting, 1 candle of any type. Gives 5 castings.

For lightning-enchanting, nugget of copper. Gives 5 castings.

A nugget does not have "ore" in its name. All nuggets weigh 0.5 lbs (238 g).

**Comment by janne-hmp** [comment]
Done, except ores kept like before.
