### ISSUE TITLE
Microsoft Store version doesn't update?

### ISSUE THREAD

**Issue by Hash56** [hyvanmielenpelit/GnollHack#2088]
I'm on version 4.2.0 (Build 7), of August 6. WinUI port build 25, version 2.5 beta. I disabled updates on Microsoft Store but neither game nor Windows Store prompt me to update, plus it seems several updates have been skipped already (just installed the game yesterday so it should've installed build 12 instead no?). 
Was trying to update following the fix of #2087

**Comment by janne-hmp** [comment]
It's in store review. Microsoft does not seem to review new apps or updates over the weekend, so we have to wait until early next week (hopefully late on Monday) for the update to be reviewed.

**Comment by janne-hmp** [comment]
The update is now at the store.
