### ISSUE TITLE
New monsters: small skeleton, skeleton warrior, skeletal mage, skeleton lord, skeleton king

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#215]
Low-to-medium difficulty undeads that leaves bones #217 on death. Bones can be used in #214 bone-crafting and as reagents for spells.

Not to be confused with Skeleton (https://nethackwiki.com/wiki/Skeleton).

**Comment by janne-hmp** [comment]
Done. Skeleton is now weaker. One should change skeletons in Orcus Town to be of stronger type. There is no Skeleton King, though. Maybe a unique monster called Skeletor?
