### ISSUE TITLE
Combine weapon skills

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#216]
**Dagger, Knife → Dagger**
Axe → Axe
Pick-axe → Pick-axe 
**Short sword, broad sword, long sword, two-handed sword, scimitar, saber → Sword**
**Club, Mace, Hammer → Club**
**Morning Star, Flail → Flail**
Quarterstaff → Quarterstaff
Polearms → Polearm (singular)
**Lance, Spear, Trident, Unicorn Horn → Spear**
Bow → Bow
Sling → Sling
Crossbow → Crossbow
**Dart, Shuriken, Boomerang → Throwing**
Whip → Whip

Also, Examine reports Dwarvish Mattock skill wrong as Mattock. Should be Pick-axe.

**Comment by TommiGustafsson-HMP** [comment]
This might help us to stay at 1 skill slot per level system.

**Comment by TommiGustafsson-HMP** [comment]
After some analysis #207 the best system is 2 skill slots per level + non-weapon skills increased to 1/2/3 system.

**Comment by TommiGustafsson-HMP** [comment]
Combining Club, mace, and Hammer would help Caveman to use the same skill for the starting club and for his quest artifact, Scepter of Might: https://nethackwiki.com/wiki/The_Sceptre_of_Might

**Comment by janne-hmp** [comment]
Done.
