### ISSUE TITLE
New artifact: Heavy Crossbow of Death

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#218]
Has a 5% chance of instakilling the target, if it has a heart. "Crossbow bolt pierces the heart of X!" Doesn't work on undead and other creatures that do not have a heart like oozes. It is a heavy crossbow.

**Comment by janne-hmp** [comment]
Maybe a crossbow that death-enchants its arrows when fired, possibly draining mana when doing so? "The Crossbow of the Gnollish Kings"

**Comment by janne-hmp** [comment]
Made an artifact repeating heavy crossbow - Crossbow of the Gnoll Lords.
