### ISSUE TITLE
Canines (d) have a chance of carrying bones

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#220]
Jackals: 20% chance of 1 bone
Fox: 25% chance of 1 bone
Coyote: 33% chance of 1 bone
Dingo: 50% chance of 1d2 bones
Wolf: 50% chance of 1d3 bones
Warg: 50% chance of 1d4 bones
Winter Cub: 50% chance of 1d3 bones
Winter Wolf: 50% chance of 1d6 bones
Hell Hound Pup: 50% chance of 1d6 bones
Hell Hound: 50% chance of 1d8+1 bones

Little Dog: 50% chance of 1 bone
Dog: 50% chance of 1d2 bones
Large Dog: 50% chance of 1d3 bones

Werejackal: 50% chance of 1 bone
Werewolf: 50% chance of 1d3 bones

**Comment by janne-hmp** [comment]
How does a dog carry more than one bone?

**Comment by TommiGustafsson-HMP** [comment]
Maybe they are stuck between teeth.

**Comment by TommiGustafsson-HMP** [comment]
Another possibility would be to create more bones like _large bone_ and _giant bone_. They could be components in higher level spells. Then high level canines would drop one large or one giant bone.

**Comment by TommiGustafsson-HMP** [comment]
#214 Bone-crafting could produce bone powder, which is used in spells. Different sizes of bones produce different amounts of powder.

**Comment by TommiGustafsson-HMP** [comment]
If
- bone = 1 measure of bone powder
- large bone = 3 measures
- giant bone = 6 measures

Jackals: 20% chance of a bone
Fox: 25% chance of a bone
Coyote: 33% chance of a bone
Dingo: 25% chance of a large bone
Wolf: 33% chance of a large bone
Warg: 50% chance of a large bone
Winter Cub: 33% chance of a large bone
Winter Wolf: 33% chance of a giant bone
Hell Hound Pup: 33% chance of a giant bone
Hell Hound: 50% chance of a giant bone

Little Dog: 50% chance of a bone
Dog: 25% chance of a large bone
Large Dog: 33% chance of a large bone

Werejackal: 50% chance of a bone
Werewolf: 33% chance of a large bone

**Comment by janne-hmp** [comment]
All canines have now 17% chance of carrying a bone.
