### ISSUE TITLE
Consolidate all special starting items into a starting room?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#224]
The starting room would have an altar of your alignment (built by you) and a stash of additional starting equipment (e.g. axe). It should be somehow special...

**Comment by janne-hmp** [comment]
Probably a good idea.

**Comment by TommiGustafsson-HMP** [comment]
The starting room could also have a forge #187 .

**Comment by janne-hmp** [comment]
Done, now the starting room has a chest named (Player name)'s stash, containing axe (if not otherwise had), a food item, a scroll of identify, and one random scroll.
