### ISSUE TITLE
Modrons and secret modron level

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#225]
Mummies can be moved from M to Z, to free space for the orderly modrons.

**Comment by TommiGustafsson-HMP** [comment]
Lesser undead could b 'z' and greater undead 'Z'. Zruty could be moved to 'q'.

**Comment by janne-hmp** [comment]
Modrons are done now, and the undead and zruty have been moved around, as suggested. Secret modron level moved to another issue.
