### ISSUE TITLE
Secret modron level

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#226]
Presumably in Gehennom

**Comment by TommiGustafsson-HMP** [comment]
Make 2 versions of the secret Modron level. 1 in dungeons of doom (where are all easy modrons) and 1 in Gehennom, with difficult modrons. Only 1 version appears in each game.

**Comment by TommiGustafsson-HMP** [comment]
There is now problem that there are no mid-level modrons (hit dice 6–14), so we might want to adjust the existing modrons. May be hit dice of modrons could be 1, 4, 7, 10, 13 for drones and 16, 19, 22, 24, 27 for lords. Damage of the lords and maybe AC need to be tuned down severely, if we want to make them usable in the game, so that they are not too difficult. Maybe 5-lord should do 1d4+STR damage, 4-lord 2d4+STR damage, 3-lord 4d4+STR damage, 2-lord 8d4+STR damage. Primus could do 16d4+STR damage. They are super fast, so this can be too much as well. Maybe reduce their speed so that monodrome is 12 and it increases by 1 to 21 on Primus.

**Comment by janne-hmp** [comment]
Modron stats changed.

**Comment by TommiGustafsson-HMP** [comment]
How about adding some magic resistance to drones: 10% for monodrone and then increasing each modron by 10% to 50% for pentradrone.

**Comment by janne-hmp** [comment]
Primus damage changed, MR changed, 3 modron levels work now, but not designed properly.

**Comment by janne-hmp** [comment]
Should a "monodrone" be a "modron monodrone" instead?

**Comment by TommiGustafsson-HMP** [comment]
Probably yes.

**Comment by janne-hmp** [comment]
Modron names changed to include name modron.

**Comment by TommiGustafsson-HMP** [comment]
Maybe levels have a structure, which is shaped

- hexagon
- pentagon
- square
- triangle
- circle

**Comment by TommiGustafsson-HMP** [comment]
Maybe the level could be factory themed. A modron factory!

**Comment by TommiGustafsson-HMP** [comment]
A new idea:

Secret modron level consists of five floating cities (levels):

![image](https://user-images.githubusercontent.com/16661034/67146118-595d2600-f290-11e9-8e8e-1819e5d14214.png)

First is controlled by a single Quinton (quite easy). 1 boss.
Second is controlled by a Quarton and two Quintons. Total of 3 bosses.
Third is controlled by a Tertian, two Quartons and four Quintons. Total of 7 bosses.
Fourth is controlled by a Secundus, two Tertians, four Quartons and eight Quintons. Total of 15 bosses.
Fifth is controlled by Primus, three Secunduses (all that is left from 4), six Tertians (all that is left from 9), nine Quartons (all that is left from 16) and 10 Quintons (all that is left from 25). Total of 29 bosses.

**Comment by TommiGustafsson-HMP** [comment]
Secret Modron level could have severals 5x5 rooms, with sliding walls. Whenever you ring a Modron bell (or something), it makes one or two walls to go down and others up. Or something like that. We could make a puzzle out it.

**Comment by TommiGustafsson-HMP** [comment]
What if the Secret Modron Level would be a set of levels of floating islands. Each island would have a structure in the middle (and why not somewhere else as well), a boss modron, and a teleporter to the next level behind the boss modron. Each island would be surrounded by air (just like in the Elemental Plane of Air).

**Comment by janne-hmp** [comment]
Done. At least a temporary version for beta testing.
