### ISSUE TITLE
Game crashed on Examine

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#234]
When pressing alt-X, the game crashed. Inventory was not shown.

**Comment by janne-hmp** [comment]
This needs to be replicated. It does not occur on my GnollHack.

**Comment by TommiGustafsson-HMP** [comment]
May be a random crash. I was able to make the game crash on new character creation, but it happened only once when the computer was still loading some start up programs.
