### ISSUE TITLE
Bag of treasure hauling to use factor 1/32 and 1/64?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#235]
If coins are now 10 times heavier than before, you need 1/10 factor. And if we want to make the bag better than the bag of holding before, we need factor that is yet lower than 1/2 ot 1/4, that is, factor lower than 1/20 (uncursed) and 1/40 (blessed).

**Comment by janne-hmp** [comment]
Changed
