### ISSUE TITLE
New item: Potion of speed

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#241]
Doubles your speed for 120 turns. Calculated from your base speed.

- Unencumbered 12 → 24
- Burdened 9 → 18
- and so on

Intrinsic and Exstrinstic Speed do not have any effect how this potion functions. They also do not stack.

**Comment by janne-hmp** [comment]
The whole speeding system has been done rather badly. This is what does now:

                        if (Very_fast) { /* speed boots, potion, or spell */
                            /* gain a free action on 2/3 of turns */
                            if (rn2(3) != 0)
                                moveamt += NORMAL_SPEED;
                        } else if (Fast) { /* intrinsic */
                            /* gain a free action on 1/3 of turns */
                            if (rn2(3) == 0)
                                moveamt += NORMAL_SPEED;
                        }

Fast is a conferred property and Very Fast is kludge from extrinsic (item) fast property. Have to check how to do it properly.

**Comment by TommiGustafsson-HMP** [comment]
Actually, there seems to be a potion of speed already.
