### ISSUE TITLE
Cannot wield two-handed weapon after finishing two-weapon fighting

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#242]
![image](https://user-images.githubusercontent.com/16661034/66698061-7bc8cf80-ece3-11e9-9778-442bc8baf99b.png)

![image](https://user-images.githubusercontent.com/16661034/66698068-85eace00-ece3-11e9-942c-2ac2cbd7f531.png)

**Comment by janne-hmp** [comment]
This was intended behavior, but for the sake of simplicity  in single-weapon combat mode, an unused left hand weapon (but not a shield) is now automatically unwielded when trying to wield a two-handed weapon.
