### ISSUE TITLE
Change spellbook reading effects

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#243]
Reading a **cursed spellbook** confers 50% of time negative effects and the reading never succeeds. 50% of time they just fail and do nothing. After being read, they have a 1/3 chance to crumble to dust.

Reading a **blessed spellbook** automatically succeeds. It always crubles to dust.

Reading an **uncursed spellbook** has a chance to succeed, based on Int/Wis/Cha. The chance what it is now seems to be good, so it does not need to be changed. If the reading did not succeed, it has a 1/3 chance to crumble to dust. The failed reading never confers any negative effects. If the reading succeeded, it always crubles to dust.

**Comment by janne-hmp** [comment]
Done, also the spellbooks in the initial inventory have crumbled to dust.
