### ISSUE TITLE
Winged gargoyle on dungeon level 5?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#244]
![image](https://user-images.githubusercontent.com/16661034/66700353-f00d6e00-ecf7-11e9-828a-b0aad9235332.png)

**Comment by janne-hmp** [comment]
Fixed. The random generation for special levels seemed to work differently from normal random monster generation; it had 50% chance of accepting ordinarily to strong monsters.
