### ISSUE TITLE
Howling Flail Sacrifice gift did not unrestrict flail skills

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#250]

**Comment by janne-hmp** [comment]
Odd, it should indeed grant it. I tested with wizard who got a long sword, and long sword skill got then unrestricted.

**Comment by TommiGustafsson-HMP** [comment]
Now I got Long Sword name Giant Slayer, but it did not unrestrict longsword skill to Expert.

![image](https://user-images.githubusercontent.com/16661034/66915374-8fe13980-f021-11e9-8331-2d182b95b7ca.png)

**Comment by TommiGustafsson-HMP** [comment]
Unrestricting works only until Basic.
