### ISSUE TITLE
Increase usefulness of useless artifacts

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#251]
Orcrist
Sting
Werebane
Ogresmasher
Giantslayer
Grimtooth
Sunsword
Trollsbane

Mainly the damage could be increased, since they affect against such a small number of creatures (orcs, ogres, trolls, undead, lycanthropes). Also, they many times give +hit bonus, which is irrelevant in the late game.

**Comment by janne-hmp** [comment]
Did two new normal magic items: Sword of giant slaying and sword of troll slaying. Giant slaying sword give +1 to AC (and +4d12 against giants) and sword of troll slaying gives regeneration (and also +4d12 permanent damage and prevents trolls from reviving. Maybe some of the useless artifact should be moved to be normal magic items, where the system is now more powerful than with artifacts.

**Comment by janne-hmp** [comment]
Three new items: Sword of orc slaying and sword of dragon slaying. Orc slaying gives poison resistance and +1d12 to orcs. Dragon slaying gives +4d12 to dragons and reflection. Troll slaying gives now regeneration and +2d12 wounding damage to trolls. Giant slaying gives +4 to hit vs everything and 19 + enchantment strength (so +3 sword give 22 strength).

**Comment by janne-hmp** [comment]
Each slaying weapon confers a warning of the specific creature type they are intended to slay. Each such warning type is a new type of intrinsic ability.

**Comment by janne-hmp** [comment]
Usefulness of the artifacts has been improved in a separate issue.
