### ISSUE TITLE
Hobbits have a small chance of carrying Sting

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#254]
Hobbits have 1/40 chance to be generated with Sting. They have a chance to be generated with an elven dagger, too. Hobbits with Sting should be surprisingly dangerous, but not too deadly.

**Comment by janne-hmp** [comment]
Done, 1/3 of hobbits have an elven dagger, and 1/20 of those hobbits have Sting, so it equates to 1/60 chance.
