### ISSUE TITLE
Add character stat page

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#255]
Stat page would give your race, sex, and experience points among others. Everything, which is not shown in the status bar. One could also remove alignment from status bar and move it to the status page.

**Comment by TommiGustafsson-HMP** [comment]
Also, add experience required for next level.

**Comment by TommiGustafsson-HMP** [comment]
Key: Alt-u. If numpad is on, simple 'u'.

**Comment by janne-hmp** [comment]
Implemented under M('y') so that no key changes are needed. Untrap can be moved later under Abilities ('A').
