### ISSUE TITLE
New item: Flindbar

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#256]
Uses Quarterstaff skill.
Damage: 2d10 vs. small, 3d10 vs large.
Material: Iron or similar hard material
Weight: Like bar of iron

Flinds and flindlords have a chance of generating with a flindbar. It is a great choice for an end game weapon due to its high damage for classes that can specialize in quarterstaff.

**Comment by janne-hmp** [comment]
Done. Flinds have 50% chance of having a flindbar and flind lords 100% chance.
