### ISSUE TITLE
Magic skill learning from mixing

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#259]
Mixing gives (Spell Level + 2) * (Castings Given) skill experience. For example, mixing a 3rd level spell with 4 castings given per mixing gives (3 + 2) * 4 = 20 skill experience. Thus, you can have a spell that has a big material component (like a gem) and gives many castings, or a spell that has a small material component (such as bat guano or fungal spore) and gives just 1 casting. But because small material components are abundant, one can mix several spells at once.

So, in the end, skill experience-wise it does not matter if you mix once a big component and many times a small component, you will get the same skill experience.

**Comment by janne-hmp** [comment]
Done
