### ISSUE TITLE
Use magic system for crafting skills

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#260]
We could use the magic system for crafting skills as well. 

- Recipes are found just like spell books
- Recipes have a level like spells and school like spells (blacksmithing, leatherworking, etc.)
- Crafting skills use STR, DEX, and CON instead of INT, WIS, CHA
- They do not use mana
- Crafting has a chance to succeed just like spells, using the same formula
- However, armor do not hinder crafting
- Crafting skills do not have cast function (like Z)
- They have only mix function (like X)
- They use reagents just like spells but produce their end result immediately after mixing
- Some crafting skills need a forge to use
- Crafting skills can be Unskilled–Expert, just like magic skills

We could also move some spells to crafting schools, like create golem. Bone-crafting and necromancy could be merged, if needed.

**Comment by janne-hmp** [comment]
Agreed. Let's do that.

**Comment by TommiGustafsson-HMP** [comment]
Not implemented.
