### ISSUE TITLE
Use C for Crafting, move Call to #call

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#261]
Call is not so useful, so it can be moved to #call. Or Call can be Ctrl-C. Quit is already Alt-Q.

Like X for mixing spells, C for crafting.

**Comment by janne-hmp** [comment]
Docraft is now 'C'. Docall moved to ctrl-c and break to ctrl-b (not sure why it ever was ctrl-c).
