### ISSUE TITLE
Caveman's initial amulet is not worn at the beginning

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#266]

**Comment by janne-hmp** [comment]
I think this is a NetHack 3.6.2 feature, since the amulet can be cursed (or amulet of change).

**Comment by TommiGustafsson-HMP** [comment]
Is it possible to do that the amulet is uncursed, beneficial only? Starting equipment should not be cursed.

**Comment by janne-hmp** [comment]
It was already limited to useful amulets, so the amulet is now automatically worn. (Rings are not, though.)
