### ISSUE TITLE
Heavy Crossbow deals 30 damage on shot

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#267]
+0 Heavy crossbow
+0 quarrels
Strength 21, should not matter
Unskilled

How can it deal 30 points of damage per shot?

**Comment by TommiGustafsson-HMP** [comment]
Bow dealing 40 damage? With unskilled?

![image](https://user-images.githubusercontent.com/16661034/66918586-55c76600-f028-11e9-86e4-3f544c6580ad.png)

![image](https://user-images.githubusercontent.com/16661034/66918605-611a9180-f028-11e9-8d1b-4eae5bd3ae25.png)

![image](https://user-images.githubusercontent.com/16661034/66918649-7d1e3300-f028-11e9-8cb5-73b2f7086339.png)

**Comment by janne-hmp** [comment]
Fixed. Bug related to doubling attack damage.
