### ISSUE TITLE
dmnsremoved program in disorder

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#269]
Fought some demons that summoned others. This came long after the fight.

**Comment by janne-hmp** [comment]
These has to do with monsters getting 0 hp without killed-function called afterwards. Have to investigate.

**Comment by janne-hmp** [comment]
Tried to fix this by wounding damage taking maximum hit points only to 1 but not below, so HP cannot go to zero because of maxhp. Maybe a different problem, but hopefully this helps.

**Comment by janne-hmp** [comment]
Hopefully now resolved.
