### ISSUE TITLE
Modron Quinton casts spell: program in disorder

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#271]
![image](https://user-images.githubusercontent.com/16661034/66926960-a09caa00-f037-11e9-8f58-a1158fca1422.png)

![image](https://user-images.githubusercontent.com/16661034/66926980-aa261200-f037-11e9-9d1b-1128ffdb9c36.png)

**Comment by janne-hmp** [comment]
This has to do with limiting out some lower level monsters from random generation. Have to investigate.

**Comment by janne-hmp** [comment]
This was probably a bug with trying to create 'a' monsters (class 1), where -1 should have been used instead of 0 to indicate search failure.
