### ISSUE TITLE
Replace Giant Mimic in the deserted shop with a unique Mimic

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#272]
Soul Trapper
Unique Mimic
Green 'm'
Base Level 10
Speed 6 (double speed)
Attacks: Claw 3d8 Sticky, Claw 3d8 Sticky
Bace AC 6
Base MR 30
Resistances: Acid

In addition to the unique mimic, there could be a couple of giant mimics in the shop, and a couple of large mimics. Small mimics are a bit too easy at that dungeon level already.

**Comment by janne-hmp** [comment]
Done, but base level 12 and name Gargantuan Mimic.

**Comment by janne-hmp** [comment]
Actually used level 10 in the end, but lowered AC to 4 (twice the speed and AC bonus).
