### ISSUE TITLE
GnollHack crashes after loading a saved game and trying to view the inventory

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#273]
The save game file attached.

[tommi-wizard.zip](https://github.com/hyvanmielenpelit/GnollHack/files/3735261/tommi-wizard.zip)

**Comment by janne-hmp** [comment]
Worked alright with me. I suggest starting Debug mode in Visual Studio, and checking where it crashes there.

**Comment by TommiGustafsson-HMP** [comment]
Works for me now, too. Don't know what was the problem yesterday.
