### ISSUE TITLE
My caveman had field plate mail and robe of magic resistance but his MC was only 4?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#274]
That should be 6 at least. With the cloak it should be 7 or so. Why was it showing only MC 4/75%?

**Comment by TommiGustafsson-HMP** [comment]
I was able to duplicate the bug. You can wish for field plate mail and robe of magic resistance and wear them. Robe does not seem to add any MC.

**Comment by janne-hmp** [comment]
Fixed. One & too much.
