### ISSUE TITLE
Make Owlbear and Ape distinguishable by color

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#276]
Ape couldbe orange Y instead of brown. Ownbear can stay brown.

**Comment by TommiGustafsson-HMP** [comment]
Also, minotaur and ettin. Minotaur can be brown. Ettin could be orange, if that is free.

**Comment by janne-hmp** [comment]
Done, also changed sasquatch to be HI_LORD (magenta), since both it and monkey were gray.
