### ISSUE TITLE
Unknown lycanthropy program in disorder

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#278]
![image](https://user-images.githubusercontent.com/16661034/67140751-5ea57b00-f266-11e9-983a-a80496c29b60.png)

**Comment by TommiGustafsson-HMP** [comment]
![image](https://user-images.githubusercontent.com/16661034/67143592-a67fce80-f275-11e9-9ecb-c661687be6f5.png)

**Comment by janne-hmp** [comment]
Fixed, there was a copy-paste error marking elf mummy as a were-creature.
