### ISSUE TITLE
Remove attribute point exercise system

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#286]
Instead gain abilities by eating corpses

- Ogres give constitution, but not always (Ogre 33%, Ogre Lord 50%, Ogre King 75%)
- Snakes give dexterity, but not always (Garter Snake 2%, Snake 5%, Water Moccasin 1/12, Pit Viper 1/8, Python 1/10, Cobra 1/6)
- Nagas give wisdom, but not always (Naga Hatchlings 5%, Red Naga 20%, Black Naga 25%, Golden Naga 33%)
- Nymphs give charisma, but not always (All nymphs 33% chance – Remove conveying of teleportiis)

Other candidate for consitution is q (mumak etc.).

**Comment by janne-hmp** [comment]
Mind flayers give intelligence, ogres ok for constitution

**Comment by TommiGustafsson-HMP** [comment]
How about adding owls for wisdom? Also, owlbear could give wisdom.

**Comment by janne-hmp** [comment]
Done. The chance depends on the monster level, except for nymphs, for whom it is always 33%.

**Comment by janne-hmp** [comment]
Giants => STR
Snakes => DEX
Ogres & trolls => CON
Mind flayers & gray dragons => INT
Silver dragons, angels, and owlbears => WIS
Nymphs => CHA

**Comment by TommiGustafsson-HMP** [comment]
Trolls are not good for CON, since they need to be eaten for other purposes (to prevent resurrection).

Silver and gray dragons provide best dragon scalemails, so that's not so good either.

**Comment by TommiGustafsson-HMP** [comment]
Added more owlbears #293 . They can confer Wisdom.

**Comment by TommiGustafsson-HMP** [comment]
Added more ogres #294 .
