### ISSUE TITLE
New monster: Chaos Mimic

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#287]
Appears in Orcus town and in Gehennom.

Chaos Mimic
Orange or Yellow 'm'
Difficulty 21
Base Level 16
AC -2
Speed 12
Attacks 3d10 sticky, 3d10 sticky, 3d10 sticky
Base MR 40
Acid resistance, Fire resistance, Sleep resistance

It is a very dangerous hitter, capable of dealing 90 damage per round.

**Comment by janne-hmp** [comment]
Done
