### ISSUE TITLE
Add MC to monsters

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#289]
Or use MR for that?

What is MR anyways for? It does not resist death magic, and not lightning, fire, etc.? It is used for resisting taming. What else?

Monster MC is used to resist hitting them with a cockatrice corpse or other attacks that MC is normally used for. This will nerf cockatrice corpse hitting.

**Comment by janne-hmp** [comment]
Magic resistance is used in resists-function, which checks if the monster resists any magical effects or attacks. Each monster level increases MR by 1% and each attack level lowers it by 1% (so not that much).

**Comment by janne-hmp** [comment]
There is now differences: If monster is cancelled by wand of cancellation, it cannot use any of its special attacks, but it may bypass magic cancellation. For example, rust monster cannot rust if cancelled by the wand, but it is not affected by MC. It is unclear when MC is same as wand cancellation and when not. For example, MC may stop a slow attack but not influence a confusion attack. Maybe more clarity needed here. One could benefit from a proper saving throw system. Now it seems that you either use MC or you do not use anything (although monster attack success is random). E.g., there could be a WIS-based saving throw against a confusion attack, etc. This applies also to monster saving throws: A saving throw should be given against petrification, but at the moment there is nothing like that for any monster, just magic resistance against some magic attacks.

**Comment by TommiGustafsson-HMP** [comment]
Rust Monster is an exception, because it rusts armors. Thus armor-based MC does not help here.

**Comment by TommiGustafsson-HMP** [comment]
Resisting by MR is a bit strange, since it applies only to wand of striking and wand of magic missile but not to wand of fire, etc. as far as I know. And also it is completely different from other resists (such as fire resistance), which give 100% immunity. MR makes you only 50% immune to wand of striking, etc.

**Comment by janne-hmp** [comment]
Note that MC never affected cockatrice petrification, there is a fixed 1/30 chance of getting petrified.

**Comment by TommiGustafsson-HMP** [comment]
Maybe can be changed? 1/30 sounds crazy low.

**Comment by janne-hmp** [comment]
Sure. It can use MC chance instead. 1/3 of cockatrice attacks may petrify. Changing the chance of petrification to be based on MC.

**Comment by TommiGustafsson-HMP** [comment]
Also, there is now the question what is difference between AC and MC, because both depict how well you are protected.

**Comment by janne-hmp** [comment]
The difference clearly should be protection vs. physical and magical touch attacks. So MC acts as a saving throw vs. energy/life drain, cockatrice petrification, ghoul paralysis, slow etc. But other non-touch attacks such as umber hulk confusion and medusa gaze should probably use another saving throw, e.g. based on wisdom or constitution.

Also, we can do so that many items give much more AC than MC and vice versa. Cloaks and robes probably should give mostly MC. So also brooch of shielding.

**Comment by TommiGustafsson-HMP** [comment]
How about Green Slime's sliming? It has fixed 25% success chance, right?

**Comment by janne-hmp** [comment]
It is affected by MC, so it needs to bypass MC and after that it has 25% chance of success.

**Comment by TommiGustafsson-HMP** [comment]
With our MC system, it could have 100% chance to succeed.

**Comment by janne-hmp** [comment]
Done. All monsters have now base MC, and cockatrice petrifies at 100% chance unless MC succeeds with every 3rd hit.
