### ISSUE TITLE
Mind-affecting spells (like taming/charm) resisted by Wisdom

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#291]
Chance to fail:

- Wis 6 or below: 0%
- Wis 7: 5%
- Wis 8: 10%
- Wis 9: 15%
- Wis 10: 20 %
- Wis 11: 25%
- Wis 12: 30%
- Wis 13: 35%
- Wis 14: 40%
- WIs 15: 45%
- Wis 16: 50%
- Wis 17: 55%
- Wis 18: 60%
- Wis 19: 65%
- Wis 20: 70%
- Wis 21: 75%
- Wis 22: 80%
- Wis 23: 85%
- Wis 24: 90%
- Wis 25: 95%

Additionally, monsters can be charm-resistant, which gives them 100% chance to resist charm, regardless of wisdom.

**Comment by janne-hmp** [comment]
Done. Charming needs to bypass both magic resistance and wisdom check. There is also a new charm resistance intrinsic, which is though not used currently by any monster.

Spells can now give -X to saving throw. Domination give -4 to the WIS saving throw.

The curve is slightly different from above.
