### ISSUE TITLE
New monsters: Owlbear Shaman, Owlbear Matriarch, Owlbear Patriarch

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#293]
**Owlbear Shaman**
Difficulty 12
Base Level 8
Speed 12
AC 4
Attacks: Claw 1d8, Claw 1d8, Hug 2d10, Spellcasting (clerical)

**Owlbear Matriarch**
Difficulty 20
Base Level 16
Speed 15
AC 1
Attacks: Claw 2d6, Claw 2d6, Hug 4d8, Spellcasting (clerical)
Appears in Gehennom

**Owlbear Patriarch**
Difficulty 22
Base Level 20
Speed 16
AC -2
Attacks: Claw 2d8, Claw 2d8, Hug 4d10
Appears in Gehennom

**Comment by janne-hmp** [comment]
Done
