### ISSUE TITLE
New Monsters: Ogre Emperor, Ogre Mage, Ogre Archmage

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#294]
**Ogre Emperor**
Difficulty 18
Base Level 15
Base AC 2
Base MR 80
Speed 16
Attacks: Weapon 3d10, Projectile 3d10
Appears in Gehennom

**Ogre Mage**
Difficulty 15
Base Level 12
Base AC 3
Base MR 90
Speed 15
Attacks: Weapon 3d6, Projectile 3d6, Mage Spell-casting

**Ogre Archmage**
Difficulty 26
Base Level 18
Base AC 0
Base MR 95
Speed 18
Attacks: Weapon 3d12, Projectile 3d12, Mage Spell-casting
Appears in Gehennom

**Comment by janne-hmp** [comment]
Done
