### ISSUE TITLE
Change armor MC

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#297]
The armor hardness affects only AC but not MC. Thus, 

MC 1:

- All body/breast armors, regardless of material
- Gray and silver dragon scale mails

MC2:

- All cloaks except protection
- Field plate mail
- All other dragon scale mails

MC3:

- All robes
- All full plate mails
- Cloak of protection
- Brooch of shielding

Ring of protection might also give only +1 or +2 to MC.

**Comment by janne-hmp** [comment]
Adjusted.
