### ISSUE TITLE
Change robes to occupy the armor slot? 

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#298]
They are now too good for non-spell casters. They have no downside being worn over heavy armor.

**Comment by janne-hmp** [comment]
Maybe think of some extra penalty for being worn with armor? Robes need their own slot, as there is a controversy in NetHack community whether they should be armor or cloaks (so make them neither).

**Comment by TommiGustafsson-HMP** [comment]
In WoW, they are cloth armor.

I guess the only problem is with priests that might want to wear armor and a robe. But in WoW, priests can wear only cloth armor.

**Comment by janne-hmp** [comment]
Robes and armors do not stack any more. They give the greater of AC and MC provided. This is indicated in the inventory.
