### ISSUE TITLE
Warhammer Ogresmasher did not increase constitution to 25

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#304]
![image](https://user-images.githubusercontent.com/16661034/67276664-d75a4080-f4cd-11e9-8a0c-e057f99c8d2d.png)
 
![image](https://user-images.githubusercontent.com/16661034/67276670-df19e500-f4cd-11e9-9f83-29b290faee28.png)

**Comment by janne-hmp** [comment]
Seems like collateral damage of the system change... Will be fixed in the future.

**Comment by janne-hmp** [comment]
Fixed with the brand new artifact system.
