### ISSUE TITLE
Crossbow at Expert level does not shoot two quarrels

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#305]

**Comment by janne-hmp** [comment]
You need some strength for it.

**Comment by TommiGustafsson-HMP** [comment]
But it works at skilled ok. Should not work at skilled either.

**Comment by TommiGustafsson-HMP** [comment]
When you wield the crossbow (using w or x) and your skill is at skilled or expert, it should say that "However, you do not have enough strength for multishot."

**Comment by janne-hmp** [comment]
This was a bug for P_SKILLED but the system has been changed now.
