### ISSUE TITLE
Nymph attack affected by MC?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#307]
Should stealing attacks be affected by MC? I think one nymph failed to steal items from me.

**Comment by janne-hmp** [comment]
Yes, it needs to by pass MC at the moment. Nymph zapped with the wand of cancellation cannot steal items either.

**Comment by TommiGustafsson-HMP** [comment]
Well, it makes nymphs a lot less dangerous than before. They also teleport away after failing to steal.

**Comment by TommiGustafsson-HMP** [comment]
If we want to make them respect MC, maybe give them some give penalty to MC, like -5??

**Comment by janne-hmp** [comment]
All nymphs are level 3. They all have now -5 to MC.

**Comment by TommiGustafsson-HMP** [comment]
How about Monkey and Wizard of Yendor?
