### ISSUE TITLE
Missile weapons a bit too good?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#308]
Boots of speed + missile weapon is a very potent combo

Also, when you get multishot, it is even better.

Even without the multishot, the missile weapons are pretty good at the moment.

Balance should be considered.

My rogue did something like 10–12 damage per quarrel with a crossbow +1, but only 1–6 damage with a short sword.

**Comment by TommiGustafsson-HMP** [comment]
How about missile weapons getting only half strength bonus? Then, crossbow strength damage could be tuned down. Also, thrown weapons should get only half strength bonus.

**Comment by janne-hmp** [comment]
New item: Repeating Crossbow. It is now possible to multishoot with multishot weapons. They can be marked to require skill level.

**Comment by TommiGustafsson-HMP** [comment]
Still, many times missile weapons do more damage than melee weapons. If you have a bow and arrows or sling and stones, they can easily do more damage than some basic melee weapon.

**Comment by TommiGustafsson-HMP** [comment]
Should be now solved with added melee damage.
