### ISSUE TITLE
Power word kill 500 mana

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#318]
![image](https://user-images.githubusercontent.com/16661034/67410431-c50efe00-f5c4-11e9-8f8d-b1c3dd62a965.png)

Not too useful.

**Comment by TommiGustafsson-HMP** [comment]
Maybe reduce mana cost and put a really long cooldown for the spell, like 600 turns.

**Comment by TommiGustafsson-HMP** [comment]
Maybe level 10 spell with 240 mana cost with 1000 turn cooldown?

**Comment by janne-hmp** [comment]
Done. 300 mana with 500 turn cooldown.
