### ISSUE TITLE
Increase generated monster difficulty

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#334]
Maybe we need to muliply (Dungeon Level + Character Level) by a value? Maybe 1.5 could be ok?

Another possibility would be to use 2 x (Dungeon Level) + (Character Level) formula. Then, the character level would not unnecessarily increase difficulty. I think this is a better option.

Also, some hard monsters are marked for Gehennom only. They should appear before Gehennom, if needed. I think it is possible even now. At least, I encountered Flindlord before Medusa level.

**Comment by janne-hmp** [comment]
Implemented. The game first tries to find monsters in a tighter range (2d+c)/6 ... (2d+c)/2, which has a mid-point of (2d+c)/3. If not found, then it tries again and progressively widens the range.
