### ISSUE TITLE
Ctrl+8 and Ctrl+9 to select all miscellaneous magic items and all reagents in multi-select view

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#338]
In a multi-select view, such as drop many (D) or put items in a bag, you can select item categories by their symbols, for example, scrolls by pressing '?'. However, miscellaneous magic items and reagents are bound to a number. Let's make so that Ctrl+8 and Ctrl+9 can be used to select them in a multi-select view.

**Comment by janne-hmp** [comment]
It is now '8' and '9', making the use of counting slightly more difficult. But maybe counting is not super-useful in "drop all" view. Or counting needs to be initiated by a special character (however, 'n' does not do here) etc. Need a new system. Not sure if Ctrl or Alt can be made to work here, but special ASCII keys like DEL, backspace and tab might work...

**Comment by janne-hmp** [comment]
Counting in menus works now by pressing '#' first (or any number between 1-7 as the first symbol).
