### ISSUE TITLE
Ioun stones are a bit too common

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#339]
Multiple ioun stones are found each game.

**Comment by janne-hmp** [comment]
Would other types of miscellaneous items been better or other types of items than misc magic items?

**Comment by TommiGustafsson-HMP** [comment]
Maybe reduce chance of miscellaneous magic items a bit.

**Comment by janne-hmp** [comment]
Fixed. They are now pretty rare.
