### ISSUE TITLE
Gnoll barbarian could detect javelin of returning and sword of orc slaying without identification

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#340]
Intended behaviour?

**Comment by janne-hmp** [comment]
Intended in NetHack as an extra bonus to fighting characters, but may be best to limit to non-magical items or remove altogether. It does not seem to add much. Most normal items are known by default.

**Comment by janne-hmp** [comment]
All weapons were marked non-magical. Barbarian was not intended to identify magical weapons. Fixed.
