### ISSUE TITLE
Attack spells to have material components?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#342]
Magic Arrow: Arrow or Bolt, 10 castings
Magic Missile: Dart, 10 castings
Lightning Bolt: Copper Ore, 10 castings
Fire Bolt: Piece of Wood, 10 castings

And so on. 

Would make components more useful and limit spell casting a bit. Maybe all spells would have a material component or a cooldown to limit its use?

We need to adjust magic skill levels higher probably, since each casting should give (Spell Level + s) skill experience.

**Comment by janne-hmp** [comment]
Done, fire spells use a new sulfurous ash material component.
