### ISSUE TITLE
New monsters: Wraith Lord & King wraith

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#343]
Wraith Lord
Base Level 12
Speed 16
AC 1
Attacks 3d6 Drain life (-2 to MC)

King Wraith
Base Level 18
Speed 20
AC -4
Attacks 6d6 Drain life (-4 to MC)

**Comment by janne-hmp** [comment]
There is already a Nazgul, ringwraith?

**Comment by TommiGustafsson-HMP** [comment]
These leave a corpse that can be eaten for a level.

**Comment by TommiGustafsson-HMP** [comment]
Wraith Lord could also be a Spectre.

**Comment by janne-hmp** [comment]
Done. Nazgul made to be a bit more challenging, too.
