### ISSUE TITLE
Triple flail to hit 3 times?

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#344]

**Comment by TommiGustafsson-HMP** [comment]
Could be. Would be a good end game weapon for gnolls.

**Comment by janne-hmp** [comment]
Done. Triple-headed flail's ability to hit many times depends currently on the user's flail skill level (basic = 1, skilled = 2, expert = 3). Double-headed flail gives 1/1d2/2 multiattack depending on the skill level. Darts and shurikens can be thrown many times at different skill levels (1/1d2/2). Multiattacks can be specified for any launcher, throwing weapon, and melee weapon.
