### ISSUE TITLE
Update in-game documentation

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#346]
Mainly all files found under ?.
Some are already updated. Some are half-updated. Some not updated at all.

**Comment by janne-hmp** [comment]
Updated keyboard shortcuts (see the appropriate commit for description) and added Alt-c for a list of main extra commands, so you do not remember them all or their keyboard shortcuts by heart.

**Comment by janne-hmp** [comment]
Done.
