### ISSUE TITLE
Indicate learning success when reading a spellbook

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#347]
"It feels easy to understand." or like

- easy: 80–100% success
- rather easy: 60–79% success
- rather difficult: 40–59% success
- difficult: 20–39% success
- very difficult: 0–19% success

Blessed spellbook and cursed spellbook indicate the success of the uncursed one, even though in reality chance to succeed is different.

**Comment by janne-hmp** [comment]
Done.
