### ISSUE TITLE
Adjust experience points required for each level

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#354]
Basic algorithm is quite bad for high levels. They require too much experience:
https://nethackwiki.com/wiki/Experience_level

Maybe we could use one from dNethack or FIQHack (see in above link).

Maybe we could also adjust experience points gained from monsters.
https://nethackwiki.com/wiki/Monsters_(by_experience)

I think (Difficulty Level)^2 could be a good figure. 10000 points from level 100 monster, 1 point from level 1 monster.

**Comment by janne-hmp** [comment]
Done
