### ISSUE TITLE
Jackal difficulty level 2?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#359]
Should jackal be difficulty level 2? It is the most dangerous creature, according to statistics on NAO. Now I put -1 adjustment to it to keep it level 1, but maybe it should be level 2, because it appears in small packs.

**Comment by janne-hmp** [comment]
Have to test. It feels quite alright. Never seemed particularly difficult to me.

**Comment by janne-hmp** [comment]
Obsolete. v4 levels seem ok.
