### ISSUE TITLE
Experience point rounding

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#360]
Experience gained per monster level = 1+ (Difficulty Level)^2

- No rounding: Levels 0–4
- Nearest 5: Levels 5–9
- Nearest 10: Levels 10–49
- Nearest 50: Levels 50–99
- Nearest 100: Levels 100–499

For example: 
- Level 5: 1+25 = 26 → 25
- Level 6: 1+36 = 37 → 35
- Level 10: 1+ 100 = 101 → 100
- Level 11: 1 +121 = 122 → 120
- Level 50: 1 + 2500 = 2501 → 2500
- Level 51: 1 + 2601 = 2602 → 2600
- Level 100: 1 + 10000 = 10001 → 10000
- Level 101: 1 + 10201 = 10202 → 10200

**Comment by janne-hmp** [comment]
Done, but rounded always down; just much easier to do.
