### ISSUE TITLE
Encounter Difficulty

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#363]
Encounter difficulty can be calculated as follows:

max_encounter_difficulty = Sum of all Monster Difficulty Levels

But because all monsters cannot attack together, we need to apply an adjustment.
Let's estimate that number of attacking monsters is max 2 in Dungeons of Doom, 3 in Gnomish Mines, and 4 in open spaces, such as Big Room. This is max_attacking_monsters. Total number of monsters in encounter is total_monsters.

final_encounter_difficulty = MIN(1, SQRT(max_attacking_monsters/total_monsters)) * max_encounter_difficulty

This has to rounded to nearest integer.

For example, 3 soldier ants attacking in Dungeons of Doom have the max_encounter_difficulty of 18 (3 times 6). final_encounter_difficulty is SQRT(2/3)*18 = 14,7 which rounds to 15.

**Comment by TommiGustafsson-HMP** [comment]
Some more thoughts. The real difficulty of monsters is actually Power of 2 of Difficulty Level, because we applied square root at the end of calculations. It means that difficulty levels are in a way adjusted to be lower than in reality by a square root.

I was thinking about how you can add difficulty levels together to form an encounter difficulty. If all monsters can attack the player you can calculate square rooted combat values together, because in reality the monsters are number^2 more difficult, for example, 2 monsters have double attack power and double hit points, so the total effect is 4. And to take a square root from that yields 2. However, because one monster dies before end of the combat, you need to apply modifier to attack power, which is:

SUM from number_of_monster to 1 as i (i/number of monsters^2)

For example two monsters =2/4 + 1/4 = 3/4. Three monsters 3/9 + 2/9 + 1/9 = 6/9 = 2/3. Let's name this group_adjustment_modifier.

When calculating square rooted combat values, that needs to be square rooted as well. So, if two monsters can attack the player together. The combat value of a group is

Sum of all Difficulty Levels * SQRT(group_adjustment_modifier)

However, if monsters cannot attack together, we have already spoken of that above. But let's consider a case, where 3 soldier ants attack one-by-one the player, so that only one can attack at a time. In this case, we cannot sum difficulty levels together, but we need to take a square root of the number. This is because real combat value is only 3 times of a single soldier ant, because attack power is only that on 1 soldier ant, but hit points are tripled. Then taking a square root brings us to SQRT(3).

This means that if we have sequential encounters, for example, 3 soldier ants that attack one-by-one, we cannot add their difficulty levels together to form the total encounter difficulty, but we need to take a square root of the number. So, the encounter difficulty of these 3 soldier ants would be 6 times SQRT(3) = 10.4. The experience gained from this encounter is right, because each ant gives 35 experience = 105 experience points. An encounter of 10 difficulty would give 100 experience points and encounter of difficulty 11 120 experience points.

The case of having multiple units, of which only a few can attack together is more difficult, but can perhaps be calculated using some examples. Let's take 3 soldier ants, of only which 2 can attack together. Then the group adjustment modifier is calculated as follows:

SUM from number_of_monsters to 1 as i (MIN(max_attacking_monsters, i) / number_of_monsters) * (1 / number_of_monsters)

Thus, for 3 soldier ants that only 2 can attack together, group_adjustment_modifier is:
(2/3) * (1/3) + (2/3) * (1/3) + (1/3)*(1/3)
= 2/9 + 2/9 + 1/9 = 5/9

And 18 * SQRT(5/9) = 13,4

Furthermore, we could investigate what happens when the encounter has different types of units, but let's leave that for a later time.

**Comment by TommiGustafsson-HMP** [comment]
**Formula for different unit types**

For example, encounter of 1 level 12 monster and 2 level 5 monsters. Let's calculate first the max and min bounds.

_Maximum difficulty level = Sum of difficulty levels_

This is valid, when all monsters can attack and they die at the same time, i.e. no focus fire. This is rarely a case, but it is good to know that it is theoretical maximum difficulty. It is 22 for this encounter.

_Minimum difficulty level = SQRT(Sum through all monster_types of (number_of_monster_type^2 * monster-type_difficulty_level^2))_

Here this is SQRT(1*12^2 + 2^2*5^2)) = 15.6. This is the encounter level when all monsters in the encounter can attack one by one.

The real encounter level is somewhere between these two values. It is useful to calculate also the value of a real encounter where all monsters can attack together and they die one-by-one, which is usually the case. This can be calculated as follows:

1. Create a table with monster difficulty levels from highest to lowest.
2. Loop through the table and remove one monster by one monster from the table
3. First, all monsters are alive and deal (Sum of All Difficulty Levels) (i.e. 22) over (First Monster Difficulty Level) / (Sum of All Difficulty Levels)
4. Multiply these values together → 12
5. Move to next monster, it deals damage (Sum of All Difficulty Levels) - (First Monster Difficulty Level) damage over (Second Monster Difficulty Level) / (Sum of All Difficulty Levels)
6. Multiply these values together → 2,27
7. Move to next monster, it deals damage (Sum of All Difficulty Levels) - (Sum of Previous Monster Difficulty Levels) damage over (Third Monster Difficulty Level) / (Sum of All Difficulty Levels)
8. Multiply these values together → 1,14
9. Sum multiplied values together → 15,41
10. Calculate total Combat Value of the encounter by multiplying the above sum with (Sum of All Difficulty Levels) → 339
11. Calculate Encounter Difficulty Level by taking a square root → 18,41. This is nicely between MIN and MAX values.

A similar procedure can easily be adjusted, when only a couple of monsters can attack the player together. We just need to adjust the damage dealt not to be sum of all living monster difficulty levels but limited to sum of biggest living monster difficulty levels up until max_attacking_monsters have been included. For example, if max_attacking_monsters is 2, we need adjust damage calculation to be sum of two biggest living monster difficulty levels. In the above example, then the first value (in step 3) would be adjusted from 22 to 17, and thus the final Encounter Difficulty would be 16,70. This is nicely between MIN and the above value, where all monsters could attack together.

**Comment by TommiGustafsson-HMP** [comment]
### **Encounter extra experience points**

All monsters can be assigned Extra Experience Points upon creation. If monsters belong to an encounter, calculate Encounter Difficulty Level. Then, Encounter Experience Points can be calculated as follows:

_Encounter Experience Points = 1 + (Encounter Difficulty Level)^2_

Note that you may use non-rounded Encounter Difficulty Level here, or the Combat Value, which is (Encounter Difficulty Level)^2. Then calculate the sum of invidual experience points from monsters:

_Individual XP Sum = Sum over all monsters of ROUND((1 + (Monster Difficulty Level)^2))_

Each item in the sum is rounded like monster difficulty levels are.

Then calculate the difference:

_Difference = (Encounter Experience Points) - (Individual XP Sum)_

If Difference is positive, divide this amount among all monsters weighted by their difficulty level:

_Monster Extra Experience Points = Difference * (Monster Difficulty Level) / (Sum of all Monster Difficulty Levels)_

This way, bigger monsters convey more bonus experience points and smaller fewer. If Sum of all Monster Difficulty Levels is 0, Monster Extra Experience Points is 0 as well. If Difference is 0 or negative, Monster Extra Experience Points are 0 as well.

**Comment by TommiGustafsson-HMP** [comment]
Monster Extra Experience Points can be also divided among monsters by weighting according to the experience given rather than the difficulty level. Then, the formula is

_Monster Extra Experience Points = FLOOR(Difference * (Monster Experience Points) / (Sum of all Monster Experience Points))_

where

_Monster Experience Points = ROUND(1 + (Monster Difficulty Level)^2))_

**Comment by janne-hmp** [comment]
Monster encounters can now be defined. Monster items and extra experience points are not working yet, but the basic functionality is working. Have to still work on which groups can be generated in hell or elsewhere etc. Small and large groups have not been deactivated yet.

**Comment by janne-hmp** [comment]
Encounter difficulty system does not seem to work with level 0 monsters.

**Comment by TommiGustafsson-HMP** [comment]
Don't know if it works, but maybe level 0 monsters could be calculated as having level 0.5.

**Comment by TommiGustafsson-HMP** [comment]
Another possibility would be that Level 0 Monsters' Combat Value is 0.5 (because they give 1/2 experience compated to Level 1 monsters). Therefore, their difficulty level would be SQRT(0.5) = 0,7071.

**Comment by TommiGustafsson-HMP** [comment]
Procedure to calculate exact encounter difficulty, when max_attacking_monsters > 1. max_attacking_monsters can be 8 at most, since more monsters cannot attack the player at the same time. Let's calculate the previous example, when max_attacking_monsters = 2.

1. Create a table with monster difficulty levels from highest to lowest. In this case, it would have items 12, 5, 5.
3. Loop through the table, setting monster_index as the loop variable
4. First, all monsters are alive and deal damage of (Sum over the monster difficulty table from monster_index to monster_index + max_attacking_monsters - 1 or at the end of the table, whichever comes first) (here it is, 12 + 5, because monster_index = 0 and monster_index + max_attacking_monsters - 1 = 1; so we take difficulty levels from indices 0 and 1, that is 12 and 5 and sum them together; which results in 17) over (First Monster Difficulty Level) / (Sum of All Difficulty Levels)
5. Multiply these values together → 9,27
6. Move to next monster. monster_index = 1 now. It deals damage (Sum over the monster difficulty table from monster_index to monster_index + max_attacking_monsters - 1 or at the end of the table, whichever comes first) damage over (Second Monster Difficulty Level) / (Sum of All Difficulty Levels). Here, monster_index + max_attacking_monsters - 1 = 2, so we sum together 5 and 5, which results in 10.
7. Multiply these values together → 2.27
8. Move to next monster. Now monster_index = 2. It deals damage (Sum over the monster difficulty table from monster_index to monster_index + max_attacking_monsters - 1 or at the end of the table, whichever comes first) damage over (Third Monster Difficulty Level) / (Sum of All Difficulty Levels). Here, monster_index to monster_index + max_attacking_monsters - 1 = 3 but the table ends at index 2. So, the damage per time is just 5.
9. Multiply these values together → 1.14
10. Sum multiplied values together → 12.68
11. Calculate total Combat Value of the encounter by multiplying the above sum with (Sum of All Difficulty Levels) → 279
12. Calculate Encounter Difficulty Level by taking a square root → 16.70.

**Comment by janne-hmp** [comment]
Done. Encounter difficulty is now calculated for attacking monster counts from 1 to 8. In run time while on various dungeon levels, you can pick the right number for the array.
