### ISSUE TITLE
Indicate in Sokoban that squeezing into boulders brings bad luck

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#369]
When you squeeze into the same space as with boulders should have a text indicating that you received bad luck.

Similarly, when Sokoban is finished, it should indicate that the bad luck has been removed, or whatever other luck changes occur.

**Comment by TommiGustafsson-HMP** [comment]
This is the actual list of luck changes in Sokoban:


−1 | Jumping on a Sokoban level before solving the puzzle.
−1 | Breaking a boulder in Sokoban before solving the puzzle.
−1 | Casting stone to flesh on a Sokoban boulder before solving the puzzle.
−1 | Polymorphing a Sokoban boulder before solving the puzzle.
−1 | Reading a scroll of earth in Sokoban before solving the puzzle.
−1 | Being pulled by a thrown heavy iron ball in Sokoban before solving the puzzle.
−1 | Hurtling through the air in Sokoban by throwing something while levitating before solving the puzzle.
−1 | Squeezing past a boulder in Sokoban (or walking over one when polymorphed into a giant) before solving the puzzle.

**Comment by janne-hmp** [comment]
Done as a part of luck notification system.
