### ISSUE TITLE
Endless stream of sewer rats

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#370]
![image](https://user-images.githubusercontent.com/16661034/69325338-a9922400-0c52-11ea-80be-0ad0de01c1f3.png)

There was an endless stream of sewer rats in the first level. I think I killed something like 7 of them until they killed me. What is going on?

**Comment by TommiGustafsson-HMP** [comment]
Even level 2 Barbarian could not make it against endless sewer rats...

![image](https://user-images.githubusercontent.com/16661034/69325941-a5b2d180-0c53-11ea-9e43-dc873eff99ff.png)

**Comment by TommiGustafsson-HMP** [comment]
It took me 1016 turns to clear the first dungeon level of rats. And got to level 4.

![image](https://user-images.githubusercontent.com/16661034/69327132-ab111b80-0c55-11ea-84a0-f4cb981e0cdc.png)

Should not be like that...

**Comment by TommiGustafsson-HMP** [comment]
Rats spawn just beside me in Gnomish Mines:
![image](https://user-images.githubusercontent.com/16661034/69333028-94bc8d00-0c60-11ea-9363-8e2aca2b1b8d.png)

**Comment by janne-hmp** [comment]
Fixed
