### ISSUE TITLE
Spell (level 9) that gives temporary life saving

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#38]
E.g., by giving a timed amulet of life saving

**Comment by TommiGustafsson-HMP** [comment]
Could be, but requires an expensive component. Perhaps blessed emerald?
Could be in the abjuration school. Lasts 60 turns. Cooldown 240 turns. (Cannot be used repeatedly.)

**Comment by janne-hmp** [comment]
Divine intervention. Implemented. Requires spider silk and blessed pearl. Can add more, if need be.
