### ISSUE TITLE
Remove figurines and nerf polymorph control

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#380]
I wished for a blessed figurine of Archon and got a level 98 monsters as a pet. It killed almost all monsters, including shopkeepers, in one or two hits.

Similarly, something should be done for polymorphing into ancient dragons etc. Polymorph and polymorph control should be limited to in-difficulty monsters.

**Comment by janne-hmp** [comment]
Done.
