### ISSUE TITLE
Dragonbane and other similar artifacts to do 3-4x damage against specific monsters

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#388]
Now they apparently do only 2x damage, which is not enough, as they are effective only a very small range of creatures. They should be really effective against such monsters.

**Comment by janne-hmp** [comment]
Fixed, general artifact weapons do 2x damage, while specific ones 3x. In addition, changed base weapons for Giantslayer to be sword of giant slaying slaying, Dragonbane sword of dragon slaying, Trollbane morning star of troll slaying, giving more abilities.
