### ISSUE TITLE
Not sure if Sunsword did any extra damage against undead

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#389]
Minor 'z' did not probably receive any extra damage... Should be 3-4x like with improved Dragonbane. Sunsword should be the best sword against any undead.

It would be neat if Sunsword did extra damage also against demons and imps.

Sunsword should be better than silver weapons, even though it is not a silver weapon.

**Comment by janne-hmp** [comment]
Now does quadruple damage, since it is not a silver weapon and has a standard base weapon. It works now also against demons.
