### ISSUE TITLE
Lawful characters have trouble getting any ores

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#390]
You normally get ores from dwarves that have done mining for you. They are peaceful to lawful characters. As a result, one has no ores and thus no components for spells using ores.

I suggest that ores will be removed from the game, as it is inconvenient to mine them. Or, their mining should be done easier. Getting pick axe easier for lawful characters and locating ores easier. Now, it is impossible or tedious.

**Comment by janne-hmp** [comment]
How about buying them from dwarves through Chat functionality? Maybe the dwarves can even offer them to the character by shouting at them from a distance?

**Comment by janne-hmp** [comment]
You can buy the ores from dwarves now.
