### ISSUE TITLE
Make attacking peaceful monsters more penalizing

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#404]
Now it gives alignment penalty, which does not work well.

Should probably give -1 or -2 luck.

The alignment penalty system should be reworked or rejected.

The same with other offenses.

The game should indicate what penalty was incurred from each offense.

You-page could show your luck or a written statement about your luck.

**Comment by TommiGustafsson-HMP** [comment]
Some luck penalties are already there:

−1 | Killing a tame monster.
−1 | Killing a peaceful monster (sometimes). See note below.
−2 | Killing a peaceful human when you are not chaotic. ("You murderer!")
−5 | Killing a co-aligned unicorn.
−5 to −2 | Cannibalism (eating your own species), unless an orc or a caveman.

**Comment by janne-hmp** [comment]
Ok like that.
