### ISSUE TITLE
Belt of hill giant strength gives strength 20

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#405]
Not 19?

**Comment by janne-hmp** [comment]
A design choice, since there are fewer giants in GnollHack than in AD&D. Also, other items give STR as follows: Sword of giant slaying => 19. Gauntlets of ogre power => 18/00, Nose ring of bull strength => 18/76.

**Comment by janne-hmp** [comment]
Closed.
