### ISSUE TITLE
Make low constitution characters gain more HP by level

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#409]
Level 3 and only 20 HP.

![image](https://user-images.githubusercontent.com/16661034/70115412-f4745880-16a2-11ea-8c7a-702a4866b9b6.png)

**Comment by janne-hmp** [comment]
Fixed. The formula for CON HP bonus is now max(-2, (min(25, con) - 7) / 2).
