### ISSUE TITLE
Should demon lords use summon abilities from a distance and just closeby?

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#41]

**Comment by TommiGustafsson-HMP** [comment]
Distance summoning will fill the level with monsters and should be severely restricted.

**Comment by janne-hmp** [comment]
Maybe if the use of the summon ability is limited by e.g. 3 / day etc., remote use could work, too.

**Comment by janne-hmp** [comment]
This is deferred. The current system works ok.
