### ISSUE TITLE
Make pet starvation cleaerer

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#412]
Now, it is easy to miss pet starvation. In a fast paced game, messages come and go. Is it possible to give colors to messages like white, yellow, red?
- White: Info message
- Yellow: Warning message
- Red: Critical message

Also, if you want to check your pet's nutrition status, you might see it after its HP by using /. For pets, which do not eat, it should show N/A or something.

**Comment by janne-hmp** [comment]
There are now many messages. Fixed.
