### ISSUE TITLE
Thrown potions could be more dangerous

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#419]
Maybe make duration 2x? Examples: Potion of Sleep, Potion of  Paralysis, etc.

**Comment by TommiGustafsson-HMP** [comment]
Potion of Paralysis
- thrown at you could be increased from 1d5 turns to 2d4 turns.
- thrown at monster could be changed from 1d25 turns to 4d4 turns. Why is it different?

Potion of Sleeping
- thrown at you could be increased from 1d5 turns to 2d4 turns.
- thrown at monster could be changed from 1d25 turns to 4d4 turns. Why is it different?

Potion of Blindness
- thrown at you could be 4d8 turns. What it is now is unknown.
- thrown at monster could be 4d8 turns.

Potion of Confusion
- thrown at you could be 4d8 turns. What it is now is unknown.
- thrown at monster could be 4d8 turns.

Potion of Acid
- thrown at you it will cause 2d8 damage. What it is now is unknown.
- thrown at monster will cause 2d8 damage.

**Comment by TommiGustafsson-HMP** [comment]
To-hit coul be increased to Dex in 20 with always a 2 % fail chance at Dex 20+.

**Comment by janne-hmp** [comment]
Done, except for DEX check. Hopefully not too dangerous.
