### ISSUE TITLE
Spell (low level) that gives more AC?

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#42]

**Comment by janne-hmp** [comment]
Like Mage Armor

**Comment by TommiGustafsson-HMP** [comment]
Mage Armor
- Creates Magical Armor giving 4 AC
- Lasts 240 turns
- Must be worn as armor
- Does not prevent spell casting
- Weighs 0
- Abjuration Level 1

**Comment by janne-hmp** [comment]
Implemented
