### ISSUE TITLE
Burdened status comes on and off

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#422]
![image](https://user-images.githubusercontent.com/16661034/70210738-cbbd9300-1776-11ea-9784-00e8450ea161.png)

![image](https://user-images.githubusercontent.com/16661034/70210751-d4ae6480-1776-11ea-9aad-817e53edc5ad.png)

![image](https://user-images.githubusercontent.com/16661034/70210759-dd9f3600-1776-11ea-8767-da9c9b9138b1.png)

![image](https://user-images.githubusercontent.com/16661034/70210768-e55eda80-1776-11ea-91d5-5df2dd6dc848.png)

**Comment by janne-hmp** [comment]
Fixed.
