### ISSUE TITLE
Trying to wear tailored silk robe -> Program in disorder

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#429]
![image](https://user-images.githubusercontent.com/16661034/70295533-b99d2c80-182a-11ea-88e3-0ad6f0b2f466.png)

![image](https://user-images.githubusercontent.com/16661034/70295546-c3bf2b00-182a-11ea-9be7-1ca6b9da3e07.png)

**Comment by janne-hmp** [comment]
Fixed.
