### ISSUE TITLE
Prevent a running character from entering known traps

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#430]
Now they happily run into known traps.

**Comment by janne-hmp** [comment]
For me, the character always stopped in front of the trap using 5+direction. Also evaded the trap if clicked travel path with mouse.

**Comment by TommiGustafsson-HMP** [comment]
Does not work for me.

![image](https://user-images.githubusercontent.com/16661034/71735668-b4e28d00-2e57-11ea-8900-4741b5c0a81f.png)

Runs directly to the squeaking board with shift+up.

**Comment by TommiGustafsson-HMP** [comment]
The same here:

![image](https://user-images.githubusercontent.com/16661034/71735752-e5c2c200-2e57-11ea-9fbf-caad51cc9ee4.png)

With shift+left.

**Comment by TommiGustafsson-HMP** [comment]
Does work with g + stuff but does not work with shift + stuff.

**Comment by janne-hmp** [comment]
Now fixed!
