### ISSUE TITLE
Nerf tame purple worm instakilling all monsters

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#434]
It does not instakill large monsters, but all human-sized and smaller, which it can swallow.

**Comment by TommiGustafsson-HMP** [comment]
Hostile purple worms also instakill your pets, if pets are small enough.

**Comment by janne-hmp** [comment]
Swallowing now just does 4d10 damage instead of instadeath. Monsters cannot swallow other monsters in reality (they cannot occupy the same square). An alive monster is regurgitated every round.
