### ISSUE TITLE
Crazy damage with Flintstone and Sling and with Dragonbane

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#435]
![image](https://user-images.githubusercontent.com/16661034/70304697-e27eeb00-1845-11ea-9961-f9e2567ebc5a.png)

Slinging a flintstone to a gas spore: 19 damage
Hitting an ancient dragon with Dragonbane: 135 damage.

![image](https://user-images.githubusercontent.com/16661034/70304785-0f330280-1846-11ea-9a04-d08a3446bc27.png)

![image](https://user-images.githubusercontent.com/16661034/70304802-19550100-1846-11ea-86bf-081e8599d5fa.png)

**Comment by janne-hmp** [comment]
Fixed.
