### ISSUE TITLE
Vlad does not kill the kitten

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#440]
![image](https://user-images.githubusercontent.com/16661034/70310225-79ea3b00-1852-11ea-8cef-cec96edb1a8b.png)

**Comment by janne-hmp** [comment]
Now certainly kills. This may entail some further balancing needs with large cat not attacking Vlad because he is too powerful, but Vlad attacking the pet. It's all a serious spaghetti code here, so takes a lot of time to fix.
