### ISSUE TITLE
Almost infinite magic skill training with some spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#442]
Such as Magic Arrow. It should be able to be cast almost indefinitely but at the same time you can get almost infinite magic skill training with it. Maybe such spells should have some kind of a multiplier or chance % to train a skill. For example 1/5 multiplier for mixing the spell bringing mixing from 10 to 2 and firing the skill could have 20% chance on success to train your arcane skill up. Something like this.

Similarly, some spells might use a positive multiplier for skill training for both mixing and casting, if they are hard to mix and meant to be used very seldomly.

**Comment by janne-hmp** [comment]
Spells now have a parameter "skillchance" that is set to 100 to most spells, and 20 to Magic Arrow and Forcebolt. It is the % chance of learning of the skill upon casting, and also a % multiplier for the skill points obtained from mixing.
