### ISSUE TITLE
Make 64-bit build of GnollHack?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#450]
64-bit is required to support macOS Catalina and possible android ports.

Don't know what it takes to support hardfought.org for online tournament play.

Needs investigation.

**Comment by TommiGustafsson-HMP** [comment]
Tried building with x64 config in Visual Studio 2019 and it worked well. So we can build it easily as 64-bit program.

![image](https://user-images.githubusercontent.com/16661034/70542836-1aea3600-1b72-11ea-934d-b78a3471b331.png)

**Comment by TommiGustafsson-HMP** [comment]
To activate x64 mode, we need to put x64 as active solution platform in COnfiguration Manager:
![image](https://user-images.githubusercontent.com/16661034/70543390-ff335f80-1b72-11ea-980f-70363b4620d2.png)

And then change Debugging options for that platform in GnollHack properties:
![image](https://user-images.githubusercontent.com/16661034/70543440-11ad9900-1b73-11ea-8d56-b31411794ae3.png)

**Comment by TommiGustafsson-HMP** [comment]
You can also set the build platform in the tool bar.
![image](https://user-images.githubusercontent.com/16661034/70787984-8ca3c900-1d98-11ea-9371-cb61b5eb859c.png)

**Comment by janne-hmp** [comment]
Done, and works well.
