### ISSUE TITLE
Wand of Orcus

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#452]
Using a death ray drains a level from the user. This draining sets your experience to a mid-point of the previous experience level. Level draining does not affect Orcus, though.

The death attack works 10% on each hit but needs to pass also MC to work. Magic resistance and death resistance prevent it, too.

**Comment by janne-hmp** [comment]
Done. Life draining happens at 50% and is normal that brings you close to previous level. It is still pretty annoying, and will make you lose any XP gained from the invoked death ray.
