### ISSUE TITLE
Pets are very easily killed now

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#454]
![image](https://user-images.githubusercontent.com/16661034/70609509-94cdfe00-1c0a-11ea-8097-f1708511dafd.png)

First dwarf zombie killed Hachiko.

**Comment by janne-hmp** [comment]
Raised constitution of dogs and cats to 18 to fix the issue. Zombies hit now hard with increased strength damage bonuses.

**Comment by janne-hmp** [comment]
Also, the starting HD for a starting little dog and kitten is now unadjusted at 2, instead of 1 as before.
