### ISSUE TITLE
Add Golf Club to Tourist, and add -18 to hit penalty to throwing weapons in melee range

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#458]
Thrown weapons should have -18 to-hit penalty in melee. Also, there should be some kind of a message, when you try to use a ranged weapon in melee, to help people understand that it is heavily penalized.

To help tourist, we should add a melee weapon to him, the Golf Club +2:

**Golf Club**
Uses Bludgeoning Weapon skill
1d3 small
1d2 large
Can be applied to hit gems and rocks, which are on the earth, a large distance (like kicking the gems and rocks). It adds its damage and enchantment bonus to the gem's/rock's normal damage. If one tries to hit a loadstone, it does not move ("Thump!"). One can also hit sling stones in this manner for a great amount of damage. Using Golf Club in this way uses the Throwing Weapon skill (or whatever).
_Golf Club is either a weapon or a tool (like pick-axe)._

Additionally, tourist can become _skilled in Bludgeoning Weapons_. Tourist should also start basic in Bludgeoning Weapons.

**Comment by janne-hmp** [comment]
Done. That required quite a lot of extra coding...
