### ISSUE TITLE
New weapon damages

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#460]
Two-handed weapons could do 2dX damage to small and perhaps 3dX to large.

Two-handed sword: 2d8 to small, 3d8 to large, or 2d6 to small and 3d6 to large if we wish not to increase damage

Battle axe: 2d8 to small, 2d8 to large

Quarterstaff: 2d4 to small, 2d4 to large

Something like this.

**Comment by janne-hmp** [comment]
Done.
