### ISSUE TITLE
Monk can start with Sleep spell, which is level 5

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#466]
Sleep at start:

![image](https://user-images.githubusercontent.com/16661034/71240674-6e971500-2312-11ea-9386-2d321d6fa184.png)

However, he is unskilled in enchantment spells:

![image](https://user-images.githubusercontent.com/16661034/71240741-91c1c480-2312-11ea-80ff-4f8076c0860f.png)

He should be at least Basic in Enchantment spells with Skilled as maximum spell level.

Add also a low level spell to Monk, which he can cast in the start. He could start with two spells.

I think Monk should be able to become Expert in Movement spells.

**Comment by TommiGustafsson-HMP** [comment]
Maybe Monk could have better CHA, less STR, and more CON. Improved martial arts will make up the lesser strength. He could have:
-5 to STR
+3 to CON
+3 to CHA

**Comment by janne-hmp** [comment]
Done. Your monk was unusually lucky with STR. Now STR, DEX, CON, WIS and CHA are all similar with a minimum score of 10 and and exponential advance probability of 20 beyond that.
