### ISSUE TITLE
Spells too difficult to cast

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#470]
![image](https://user-images.githubusercontent.com/16661034/71351364-22e7a400-257c-11ea-98b8-d0e1a5372d39.png)

Even casting healing is very difficult. Why?

![image](https://user-images.githubusercontent.com/16661034/71351397-3d218200-257c-11ea-95f3-fd951def6ab9.png)

It should be much easier. Many spells now have the problem that you cannot cast them.

**Comment by janne-hmp** [comment]
Fixed. Made all spell casting 30% easier, and removed the role-specific penalty concept, which was 40% for monk. Consequently, healing will have 0% fail probability at 13 WIS. Cure sickness will have 40% fail probability. One experience level is 40%, as is one skill level and 4 points of WIS.
