### ISSUE TITLE
Apples and other vegetable food could give lot of more nutrition

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#476]

**Comment by janne-hmp** [comment]
Done. The fruits are now bigger (more realistic weight), and the nutrition has been increased accordingly, and also balanced compared to food ration. Cram ration, C-ration and K-ration nutrition has been increased to 900, 450, and 525, respectively, to make them better than food ration and therefore a bit less pointless. Also, new veggy food item: handful of nuts.
