### ISSUE TITLE
Better material components

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#479]
![image](https://user-images.githubusercontent.com/16661034/71410046-7fb28f80-264c-11ea-9889-eab7132f9557.png)

Protection could use something else than a thread of spider silk.

Charm monster should not use ginseng, which is used for healing.

**Comment by TommiGustafsson-HMP** [comment]
Maybe some kind of common ore, like iron?

**Comment by janne-hmp** [comment]
Done. Charm monster now uses magic mushrooms that can be found in the Gnomish mines.
