### ISSUE TITLE
Touch of death really easy to mix

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#491]
Only one bone? How about a skull?

**Comment by TommiGustafsson-HMP** [comment]
![image](https://user-images.githubusercontent.com/16661034/71419807-32e5ad80-267a-11ea-8f07-2bc84b70de83.png)

**Comment by janne-hmp** [comment]
Fixed. It is skull now.

**Comment by janne-hmp** [comment]
Since skulls are easy to find, added also death cap (mushroom). They are may be frequent in garden rooms and gnomish mines, but may help a bit still.
