### ISSUE TITLE
Eyes of the Overworld does not confer its powers on examine

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#492]
![image](https://user-images.githubusercontent.com/16661034/71420096-f1560200-267b-11ea-81a5-27c6bc420c8e.png)

https://nethackwiki.com/wiki/The_Eyes_of_the_Overworld

**Comment by janne-hmp** [comment]
Nor does any other artifact at the moment.

**Comment by janne-hmp** [comment]
Fixed. Now examine shows (almost) all artifact powers.
