### ISSUE TITLE
Martial arts a bit too good

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#494]
Martial arts deals easily something like 60 points of damage on Expert wearing ordinary gloves +1 and a belt of frost giant strength. I think it must be a bit down scaled and a new level Master should be added, after Expert, costing 7 skill points. This should be the end game level, when one is level 20+. And of course, we can add Grand Master level, for levels 30+, which costs 8 skills points, if we want.

**Comment by janne-hmp** [comment]
Reduced the strength bonus at Expert level, as well as kicking extra damage. Probably does not help enough, as the main source of higher damage is the multistrike.

**Comment by janne-hmp** [comment]
What is the difference between basic, skilled, expert, master and grand master in martial arts?

**Comment by TommiGustafsson-HMP** [comment]
Maybe we can try to keep strength bonus at 50% at all levels.
Then, just add some damage and to-hit bonus, and multiattack on all levels.
- Skilled: 1d2
- Expert: 2
- Master: 1d2+1
- Grand Master: 3

To-hit and damage bonuses:
- Basic: +1/+1
- Skilled: +2/+2
- Expert: +3/+3
- Master: +4/+4
- Grand Master: +5/+5

Must calculate to see what is total damage.

**Comment by janne-hmp** [comment]
How about bare handed combat to-hit and damage bonuses, at the moment they are at expert +2/+3, which come on the top of Martial Arts bonuses? The main problem with high damage is multiattack, which multiplies the strength bonus and all the other bonuses.

**Comment by TommiGustafsson-HMP** [comment]
The other possibility is the nerf multi-attack to be
- 20% at Basic
- 40% at Skilled
- 60% at Expert
- 80% at Master
- 100% at Grand Master

**Comment by TommiGustafsson-HMP** [comment]
Or
- Basic 100% strength bonus
- Skilled: 25% multiattack
- Expert: 50% multiattack
- Master: 75 % multiattack
- Grand Master: 100% multiattack

And on top some To-hit and damage bonuses?

**Comment by janne-hmp** [comment]
Let's try that.

**Comment by janne-hmp** [comment]
Implemented now.
