### ISSUE TITLE
Stethoscope and Wand of Probing should list intrinsics and extrinsics

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#496]
Stethoscope and wand of probing should reveal intrinsics and extrinsics of a target. Specifically, one should get to know what resistances the monster has. Does it have death resistance or petrification resistance? How about sleep resistance? How about magic resistance extrinsic or magic resistance %? This is important when facing powerful foes and you need to know what they resist.

Wand of Probing also should not consume a turn. It is enough that it consumes a charge.

One could also use these items on yourself to identify some rings and amulets that convey extrinsic resistances.

**Comment by janne-hmp** [comment]
Wand of probing lists intrinsics now. Wand of probing does not take turn (fixed before). Zapping yourself with wand of probing provides enlightenment.
