### ISSUE TITLE
Spell Skills / Schools

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#50]
Arcane – Int – Contains Wizard spells, mostly attack spells (Wizard is expert in this school)
Clerical – Wis – Contains Bless/Curse spells and others, which are clearly clerical, such as Undead Turning (Priest is expert in this school)
Healing – Wis – Contains all healing and cure spells (Healer, Priest, and Monk are experts in this school)
Divination – Wis – Contains divination spells, such as identify and magic mapping (Archaeologist is expert in this school)
Movement – Int/Wis – Contains all spells like teleport, levitate, and haste self (Monk is expert in this school)
Transmutation – Int – Contains spells like Digging, Stone to Flesh, and Polymorph (Archaeologist is expert in this school)
Enchantment – Int – Contains charm and sleep spells (Wizard should be expert in this school)
Conjuration – Int/Wis – Contains summoning spells and Wish (Wizard and Priest are experts in this school)

Thus, there are 3 Int schools, 3 Wis Schools, and 2 Int/Wis universal schools.

**Comment by TommiGustafsson-HMP** [comment]
Possibly add Protection or Abjuration school:

Abjuration – Wis – Includes protection spells and cancellation (Monk and Priest could be experts in this school)

**Comment by janne-hmp** [comment]
Added Necromancy

**Comment by janne-hmp** [comment]
Implemented.
