### ISSUE TITLE
Make a Polearm able to hit corners

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#507]
Now applying a polearm lets you hit 2 squares away in orthogonal directions but not in any corners. See the below diagram, where Y is the place you are able to hit now:
```
    -------
    ---Y---
    -------
    -Y-@-Y-
    -------
    ---Y---
    -------
```

Make it possible to hit corners as well. See the below diagram, where Y is the place you should be able to hit:
```
    -------
    -YYYYY-
    -Y---Y-
    -Y-@-Y-
    -Y---Y-
    -YYYYY-
    -------
```

**Comment by janne-hmp** [comment]
Fixed.
