### ISSUE TITLE
Weapon skills on Skilled and Expert could give +1 to hit and +2 or +3 to damage per level

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#510]
Including bare-handed combat.

I think it is less now.

Weapon damages have increased, so skill levels should add +2 or +3 to damage as well.

**Comment by janne-hmp** [comment]
Now it is (to-hit / dmg):

**Bare handed combat:**
Unskilled -1/+0
Basic +0/+1
Skilled +1/+2
Expert +2/+3

**Weapon skills:**
Unskilled -4/-2
Basic +0/+0
Skilled +2/+1
Expert +3/+2

**Comment by janne-hmp** [comment]
Changed to:
Weapon skills:
Unskilled -4/-2
Basic +0/+1
Skilled +2/+4
Expert +4/+7

**Comment by janne-hmp** [comment]
Also, the "#attributes" command now shows you the bonuses you get from active skills.
