### ISSUE TITLE
Quarterstaff largely overperforms spells at low levels

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#511]
Hitting around 15 damage per hit.

Spells doing something like 5 damage per hit.

![image](https://user-images.githubusercontent.com/16661034/71544519-3b472c80-2989-11ea-827e-29541545a0d6.png)

Maybe spells should be better?

The reason is Gauntlets of Power, str 18/**

![image](https://user-images.githubusercontent.com/16661034/71544539-83fee580-2989-11ea-87b0-fa7c1b21286d.png)

**Comment by TommiGustafsson-HMP** [comment]
Magic missile is ok.

**Comment by janne-hmp** [comment]
Also made force bolt hit with 100% chance. So this can be closed.
