### ISSUE TITLE
What is this abaneogakh?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#512]
![image](https://user-images.githubusercontent.com/16661034/71545110-d3e0ab00-298f-11ea-9c95-84619f87c25a.png)

**Comment by janne-hmp** [comment]
I think it is an orc random generated name. Not sure what it is doing there.

**Comment by janne-hmp** [comment]
Polypiled orc corpses?

**Comment by TommiGustafsson-HMP** [comment]
No, it appeared on random items, including candles.

**Comment by janne-hmp** [comment]
Fixed. It was a normal behavior in NetHack, and was meant to indicate that they are booty of an orc gang called the Abaneogakh clan. Changed now the first letter to capital and changed the full text to "property of the Abaneogakh clan" to make it clearer.

**Comment by janne-hmp** [comment]
To shorten the text, the items are now labeled"loot of Abaneogakh".
