### ISSUE TITLE
Magic Arrow should hit only the first target and with a 100% chance

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#513]
Now it hits multiple targets and has a big chance to miss.

**Comment by TommiGustafsson-HMP** [comment]
Could it have a visual effect of shooting a white arrow? Just like when you shoot an arrow.

**Comment by janne-hmp** [comment]
Done. A visual effect and whether hits only one or multiple targets can be specified for all "immediate" spells. All such spells hit just one target except Fear, which is currently the only one hitting multiple targets.
