### ISSUE TITLE
Spells to cast less mana on high skill levels?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#514]
Basic: -15% mana or -20% mana
Skilled: -30% mana or -35% mana
Expert: -45% mana or -50% mana

End result rounded down, to a minimum of 2.

Usually, there is no lack of mana, but it would be nice if high skill levels would have also some other benefit than +% to casting success, since it becomes probably useless on high experience levels.

This way, we could also have spells that cost lots of mana, and you would the expert skill level to reduce their mana cost.

**Comment by janne-hmp** [comment]
Done.
