### ISSUE TITLE
Add some way to track luck changes

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#515]
One should not be at loss, when something negative or positive happens.

For example, what happens when you unsuccessfully try to convert an altar or throw a gem to an unicorn?

Things are not clear at the moment. Best thing would be that the game would tell that
- your luck has increased a little (+1)
- your luck has increased somewhat (+2)
- your luck has increased much (+3)
- your luck has increased greatly (+4)
- your luck has increased very greatly (+5 or more)

Negative luck:
- your luck has decreased a little (-1)
and so on

Or something like this so that the player would not be at loss what just happened and how it affects the gameplay.

**Comment by TommiGustafsson-HMP** [comment]
Or it could be also as simple as

- Your luck has increased by 1.
- Your luck has decreased by 1.
- Your luck has been set to 0.
- Your luck is now 5.

**Comment by janne-hmp** [comment]
Done, there are some special messages for each level.
