### ISSUE TITLE
Add mixing and casting training bonus to spells that are difficult to mix and used seldomly

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#516]
Enchant weapon, enchant armor, protect armor, protect weapon and the like could have training bonus, similarly like we did training penalty to attack spells.

Maybe they could produce double or triple amount of training?

**Comment by janne-hmp** [comment]
Done. Now enchant-spells produce 3x, and protect-spells 2x.
