### ISSUE TITLE
Animate fire has very short duration

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#520]
![image](https://user-images.githubusercontent.com/16661034/71581687-0a90ff80-2b0f-11ea-848c-98041eaf28d8.png)

I would expect the fire elemental to last at least 150-300 turns or so.

Cooldown could also be longer, like 60-120 turns to prevent elemental spamming.

**Comment by janne-hmp** [comment]
Cooldown is now 90, and duration 5d20+150 for all animate elemental spells.
