### ISSUE TITLE
Read a spellbook and got a really long stun and died at AC -15 and 150 HP

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#529]
I think reading spellbooks should not be so dangerous.

**Comment by janne-hmp** [comment]
Confusion or blindness perhaps?

**Comment by janne-hmp** [comment]
A failed reading a spellbook should not give stun but a maximum of 22 rounds of confusion. Alternatively, blindness can last 250 rounds. In any case, changed so that an uncursed spellbook can give at most 1d4 + 5 rounds of confusion. A cursed spellbook can be more dangerous.

**Comment by janne-hmp** [comment]
Fixed this now by making sure that positive and negative effects happen only after the book has been successfully studied.
