### ISSUE TITLE
Attack spells did not do enough damage on high levels and there were too few of them

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#530]
Attack spells were not good enough at high levels. I used mainly firebolt, but it did only domething like 15 points of damage, when one hit with long sword of life stealing and belt of frost giant strength did much more.

There should be better attack spells and more of them.

Also, some high level attack spells gave quite few castings, like 3. I think Firestorm was one of them.

I think we should give some more thought how attack spells should work, since they now require components. Only some components like arrows and crossbow bolts are really plenty, but others like sulphurous ash are not.

**Comment by janne-hmp** [comment]
Now there are a lot more of them.
