### ISSUE TITLE
Way to hotkey best current spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#532]
Maybe also a way to show favorite spells only. And a way to mark a spell as a favorite or not.

**Comment by janne-hmp** [comment]
Done. Spells can be now set a hot key between 0-9 by using Alt-z. The spell menus will always show only 52 first spells, but there can actually be any number of spells. The unshown spells can be marked with hotkey, so they will be shown in the beginning, or sorted using '+' command to be shown. '+' command also allows you to change the order of the spells, so any spells not initially shown can be sorted to be in the beginning (in theory). Hotkeys and spell sorting double the functionality a bit, but maybe are both useful if there are really a lot of spells. You can also forget spells now, if that helps.
