### ISSUE TITLE
New Clerical Spells: Destroy Undead, Slay Demon, Resurrection

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#54]
Destroy Undead – Level 5 Clerical with Material Component
Slay Demon – Level 6 Clerical with Material Component
Resurrection – Level 5 Healing/Clerical with Material Component (can be copied from Undead Turning)

**Comment by janne-hmp** [comment]
Implemented under the names of Negate Undeath (level 7) and Banish Demon (level 8). Both are instadeaths for the monsters unless they succeed in magic resistance (in which case they deal 10d6 and 15d6 damage, respectively). Resurrection is also done.
