### ISSUE TITLE
One Ring to generate lesser wraiths 'W' on low levels

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#540]
Wraith maximum level would be
3 x Dungeon Level + 1.5 x Character Level

On Dungeon Level 1 and Character Level 1
-> Nothing can be generated

So, On Dungeon Level 2 and Character Level 2 (total 9)
-> Barrow Wight (Level 6)
-> Wraith (Level 8)

On Dungeon Level 4 and Character Level 4 (total 18) and onwards 
-> Spectre (Level 15) can be generated

On Dungeon Level 8 and Character Level 8 (total 36)
-> King Wraith (Level 31) can be generated

On Dungeon Level 13 and Character Level 13 (Total of 58)
-> Nazgul (Level 55) can be generated

It replaces only 5% of generated monsters with these.

Wraiths generated in this way never leave a corpse.

**Comment by janne-hmp** [comment]
Done.
