### ISSUE TITLE
Difficulty Levels

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#543]
Very Easy: Monsters have 1/4 HP
Easy: Monsters have 1/2 HP
Normal: Monsters have normal HP
Hard: Monsters have 2 x HP
Very Hard: Monsters have 4 x HP

Additionally, when a monster is tamed, summoned, or joins your party, its maximum hit points are set to the normal amount and its current hit points are set to to the percentage that it was before, to the minimum of 1 HP.

**Comment by janne-hmp** [comment]
Done.
