### ISSUE TITLE
Increase spell casting penalty for Dragon Scale Mails

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#547]
Gray Dragon is magic resistant, so maybe it could be -200%.
Silver Dragon Scale Mail could be -120% or -160%.
Red Dragon Scale Mail and other scale mails could be -80% or -120%.

So that they do not overshadow other armors like full plate mail (-100%), mithril full plate mail (-60%), and crystal plate mail (-20%).

They are also lighter 34 lbs vs. 60 lbs full plate mail.

Orichalcum full plate mail is similar to Gray Dragon Scale Mail but is heavier but also gives more MC.

Something like this.

**Comment by janne-hmp** [comment]
Done. They are now -200% gray, -150% silver and all other -100%.
