### ISSUE TITLE
Cancellation Level 5 with Material Component, skipping Magic Resistance

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#55]
Cancellation spell revamp:
- Level 5 Abjuration
- Skips magic resistance
- Prevents spell casting
- Not permanent (maybe 30–50 turns?)
- Has material component (a ruby or a sapphire?), maybe gives more than 1 casting, like 3

Would be a perfect spell against Liches.

**Comment by janne-hmp** [comment]
There is already such a spell, which gives permanent cancellation, the same effect as the wand of cancellation. Moved to level 5, no material component yet. May warrant further research into how it works.

**Comment by janne-hmp** [comment]
Cancellation has now a timer and bypasses magic resistance.
