### ISSUE TITLE
Staff of Frost should have base damage 2d4 and extra damage 2d4

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#550]
![image](https://user-images.githubusercontent.com/16661034/71809987-f0f53800-3079-11ea-88f3-700d1589faed.png)

Now it is 1d6.

Also it seems to hit somehow poorly. It uses the Quarterstaff skill but the normal Quarterstaff seems to hit better.

**Comment by janne-hmp** [comment]
Fixed. Not sure about what's up with hitting.
