### ISSUE TITLE
Ability boosting fruits a bit too common

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#555]
Could be 30-50% rarer than now.

**Comment by janne-hmp** [comment]
Frequency was 3/1000 for each of the four, so total was 12/1000 = 1.2% chance, reduced to 2/1000, so the chance is now 0.8% to get a ability boosting fruit, probably already less than with Potion of Gain Ability. Reduced the likelihood of appearing in Gardens to 1/4 of before. They used to have a 4/18 chance = 22% of appearing in every third square in garden. Now they have a 1/18 chance = 5.6% in a appearing in every third a square in garden, so a 1.85% chance per square. In a garden with 20 squares, the chance of getting at least one ability-boosting fruit is 31.2%

**Comment by TommiGustafsson-HMP** [comment]
Yes. The problem was the gardens. I found 4 such fruits in one garden.
