### ISSUE TITLE
Why Lightning Bolt deals 6d6 damage as level 2 spell while Firebolt deals 3d6 damage as level 3 spell?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#557]
![image](https://user-images.githubusercontent.com/16661034/71820912-5573bf80-3099-11ea-936f-4c8c2ba4a442.png)

![image](https://user-images.githubusercontent.com/16661034/71820936-66bccc00-3099-11ea-88bb-a224b3450ee9.png)

Also Skill chance could read "train chance" or "training chance."

**Comment by janne-hmp** [comment]
Put fire bolt to level 2 with 4d6 damage and moved lightning bolt to level 3.
