### ISSUE TITLE
New Enchantment Spells: Enchant Weapon, Enchant Armor, Protect Weapon, Protect Armor

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#56]
Enchant Weapon – Level 4 Enchantment with Material Component
Enchant Armor – Level 3 Enchantment with Material Component
Protect Weapon – Level 2 Enchantment with Material Component (erode-proofs)
Protect Armor – Level 1 Enchantment with Material Component (erode-proofs)

**Comment by janne-hmp** [comment]
Implemented. Also implemented Bless and Curse.
