### ISSUE TITLE
Why is Wizard Basic in Necromancy, even though he does not have necromantic spells?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#561]
![image](https://user-images.githubusercontent.com/16661034/71827011-f9646780-30a7-11ea-994f-40c4ab9954be.png)

Does not make sense. Should be unskilled.

**Comment by janne-hmp** [comment]
That was a chaotic wizard. But changed to enchantment for all.
