### ISSUE TITLE
Attack Spell Skill Training chance should be at least 20%

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#562]
I played 4 hours or so and got only 26 extra training in arcane spells.

Now it is 5%, should be at least 20%.

![image](https://user-images.githubusercontent.com/16661034/71832119-eb681400-30b2-11ea-84c8-98b71c8d37e1.png)

**Comment by janne-hmp** [comment]
Now 20%.
