### ISSUE TITLE
Necromancy Spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#564]
Summon Undead Host
Minor Cantrip
Material Component: Sporal Powder
Casts: 20
Summons all friendly undead around you as per Magic Whistle

Raise Minor Zombie
Major Cantrip
Material Component: Bat guano
Requires a low level corpse to animate (works on humans, gnomes, elves, goblins, orcs, dwarves, etc.)
Casts: 4
Raises a low level zombie (up to level 4 or so). Cannot raise giant zombies.

Raise Skeleton
Level 1
Material Component: Bone
Casts: 1
Summons a permanent skeleton.

Raise Minor Mummy
Level 2
Material Component: Spidersilk
Requires a low level corpse to animate (works on humans, gnomes, elves, goblins, orcs, dwarves, etc.)
Casts: 4
Raises a low level mummy (up to level 7 or so). Cannot raise giant mummies.

Raise Giant Skeleton
Level 3
Material Component: 2 bones
Casts: 1
Summons a permanent giant skeleton

Raise Giant Zombie
Level 4
Material Component: Bat guano, jet stone
Requires a giant or ettin corpse to animate
Casts: 2
Raises only giant and ettin zombies

Raise Skeleton Warrior
Level 4
Material Component: human skull, bone
Casts: 1
Summons a permanent skeleton warrior

Raise Giant Mummy
Level 5
Material Component: Spider silk, jet stone
Requires a giant or ettin corpse to animate
Casts: 2
Raises only giant and ettin mummies.

Raise Skeleton Lord
Level 8
Material Component: Human skull, bone, black opal
Casts: 1
Summons a permanent Skeleton Lord

Raise Skeleton King
Level 10
Material Component: Human skull, bone, 2 black opals
Casts 1
Summons a permanent Skeleton King

Heal Undead
Level 2
Material Component: Mandrake root(?)
Casts: 5
Heals undead for 6d6 damage

Greater Undead Healing
Level 5
Material Component: Mandrake Root(?), Sporal Powder
Casts: 3
Heals undead for 12d6 damage

**Comment by janne-hmp** [comment]
All done except healing spells and summon undead host, which unnecessarily repeats the summoning call spell.

**Comment by janne-hmp** [comment]
Done, except Summon Undead Host, which seems unnecessary with Summoning Call. Names are Replenish Undeath and Greater Undeath Replenishment. The latter is level 4 instead of 5. They affect only undead. Healing spells and potions affect now only living. This means that golems and other non-undead non-living creatures cannot be currently healed by any means. (Probably should be repaired somehow.)
