### ISSUE TITLE
Resurrection applied to human zombie corpse produces a zombie

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#566]
Should not produce a human?

Also dwarf zombie corpse produces a dwarf zombie, not a dwarf...

**Comment by janne-hmp** [comment]
Well, it brings back whatever monster it was before. If you use it on  a wraith corpse, it will bring back a wraith, not the theoretical human the wraith was before.

**Comment by janne-hmp** [comment]
Fixed. The corpses now revive into the shown corpse type (dwarf zombie -> dwarf corpse -> dwarf).
