### ISSUE TITLE
Increase the chance of finding secret doors with bad luck

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#568]
Sometimes you can get totally stuck, if you have bad luck and you need to find a secret door. It is almost impossible!
https://nethackwiki.com/wiki/Search
It is 0,27%! Something like 1/370. What?!?
Simply the One Ring or cursed luckstone can do it, as they give -3 to luck.

I guess 7% should be rightly the minimum chance with any amount of bad luck.

**Comment by janne-hmp** [comment]
Fixed, with luck 0, chance of finding a hidden door is now 1/6 at 0 luck (the same as D&D); with luck -3, it is 1/7; with luck +3, 1/4. With luck -11, the chance is 1/11 = 9%, and at the very minimum it will be 1/17= 5.9% when luck is -21.
