### ISSUE TITLE
New Spells: Lower Resistance, Forbid Summoning, Spell Shield, Protection from Magic, Reflection, Negate Magic Resistance

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#57]
Lower Resistance – Abjuration Level 4 – Lowers target creatures resistance by -50%. 50% becomes 0%, 100% becomes 50%. Lasts 60 turns. No Material Component.

Forbid Summoning – Abjuration Level 3 – Prevents target creature from summoning others for 60 turns. No material component.

Spell Shield – Abjuration Level 3 – Prevents single spell from taking effect. Shield lasts for 120 turns or until used. No material component. Cooldown 4 turns.

Protection from Magic – Abjuration Level 7 – Grants magic resistance for 60 turns. No material component.

Reflection – Abjuration Level 6 – Grants reflection for 60 turns. No material component.

Negate Magic Resistance – Abjuration Level 8 – Reduces target creature's magic resistance to 0% for 60 turns. No material component.

**Comment by TommiGustafsson-HMP** [comment]
Additionally,

Protection from Fire – Abjuration Level 2 – Grants fire resistance for 60 turns.
Protection from Lightning – Abjuration Level 2 – Grants lighting resistance for 60 turns.
Protection from Cold – Abjuration Level 2 – Grants cold resistance for 60 turns.
Protection from Acid – Abjuration Level 1 – Grants acid resistance for 60 turns.
Protection from Poison – Abjuration Level 1 – Grants poison resistance for 60 turns.
Protection from Life Draining – Abjuration Level 0 – Grants life drain resistance for 60 turns.
Protection from Lychantropy – Abjuration Level 0 – Grants lycanthropy resistance for 60 turns.
Protection from Death Magic – Abjuration Level 3 – Grants death magic resistance for 60 turns.
Protection from Disintegration – Abjuration Level 4 – Grants disintegration resistance for 60 turns.
Protection from Sickness – Abjuration Level 4 – Grants protection from all kinds of sickness for 60 turns. Does not heal existing sicknesses.

**Comment by janne-hmp** [comment]
All the other spells are done, except the following ones requiring new data structures:
Lower Resistance, Forbid Summoning, Spell Shield, Negate Magic.

**Comment by janne-hmp** [comment]
Implemented all but Spell Shield
