### ISSUE TITLE
Fire bolt deals damage to succubus even though it is fire resistant

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#572]
![image](https://user-images.githubusercontent.com/16661034/71903063-ee730b00-316b-11ea-9c67-ca021bf5c51d.png)

**Comment by janne-hmp** [comment]
The bolt hit somebody else ("it") for 19 damage. Succubus took now damage. Will improve messaging.

**Comment by TommiGustafsson-HMP** [comment]
Maybe also add a resists animation.
