### ISSUE TITLE
Game tells that you are burdened and unencumbered when weight is a bit over limit

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#579]
![image](https://user-images.githubusercontent.com/16661034/71965695-d9988500-3208-11ea-968a-30468c5dae4b.png)

![image](https://user-images.githubusercontent.com/16661034/71965715-e5844700-3208-11ea-8bab-3220640a354d.png)

![image](https://user-images.githubusercontent.com/16661034/71965755-f3d26300-3208-11ea-9621-d386b307ade6.png)

**Comment by janne-hmp** [comment]
Fixed. The carrying capacity ended up being random with STR levels 18/01 - 18/99, because the STR bonus was changed to be random.
