### ISSUE TITLE
Garden rooms

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#58]
Some rooms could be designated as gardens. In each square, there is a vegetable or herb, or multiple of them. Also some trees could be there, such as an apple tree with 20 apples, etc. Also, reagents could grow here.

There are no special monsters in garden rooms.

**Comment by janne-hmp** [comment]
Done. Garden has currently garden gnomes and ogres sleeping there. Probably needs some fine tuning.
