### ISSUE TITLE
Juiblex is summoned from same-race sacrifice but is peaceful (chaotic character)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#581]
![image](https://user-images.githubusercontent.com/16661034/71969822-22077100-3210-11ea-860e-8d983bb2c009.png)

It is good that he is peaceful but it is a bit strange.

**Comment by red-kangaroo** [comment]
This was also the case in vanilla NetHack.

I guess the demon lord is pleased by your sacrifice?

**Comment by TommiGustafsson-HMP** [comment]
Yes, I know. It is just a little bit strange. Usually demon lords are hostile, and you would expect to get some kind of punishment for same-race sacrifice. But we haven't done anything about it.

**Comment by janne-hmp** [comment]
It is now better done.
