### ISSUE TITLE
Monk to gain very fast intrinsic on level 15

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#585]
So that he can wear boots of kicking or silver boots at high levels.

**Comment by janne-hmp** [comment]
Done. At the moment Due to how geometric series works, very fast intrinsic gives, on expectation, 3x normal speed and fast 1.5x normal speed, and there is nothing in between. Not sure if this is optimal.

**Comment by TommiGustafsson-HMP** [comment]
Should not very fast give 5/3 speed an fat 4/3 speed?
