### ISSUE TITLE
Spell damages per level

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#588]
Doubles every 2 levels.

We must remember that on very hard difficulty, monsters can have over 1000 hit points. 

### Ray spells and ranged 100% to-hit spells
Level -1: 1d8+1 (avg. 5.5)
Level 0: 2d6 (avg. 7)
Level 1: 3d6 (avg. 10.5)
Level 2: 4d6 (avg. 14)
Level 3: 6d6 (avg. 21)
Level 4: 8d6 (avg. 28)
Level 5: 12d6 (avg. 42)
Level 6: 16d6 (avg. 56)
Level 7: 24d6 (avg. 84)
Level 8: 32d6 (avg. 112)
Level 9: 48d6 (avg. 168; comparable to Finger of Death, an instakill ray)

### Touch spells

_Double as ray spells_

Level -1: 3d6
Level 0: 4d6
Level 1: 6d6
Level 2: 8d6
Level 3: 12d6
Level 4: 16d6
Level 5: 24d6
Level 6: 32d6 (avg. 112)
Level 7: 48d6 (avg. 168; comparable to Touch of Death)
Level 8: 64d6 (avg. 224; comparable to Touch of Death)
Level 9: 96d6 (avg. 316; comparable to Touch of Petrification)

### Area of Effect Spells (like Fireball)

_Damage like Ray Spells of 1 level lower_

_It seems that previously it was balanced like 2 levels lower, but I think it is too much, since rays can hit multiple targets as well. HOWEVER, AoE spells hit target 100% so we should test the right balance!_

Level -1: 1d6 (avg. 3.5)
Level 0: 1d8+1 (avg. 5.5)
Level 1: 2d6 (avg. 7)
Level 2: 3d6 (avg. 10.5)
Level 3: 4d6 (avg. 14)
Level 4: 6d6 (avg. 21) – **Fireball (should be level 4, is now level 5)**
Level 5: 8d6 (avg. 28) – **Ice Storm (should be level 5, is now level 6)**
Level 6: 12d6 (avg. 42)
Level 7: 16d6 (avg. 56)
Level 8: 24d6 (avg. 84)
Level 9: 32d6 (avg. 112)

**Comment by janne-hmp** [comment]
Noted.
