### ISSUE TITLE
Fireball has an odd description

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#589]
Actually all spells have after loading a saved game:

![image](https://user-images.githubusercontent.com/16661034/71982815-15921100-322e-11ea-80f9-1b32e5b76cf3.png)

Long Description too:
![image](https://user-images.githubusercontent.com/16661034/71983088-b1bc1800-322e-11ea-92bb-d62971245dfb.png)

**Comment by janne-hmp** [comment]
It is odd. Constant character strings seem to get corrupted for some reason.

**Comment by janne-hmp** [comment]
They are consts that should not be able to change. Of course something can scrabble the memory, e.g. an accidental wrongly pointing pointer etc. But the whole const char part of the memory seems to be scrambled?

![ConstChar](https://user-images.githubusercontent.com/53081197/72002773-bb567780-3250-11ea-9951-6d6e60efa559.png)

**Comment by TommiGustafsson-HMP** [comment]
If it is difficult to resolve, you can post a question on stackoverflow.com.

**Comment by TommiGustafsson-HMP** [comment]
Hopefully, this will be resolved, when all compiler warnings and code analysis warnings have been addressed.

**Comment by janne-hmp** [comment]
Now solved for real.
