### ISSUE TITLE
New Spell: Sphere of Death

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#591]
Necromancy Level 10 or 11
Kills all monsters around you.
Material Component:?
Casts:?

**Comment by janne-hmp** [comment]
Done, but under the name of Sphere of Annihilation, which disintegrates all creatures within 5 square radius. Level 12. One cast for Black Opal, Obsidian and Sporal Powder. Starts with Giga Slave chant.
