### ISSUE TITLE
Slow and fast levels

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#592]
At the moment you have only the following:
- You cannot be slowed, slow attacks merely end the effect of a potion of speed and nothing else
- 1.5x normal speed when fast (1/3 chance of a new round every round)
- 3x normal speed when very fast (2/3 chance of a new round every round)

Monsters have only the following:
- Slowed = 2/3 normal speed
- Sped up = 4/3 normal speed

**Comment by TommiGustafsson-HMP** [comment]
Something is badly bugged with moving now:
#594

**Comment by janne-hmp** [comment]
Moi,
Joo, voitko tehdä allmain.c:hen seuraavan korjauksen:

if(Slowed)
moveamt = youmonst.data->mmove;
else
moveamt = (youmonst.data->mmove + 2) / 3;pitäisi olla

if(!Slowed)
moveamt = youmonst.data->mmove;
else
moveamt = (youmonst.data->mmove * 2 + 1) / 3;

to 9. tammik. 2020 klo 11.02 Tommi Gustafsson (notifications@github.com)
kirjoitti:

**Comment by janne-hmp** [comment]
Done.
