### ISSUE TITLE
New Arcane Spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#593]
Arcane Blast
Level 4 Arcane
Deals 6d6 magic damage to monsters around you (1 square)
Material Component: Platinum Ore
Casts: 20

Circle of Fire
Level 5 Arcane
Deals 8d6 fire damage to monsters around you (1 square)
Material Component: Sulphurous Ash, Sporal Powder
Casts: 20

Circle of Lightning
Level 6 Arcane
Deals 12d6 damage to monsters around you (1 square)
Material Component: Copper Ore, Sporal Powder
Casts: 15

Circle of Frost
Level 7 Arcane
Deals 16d6 cold damage to monsters around you (1 square)
Material Component: Iron Ore, Sporal Powder
Casts: 15

**Comment by janne-hmp** [comment]
All done.
