### ISSUE TITLE
Disarming an arrow trap did not generate any training in Disarm Traps

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#595]
![image](https://user-images.githubusercontent.com/16661034/72098895-1a3af000-3328-11ea-91be-d1ad4989ee6a.png)

Stayed at 20.

Should generate 5 training.
Magical traps should generate 10 training (this works alright, tried with magic trap).

Note that you can wish for traps.

**Comment by janne-hmp** [comment]
It generates training 0 if it is made by you, otherwise 4 for an arrow trap.
