### ISSUE TITLE
Peaceful Juiblex swallows peaceful goblin

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#596]
![image](https://user-images.githubusercontent.com/16661034/72142421-4e9cc380-339d-11ea-8811-3a2e0e6c05f0.png)

![image](https://user-images.githubusercontent.com/16661034/72142388-39c03000-339d-11ea-8a8c-465134d20c67.png)

Do they have some grudge?

Also the goblin does not die. I think nothing happens to him.

**Comment by janne-hmp** [comment]
Fixed. AD_DISE attacks have never worked to other monsters before in NetHack. Now they also use a new monster prop system so that the target becomes terminally ill if it fails MC and dies about 20 rounds later unless cured before.
