### ISSUE TITLE
Change AoΕ spell damages and levels according to Spell Damage system

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#597]
#588 

Fireball Level 4 6d6 damage
Ice Storm Level 5 8d6 damage
Fire Storm Level 6 12d6 damage
Thunderstorm Level 7 16d6 damage

Could add Arcane Storm, Level 8, 24d6 magic damage. Should be rather difficult to mix. Platinum ore + Dilithium Crystal. Castings: 10–15.

Also could add Magic Explosion, Level 3, 4d6 magic damage. Material Component: Platinum ore. Castings: 20.

Also, Meteor Swarm (Level 9) should deal total of 32d6 damage. It could be 4 meteors of 8d6 damage, Each meteor 4d6 physical damage and 4d6 fire damage. Material Component: 4 stone pebbles, 4 sulfurous ash. Castings: 20.

**Comment by janne-hmp** [comment]
All done.
