### ISSUE TITLE
Possible Mana Cost System 2

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#598]
Previous mana cost system: #165.

The second mana cost system could be that mana cost ramps up 1.5x each level. And it can be extended also as a series so that mana cost becomes 5x each 4 levels. The level multiplier is then = 5^(1/4) = 1,495, which is very close to 1.5.

Unskilled mana cost:
-1: 5
0: 7
1: 10
2: 15 – Same as previously
3: 22
4: 35 (or 34) – 117% of previous system
5: 50
6: 75 – 125% of previous system
7: 110 (or 115)
8: 175 (or 170) – 146% of previous system
9: 250 (or 255)
10: 375 (or 385) – 156% of previous system
11: 550 (or 575)
12: 875 (or 865) – 182% of previous system

Expert mana cost would be 50% of that:
-1: 2.5
0: 3.5
1: 5
2: 7.5
3: 11
4: 17
5: 25
6: 37
7: 55 (or 57)
8: 87 (or 85)
9: 125 (or 127)
10: 187 (or 192)
11: 275 (or 287)
12: 437 (or 432)

**Comment by janne-hmp** [comment]
The current system is almost that at the moment (using 1.5x multiplier):

-1: 4
0: 7
1: 10
2: 15
3: 20
4: 30
5: 50
6: 75
7: 100
8: 150
9: 200 
10: 300
11: 500
12: 750-1000

**Comment by TommiGustafsson-HMP** [comment]
It is also good as it is 10x each 6 levels. Multiplier is 1,468.

**Comment by TommiGustafsson-HMP** [comment]
Logically, in that system level 5 should be 45 mana, level 6 70 mana, level 11 450 mana and level 12 700 mana.

**Comment by janne-hmp** [comment]
Looks ok enough at the moment.
