### ISSUE TITLE
Align Ray Attack Spells and Wands with the Spell Damage System

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#599]
Spell Damage System: #588 

Magic Missile Spell: 2d6 damage
Wand of Magic Missile: 2d6 damage (should already be right) – **Can have charges up to 150 if possible!** (Total of 1050 damage)

Force Bolt Spell: 3d6 damage (10.5 average; down from 2d12, average 13)
Wand of Striking: 3d6 damage (down from 2d12) – **Can have charges up to 90!** (Total of 945 damage)

Fire Bolt Spell: 4d6 damage (14 average; should be already right)
Wand of Fire: 4d6 damage (down from 6d6) – **Can have charges up to 60!** (Total of 780 damage)

Lightning Bolt Spell: 6d6 damage (21 average; should be already right)
Wand of Lightning: 6d6 damage (should be already right) – **Can have charges up to 30** (Total of 630 damage)

Cone of Cold Spell: 12d6 damage (42 average; should be already right)
Wand of Cold: 12d6 damage (up from 6d6) – **Can have charges up to 12, or whatever is normal now** (Total of 504 damage)

Wand charges have been increased, because monster HP has been increased in GnollHack.

**Comment by TommiGustafsson-HMP** [comment]
Also enchantments could be aligned with this system as well.

Cone of Cold deals 12d6 damage
- 15 castings per iron ore 

Cold-enchant item could deal 6d6 damage (removed after one hit)
- 15 castings per iron ore
- Each casting enchants 5 stackable items
- Level 5 enchantment

Lightning bolt deals 6d6 damage
- 20 castings per copper ore

Lightning enchant item 3d6 damage (removed after one hit)
- 20 castings per copper ore
- Each casting enchants 5 stackable items
- Level 3 enchantment

Fire Bolt deals 4d6 damage
- 40 castings per sulfurous ash

Fire-enchant item 2d6 damamge (removed after one hit)
- 40 castings per sulfurous ash
- Each casting enchants 5 stackable items
- Level 2 enchantment

This way also using a wand to enchant items would stay in order.

**Comment by janne-hmp** [comment]
Done. One can specify initial charge amounts for all items.
