### ISSUE TITLE
Revised Disarm Trap probabilities

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#600]
_Idea: Fail chance halves each time._

Normal Trap
* Unskilled: 1/3 chance to succeed, 2/3 to fail
* Basic: 2/3 chance to succeed, 1/3 chance to fail.
* Skilled: 5/6 chance to succeed, 1/6 chance to fail.
* Expert: 11/12 chance to succeed, 1/12 chance to fail.

Magical Trap
* Unskilled: 0% chance to succeed, 100% chance to fail
* Basic: 1/3 chance to succeed, 2/3 to fail
* Skilled: 2/3 chance to succeed, 1/3 chance to fail.
* Expert: 5/6 chance to succeed, 1/6 chance to fail.

**Comment by janne-hmp** [comment]
Done.
