### ISSUE TITLE
Covetous monsters (=Wizard of Yendor) should not regenerate extra HP while standing on the staircase up.

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#602]
They should regenerate hit points at a normal speed, while away from the player.

**Comment by janne-hmp** [comment]
But he is casting healing spells there?

**Comment by TommiGustafsson-HMP** [comment]
Who knows? I think he should not. Otherwise he gets infinite hit points.

**Comment by janne-hmp** [comment]
Reduced the healing amount per round from 1d8 to 1 (like regeneration, or if has also regeneration then 2x fast regeneration, which sounds ok), so he heals now 4.5x times slower than before.
