### ISSUE TITLE
Monster magic resistance to block death, sleep, and fear

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#603]
Instadeath and all disabling spells. Makes Wizard of Yendor more dangerous.

**Comment by janne-hmp** [comment]
Including disintegration and petrification?

**Comment by janne-hmp** [comment]
Done. Now works for death and disintegration. There is no petrification ray, so can think that separately. The player gets the same benefit if is polymorphed into a magic resistance form.
