### ISSUE TITLE
Command "S" is overloaded

### ISSUE THREAD

**Issue by TeroKarttunen** [hyvanmielenpelit/GnollHack#604]
Command "S" used to be Save, but it is now being overridden by Skills command.

The only way to save is to use #save command.

I do not think this is intentional, because help file (?c) still lists S as Save as well as Skills.

**Comment by TeroKarttunen** [comment]
Found a comment on Save being bound to "Alt-s". Ok, but command help should be updated. I think this change will baffle many players.

**Comment by janne-hmp** [comment]
Ok, seems it was not changed in the help file, now fixed. The change is to align Alt-q - Quit and Alt-s Save, and free us space for skill menu, which is more important.
