### ISSUE TITLE
cmd.c uses open() without declaration

### ISSUE THREAD

**Issue by MikkoSpoo** [hyvanmielenpelit/GnollHack#605]
MacOS compile test:

```
cmd.c:1626:8: warning: implicit declaration of function 'open' is invalid in C99 [-Wimplicit-function-declaration]
                fd = open(fq_save, O_WRONLY | O_TEXT | O_CREAT | O_TRUNC, FCMASK);
                     ^
cmd.c:1626:22: error: use of undeclared identifier 'O_WRONLY'
                fd = open(fq_save, O_WRONLY | O_TEXT | O_CREAT | O_TRUNC, FCMASK);
                                   ^
cmd.c:1626:33: error: use of undeclared identifier 'O_TEXT'
                fd = open(fq_save, O_WRONLY | O_TEXT | O_CREAT | O_TRUNC, FCMASK);
                                              ^
cmd.c:1626:42: error: use of undeclared identifier 'O_CREAT'; did you mean 'S_TREANT'?
                fd = open(fq_save, O_WRONLY | O_TEXT | O_CREAT | O_TRUNC, FCMASK);
                                                       ^~~~~~~
                                                       S_TREANT
```

**Comment by MikkoSpoo** [comment]
Would probably be nicer to use fopen()

**Comment by janne-hmp** [comment]
This is an original NetHack thing. Will investigate and can change, but needs to be tested on Mac. So far I have used Visual Studio for development.

**Comment by MikkoSpoo** [comment]
It seems that this monster data dump code is new; I can look at this.

Other issue is that code uses SHRT_MAX now in multiple places without declaration. This would normally come from limits.h system header. Have to check how to fix, including system headers directly seems not be the way in nethack code base (for crossplatform support).

**Comment by janne-hmp** [comment]
Yes, I used it because I changed something into shorts and unsigned shorts. Mac version does not have an include on limits.h?

**Comment by janne-hmp** [comment]
One option is to make redefinition with a slightly different name e.g. in hack.h, e.g. GH_SHRT_MAX with the same value. Does not need to be just that definition if it is unavailable in Mac.

**Comment by janne-hmp** [comment]
Removed SHRT_MAX's and added the following if directive for opens:

#ifdef MAC
		fd = macopen(fq_save, O_WRONLY | O_TEXT | O_CREAT | O_TRUNC, TEXT_TYPE);
#else
		fd = open(fq_save, O_WRONLY | O_TEXT | O_CREAT | O_TRUNC, FCMASK);
#endif

Let me know if this does not help.
