### ISSUE TITLE
Clerical Spells are missing low level spells (-1 to 2)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#607]
https://github.com/hyvanmielenpelit/GnollHack/wiki/Clerical-Spells

Hard to level up without low level spells.

**Comment by janne-hmp** [comment]
Now there are many. Probably will also make Prayer to do just prayer and move it to level 4, and Absolution to be its own spell around level 6.

**Comment by TommiGustafsson-HMP** [comment]
A variant of Prayer could be called Supplication.
