### ISSUE TITLE
Wand of Cold deals 12d6 damage but cold-enchanted arrow only 1d6?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#608]

**Comment by janne-hmp** [comment]
With spells cold is the strongest element, but with weapon enchantment the weakest. Can be rearranged, if need be.

**Comment by TommiGustafsson-HMP** [comment]
The problem is that you will never want to use wand of cold to enchant an item then.

**Comment by janne-hmp** [comment]
Done.
