### ISSUE TITLE
Cold-enchant item gives only 2 castings, which is very low compared to other attack spells, which give something like 20

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#609]
Need to rebalance according to other attack spells.

The same problem can be with other enchant item spells.

**Comment by janne-hmp** [comment]
Changed to 5. Lightning enchants 5 arrows, fire 10, and cold 20. If you have 4 castings you will have 25 for lightning (3d6 damage), 50 for fire (2d6 damage), and 100 for cold (1d6 damage), which seems to be alright.
