### ISSUE TITLE
Necromancy spells balance

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#611]
Raise Skeleton makes a level 4 skeleton. Should not be level 3 spell, but level 1 or level 2.

Raise skeleton warrior creates a level 17 skeleton warrior. Should be level 5, since raise giant skeleton creates a level 10 giant skeleton. Raise giant skeleton should be level 3 or stay at level 4.

Also call ghoul could be a level 3 spell, since ghouls got upgraded with a paralysis attack.

See all Necromantic Spells here:
https://github.com/hyvanmielenpelit/GnollHack/wiki/Necromancy-Spells

It would be nice also to have a class that starts Basic in Necromancy spells, like the Necromancer.

**Comment by janne-hmp** [comment]
Chaotic healer = Necromancer like Herbert West the Reanimator?

**Comment by janne-hmp** [comment]
Or we make Caveman more like a cannibal with voodoo and necromancy skills?

**Comment by janne-hmp** [comment]
Done.
