### ISSUE TITLE
Time Stop could be Movement Spell instead of Transmutation Spell

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#614]
https://github.com/hyvanmielenpelit/GnollHack/wiki/Transmutation-Spells

https://github.com/hyvanmielenpelit/GnollHack/wiki/Movement-Spells

Movement space kind a modify the time and space. Haste and teleport. Fly and levitation...

**Comment by janne-hmp** [comment]
Done.
