### ISSUE TITLE
Option for showing xp gain needed

### ISSUE THREAD

**Issue by TeroKarttunen** [hyvanmielenpelit/GnollHack#617]
After each kill, the game tells the experience points gained ("You gain xx experience points.") There should be an Option to disable this, or better still, this could be tied to existing "show_exp" option (default = false, which is how I would like it anyway). In big battle, these messages slow down the game.

**Comment by janne-hmp** [comment]
Done. There is now a new tellexp option that you can change from 'O'. It is now set to TRUE by default, but you can put the following line in defaults.nh

OPTIONS=!tellexp

to initiate it to FALSE.
