### ISSUE TITLE
Balance MR of monsters

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#618]
We should give serious thought to which are correct levels of MR for monsters. Now, usually they are very low (0) or something like 90–100 (almost completely immune). Some good system should be devised.

**Comment by TommiGustafsson-HMP** [comment]
Also, now when MR blocks instadeath attacks, we should probably give more castings per mixing for these spells.

Also, Touch of Petrification should not be blocked by MR but by MC probably. It should also, then, have more castings per mixing.

Should test things thoroughly.

**Comment by TommiGustafsson-HMP** [comment]
Also, we probably can remove wand hitting chance and make it 100% because things are now resisted by MR and not monster AC.

**Comment by TommiGustafsson-HMP** [comment]
MC is now too high as wand of disintegration does not kill the dracolich very easily.

**Comment by TommiGustafsson-HMP** [comment]
How would be:

- Very magic resistant monsters: About 2% x Difficulty Level
  - Max. Normal Monster 80%
  - Max. Unique Monster 90%
  - Maxes out at level 40/45
  - Mind Flayers
  - Liches
  
- Normally Magic resistant monsters: About 1% x Difficulty Level
  - Max. Normal Monster 50% 
  - Max. Unique Monster 75%
  - Maxes out at level 50/75

- Lightly Magic Resistant Monsters: About 0.5% x Difficulty Level
  - Max. 20% Normal Monster
  - Max. 40% Unique Monster
  - Maxes out at level 40/80
  - Dragons

- Non Magic Resistant Monsters: 0%
  - Minotaurs
  - Giants
  - Cyclops

**Comment by TommiGustafsson-HMP** [comment]
Another possibility would be that the max MR would be 90% for all magic resistance types, making max out levels:
- Very: 45
- Normal: 90
- Lightly: 180

Thus, Archon (level 98), could be normally magic resistant with 90% magic resistance. Kirin (level 68) could be normally magic resistant with 70% magic resistance.
Lich (level 15): 15% magic resistance
Demilich (level 20): 20% magic resistance
Master Lich (level 26): 25% magic resistance
Arch-Lich (level 35): 35% magic resistance

Master Mind Flayer (level 36): 75% magic resistance
Mind Flayer (level 13): 25% magic resistance

Dragon (about level 36): 20% magic resistance
Ancient Dragon (about level 56): 30% magic resistance

**Comment by TommiGustafsson-HMP** [comment]
Or liches could be very resistant:
- Lich 30%
- Demilich: 40%
- Master Lich: 50%
- Arch-Lich: 70%

**Comment by TommiGustafsson-HMP** [comment]
Dragons could also be normally magic resistant:
- Dragons: 35%
- Ancient Dragons: 55%
- Dragon hatchlings: 10%

**Comment by TommiGustafsson-HMP** [comment]
So maybe the magic resistance categories would be:

Normal: 1% magic resistance / difficulty level
- All "magical" monsters
- Dragons and unicorns, etc.

Magic resistant monsters: 2% magic resistance / difficulty level
- Mind flayers and liches, etc.

Magic vulnerable monsters: 0.5% magic resistance / difficulty level
- All animals and natural monsters
- Some special monsters, such minotaurs (level 39->20% MR) and Cyclops (Level 84 -> 42% MR), which normally had 0% MR.

0% category is removed.

**Comment by TommiGustafsson-HMP** [comment]
Maybe MR can be removed if
- Charm is resisted by a Wisdom based saving throw.
- Death can be resisted only by death resistance and magic resistance.
- Disintegration works as in NetHack, first disintegrating armor, then the target.
- Petrification works as in NetHack, slowing first and then petrifying.
- Sleep works as in NetHack, but the duration might be shorter for bigger monsters.
- Fear works as in NetHack, but the duration might be shorter for bigger monsters.

Additionally,
- Touch attacks need to pass MC to take effect. This should be taken into account when designing spells. The spells might give penalties to MC, though.
- Ray attacks need to hit; this could also be A Dexterity Based Saving Throw.
- Area of Effect attacks always hit, but there might be a Dexterity based saving throw.

**Comment by TommiGustafsson-HMP** [comment]
Magic resistance granting death resistance can also be removed if we remove Touch of Death monster spell. I believe that it was the reason why it was there in the first place.

We could also add more ways to gain death resistance. For example, a new ioun stone might do well.

**Comment by janne-hmp** [comment]
Touch of death now requires passing MC. Rays need to hit the target's AC, which is influenced by DEX.

**Comment by janne-hmp** [comment]
Since the nature of magic resistance has been changed, this is now obsolete. We can think later if magic resistance numbers with different monsters need adjusting.
