### ISSUE TITLE
Some issues with the spell schools

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#619]
- No role starts with Basic skill level in Conjuration spells
- No role can be Expert in Enchantment spells
- No role starts with Basic skill level in Transmutation spells

See spell schools in https://github.com/hyvanmielenpelit/GnollHack/wiki/Spells

**Comment by TommiGustafsson-HMP** [comment]
How about:
1. Ranger starting with Basic in Conjuration, or a new role, **Druid**, who starts Basic in Conjuration. Add 1–2 starting conjuration spells and some reagents.
2. Wizard can be Expert in Enchantment.
3. Wizard starts Basic in Transmutation.

**Comment by janne-hmp** [comment]
Done, except for starting spells that take more time.
