### ISSUE TITLE
[From xNetHack] Items in an exploding bag of holding have a 12⁄13 chance of being scattered instead of destroyed.

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#62]
Items in an exploding bag of holding have a 12⁄13 chance of being scattered instead of destroyed.
Copy the changes from xNetHack, do not implement by yourself.

Source of Information: https://nethackwiki.com/wiki/XNetHack
GitHub Repository: https://github.com/copperwater/xNetHack

Should be easy to copy, since xNetHack is based on NetHack 3.6.2.

**Comment by janne-hmp** [comment]
Bag of Wizardry will drain the charges from the wand of cancellation instead of exploding. Otherwise, the bags still explode. However, almost all classes start with non-magical bags, so there is a place to put all your wands.

**Comment by TommiGustafsson-HMP** [comment]
Apparently not implemented.

**Comment by janne-hmp** [comment]
Done.
