### ISSUE TITLE
Chaotic Priest to start with 1–2 Necromancy spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#620]
No he has none. No abjuration spells for him.

And some appropriate reagents, too.

**Comment by janne-hmp** [comment]
New all classes start, for each school, with one spell per skill level beyond unskilled (1 for basic, 2 for skilled, and so on). Priest also has 2 random WIS-based spells and wizard Magic Arrow and 1 random INT-based spell. Healer has just Healing and 2 spells from Healing school.
