### ISSUE TITLE
Female characters to have -2 STR, +1 DEX, -1 CON, and +2 CHA?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#622]
Maybe a nerf, but it could be more challenging to play a female character.

Racial maximums would also be adjusted likewise.

**Comment by janne-hmp** [comment]
Maybe should be balanced and may depend on race. Gnolls like hyenas possibly have no differences between males and females, or maybe have STR -1, WIS +1. Humans maybe -1 STR, +1 CHA. Elves -2 STR, +2 CHA.

**Comment by TommiGustafsson-HMP** [comment]
Yes, maybe -1 STR, +1 CHA could be ok for females, so that it does not affect too much, but still have some effect. So, women can have Charisma 19.

**Comment by janne-hmp** [comment]
Deferred.
