### ISSUE TITLE
New Spells: Stick to Snake and Stick to Cobra

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#626]
**Stick to Snake**
Level 1 Clerical Spell
Material Component: Piece of Wood
Castings: 1
Summons a permanent Snake
200% Training

**Stick to Cobra**
Level 2 Clerical Spell
Material Component: Piece of Wood, Mandrake Root
Castings: 1
Summons a permanent Cobra
200% Training

**Comment by janne-hmp** [comment]
Done.
