### ISSUE TITLE
Prevent monsters using ranged attacks if there is another target in between

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#627]
For example, kobolds not to throw darts in the back of other kobolds. If there is invisible target in between, and cannot be seen by the monster, that's another thing.

Tame monsters should also not attack the player, if he is in between of the target. However, breath weapons can bounce to the player by accident, though.

I think the same goes for wand use. I guess monsters do not want to kill other monsters with their wands.

**Comment by janne-hmp** [comment]
Done.
