### ISSUE TITLE
Applying a Holy Symbol to give indication if prayer timeout has elapsed

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#628]
You could apply a Holy Symbol to check if your prayer timeout is 0.

For example, if it is 0, it could say "The Holy Symbol radiates white light."

If it is more than 0, it could say "The Holy Symbol radiates black light." Or something like that.

Also, if there is another reason, why it is not safe to pray (as being in Gehennom), they same messages would apply.

**Comment by janne-hmp** [comment]
You use holy symbol for turning currently, so this might be confusing. I made a new spell called commune (minor clerical cantrip, material component yellowish-brown glass) through which you can check whether you can pray safely. There is also now a major clerical cantrip called "enlightenment" (material component yellow glass), equivalent to wand of enlightenment. Finally, there is a new level 10 clerical spell called "prayer" (material component citrine stone, cooldown 150) that is equivalent to wizard mode prayer (which absolves your sins and forces gods to be pleased).
