### ISSUE TITLE
Make sure that classes with healing spells start with at least Healing

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#629]
Healer: Skilled
Monk: Basic
Priest: Basic

And healer could start with Extra Healing, too. Now you can have a healing class that cannot heal hit points at all.

**Comment by janne-hmp** [comment]
Healer should already always start with Healing indeed + 2 random spells from healing school. Can add Extra Healing as well. It used to be the case, but I removed it since it seemed redundant to have both Healing and Extra Healing.

**Comment by janne-hmp** [comment]
Can add Minor Healing to Monk and Healing to Priest.

**Comment by janne-hmp** [comment]
Done.
