### ISSUE TITLE
New Spells: Controlled Teleport and Circle of Teleportation

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#631]
**Controlled Teleport**
Movement Level 5
Teleports you to a chosen square.
Material Component: Heap of sporal powder, spider silk
Castings: 5

**Circle of Teleportation**
Movement Level 5
Teleports all monsters around you away.
Material Component: Heap of sporal powder, some gem
Castings: 4

**Comment by janne-hmp** [comment]
Done.
