### ISSUE TITLE
New Spells: Level Teleport, Controlled Level Teleport, and Portal

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#633]
**Level Teleport**
Level 6 Movement Spell
Teleports you as per cursed scroll of teleportation. Teleport control allows you to teleport in a controlled manner. Might also teleport all your pets that are around you.
Material Component: A precious gem
Castings: 2

**Controlled Level Teleport**
Level 8 Movement Spell
Teleports you to a dungeon level of your choice. Might also teleport all your pets that are around you.
Material Component: A precious gem, spider silk
Castings: 1

**Portal**
Level 7 Movement Spell
Teleports you to a branch of dungeon, in the same way as when you invoke The Eye of the Aethiopica. Might also teleport all your pets that are around you.
Material Component: 2 precious gems of different type
Castings: 2

**Comment by janne-hmp** [comment]
Done.
