### ISSUE TITLE
Make CHA as useful as other statistics

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#634]

**Comment by TommiGustafsson-HMP** [comment]
The effect of charisma on item prices could be revised.

Now they are:
Charisma	Price
3–5:	×2
6–7:	×1.5
8–10:	×1.33
11–15:	×1
16–17:	×0.75
18:	×0.67
19–25:	×0.5

Increasing charisma over 19 has no effect whatsoever.

Here's an alternative table:

CHA | Purchase Price % of normal price
1 | 350 %
2 | 325 %
3 | 300 %
4 | 275 %
5 | 250 %
6 | 225 %
7 | 200 %
8 | 175 %
9 | 150 %
10 | 125 %
11 | 100 %
12 | 80,0 %
13 | 66,7 %
14 | 57,1 %
15 | 50,0 %
16 | 44,4 %
17 | 40,0 %
18 | 36,4 %
19 | 33,3 %
20 | 30,8 %
21 | 28,6 %
22 | 26,7 %
23 | 25,0 %
24 | 23,5 %
25 | 22,2 %

**Comment by TommiGustafsson-HMP** [comment]
Further alternative table would be (this is exponential):

CHA | Purchase Price % of normal price
1 | 565,7 %
2 | 475,7 %
3 | 400,0 %
4 | 336,4 %
5 | 282,8 %
6 | 237,8 %
7 | 200,0 %
8 | 168,2 %
9 | 141,4 %
10 | 118,9 %
11 | 100,0 %
12 | 84,1 %
13 | 70,7 %
14 | 59,5 %
15 | 50,0 %
16 | 42,0 %
17 | 35,4 %
18 | 29,7 %
19 | 25,0 %
20 | 21,0 %
21 | 17,7 %
22 | 14,9 %
23 | 12,5 %
24 | 10,5 %
25 | 8,8 %

**Comment by TommiGustafsson-HMP** [comment]
There comes a problem that sell price is higher than purchase price. We need to think a solution.

**Comment by TommiGustafsson-HMP** [comment]
Maybe service costs (e.g. identifying, oracle, priest, join party) could be using the new table while purchase and sell prices would be using the old formula.

We can of course adjust the new formula to doubling every 5 levels or so, if doubling every four levels (i.e. 2^(1/4)) is too much.

**Comment by TommiGustafsson-HMP** [comment]
Doubling every five levels looks like this:

CHA | Service Price %
1 | 400,0 %
2 | 348,2 %
3 | 303,1 %
4 | 263,9 %
5 | 229,7 %
6 | 200,0 %
7 | 174,1 %
8 | 151,6 %
9 | 132,0 %
10 | 114,9 %
11 | 100,0 %
12 | 87,1 %
13 | 75,8 %
14 | 66,0 %
15 | 57,4 %
16 | 50,0 %
17 | 43,5 %
18 | 37,9 %
19 | 33,0 %
20 | 28,7 %
21 | 25,0 %
22 | 21,8 %
23 | 18,9 %
24 | 16,5 %
25 | 14,4 %

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp  Charisma is pretty useful now as it helps casting spells and reduces hireling costs and shop prices. Still a small effect on service prices #769 could be added. The effect needs to be small that it does not hinder too much the game with low charisma characters.

**Comment by TommiGustafsson-HMP** [comment]
As charisma increases also your mana pool, we may say that it may now be even better than Int and Wis.
