### ISSUE TITLE
Mana is plenty for everything except arcane spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#642]
There's a little thing to consider. When you are playing any other class except Wizard, the mana is always too much. Most spells are used seldomly and therefore mana usage is very low. The only situation, where mana _may_ be a problem, is with attack spells, which you may cast even every round. We should think, if this is ok, or if something should be done about it. Like what is good game design. Of course, it is better that mana is too much than that it is too little.

**Comment by janne-hmp** [comment]
Attack spells can take less mana than other spells.

**Comment by janne-hmp** [comment]
And speaking of mana, I just changed Pw on status line to MP (mana points) to be aligned with HP (hit points).

**Comment by TommiGustafsson-HMP** [comment]
Maybe we could consider halving cost of attack spells, and maybe reduce cost of HP healing spells by 25%, and reducing mana regen to MaxMana/600. But must test well first.

**Comment by TommiGustafsson-HMP** [comment]
Or mana regen could be even as low as MaxMana/1000.

**Comment by janne-hmp** [comment]
Can you make a calculation based on magic arrow and force bolt, and some other rarer spells, and see that what is a good cost for them and how quickly mana needs to regenerate so that mana does not run out and is not overly plenty?

**Comment by TommiGustafsson-HMP** [comment]
It needs to be tested. Cannot calculate.

**Comment by janne-hmp** [comment]
Fixed. Mana reneration is now MaxMana/900. Attack spells have base mana as follows: Level -1: 3, 0: 4, 1: 5, 2: 7, 3: 10, and so on. Healing spells are -1: 3, 0: 5, 1: 7, 2: 10, 3: 15, and so on.
