### ISSUE TITLE
Bug: Game Collapsed when trying to go up from Mine Town (to unsearched level)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#65]
In Wizard Mode, but I used no Wizard Mode things:

![image](https://user-images.githubusercontent.com/16661034/63635273-8d89e100-c669-11e9-8bbb-b5a93f4002c9.png)

**Comment by janne-hmp** [comment]
This has something to do with gems

**Comment by janne-hmp** [comment]
Was probably caused by calling setgemprobs at dungeon level initialization. It does not work anymore after with more gems have been added. Removed calling setgemprobs.
