### ISSUE TITLE
Change message 'You feel you are starting to slow down'

### ISSUE THREAD

**Issue by moon-chilled** [hyvanmielenpelit/GnollHack#655]
I got that message after a potion of speed started to wear off.  The thing is, it's very similar to the message you get when a cockatrice is petrifying you (basically the same aside from the 'you feel' at the beginning), so I freaked out for a second.  Probably doesn't hugely matter either way, but IMO it would be good to change, just to avoid confusion.

**Comment by janne-hmp** [comment]
Sure, many thanks for the comment. We'll change the text to something less freaky. An unintended consequence of a friendly early warning.

**Comment by janne-hmp** [comment]
I changed it now to "You are starting to feel less quick than before." and when slow-down finally happens "You feel less quick than before."
