### ISSUE TITLE
Adjust HP and damage by difficulty levels

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#660]
To remove some tedium in hard difficulties, we could implement that

1. Very easy difficulty: Damage lowered to 71% (SQRT(1/2)) , hit point lowered to 35% (SQRT(1/8)) = total effect 25%.
2. Easy difficulty: Damage lowered to 84% ((1/2)^(1/4)), hit points lowered to 59% ((1/2)^(3/4)) = total effect 50%.
3. Hard difficulty: Damage increased to 119% (2^(1/4)), hit points increased to 168% (2^(3/4)) = total effect 200%.
4. Very hard difficulty: Damage increased to 141% (SQRT(2)), hit points increased to 283% (2^(3/2)) = total effect 400%.

**Comment by TommiGustafsson-HMP** [comment]
Another possibility would be using (TotalEffect)^(1/3) for Damage and (TotalEffect)^(2/3) for HP.

- Very Easy: Total 25 % | Damage 63 % | HP 40 %
- Easy: Total 50 % | Damage 79 % | HP 63 %
- Normal: 100 % all
- Hard: Total 200 % | Damage 126 % | HP 159 %
- Very Hard: Total 400 % | Damage 159 % | HP 252 %

**Comment by TommiGustafsson-HMP** [comment]
Actually, there is no need to adjust HP or damage directly. Instead, we can implement it so that monsters take less damage on higher difficulties and you and tame monsters take extra damage on higher difficulties. Likewise, in easier difficulties monsters take extra damage and you and tame monsters take reduced damage.

**Comment by janne-hmp** [comment]
Done.
