### ISSUE TITLE
Make GnollHack support Unicode/UTF-8 rendering?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#661]
Terminals use Unicode/UTF-8 by default. This way, we would have better ASCII-grahpics out of box.

**Comment by janne-hmp** [comment]
Can look into how this is done in Nethack4/FIQHack.

**Comment by TommiGustafsson-HMP** [comment]
Or we can instruct people to set the right settings in the dgamelaunch start screen. #671

**Comment by TommiGustafsson-HMP** [comment]
Yes, can be implemented as new options and instructions in dgamelaunch.
