### ISSUE TITLE
Should most effects check for your polymorphed form's magic resistance?

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#663]
Now they do not. Added this only for AD_SLEE for the time being.

**Comment by TommiGustafsson-HMP** [comment]
If we balance the monster MR #618  , and because you are not able to polymorph into out-of-difficulty forms, I think it would be ok to check for MR as for monsters.

**Comment by janne-hmp** [comment]
The game now checks both for your form's magic resistance % and innate Antimagic property as well as any Antimagic property from items or from potion of magic resistance.
