### ISSUE TITLE
Gold ($) and MC do not show up in Curses Interface in the Status Bar

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#664]
![image](https://user-images.githubusercontent.com/16661034/74169143-83699800-4c33-11ea-8d63-bd897344a0d1.png)

**Comment by janne-hmp** [comment]
Windows does not have Curses Interface, so it's currently a bit difficult to do this with Visual Studio.

**Comment by janne-hmp** [comment]
Amazingly enough, this has now been fixed.
