### ISSUE TITLE
Add in-game information about what different skill levels do

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#667]
**Weapon skills**
- +to hit, + to damage

**Bare handed combat + Martial arts**
- +to hit, + to damage
- Strength bonus%
- Chance of multistrike
- Effects on kicking

**Disarm Traps**
- Chance to disarm normal traps and magical traps

**Magic school skills**
- Bonus to cast %
- Recuction in mana cost

There should be information about what the **current skill level does** (always) and what the **next skill level does** (when training).

**Comment by janne-hmp** [comment]
Done, except for extra detail on bare-handed combat and martial arts. Maybe that needs to be included in in-game help files or wiki.
