### ISSUE TITLE
Enhancing Arcane skills is bugged, shows 65536 turns (in Wizard mode)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#67]
![image](https://user-images.githubusercontent.com/16661034/63635634-279f5880-c66d-11e9-9ba8-478c3c379df0.png)

**Comment by janne-hmp** [comment]
Does not show with me. Did you something special beforehand?

**Comment by janne-hmp** [comment]
Fixed, this was a problem with spells of level -1, got -1 skill points
