### ISSUE TITLE
Make font colors work in Curses interface

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#670]
- Cursed items: red
- Blessed items: green
- Status bar colors: HP indicator behind name
- Status indicators, such as hunger, colored
- Attribute colors, when changing: red, green
- HP font color: red, yellow, green
- Mana font color: red, yellow, green

**Comment by janne-hmp** [comment]
These should be copied from Windows defaults.nh to your options file on the Linux server. It works for me with the right options.
