### ISSUE TITLE
Curses interface does not work on Windows Desktop

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#672]
`OPTIONS=windowtype:curses` does not work. Says 

> config_error_add: Window type curses not recognized.  Choices are:  tty.

![image](https://user-images.githubusercontent.com/16661034/75054225-5b9fed00-54db-11ea-95c7-33fb08e7d525.png)

**Comment by janne-hmp** [comment]
I do not think that curses interface is available in Windows in the first place. It is sort of a simple windowing system for Linux.

**Comment by janne-hmp** [comment]
Curses not available on Windows.
