### ISSUE TITLE
New MR lowering spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#674]
Lesser Lower Resistance:
- Lowers MR by 25%
- Level 3 Abjuration

Lower Resistance
- Lowers MR by 50%
- Level 5 Abjuration

Greater Lower Resistance
- Lower MR by 75%
- Level 7 Abjuration

Negate Resistance
- Lowers MR by 100%
- Level 9 Abjuration

All have precious material components, probably gems.

**Comment by janne-hmp** [comment]
Done under the names of Lower/Halve/Diminish/Negate Magic Resistance. All using a single orichalcum ore as material component giving 20/10/5/2 castings.
