### ISSUE TITLE
Crash report - Crashed on reading a spellbook of Divine Intervention

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#679]
I was reading a heavy spellbook. Seemed to be Divine Intervention.

![image](https://user-images.githubusercontent.com/16661034/75241412-b46ad080-57ce-11ea-9eb5-d56c3415c819.png)

![image](https://user-images.githubusercontent.com/16661034/75241461-cd738180-57ce-11ea-94a8-109e6b10544d.png)

![image](https://user-images.githubusercontent.com/16661034/75241483-d6645300-57ce-11ea-81a9-5ce325f02405.png)

**Comment by janne-hmp** [comment]
Seems like this might have been caused by a corrupted description, a string without ’/0’.

**Comment by TommiGustafsson-HMP** [comment]
Same comes when trying to use Alt-Z.

![image](https://user-images.githubusercontent.com/16661034/75263255-6669c300-57f6-11ea-8425-00528bd27d88.png)

In the Immediate Window it says:

```
objects[spl_book[splnum].sp_id].oc_short_description
0x00007ff7629d49b8 <Error reading characters of string.>
```

Which is the reason of the crash.

**Comment by TommiGustafsson-HMP** [comment]
Here is the contents of the object in question:

```
objects[spl_book[splnum].sp_id]
{oc_name_idx=645 oc_descr_idx=586 oc_uname=0x0000000000000000 <NULL> ...}
    oc_name_idx: 645
    oc_descr_idx: 586
    oc_uname: 0x0000000000000000 <NULL>
    oc_content_desc: 0x0000000000000000 <NULL>
    oc_short_description: 0x00007ff7629d49b8 <Error reading characters of string.>
    oc_name_known: 1
    oc_merge: 0
    oc_uses_known: 0
    oc_pre_discovered: 0
    oc_magic: 1
    oc_charged: 0 '\0'
    oc_unique: 0
    oc_nowish: 0
    oc_big: 0
    oc_tough: 0
    oc_dir: 1
    oc_material: 6
    oc_subtyp: 0 '\0'
    oc_skill: 22 '\x16'
    oc_oprop: 0 '\0'
    oc_oprop2: 0 '\0'
    oc_oprop3: 0 '\0'
    oc_pflags: 0
    oc_class: 10 '\n'
    oc_delay: 2 '\x2'
    oc_color: 15 '\xf'
    oc_prob: 10
    oc_weight: 50
    oc_nutrition: 20
    oc_cost: 245
    oc_damagetype: 0
    oc_wsdice: 0
    oc_wsdam: 0
    oc_wsdmgplus: 0
    oc_wldice: 0
    oc_wldam: 0
    oc_wldmgplus: 0
    oc_extra_damagetype: 0
    oc_wedice: 0
    oc_wedam: 0
    oc_wedmgplus: 0
    oc_aflags: 0
    oc_hitbonus: 0
    oc_mc_adjustment: 0
    oc_fixed_damage_bonus: 0
    oc_range: 0
    oc_oc1: 0
    oc_oc2: 2
    oc_oc3: 15
    oc_oc4: 6
    oc_oc5: 0
    oc_oc6: 0
    oc_oc7: 200
    oc_oc8: 0
    oc_dir_subtype: 0
    oc_material_components: 24
    oc_item_cooldown: 0
    oc_item_level: 0
    oc_flags: 0
    oc_flags2: 0
    oc_flags3: 0
    oc_power_permissions: 0
    oc_target_permissions: 0
    oc_critical_strike_percentage: 0
    oc_multigen_type: 0
```

**Comment by janne-hmp** [comment]
That’s also corrupted. Those two strings (even though they are const chars) tend get corrupted at the same time.

**Comment by TommiGustafsson-HMP** [comment]
Maybe there is somewhere a memory error that destroys data structures in memory?

**Comment by janne-hmp** [comment]
Does it occur on any other machine than your laptop?

**Comment by TommiGustafsson-HMP** [comment]
It crashed again on reading a spellbook, but this time I was unable to catch the error, because I was not running the game in debugger.

**Comment by janne-hmp** [comment]
Maybe this is also a 64-bit bug (the memory randomly being allocated to over 4GB, causing the corruption). Can you see if this happens also in 32-bit game?

**Comment by TommiGustafsson-HMP** [comment]
Hopefully, this will be resolved when all compiler warnings and code analysis warnings have been addressed.
