### ISSUE TITLE
Way to transfer items from one container to another

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#681]
Maybe a new command to do that or combine it with loot and apply bag.
- transfer items from one bag to another (e.g. from bag of holding to bag of treasure hauling)
  - needs one free inventory slot, through which all items are transferred into a second bag
  - if an item resists putting into a second bag, it stays in your inventory
  - the process ends if there are no free inventory slots
  - if there are more free slots, the process continues using them, until all is put into the second bag
- pick up selected items on the floor and put them directly into a container (without putting them into inventory)
  - items that resist this (e.g. amulet of yendor and loadstone?) just stay on the floor or end up in your inventory (so that you cannot identify them by this)
  - maybe it could work like this: you need one free item slot in your inventory, and the item first ends up in this slot and then is automatically put in the bag
  - if an item resists putting into a bag, it stays in your inventory
  - the process ends if there are no free inventory slots
  - if there are more free slots, the process continues using them, until all is put into the bag
- drop selected items from a container on the floor
  - needs one free inventory slot and works like putting things into a bag but with a drop action

Use cases
- loot a large chest and put everything into your bag **('l' - loot and then 'g' - transfer to your bag)**
- take items from your bag and put them into a large chest **('a' - apply bag and then 'c' - put items into a container on floor OR 'l' - loot and then 'c' - put items into the container from your bag)**
- drop items from your bag onto the floor **('a' - apply bag and then 'd' - drop items on the floor)**
- put items on the floor to your bag **('a' - apply bag and then 'p' - pick up items on the floor)**
- transfer items between your bags **('a' - apply bag and then 'g' - another bag)**

You can comment this on reddit:
https://www.reddit.com/r/nethack/comments/fa32i7/current_late_game_save_is_such_a_grind_but_have/

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp I think this more useful in GnollHack than Nethack, since you have more useful bags. It would be rather helpful to be able to transfer all gems from Bag of Holding to Bag of Treasure Hauling. Or reagents to Bag of Wizardry.

**Comment by janne-hmp** [comment]
Transferring works now. Have to look next to the picking up functionality, probably needs another command in addition to ',' to make it seemless. Dropping already works with 'tip' somehow - it pours all contents to the floor so maybe not super-helpful, but at least a start.

**Comment by TommiGustafsson-HMP** [comment]
Current implementation is very confusing. It is not at all clear where you put items. Idea in my commands were the following:
- using 'c' you always put items into the container on the floor, regardless if you looted the container or applied a bag
- using 'd' you always drop items on the floor from the container or bag
- using 'p' you always pick items on the floor and put them into the container or bag
- using 'g' you always put items into a bag in your inventory

Some improvements:
- you should always choose the container where you put the items, even if there is only 1 (to make it clear what is happening)
- If there is only one container, the question can be yes/no. "Are you sure to move 23 items from bag of holding to bag of treasure hauling?"

**Comment by janne-hmp** [comment]
Done, except for the confirmation question, which seemed unnecessary. Move to a container in inventory is 'm' and others are as above.
