### ISSUE TITLE
Monster join party cost is too high

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#683]
I had charisma 20 and gnome charged me 170 gold.

This is related to #634 .

**Comment by janne-hmp** [comment]
Let’s adjust the cost to charisma.

**Comment by janne-hmp** [comment]
Now lower level monsters are cheaper by default (50 gold less) and you get a big discount on charisma (5% discount for every CHA beyond 8). Gnome charges now a CHA 20 character 32 gold instead, and CHA 8 character 80 gold.
