### ISSUE TITLE
You can still multishot throwing weapons

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#684]
I thought multishot was removed.

**Comment by janne-hmp** [comment]
It is now skill-based on only with darts and shurikens (1 normally, 1d2 at skilled and 2 at expert). No other thrown weapons should be multishot. Of bows, only repeating crossbows can multishot.

**Comment by TommiGustafsson-HMP** [comment]
Doesn't it make throwing darts and shurikens quite overpowered compared to other ranged skills?

**Comment by janne-hmp** [comment]
This is deferred until the overpowered nature of darts and shurikens is demonstrated.
