### ISSUE TITLE
Do not use average of attributes in spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#689]
Like All or I+W.

Abjuration spells should be I/W.
Arcane spells should be Int.
Clerical spells should be W/C.
Conjuration spells should be Cha.
Divination spells should be Any.
Enchantment spells should be I/C.
Healing spells should be Wis.
Movement spells should be Any.
Necromancy spells should be Any.
Transmutation spells should be I/C.

Total:
- Intelligence used in 7 Spell Schools
- Wisdom used in 6 Spell Schools
- Charisma used in 7 Spell Schools

Schools:
- Int Schools: 1
- Wis Schools. 1
- Cha Schools: 1
- I/W Schools: 1
- I/C Schools: 2
- W/C Schools: 1
- Any Schools: 3

**Comment by janne-hmp** [comment]
Done, except changed Transmutation to be mixed (different combinations, roughly all stats equally useful there). Then there are:

- Int Schools: 1
- Wis Schools. 1
- Cha Schools: 1
- I/W Schools: 1
- I/C Schools: 1
- W/C Schools: 1
- Any Schools: 3
- Mixed Schools: 1
