### ISSUE TITLE
Pet Gnome does not pick up armors and wear them

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#690]
Also, when he dies, his gold is gone. (Maybe this is ok.)

**Comment by janne-hmp** [comment]
Maybe he or she is too small for them, but let’s investigate.

**Comment by janne-hmp** [comment]
So: gnome is small and cannot wear armor in general. Tame gnome is also a party member, which does not pick up items and who is not willing to give you any items that he has, e.g. at the time of hiring (unlike a dog). However, you can give him items and ask him to wear or wield them. But he will not do any of that automatically. If he did, he could pick up powerful items and would never give them back to you. The behavior can possibly be improved somehow.
