### ISSUE TITLE
Prevent gremlins spawning in elemental plane of water

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#696]
![image](https://user-images.githubusercontent.com/16661034/75611254-81537480-5b21-11ea-9a31-29b9d89f2c19.png)

**Comment by janne-hmp** [comment]
Changed their reproduction rate on water plane from 66% to 0% per round (can be changed later to a positive chance if need be). Also, if a gremlin reaches now 1 base HP (rather than 1 HP, which can go up from there due to constitution bonus), it cannot reproduce any more.
