### ISSUE TITLE
Armageddon requires too much mana to cast

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#697]
It is 1000 normally.

Should be 500-750 or so.

It is stupid that it cannot be cast because of requiring too much mana.

**Comment by TommiGustafsson-HMP** [comment]
Also, 5th component is not visible:
![image](https://user-images.githubusercontent.com/16661034/75611428-0e4afd80-5b23-11ea-8888-bca951feb687.png)

But it has too many components anyways.

**Comment by janne-hmp** [comment]
Lowered to 750 like other level 12 spells
