### ISSUE TITLE
If Special Attack Touch Spells need to pass MC and rays need to pass DEX Saving throw, add castings to such spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#698]
All instadeath spells have been designed the fact in mind that they work 100% of time. However, if this is not the case (see #618 ), but they can miss, we need to double, triple, or even quadruple their castings, based on whatever their success chance might normally be. Higher level spells of course are used later in the game, and MC and Dex Saving Throws can be greater there.

**Comment by janne-hmp** [comment]
It is better for the rays use AC. If you want to make the big monsters more difficult to kill with wands etc. just make their AC more negative. However, instantaneous non-ray spells such as Power Word Kill and Flesh to Stone use ability saving throws (CON and DEX, respectively, as words cannot be dodged). Touch spells use now MC. Increased castings of touch spells and Flesh to Stone. Power words can be cast infinite times.
