### ISSUE TITLE
Make charging rings safe

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#702]
Rings have a chance to explode only if enchanted 
- Normal rings (like +constitution): Can be safely charged to +3 (safe to charge, when +2 or below). After that, 33%/67%/100% chance to explode per additional enchantment. (Max. +6)
- Double effect rings (like +damage): Can be safely charged to +7 (safe to charge, when +6 or below). After that they have 25%/50%/75%/100% chance to explode per additional enchantment. (Max. +12)
- Ring of power: Can be safely charged to +2 (safe to charge, when +1 or below). After that has 50%/100% chance to explode per additional enchantment. (Max. +3)

Blessed scroll of charging gives 
- Normal Rings: +1 or +2
- Double Rings: +1-+3
- Power: +1

Normal scroll of charging gives:
- Normal Rings +1
- Double Rings: +1 or +2
- Power: +1

**Comment by janne-hmp** [comment]
Done, with small adjustments: Double rings are exactly double in everything. However, there nowadays only 1.5x powered rings, which are exactly 1.5x normal rings in above.
