### ISSUE TITLE
In Explore Mode, add a clear indication text at the end of the game that the game was in Explore Mode

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#708]
Also, make a clear indication to every game end in Explore Mode that the game was in Explore Mode. This text should not be able to be skipped by pressing 'q' or whatever else.

The same goes for Wizard Mode.

Maybe there could be also some kind of an indicator in the status bar in Explore and Wizard mode. For example, inverted orange 'E' for explore mode and inverted blue 'W' in Wizard Mode.

**Comment by janne-hmp** [comment]
There is now a non-colored W or E at the start of the second status line (in front of "DL"). When you die or quit, the game tells you if you were in debug (wizard) or explore mode.
