### ISSUE TITLE
Magic Resistance (Player and Monster) to work only against Magic Attacks and Polymorph

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#709]
- Magic Missile
- Force Bolt
- Magic Arrow
- Circle of Magic
- Magic Storm
- Polymorph (all forms except quaffing of Potion of Polymorph)
- All monster spells (such as Destroy Armor, if they are already resisted)

It will not work against
- Death attacks
- Sleep
- Fire, Cold, Lightning
- Disintegration
- or anything else

This will make magic spells worse than before, and I think we should increase castings for Circle of Magic and Magic Storm, since they are so often resisted.

Also, reduce magic resistance spells might also be improved with more castings as they also become worse.

**Comment by janne-hmp** [comment]
Done. Lowered also reduce magic resistance spell levels. Magic resistance now (and before) will halve the damage of fire / cold / lightning rays from wands, making it slightly more useful. Most other spells are resisted using CON (power word and holy word) or WIS (most other ones).
