### ISSUE TITLE
Game Crashed when trying to wear Elven Mithril Coat as a Wizard and then trying to cast a spell

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#71]
I was a wizard. I found Elven Mithril Coat. I had also a robe and cloak of MR. I tried to wear elven mithril coat and see how much it affected my casting success. But then the game crashed.

**Comment by janne-hmp** [comment]
Maybe a problem with the elven mithril cloak's half magic penalty ability.

**Comment by janne-hmp** [comment]
Fixed, accidently was using the wrong pointer.
