### ISSUE TITLE
Touch of Death only available for high level unique spell casting monsters

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#710]
Not including the Chromatic Dragon, but including demon lords and Wizard of Yendor. Against them, you need death resistance. Magic resistance is not enough. Touch of Death could be available for high level priests such as the high priest of Moloch in the sanctum and the high priests on the astral plane.

Touch of Death needs to pass MC to work, though.
The existing mechanic based on monster level or so for the spell to work can be removed.

Monk could gain death resistance at level 17 or 19.

**Comment by janne-hmp** [comment]
Done. Touch of death has -4 MC adjustment. Also, Knights, Healers and Priests gain death resistance at level 19. High priests have their own clerical version of Touch of Death.
