### ISSUE TITLE
New Monster: Gorgon

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#711]
Has Petrification breath weapon
Is stoning resistant

Petrification breath weapon causes you to slow down and then turn to stone.
Maybe it cannot use it every turn. Would be too overpowered.

**Comment by janne-hmp** [comment]
Done. Also a beholder and its kin can now shoot a petrification ray now. There is also a wand of petrification. Flesh to stone spell also shoots a petrification ray.
