### ISSUE TITLE
Dipping a weapon into fountain of poison does not make it poisoned

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#718]
Also, add ways to identify fountains. Maybe the fountains could be identified by color? One could learn the colors and they always stay the same from game to game.

Also, make it clear to old players that these are not "old fountains". I think different color would be enough.

**Comment by janne-hmp** [comment]
Now all non-bludgeoning weapons can be poisoned. All fountains remain of the same color. It would be odd if you could know in advance which fountain is which. However, we need to devise new ways identifying fountains, e.g., by dipping different kinds of objects into them.
