### ISSUE TITLE
Oracle to have an option to give GnollHack specific information

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#722]
Something like an oracle for old NetHack users, whatever it may be called. It could be 50 gold adjusted by charisma.

Also, remove oracles that are no longer true in GnollHack.

**Comment by janne-hmp** [comment]
The Oracle offers consulations just like she did in NetHack. What do you mean?

**Comment by TommiGustafsson-HMP** [comment]
I mean that the Oracle could give out information to old Nethack players about new features in GnollHack.

**Comment by janne-hmp** [comment]
Ok, and the Oracle should ask them first if they are old NetHack players, or they tell that through setting an option?

**Comment by TommiGustafsson-HMP** [comment]
Maybe he could ask "Are you already acquainted with the secrets of NetHack?" or "Would you like to hear only the mysteries of the new era? Or also the mysteries of the past?" Something like this.

**Comment by janne-hmp** [comment]
Obsolete with new hints and voiceovers.
