### ISSUE TITLE
Spears to work as reduced range polearms

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#723]
From Tommi's forum post:
Maybe the difference would be that spears can hit also melee range but you need to increase the skill to expert to be able to hit SQRT(8) squares away. So,
- Unskilled: Cannot apply, or range of SQRT(4)
- Basic: SQRT(4) range
- Skilled: SQRT(5) range
- Expert: SQRT(8) range

**Comment by TommiGustafsson-HMP** [comment]
Unskilled should be SQRT(4) according to NetHack wiki on lances.

**Comment by janne-hmp** [comment]
Done. There are now 3 types of appliable weapons:
- Polearms with min distance of SQRT(4) and max distance of SQRT(8), uses polearm skill
- Spears with min distance of 1 and max distance of SQRT(2/4/5/8), uses spear skill
- Lances with min distance of SQRT(4) and max distance of SQRT(4/4/5/8), uses spear skill
