### ISSUE TITLE
Replace Magic Mirror of Merlin with Artifact Lance

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#724]
Would be more useful for a knight, since double spell damage has been removed from Magic Mirror of Merlin.

**Comment by janne-hmp** [comment]
Rhongomyniad, the lance of King Arthur, sounds like an appropriate candidate.

**Comment by janne-hmp** [comment]
Done, and King Arthur has a new story behind this great lance, too.
