### ISSUE TITLE
Add a rune word that prevents monsters from picking up items and looting containers in the square where it is engraved

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#726]
This will replace Elbereth and a scroll of scare monster as a means of protecting important loot such as the wand of wishing in the castle and the prize in Sokoban.

The new rune word will NOT:
- prevent monsters from entering the square
- prevent monsters from attacking anyone in the square
- fade away

It can be engraved with a dagger or two.

Should this rune word also be from Lord of the Rings?

Or maybe it could be "InSanct" or "InSanctGrav" as reference to Ultima V.

**Comment by janne-hmp** [comment]
Done, the rune word is "Gilthoniel", which is a reference to Elbereth Gilthoniel, one of the Valar.
