### ISSUE TITLE
Consider mechanics for unicorn horn

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#729]
Maybe overpowered.

**Comment by TommiGustafsson-HMP** [comment]
One way is to limit its usefulness is to add charges to it. This would make it similar to other horns, such as fire horn.

**Comment by TommiGustafsson-HMP** [comment]
Maybe the horn could work 100% of time as well but cure only 1 ailment per charge.

Uncursed could cure:
- blindness except from cream pies and venom
- deafness
- confusion
- hallucination
- stun
- sickness
- nausea (from eating tripe/eggs)

Blessed could also cure:
- lost attribute points

**Comment by TommiGustafsson-HMP** [comment]
Some variants remove attribute points curing altogether, though. 

Maybe blessed would not cure attribute points but cure 2 ailments per use.

**Comment by janne-hmp** [comment]
Ok, working to add charges to the unicorn horn. Proved a bit more challenge, since the horn can also be used as a weapon.

**Comment by TommiGustafsson-HMP** [comment]
The weapon thing can also be removed.

**Comment by TommiGustafsson-HMP** [comment]
If Luckblade #732 is made so that it can be applied (or invoked) even when being a weapon, we can make it so that Unicorn horn also remains as a weapon. Otherwise, I think, unicorn horn does not need to be a weapon, if it is hard to implement.

**Comment by janne-hmp** [comment]
That's the plan -- To allow any item to have both +X enchantment and charges (expended by applying or invoking, or both). The current system for spe in struct obj was a bit of a mess anyway.

**Comment by TommiGustafsson-HMP** [comment]
I just changed the plan for Luckblade #732 . So, it does not need to be applied or invoked. Therefore, we can also make unicorn horn a normal tool that can only be applied like other horns.

**Comment by janne-hmp** [comment]
Noted. Let me see about the system anyway.

**Comment by janne-hmp** [comment]
Done. Unicorn horn has now both +X enchantment and charges.
