### ISSUE TITLE
New item: Luckblade

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#732]

**Comment by TommiGustafsson-HMP** [comment]
Adds +3 + Enchantment bonus to Luck.
If blessed, your good luck does not time out (the same as blessed luckstone).
It has 1d3 charges. Each charge can be used to cast a wish (On apply or on Invoke).
Cannot be recharged (or charged just once like Wand of Wishing).
Cannot be wished for (just like Wand of Wishing).
Is extremely rare.

**Comment by TommiGustafsson-HMP** [comment]
Even better:

Luckblade gets bonuses to hit and to damage equal to your luck. That is maximum of+13/+13 with maximum luck!

It is a very rare artifact that cannot be wished for.

**Comment by TommiGustafsson-HMP** [comment]
Also, I think we might want to remove it as acting as a luckstone. It just has great synergies with a blessed luckstone. Also, it does not need to have wishes.

So, in the end,
- Luckblade is not an artifact
- it does not grant wishes
- it only gets bonuses to hit and to damage equal to your luck. That is maximum of+13/+13 with maximum luck!
- it can be wished for.
- it can be enchanted,

Like this it is still a very powerful weapon to wish for.

**Comment by janne-hmp** [comment]
Done. It is an artifact that gives luck like luckstone, has 2-4 charges, and grants wishes upon invoke (uses one charge).
