### ISSUE TITLE
New item: Nine lives stealer

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#733]

**Comment by TommiGustafsson-HMP** [comment]
+3 to hit and to +3 damage.

Can be applied or invoked to kill an opponent in a melee range. If successful, grants HP equal to the HP of the slain creature to the wielder.

Has 9 charges. Cannot be recharged.

**Comment by TommiGustafsson-HMP** [comment]
Or better yet:

Has 9 charges. Can be recharged.
Applying or invoking can be used to kill opponent in a melee range as by touch of death. There is penalty to opponent MC equal to 9-(Number of Charges).

Has to-hit and damage bonuses equal to 9-(Number of Charges).

So, with 9 charges, the weapon is +0/+0 and with 0 charges it is +9/+9. On top of that, regulard enchantment bonuses apply.

**Comment by TommiGustafsson-HMP** [comment]
Blessed charging sets charges to maximum. Uncursed charging gives 1d6+1 charges.

**Comment by janne-hmp** [comment]
Done, but it works like in D&D so that whenever it hits the opponent it will expend one charge and kill the target unless it succeeds in a magic resistance or magic cancellation (either one protects). Does not grant HP or do anything else. Can be recharged.
