### ISSUE TITLE
New spell: Ghost Touch

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#737]
**Ghost Touch**
Abjuration Level 3
Give -4 to MC against your touch attacks and touch attack spells. Duration: 60 turns.
Material Component: Blue glass
Castings: 4

There could also be

**Greater Ghost Touch**
Abjuration Level 6
Gives -8 to MC against your touch attacks and touch attack spells. Duration: 60 turns.
Material Component: Sapphire
Castings: 4

**Comment by janne-hmp** [comment]
Not needed either.
