### ISSUE TITLE
Whatis '/' does not work right in the Curses Interface

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#740]
windowborders:0
![image](https://user-images.githubusercontent.com/16661034/76507266-2ab93500-6455-11ea-823f-16aecbb6070a.png)

windowborders:2
![image](https://user-images.githubusercontent.com/16661034/76507351-55a38900-6455-11ea-8a2e-74522c1a2e8c.png)

**Comment by janne-hmp** [comment]
Interesting

**Comment by janne-hmp** [comment]
This is a bug from NetHack 3.6.2. The cause why the last command line get reprinted on screen on the top of looked object / monster requires more investigation.

**Comment by janne-hmp** [comment]
Fixed.
