### ISSUE TITLE
Menus in the curses interface could be wider

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#742]
![image](https://user-images.githubusercontent.com/16661034/76515142-bfc22b00-6461-11ea-9b9e-b31097b2818f.png)

**Comment by TommiGustafsson-HMP** [comment]
![image](https://user-images.githubusercontent.com/16661034/77657912-9f748f00-6f7e-11ea-8015-c9a66131b7e4.png)

**Comment by janne-hmp** [comment]
Fixed.
