### ISSUE TITLE
'9' and '8' fast type selectors do not work in Curses Interface

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#744]
![image](https://user-images.githubusercontent.com/16661034/76516113-8d193200-6463-11ea-9ddc-855fe3714f94.png)

It just does normal count.

**Comment by janne-hmp** [comment]
The new functionalities fro 8, 9, and ' probably need to be separately implemented for each windowing system and front end. Curses is difficult to develop using Visual Studio.

**Comment by TommiGustafsson-HMP** [comment]
You could try Linux development with Visual Studio Code according to my instructions in the Linux Development Guide.

**Comment by janne-hmp** [comment]
Fixed.
