### ISSUE TITLE
Can we add a third row in Curses Interface for status messages?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#745]
Such as satiated or burdened.

![image](https://user-images.githubusercontent.com/16661034/76517691-6f010100-6466-11ea-98fb-60d071ceda30.png)

It could be an option. There used to be such an option but it was removed in 3.6.0. However, I think that our version would be just to put status messages there and nothing else.

**Comment by TommiGustafsson-HMP** [comment]
This is already possible with `OPTIONS=statuslines:3`. However, the layout is a bit strange there:

![image](https://user-images.githubusercontent.com/16661034/76697672-8a585000-66a2-11ea-841d-9978ce009009.png)

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp If `statuslines:3` is fixed to look nice, **it could be added to the default options on Windows and when using Curses Interfaces**. Of course, it cannot be added to the default configuration on basic SSH, because the terminal size is 80x24 as `statuslines:3` requires it to be 80x25.

**Comment by TommiGustafsson-HMP** [comment]
One more screenshot:

![image](https://user-images.githubusercontent.com/16661034/77197878-9e5ee000-6aee-11ea-82d3-44fbd07554c4.png)

I think it can work like this also well.

**Comment by TommiGustafsson-HMP** [comment]
In `statuslines:3`, the status messages appear a bit randomly:

![image](https://user-images.githubusercontent.com/16661034/77326182-1d882a00-6d22-11ea-88fa-ada7ccde0cab.png)

Blind is on the 3rd row, while others are on the 2nd row.

**Comment by TommiGustafsson-HMP** [comment]
Here's how all other statuses come up:

![image](https://user-images.githubusercontent.com/16661034/77345395-39e59000-6d3d-11ea-899d-80e508a0ef8d.png)

**Comment by janne-hmp** [comment]
Done.
