### ISSUE TITLE
Could not load saved game on Public Server

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#747]
This happened on Public Servers, when I tried to continue my saved game:

![image](https://user-images.githubusercontent.com/16661034/76533478-cf9d3780-6480-11ea-980e-3cf99e3a5067.png)

That is, program initialization failed. Memory allocation failure: cannot get 9 bytes.

**Comment by TommiGustafsson-HMP** [comment]
Could this be related to the fact that I had over 300 Magic Arrow spells mixed?

**Comment by janne-hmp** [comment]
Probably the same problem with savenames having unsigned int instead of size_t.
