### ISSUE TITLE
Telepathy could have 10 castings instead of 3

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#749]
Also it is quite difficult to cast, since level 1 Archaeologist has 100% fail:

![image](https://user-images.githubusercontent.com/16661034/76623856-e7d28c80-653c-11ea-9f05-524ec934d6b0.png)

He has even Basic skill in divination (+80%) but it is still 100% fail. And no penalties from armor.

**Comment by janne-hmp** [comment]
Fixed, now the casting chance is 60% at Int 16. There was a bug that the system gave one skill level too little bonuses.
