### ISSUE TITLE
Priest to not to get armor penalties for casting Wis or Int/Wis spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#75]
He would get penalties for casting Int spells though.

Int/Wis spells should show Stat as "Any".

**Comment by janne-hmp** [comment]
Two more attribute options implemented for spells: Maximum of INT and WIS (shows "I/W") and Average of INT and WIS (shows "I+W").

Priest gets now no armor penalties for casting such spells, but does get the initial spell casting penalty for the class and other such adjustments, if specified.
