### ISSUE TITLE
Stone Golem becomes hungry

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#751]
![image](https://user-images.githubusercontent.com/16661034/76630333-86b0b600-6548-11ea-8a5e-690fd2b6a7e5.png)

![image](https://user-images.githubusercontent.com/16661034/76630357-8e705a80-6548-11ea-95ba-c256890ea500.png)

**Comment by TommiGustafsson-HMP** [comment]
Also, Create Stone Golem is level 3 spell and it has 226 HP? Has it gotten some XP levels?

**Comment by janne-hmp** [comment]
Fixed. Create Stone Golem raised to level 5.
