### ISSUE TITLE
New Spells: Minor Oracle and Major Oracle

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#752]
**Minor Oracle**
Divination Minor Cantrip
Gives you a single minor oracle (as by eating a fortune cookie)
Material Component: Violet glass
Castings: 3

**Major Oracle**
Divination Level 4
Gives you a major oracle (as by consulting the oracle)
Material Component: Amethyst stone (violet)
Castings: 1

**Comment by janne-hmp** [comment]
Done under the name of Minor Consultation and Major Consultation.
