### ISSUE TITLE
Add more vegetable food for horses

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#756]
Maybe more vegetable monsters or more fruits everywhere?

Should be doubled or tripled. Problem especially in Gnomish mines.

Maybe add some vegetable rations which horses and ponies can eat, like tripe rations, but for horses, which give lots of vegetable nutrition. Some of real food rations can be changed for those. For example, a big bag of oat grains.

May be also areas of grass and hay.

**Comment by TommiGustafsson-HMP** [comment]
How about creating grazing squares. They are like fountains, having something like 10 uses so that the horse can graze there 10 times until it disappears.

**Comment by janne-hmp** [comment]
Deferred. You can now feed food rations to horses using the feed command.
