### ISSUE TITLE
Lower magic resistance is a minor cantrip

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#762]
![image](https://user-images.githubusercontent.com/16661034/76687126-a966cb80-6629-11ea-91d1-2d2db841a6e5.png)

Should it be a minor cantrip?

It also gets 40 castings per orichalcum ore. Is it right?

**Comment by TommiGustafsson-HMP** [comment]
Abolish Magic Resistance is level 3?

![image](https://user-images.githubusercontent.com/16661034/76687707-221c5680-662f-11ea-90c8-014394cdf44e.png)

**Comment by janne-hmp** [comment]
Raised magic resistance spells to levels 1/3/5/7 with castings of 10/7/5/4.
