### ISSUE TITLE
Conjuration school was supposed to be Cha but is not in reality

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#766]
Reference: #689 

At least these are not:

![image](https://user-images.githubusercontent.com/16661034/76689220-564a4400-663c-11ea-9873-6a329ab7b66a.png)

**Comment by TommiGustafsson-HMP** [comment]
If the spells are changed to Cha, Ranger should have more Charisma, like 13–14 at least.

**Comment by janne-hmp** [comment]
In the latest source files, all conjuration spells are already CHA-based. Not sure what game version that is.

**Comment by TommiGustafsson-HMP** [comment]
I accidentally started an old Win32 build...
