### ISSUE TITLE
Ranger could have high Cha and less Int and Wis

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#767]
Because Conjuration magic school is now Cha-based.

13-14 Cha is enough I think.

Now he starts with 7 or so:
![image](https://user-images.githubusercontent.com/16661034/76689467-ca85e700-663e-11ea-9a38-72ae3187f3bb.png)

Int and Wis can be reduced.

**Comment by janne-hmp** [comment]
Done.
