### ISSUE TITLE
Curses Interface could have an option for windowborders that adds 1 square spacing between areas

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#768]
windowborders:3 — 1 square spacing to the areas marked with red:

![image](https://user-images.githubusercontent.com/16661034/76689547-95c65f80-663f-11ea-83e1-d2b3a23ffa6b.png)

**Comment by TommiGustafsson-HMP** [comment]
Works already somehow on Linux:

![image](https://user-images.githubusercontent.com/16661034/77820981-1a5cb780-70ef-11ea-9f80-fcb0344a471f.png)

**Comment by TommiGustafsson-HMP** [comment]
Takes a bit less space and looks cleaner. However, I think we are fine with windowborders:0, too.

**Comment by janne-hmp** [comment]
Deferred.
