### ISSUE TITLE
Service costs to be affected by Charisma

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#769]
Not sure if service costs are affected by charisma or not, but they could be to some extent.

Of course, we must make sure that it is balanced so that it is not impossible to use services when playing a low Cha character and also that they are not ridiculously cheap when playing a high Cha character.

**Comment by TommiGustafsson-HMP** [comment]
They could be adjusted, for example, with a factor of 2^(1/8) = 1,090508 by each attribute point, 11 being 100% price. That is, the price is doubled every 8 points of charisma.

Cha | Service Price
1 | 237,8 %
2 | 218,1 %
3 | 200,0 %
4 | 183,4 %
5 | 168,2 %
6 | 154,2 %
7 | 141,4 %
8 | 129,7 %
9 | 118,9 %
10 | 109,1 %
11 | 100,0 %
12 | 91,7 %
13 | 84,1 %
14 | 77,1 %
15 | 70,7 %
16 | 64,8 %
17 | 59,5 %
18 | 54,5 %
19 | 50,0 %
20 | 45,9 %
21 | 42,0 %
22 | 38,6 %
23 | 35,4 %
24 | 32,4 %
25 | 29,7 %

So, with Cha 24, services would be at about 1/3 price, which is I think reasonable for such a high charisma.

**Comment by janne-hmp** [comment]
Done.
