### ISSUE TITLE
Tune down difficulty levels

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#771]
- **Very Easy:** 2x easier than normal (the same as current Easy)
- **Easy:** SQRT(2) easier than normal
  - Factor 1: 2^(1/2)^(1/3) = 2^(1/6) = 1,12246 (1/X: Monsters deal 89.1% damage)
  - Factor 2: 2^(1/2)^(2/3) = 2^(2/6) = 1,25992 (X: You deal 126% damage)
- **Very Hard:** 2x harder (the same as current Hard)
- **Hard:** 
  - Factor 1: 2^(1/2)^(1/3) = 2^(1/6) = 1,12246 (X: Monsters deal 112% damage)
  - Factor 2: 2^(1/2)^(2/3) = 2^(2/6) = 1,25992 (1/X: You deal 79.4% damage)

We can add more difficulties later if needed.

**Comment by TommiGustafsson-HMP** [comment]
Names could be
- Easy
- Slightly easier
- Normal
- Slightly harder
- Hard

**Comment by janne-hmp** [comment]
Done, but not name change.
