### ISSUE TITLE
Disarming a squeaky board ask for an item

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#772]
![image](https://user-images.githubusercontent.com/16661034/76731622-82fa7a80-6766-11ea-9320-c43e37ca4387.png)

Should it not be as easy as untrapping other traps? Why does it ask for an item?

**Comment by janne-hmp** [comment]
A very good question.

**Comment by janne-hmp** [comment]
It seems to require the use of potion of oil or can of grease. I guess idea is to make the floor board not to squeak.

**Comment by TommiGustafsson-HMP** [comment]
I think all traps should be disarmable with Disarm Traps skill without any items.

**Comment by janne-hmp** [comment]
Fixed.
