### ISSUE TITLE
Entering Mine's End caused Oops...

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#773]
![image](https://user-images.githubusercontent.com/16661034/76741860-e8576700-6778-11ea-8b8f-d149be05b72e.png)

![image](https://user-images.githubusercontent.com/16661034/76741917-00c78180-6779-11ea-9fba-98eaad0ee381.png)

![image](https://user-images.githubusercontent.com/16661034/76741948-0d4bda00-6779-11ea-8403-460e17eff77a.png)

![image](https://user-images.githubusercontent.com/16661034/76742016-22286d80-6779-11ea-9178-91235a90dae4.png)

![image](https://user-images.githubusercontent.com/16661034/76742042-2c4a6c00-6779-11ea-85c5-6d67faa2454c.png)

![image](https://user-images.githubusercontent.com/16661034/76742077-37050100-6779-11ea-855b-af39d0f8c3b1.png)

![image](https://user-images.githubusercontent.com/16661034/76742092-3ec4a580-6779-11ea-9988-9ebd3e42431c.png)

![image](https://user-images.githubusercontent.com/16661034/76742104-45ebb380-6779-11ea-9859-819d0951f147.png)

![image](https://user-images.githubusercontent.com/16661034/76743138-d4ad0000-677a-11ea-9a94-a1ae8c40e84c.png)

![image](https://user-images.githubusercontent.com/16661034/76742223-72073480-6779-11ea-83d5-24b7967c79d7.png)

**Comment by TommiGustafsson-HMP** [comment]
Situation was (from Recovery):

![image](https://user-images.githubusercontent.com/16661034/76743040-ae876000-677a-11ea-841b-267f34b1ba23.png)

**Comment by janne-hmp** [comment]
Fixed.
