### ISSUE TITLE
Add items which can be used to heal your pets and hirelings

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#774]
Bandages?
Using a bandage takes 10 turns and heals 20 damage.
Bandages stack as items.
There could be 3–5 bandages in the starting chest.

There might be better bandages for high level characters later on.

**Comment by janne-hmp** [comment]
Healing salve?

**Comment by TommiGustafsson-HMP** [comment]
Yes. It would be ok as well.

**Comment by janne-hmp** [comment]
Done. There are now jar of healing salve (6d6, 4-9 charges) and jar of extra healing salve (12d6, 4-9 charges).
