### ISSUE TITLE
Add a description to examine about what an item does

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#776]
For example, potion of restore ability:

![image](https://user-images.githubusercontent.com/16661034/76762605-3fb9ff00-679a-11ea-9edb-19565fd91e9b.png)

Blessed: Restores all lost ability points and all lost experience levels.
Uncursed: Restores one lost ability point and one lost experience level.
Cursed: Does nothing.

Option 1. All BUC effects should be listed, when the item name is known, so that you know if you want to bless the item or not. If the BUC status is known, the right effect could be highlighted.
Option 2. Only the current effect is listed, not all.

Option 3. Nothing is listed. You must check the wiki. Should not be so, or?

**Comment by TommiGustafsson-HMP** [comment]
Only one generic description, unrelated of BUC status.

**Comment by janne-hmp** [comment]
Closed, since there is also issue #654
