### ISSUE TITLE
Whatis '/' should show if the pet is ill, stunned, or whatever else

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#777]
No, no mention of terminal illness.

![image](https://user-images.githubusercontent.com/16661034/76767915-f9b56900-67a2-11ea-82f7-7672e36681a3.png)

**Comment by janne-hmp** [comment]
Actually, this is what the stethoscope does. If we change '/' to be like stethoscope, then what should the stethoscope do?

**Comment by TommiGustafsson-HMP** [comment]
Stethoscope would work on enemies.

**Comment by janne-hmp** [comment]
Done.
