### ISSUE TITLE
Examining a fig in inventory causes a crash after loading a saved game

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#779]
![image](https://user-images.githubusercontent.com/16661034/76768313-7c3e2880-67a3-11ea-894c-0a2cd18678a7.png)

### objects[otyp].oc_short_description is corrupted:

![image](https://user-images.githubusercontent.com/16661034/76768466-b7d8f280-67a3-11ea-881d-ca89f22dc001.png)

![image](https://user-images.githubusercontent.com/16661034/76768524-cb845900-67a3-11ea-94fe-03d198b10f37.png)

**Comment by janne-hmp** [comment]
Is this repeatable? Does not happen with me.

**Comment by TommiGustafsson-HMP** [comment]
This is the same old string corruption bug after a long game. But I can test more.

**Comment by TommiGustafsson-HMP** [comment]
Played 2.5 hours and everything is working well so far.

**Comment by janne-hmp** [comment]
It would also be good to know if string corruption happens on some other computer than your laptop. I think we haven’t seen it on any other computer.

**Comment by TommiGustafsson-HMP** [comment]
I think it happened once to me on public servers #747 .

**Comment by janne-hmp** [comment]
Ok, more testing is needed, but probably due to a generic x64 problem. I should probably test much more, too.

**Comment by TommiGustafsson-HMP** [comment]
It happened again. After rebuilding and debugging:

![image](https://user-images.githubusercontent.com/16661034/77039746-41b0d780-69bf-11ea-8c39-ff847d93d028.png)

It did not happen directly after loading and saving. But Visual Studio had to rebuild the solution in between.

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp So the bug is caused by Rebuilding the solution and Running Code Analysis on solution #794 .

**Comment by janne-hmp** [comment]
Fixed.
