### ISSUE TITLE
New monsters: Hydra and friends

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#782]
**Hydra**
Has 7 heads
Attacks 7 times
Vorpal Blade decapitates only 1 head per time, reducing attacks by 1

**Lernaean Hydra**
Has 7 heads
Attacks 7 times
Regenerates heads back over time
Regenerates fast
Raises from the dead like a troll
Vorpal Blade decapitates only 1 head per time, reducing attacks by 1

**Pyrohydra**
Has 7 heads
Attacks 7 times
Breathes fire (one beam but 7x damage)
Immune to fire
Vorpal Blade decapitates only 1 head per time, reducing attacks by 1 and fire breath damage by 1x

**Comment by janne-hmp** [comment]
Done, except pyrohydra's breath weapon does always 4d8 damage for the sake of simplicity.
