### ISSUE TITLE
Crown of Rulership gives pretty big Charisma

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#783]
![image](https://user-images.githubusercontent.com/16661034/76836247-32078680-6839-11ea-9b47-b8786be5ecfa.png)

I think it is 23 + Enchantment bonus.

Would it be better to give 19 + Enchantment bonus?

**Comment by janne-hmp** [comment]
I changed it to fixed 24 (like belt of storm giant strength) to make it different from Robe of Splendor (20+enchantment).

**Comment by TommiGustafsson-HMP** [comment]
Ok. It was pretty powerful, though. I found 2 of them. It must be very expensive, too.
