### ISSUE TITLE
Pony did not attack orange dragon hatchling

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#787]

**Comment by janne-hmp** [comment]
Maybe too scared to do that. It is just a pony.

**Comment by TommiGustafsson-HMP** [comment]
Maybe so yes. So it is inteded behaviour=

**Comment by janne-hmp** [comment]
Deferred, until further problems emerge. This was most likely intended behavior for a pony.
