### ISSUE TITLE
Make search 's' to find roots in garden rooms.

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#790]
So that it searches all 9 squares when pressed.

Also, searching ability could find roots in garden rooms.

Digging every square with Alt-g is quite tiring and boring.

**Comment by janne-hmp** [comment]
Done, but it searches only for the current square for roots. If it does not find anything, it searches also the adjacent squares for secret doors and other normal stuff.
