### ISSUE TITLE
Add a party member view

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#791]
How about adding a view where you can see the status of your party members?

The view would show their HP, mana, AC, MC, attribute points, different statuses, such as hungry. So much like a status line for the player character.

Maybe the key could be Alt-h as in **H**irelings.

_Optional._ In the Curses Interface, it could be a separate view in place of the permanent inventory. Or the right part of the screen could be split by party member stats and permanent inventory. Another, maybe a better possibility, is that in the curses interface the party member stats would appear under your status bar as separate "status bars". This way, the height of the window could be used for something else than info messages.

In Ultima, the HP of party members is always visible (and also if they are poisoned):

![image](https://user-images.githubusercontent.com/16661034/76962402-d2d46f80-6927-11ea-8bac-26c2c9707b25.png)

**Comment by transcendreamer** [comment]
You are doing something fantastic. Yes, it would be very nice to see companion status to know if he/she needs to be healed.

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp Maybe there could be 1–3 optional statusbar lines for party members with the following format:

```
Name of Party Member: 30(30) Hungry
```

where 30(30) is hit points (can be colored like your HP).

For example,

```
Stone Golem: 147(147)   Slasher: 49(49) Hungry
```

So, the name is either the object name of the monster (e.g., stone golem), or if the monster is named, it's name (e.g. Slasher). Thus, you can name your party members to tell them apart. If you, let's say, have two stone golems, you can name one Max and the second Luke to tell them apart.

One could set the party member lines with

```
OPTIONS=partylines:2
```

**Comment by janne-hmp** [comment]
Done with one party line for TTY. Just set statuslines to 4. Does not work for curses yet.

**Comment by janne-hmp** [comment]
This now works for 5 extra status lines for TTY. Just set statuslines to 4-8.

**Comment by janne-hmp** [comment]
Now this also works for Curses Interface. Closed.
