### ISSUE TITLE
Add a way to identify the scroll of identify

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#795]
Now, I've used price identification in Mine Town exclusively. Maybe there could be another way?

**Comment by janne-hmp** [comment]
Identified by default for everybody?

**Comment by TommiGustafsson-HMP** [comment]
Can be. Would make some sense.

**Comment by TommiGustafsson-HMP** [comment]
Then, also the second starting scroll can be removed.

**Comment by janne-hmp** [comment]
Sure. a scroll of identify is self-identifying. Does everybody then have the scroll in the inventory? Sounds like the stash is then empty?

**Comment by TommiGustafsson-HMP** [comment]
It is no longer in stash?

**Comment by janne-hmp** [comment]
No, it is still in stash, but does it make sense that you have to always pick it up from there first? Maybe it does? What should be in the stash? Some people didn't think an axe is a great thing to be there.

**Comment by TommiGustafsson-HMP** [comment]
It can be in the starting inventory, too. Saves some actions.

**Comment by janne-hmp** [comment]
But what is then in the stash?

**Comment by TommiGustafsson-HMP** [comment]
Maybe it can be removed.

**Comment by janne-hmp** [comment]
Stash has now 2-3 random items, whose blessing status is identified (due to altar).
