### ISSUE TITLE
Disarm Traps skill shows % wrong

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#797]
![image](https://user-images.githubusercontent.com/16661034/77148711-c3c0ff00-6a98-11ea-9817-1a91cce9a80a.png)

I guess at unskilled it should be 33%/0% (normal/magical traps).

Also, 4 successful disarms of non-magical traps should generate enough training to go from Unskilled to Basic.

Disarming magical traps should generate double training.

Basic -> Skilled: 8 normal traps or 4 magical traps.
Skilled -> Expert: 16 normal traps or 8 magical traps.

Something like this.

**Comment by janne-hmp** [comment]
% is fixed. Disarming traps now gives at least 5 skill points for all traps. Disarming a polymorph trap gives the highest amount, 16 skill points. Thus, disarming 4 easiest traps moves one from Unskilled to Basic (20 points), 12 easiest traps / 4 polymorph traps moves advances one from Basic to Skilled (60 points), and 20 easiest traps / 7 polymorph traps moves one from Skilled to Expert (100 points).
