### ISSUE TITLE
Whatis for pets could be formatted nicer

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#800]
![image](https://user-images.githubusercontent.com/16661034/77150687-1e5c5a00-6a9d-11ea-83fb-c4f79c6bfa7d.png)

Hungry and apport is confusing. Could it be somehow clearer?

Stone golem should not eat so useless information should not be displayed.

![image](https://user-images.githubusercontent.com/16661034/77150778-506dbc00-6a9d-11ea-9b18-de38c5269261.png)

What does this hungry 43103 mean anyways?

**Comment by janne-hmp** [comment]
Done. Format has been updated, and the wizard mode data (hungry time and apport) can be turned on using a new wiz_mstatusline option (off by default).
