### ISSUE TITLE
New tool: Saw

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#802]
Can be used to cut down tree. Should be rather light.

**Comment by TommiGustafsson-HMP** [comment]
Maybe there could be a chance that bugbears or ogres in garden rooms carry a saw?

**Comment by janne-hmp** [comment]
Done. It is now Saw of Mighty Cutting, which also deals extra damage against wooden creatures (wood golems and treants) and has double normal cutting speed. Bugbears do not have such a powerful magic item.

Also, shovel has now been changed to Spade of Colossal Excavation that deals double damage against stone creatures (stone and clay golems, earth elementals, gargoyles, etc.) and has double normal digging speed. A dwarf with such a spade has quadruple digging speed!
