### ISSUE TITLE
Entering Gnomish Mines instantly crashes the game!

### ISSUE THREAD

**Issue by transcendreamer** [hyvanmielenpelit/GnollHack#805]
Playing the latest beta every time I descent to Gnomish Mines the game drops saying "Oops" at the center of terminal screen, please take a look into this problem.

**Comment by janne-hmp** [comment]
Fixed. A bug created by the hunt for other x64 bugs, but now this is also fixed. As a bonus, there are now the latest 4.0.22 features on the servers.

**Comment by transcendreamer** [comment]
Thanks!
