### ISSUE TITLE
Thematic rooms and furniture

### ISSUE THREAD

**Issue by transcendreamer** [hyvanmielenpelit/GnollHack#806]
I'm going to suggest adding special objects class: furniture and special thematic rooms, like library, armory, canteen, pub, warehouse, maybe even hospital and dormitory. Gnollhack already has gardens where adventurer may replenish stocks for fruits and mushrooms. The idea is that items of specific type should be found not just anywhere but in specific places.

- Library: contains bookshelves for storing books and scrolls, that makes sense rather than finding them anywhere e.g. in caves.
- Armory: racks for weaponry, wall panels for armor.
- Canteen and pub: tables and chairs, food on tables, bar with drinks.
- Hospital & dormitory: beds for resting/healing, first aid kits.
- Warehouse: barrels and crates with goods.
- Wardrobe with hangers for garments.
- Wizard rooms with stack for rings & wands.
- Treasury with showcases & lockers for jewelry and gold.
- Workshop: tables, panels for tools and maybe some raw materials.
- Smithery with forges.
- Etc...

For years we're used to see bare walls and floors in Nethack and items just randomly scattered over the floor. Hell, we even eat food from floor like tramps. Adding furniture and thematic rooms will enhance adventure simulation and will add to atmosphere of nice RPG game.

**Comment by janne-hmp** [comment]
A good idea in general, especially in order to add to the proper RPG atmosphere. Let us think about this more. We probably need to make it so that the rooms would make a bit more sense what is where, but e.g. storage rooms could be put anywhere. It is not difficult to make more rooms of different types, but the vanilla NetHack has zero rationale why different rooms appear in different place (it just randomized without any story or other logic), so one might want to make an engine/routine that creates a randomized rationale for placing rooms across the dungeon.

On another note, there's actually already a library with liches more down the dungeon, but it is relatively rare.

**Comment by transcendreamer** [comment]
Maybe... intelligent races could occupy a level having sort of base or outpost there, so thematically furnished rooms would look like in their household? They could even have some kind of rural economy with gardens and grazing squares (I've peeped them from another issue #756). So there could be levels where hobbits live and levels for kobolds, orcs, elves, drows, etc. And of course some abandoned levels with ghosts, crawling with different non-intelligent monsters, maybe even underground forest with wild animals. Earlier in Slash'em there was a kobold level, spider caves and a level with rat king...

**Comment by janne-hmp** [comment]
Sure, let us think about these. Lairs for various kinds of monsters would make sense as individual rooms. But making all of these work properly needs some serious work. For example, currently all monsters in all rooms must be sleeping to make sure that they do not wander out of them, which is not ideal. It would be better to assign "lair monsters" a home room that they do not leave unless necessary, but this would require big changes in the monster AI (though, doable for sure). And quite a few other stuff probably needs to be fixed to make them work in reality. In any case, we'll make a mark of this.

**Comment by janne-hmp** [comment]
Following have been added: Library (spellbooks), armory (weapons), smithy (blacksmith NPC services), and artificer wizard (magical NPC services).
