### ISSUE TITLE
Entering Gnomish Mines crashes on Linux

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#807]
![image](https://user-images.githubusercontent.com/16661034/77251447-11836600-6c57-11ea-9c90-2fb1b8074c6e.png)

Suddenly, the dungeon collapses.
To report this error, contact root or games
and it may be possible to rebuild.
Memory allocation failure; cannot get 171798691841 bytes

**Comment by janne-hmp** [comment]
Fixed.
