### ISSUE TITLE
Prayer spell, which is Level 4, is aeon-old prayer

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#811]
Usually comes only with high level spells...

What does Prayer do anyways? It is not clear. Is it the same as praying? Does it increase your prayer timeout?

**Comment by janne-hmp** [comment]
Prayer is the same as the prayer command, but by casting it you can always "safely pray".

**Comment by janne-hmp** [comment]
Fixed.
