### ISSUE TITLE
Healer feels wide awake after eating a corpse, even though is sleep resistant from Role

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#812]
![image](https://user-images.githubusercontent.com/16661034/77318620-07746c80-6d16-11ea-9c85-8ed093d0eef0.png)

![image](https://user-images.githubusercontent.com/16661034/77318632-0b07f380-6d16-11ea-9d70-bf9ef000061b.png)

**Comment by janne-hmp** [comment]
In NetHack, it says so when you acquire it by eating even if you had it also otherwise, e.g. from role etc. So this is a feature letting you know that an permanent intrinsic has been acquired by eating.

**Comment by janne-hmp** [comment]
Deferred.
