### ISSUE TITLE
Tone down One Ring

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#813]
https://community.soundmindgames.com/threads/what-a-find.44/

Summoned King Wraith was pretty tough. I think it is more dangerous than useful.

**Comment by janne-hmp** [comment]
Changed it to give +3 attribute bonus, and generated monster levels are 2x your level for lower level monsters and 2.4x for King Wraith and 2.8x for Nazgul.
