### ISSUE TITLE
New spell: Detect Holiness

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#815]
Divination Major Cantrip
Detects the BUC status of an item
Material Component: Glass of the same type as identify spell
Castings: 4–5

Identify spell can be moved to 3rd level from 1st.

**Comment by janne-hmp** [comment]
Done. Name is Detect Blessedness (could be also Detect Beautitude, but it would be a bit unclearer). 5 castings. Identify had already been moved to level 1 at some point.
