### ISSUE TITLE
Buff line

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#816]
There could be one line in the status bar for showing different buffs from spells. For example, noting that the Reflection spell is on. The buff badge could be green when the spell on and maybe yellow/orange when it is about to time out.

You could activate the buff line in the status bar with

`OPTIONS=bufflines:1`

**Comment by janne-hmp** [comment]
GUI has now possibility to define buffs for all (timed) properties.
