### ISSUE TITLE
Fighting Mind Flayer with Ring of Sustain Ability causes program in disorder

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#817]
![image](https://user-images.githubusercontent.com/16661034/77856589-d659d780-7200-11ea-89e8-ed0326badf17.png)

![image](https://user-images.githubusercontent.com/16661034/77856594-de197c00-7200-11ea-8d7b-be86eb198f5f.png)

Does it also protect against amnesia? No it does not. It should.

**Comment by janne-hmp** [comment]
Should be fixed. Now. There was a problem with iron shoes being accidentally identified by default.
