### ISSUE TITLE
Error entering the end game from level 1

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#819]
![image](https://user-images.githubusercontent.com/16661034/78011347-23969000-734c-11ea-82ef-8d56822c79d0.png)

![image](https://user-images.githubusercontent.com/16661034/78011381-2ee9bb80-734c-11ea-90da-a901a3a10dff.png)

![image](https://user-images.githubusercontent.com/16661034/78011411-36a96000-734c-11ea-8802-8fa5d417e982.png)

![image](https://user-images.githubusercontent.com/16661034/78011430-3dd06e00-734c-11ea-9323-2a132e9ef769.png)

![image](https://user-images.githubusercontent.com/16661034/78011447-432db880-734c-11ea-9571-ae3b5ce20da1.png)

![image](https://user-images.githubusercontent.com/16661034/78011457-47f26c80-734c-11ea-83fc-3c4bef3b140d.png)

![image](https://user-images.githubusercontent.com/16661034/78011477-4e80e400-734c-11ea-8af9-cb6b59961960.png)

![image](https://user-images.githubusercontent.com/16661034/78011510-593b7900-734c-11ea-852d-d50e62c7d664.png)

![image](https://user-images.githubusercontent.com/16661034/78011529-5f315a00-734c-11ea-942b-fbd67a66343d.png)

![image](https://user-images.githubusercontent.com/16661034/78011558-68bac200-734c-11ea-9ee6-fc93bbb78e5e.png)

![image](https://user-images.githubusercontent.com/16661034/78011598-74a68400-734c-11ea-930e-ca3e1cb1fb3c.png)

**Comment by janne-hmp** [comment]
Fixed.
