### ISSUE TITLE
Ask pet take off Eyes of the Underworld crashes the game

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#821]
Previously I asked him to unwear Shield of Reflection.

![image](https://user-images.githubusercontent.com/16661034/78013323-fbf4f700-734e-11ea-8bb1-101108d411bc.png)

![image](https://user-images.githubusercontent.com/16661034/78013358-0a431300-734f-11ea-9bbf-a0fb1b1f05fe.png)

![image](https://user-images.githubusercontent.com/16661034/78013388-1202b780-734f-11ea-9d2d-6e76e75ffd46.png)

**Comment by janne-hmp** [comment]
Fixed.
