### ISSUE TITLE
Wizlevelporting to endgame levels (-1 - -5) crashes game

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#822]
![image](https://user-images.githubusercontent.com/16661034/78015806-973b9b80-7352-11ea-9b79-908aecfc60d7.png)

![image](https://user-images.githubusercontent.com/16661034/78015823-9d317c80-7352-11ea-9904-4fb69dac9108.png)

![image](https://user-images.githubusercontent.com/16661034/78015863-aae70200-7352-11ea-83ac-16616a3ad753.png)

![image](https://user-images.githubusercontent.com/16661034/78015896-b5a19700-7352-11ea-8518-6bfa7f27fcd9.png)

![image](https://user-images.githubusercontent.com/16661034/78015912-bb977800-7352-11ea-8922-cf06f16f12a3.png)

![image](https://user-images.githubusercontent.com/16661034/78015927-c3571c80-7352-11ea-925e-6db696af3c1b.png)

**Comment by janne-hmp** [comment]
Fixed.
