### ISSUE TITLE
The game generates entrance to Fort Ludios less than 5% of time

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#823]
At least according to `#wizlevelport`. It should read Portal to Fort Ludios, if it is generated, but it almost never shows up.

Teleporting to Fort Ludios with no portal to return ends the game. Is probably intended behavior.

According to NetHack wiki, Fort Ludios should be accessible 74.9% of all games, which is certainly not the case with GnollHack.

**Comment by janne-hmp** [comment]
It seemed to create the portal for me immediately at level 11.

**Comment by janne-hmp** [comment]
I think the portal is created dynamically as you advance from level 11 onwards. You can't wizteleport there directly. You must go first to level 11 and see if it gets created.

**Comment by TommiGustafsson-HMP** [comment]
Seems to be this way.
