### ISSUE TITLE
Archons do not attack Giant Cockatrice

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#824]
![image](https://user-images.githubusercontent.com/16661034/78019551-9ad22100-7358-11ea-8cf1-bb1b329689de.png)

**Comment by TommiGustafsson-HMP** [comment]
They were invisible.

**Comment by janne-hmp** [comment]
Fixed. Archon did not realize it had a weapon to strike it with. Otherwise it would have turned to stone.
