### ISSUE TITLE
Eating a lizard corpse to cure petrification (or any other method) should grant immunity to petrification for 5–10 turns

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#825]
So that you do not need to eat the lizard corpse each round when fighting cockatrices.

**Comment by janne-hmp** [comment]
Done. Grants petrification resistance for 6-9 rounds.

**Comment by janne-hmp** [comment]
Actually had to change it to 13 rounds to make it work properly for a messaging stand point. Eating the corpse takes some 4 rounds, and you get a message of stone resistance wearing out 3 rounds before the end.
