### ISSUE TITLE
Sprig of Wolfspane does not have description and tells Magic Cancellation: -7

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#826]
![image](https://user-images.githubusercontent.com/16661034/78137808-95470a80-742e-11ea-8c1d-bfeff182aa63.png)

I think it cures from Lycanthropy, right?

What is this thing with Magic Cancellation?

**Comment by janne-hmp** [comment]
Fixed.
