### ISSUE TITLE
Examine tells that Enchantment bonus gives more MC, but it does not do so in reality, according to the status bar

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#827]
![image](https://user-images.githubusercontent.com/16661034/78138030-f7077480-742e-11ea-9593-d69e06d58359.png)

I think enchantment bonus could give +X/2 to MC or so? So, +1 for every +2 enchantment.

**Comment by janne-hmp** [comment]
Fixed. Also halved MC effect for enchantment, as suggested.
