### ISSUE TITLE
Prevent low level nasties being summoned by high level liches

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#829]
Sometimes they summon too easy monsters, which is now important, because they summon only 1 monster now. Also, it could be that high level liches could summon 2 or 3 nasties instead of one, if the lower limit is kept the same.

**Comment by janne-hmp** [comment]
Changed most of them be very difficult. Level 50+ monsters and Wizard of Yendor can now summon 1d2 nasties, everybody else just 1.
