### ISSUE TITLE
You can throw daggers in melee range

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#833]
It should not be possible. There should be also information message for old nethack players that you cannot do that anymore. There is -20 penalty.

Something like "You begin throwing daggers in a melee range but you find it very hard to hit."

**Comment by janne-hmp** [comment]
The penalty was only for bows, but now it is also for all thrown weapons and objects. No big chance in hitting by throwing an iron ball in melee.
