### ISSUE TITLE
Elbereth does not seem to work

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#834]
https://www.twitch.tv/videos/580025506?t=0h16m50s

Also does not work for me:
![image](https://user-images.githubusercontent.com/16661034/78280650-1af7b280-7522-11ea-84b6-26b02dd86c6a.png)

**Comment by TommiGustafsson-HMP** [comment]
It works sometimes, but not against Elf-lord. Is this intended?

**Comment by janne-hmp** [comment]
Fixed. A few problems: It did not affect mindless creatures and searching due to checking buried objects deleted it. It does not work against '@'. That is intended in NetHack.
