### ISSUE TITLE
Use current monster generation difficulties for Hard difficulty and lower them for easier difficulties

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#845]
We should also test the game on Hard.

Lower level monsters should be generated on Very Easy, Easy, and Normal difficulties.

Very hard can generate a bit more dangerous creatures.

**Comment by TommiGustafsson-HMP** [comment]
Difficulty level of generated monsters could increase by 2^(1/5) = 1,49 each level, so that generated monsters on Very Hard difficulty are 2x higher than those on Very Easy difficulty.

**Comment by TommiGustafsson-HMP** [comment]
I calculated the multiplier wrong. It should be of course 2^(1/4) = 1,189.

**Comment by janne-hmp** [comment]
Done. Used the last idea, i.e. 1.189 multiplier.
