### ISSUE TITLE
Add an item that indicates it is safe to pray (glowing then)

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#849]

**Comment by TommiGustafsson-HMP** [comment]
Maybe some sort of a gray stone or a charm (lucky object)?

**Comment by janne-hmp** [comment]
Done. It is named savestone. A pun on loadstone, but also tells you when it is safe to do something, also analogous to saving one's soul. Also a holy symbol shimmers similarly to add to its usefulness.

**Comment by janne-hmp** [comment]
Name changed to prayer bead.

**Comment by janne-hmp** [comment]
And again to prayerstone. It is bigger than a bead.
