### ISSUE TITLE
Add artifact gauntlets and make them monk crowning gift

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#851]
Artifact Gauntlets
- Give Speed
- Give Ogre Power
- Give extra damage for martial arts

This should be monk crowning gift instead of spellbook of restore ability, which is usually considered as useless.

https://nethackwiki.com/wiki/Crowning

**Comment by janne-hmp** [comment]
Done. The crowning gift is called Gauntlets of Yin and Yang. It also gives time stop when invoked.
