### ISSUE TITLE
Bad fruit #1. Program in disorder.

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#853]
Happened after death. Appeared after "You played on normal difficulty." Player: sflicht.

**Comment by TommiGustafsson-HMP** [comment]
Here's a screenshot of carried fruits:

![image](https://user-images.githubusercontent.com/16661034/78504945-c8640380-7778-11ea-87e8-03fce0150b8a.png)

**Comment by janne-hmp** [comment]
This happens when the program cannot find a specified name for the slime mold. It could be a name given by another player or an orc in minetown. Did sflicht find a slime mold renamed by a player (through a bones file) or loot from orcs in minetown?

**Comment by TommiGustafsson-HMP** [comment]
TTYREC attached.

[badfruit.zip](https://github.com/hyvanmielenpelit/GnollHack/files/4434629/badfruit.zip)

You can play it with NHTangles' ttyplay. You need full screensize terminal and even it can be too small for sflicht play. I think he/she uses 56 lines in the terminal.

**Comment by TommiGustafsson-HMP** [comment]
You can use Ctrl-- (Ctrl-Minus) to make terminal font smaller so that all 56 lines fit in the screen.

And yes, you need to use Linux to play the ttyrec file. Don't try it on Windows.

**Comment by janne-hmp** [comment]
ttyplay gives a extremely garbled printout the ttyrec file on both my local Ubuntu and the test server. It is unusable for playing back. The same applies to all ttyrec files regardless of the screen size. ttyrec from GitHub does not compile on Ubuntu 19, so cannot fix it either from source code.

**Comment by janne-hmp** [comment]
It seems to work if compiled on test server, but not if installed through apt command. However, it is difficult to get the compiled file from the server to the local computer.

**Comment by TommiGustafsson-HMP** [comment]
Here's a compiled version:

[ttyplay.zip](https://github.com/hyvanmielenpelit/GnollHack/files/4435794/ttyplay.zip)

**Comment by janne-hmp** [comment]
Also is needed libncurses.so.5. I have only so.6.

**Comment by janne-hmp** [comment]
Actually I got it work now!

**Comment by janne-hmp** [comment]
However, in this replay, I cannot see any error warnings.

**Comment by TommiGustafsson-HMP** [comment]
`sudo cat gnh2/var/paniclog` antaa:

`1586100771 sflicht: impossible Bad fruit #1?`

**Comment by TommiGustafsson-HMP** [comment]
Ja tuo Unix Timestamp = 04/05/2020 @ 3:32pm (UTC)

**Comment by TommiGustafsson-HMP** [comment]
Real ttyrec here:

[realbadfruit.zip](https://github.com/hyvanmielenpelit/GnollHack/files/4439127/realbadfruit.zip)

**Comment by janne-hmp** [comment]
Fixed. This was a NetHack curses interface bug with permanent inventory and slime mold.
