### ISSUE TITLE
Make it still a bit easier

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#854]
I'm planning to play on hard, and I would like to have it so that it is still a bit easier. Because in HP things are SQRT(2) harder, it would be good that in monster levels things were still 2^(1/4) easier. That means that the monster levels could be reduced by one more 2^(1/4). This way Very Hard would be the only difficulty using 4.0.22a/b monster generation difficulties. All other difficulty levels would be easier.

I want to make Hard the right difficulty to play for developers. It should not feel hard to them but normal.

**Comment by janne-hmp** [comment]
Done. Hard and very hard are between normal monster generation so that hard is a bit easier and very hard a bit harder than now.
