### ISSUE TITLE
New spells: Create food and others

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#856]
Create Food
Transmutation Level 1
Creates a food ration.
Material Component: Bat guano (or something)
Castings: 3

Create Fruits
Transmutation Level 2
Creates 1 or more random fruits (1 of very good fruits, 2 good fruits, 3 medium fruits and 6 normal fruits).
Material Component: Piece Wood
Castings: 1

Create Water
Transmutation Level 3
Creates a potion of water
Material Component: 1 stone pebble
Castings: 1

**Comment by janne-hmp** [comment]
Done, but create food uses either bat guano or sporal powder (there will be a lots of them) and gives only one casting per component. Create water takes 2 stone pebbles just in case, as they can be plenty, and potions of water can be very useful.
