### ISSUE TITLE
Monk to gain intrinsic protection +1/2 levels

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#859]
So that level 36 monk has +18 intrinsic protection.

Make to-hit penalty with armor -30 to compensate for the buff (-20 is too little).

**Comment by janne-hmp** [comment]
There is only one level of intrinsic protection, which is now -4 AC / +2 MC. You cannot adjust the effects given by intrinsics, unless it is level dependent for all. Should we change it to be level-dependent or create a new type of protection intrinsic that depends on player level? How does this affect Protection spell?

**Comment by TommiGustafsson-HMP** [comment]
Isn't instrinsic protection you gain from offering to a priest already incremental?

**Comment by janne-hmp** [comment]
No, I think that is something else, or nothing happens there, not sure.

**Comment by janne-hmp** [comment]
Just checked. It is not cumulative anymore. You get protection just once.

**Comment by TommiGustafsson-HMP** [comment]
Maybe change it back. It needs to be cumulative.

**Comment by janne-hmp** [comment]
Protection intrinsic cannot do it, but it is possible to make a new feature to the player statistic that implements it. But shouldn't there be a limit how much protection can be acquired? Does the monk use the same system, i.e., getting +1 cumulative protection every other level, on the top of which you can get more protection from the temple?

**Comment by TommiGustafsson-HMP** [comment]
Well, monk misses +4 dragon scalemail and perhaps +4 shield, so +18 intrinsic protection is quite ok, or no? And in vanilla NetHack, you also get intrinsic protection on top of that.

**Comment by TommiGustafsson-HMP** [comment]
If that's too much, monk can get +1/3 levels, making it +12 at level 36.

**Comment by janne-hmp** [comment]
Should the amount of protection from the temple or Monk levels be shown or mentioned somewhere?

**Comment by TommiGustafsson-HMP** [comment]
Probably yes.

**Comment by janne-hmp** [comment]
Done.
