### ISSUE TITLE
New Spells: Fear and Mass Fear (implemented from Cause Fear)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#86]
Fear – Level 0 Enchantment Spell. Targeted at single creature. Duration 30 turns. Simple material component. Could add more than 1 casting.

Mass Fear – Level 4 Enchantment Spell. All creatures around the caster experience fear. Duration 30 turns. Simple or medium material component.

Also, one could rework:
Sleep – Level 3 Enchantment Spell. The same as wand of sleep. I think it is now level 1. Simple material component. Could add a cooldown to prevent a permanent sleep lock. Perhaps, not necessary, if material component is right.

**Comment by janne-hmp** [comment]
Done
