### ISSUE TITLE
New monsters: Yacc (Yak) and Bison

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#862]
Yacc (or yak) is a monster type of 'q'. Yacc has a special attack like Umber Hulk to confuse you.

Bison is a monster of type 'q', too. It is very similar to Yacc, but harder.

**Comment by janne-hmp** [comment]
Done. Yacc is now the demon lord of bison (also a yak/bison form itself). Yacc butts and kicks hard, has a confusion gaze like an umber hulk, and can summon demon as well as 1d3 bison to assist itself. Yacc is a former lieutenant of Baphomet and the enmity between the two is immense and unending. Bison is a "q" bit less dangerous (level 9) than a mumak (level 11).
