### ISSUE TITLE
Secret bovine level in Gehennom ruled by demon lord Yacc

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#864]

**Comment by TommiGustafsson-HMP** [comment]
We probalby need Hell Bovine there.

**Comment by janne-hmp** [comment]
Sound appropriate for the demon lord of bovines (now with an expanded portfolio). I suppose they are like minotaurs but way more dangerous.

**Comment by TommiGustafsson-HMP** [comment]
Käyttävät halberdia:

![image](https://user-images.githubusercontent.com/16661034/78794860-f0dc3f80-79bc-11ea-982f-11309665da1a.png)

**Comment by TommiGustafsson-HMP** [comment]
Hell bovines should not be very dangerous, but they come in large groups of 10-20 or so.

**Comment by janne-hmp** [comment]
Done.
