### ISSUE TITLE
Beholder at mines end?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#867]
![image](https://user-images.githubusercontent.com/16661034/78896439-25153600-7a79-11ea-89d2-bc0efef8c062.png)

**Comment by janne-hmp** [comment]
That's possible if in the first round the game does not find suitable enemies; it multiplies the higher level by 1.5x. So (10+8) x 1.5 x 1.189 = 32. Reduced the multiplier to 1.189. Not sure why the monsters were not found there in the first round.
