### ISSUE TITLE
end_burn: ?? Program in disorder

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#870]
4.0.22 20200409 161653 1 D: impossible end_burn: obj gold pieces not lit
4.0.22 20200409 161656 1 D: impossible end_burn: obj dagger not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj sack not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj spiked shield not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj pair of fumble boots not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj wand of digging not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj robe of starry wisdom not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj ring of life protection not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj crossbow not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj pair of speed boots not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj belt of fortitude not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj dwarvish cloak not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj ioun stone of experience not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj ring of searching not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj scroll of gold detection not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj wand of make invisible not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj gnollish quarrels not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj can of grease not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj expensive camera not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj wand of magic missile not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj ducal crown not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj blindfold not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj oil lamp not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj magic whistle not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj crossbow bolts not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj bag of treasure hauling not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj sword of giant slaying not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj gray dragon scale mail not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj tallow candle not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj wand of create monster not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj wand of magic missile not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj skeleton key not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj prayerstone not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj gnomish felt hat not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj wax candle not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj amulet versus death magic not lit
4.0.22 20200409 161728 1 D: impossible end_burn: obj pick-axe not lit

![image](https://user-images.githubusercontent.com/16661034/78899147-a40c6d80-7a7d-11ea-911e-0a5b9751bbee.png)

**Comment by janne-hmp** [comment]
When did this happen?

**Comment by janne-hmp** [comment]
Fixed. That happened when you turned into a statue.
