### ISSUE TITLE
Throw does not list darts to throw when using sling

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#879]
![image](https://user-images.githubusercontent.com/16661034/78981581-e2ab3200-7b28-11ea-9e64-87cf878219b0.png)

![image](https://user-images.githubusercontent.com/16661034/78981600-f060b780-7b28-11ea-9b39-1505a2f53f28.png)

Actually stones should be fired with 'f' with sling.

**Comment by janne-hmp** [comment]
Fixed. This is now a feature only in firing, and that has been improved.
