### ISSUE TITLE
Create gold golem spell to use gold ore OR gold coins as component

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#880]
![image](https://user-images.githubusercontent.com/16661034/78981724-3584e980-7b29-11ea-94fd-cded41b80b6d.png)

**Comment by janne-hmp** [comment]
Changed just to gold ore. The system does not support using different amounts in OR, you can have only 1 matcomp X or matcomp Y, but you cannot have 1 matcomp X OR 20 matcomp Y.
