### ISSUE TITLE
Add charges to Holy Symbol undead turning

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#883]
Maybe 10–30 charges or so.

Also, make it work better. Last time I used it on a giant mummy, it did not do so much. It did say that the monster flees, but it still hit me. Maybe because it was blocked to flee?

**Comment by janne-hmp** [comment]
Can you charge it on the altar?

**Comment by TommiGustafsson-HMP** [comment]
Maybe it could be fully charged by dropping it on the altar and praying?

**Comment by janne-hmp** [comment]
Done.
