### ISSUE TITLE
Rethink fountains of healing and mana

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#888]
Too easy to gain full healing potions.

How about:

Fountain of healing
- Dipping almost any potion into fountain of healing produces a healing potion.
- Dipping any healing potion into fountain of healing does not do anything.
- Dipping a potion of energy into fountain of healing produces extra healing potion.
- Dipping a potion of greater energy into fountain of healing produces greater healing potion.
- Dipping a potion of full energy into fountain of healing produces a full healing potion.

Fountain of mana
- Dipping almost any potion into fountain of mana produces a potion of gain energy.
- Dipping any mana potion into fountain of mana does not do anything.
- Dipping a potion of greater healing or potion of extra healing into a fountain of mana produces a potion of greater energy
- Dipping a potion of full healing into fountain of mana produces a potion of full energy

Fountain of power
- Dipping almost any potion into a fountain of power produces potion of enlightenment.
- Fountain of power improves healing and mana potions by one degree (so you need to have one to start with).
- Dipping a full healing or full energy potion produces a potion of gain ability.
- Potion of gain ability does not change if dipped.

**Comment by janne-hmp** [comment]
Done, with minor modifications.
