### ISSUE TITLE
Polypiling too many real gems has a chance of creating Gemstone Golem

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#89]
Take example from paper golem and glass golem.

Would prevent people from transforming gems into diamonds for wishing.

Must be at least 4 gems, since Gemstone Golem drops 1d4 gems, to prevent the number of gems from increasing.

**Comment by janne-hmp** [comment]
Already implemented in polypiling function. Didn't check the amount of gems used, though.
