### ISSUE TITLE
Add a tool that can be used to change rocks, stone pebbles, and ore into sling bullets

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#891]
Sling bullets are weapons, which can be enchanted (what you cannot do for stones).

Rocks -> stone sling-bullets (1 per rock)
Iron -> iron sling-bullets (5 per iron)
Stone pebbles? -> stone sling-bullets (2 per stone pebble?)
Mithril -> mithril sling-bullets (5 per mithril)
Adamantium -> adamantium sling-bullets (5 per adamantium)

Caveman starts with this tool.

**Comment by janne-hmp** [comment]
For the time being, added a feature that you can enchant flint stones, rocks, stone pebbles, and clay pebbles. They look like normal stones, but if you manage to enchant them with enchant weapon scroll, they will start to read like other ammunition, saying e.g. +3 stone pebbles. They, however, always start with +0 enchantment that you cannot see at start (like they always have done). You can also elemental-enchant them now. This all works only for those four item types currently, but if need be can be extended to any other gem or rock type item.

**Comment by janne-hmp** [comment]
Has already been fixed as above.
