### ISSUE TITLE
Increase Dragons to level 25 so that they can always be generated

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#892]
Now they are 22. Ancient Dragons could be increased to level 40 likewise.

Also, one could check all monster classes that they can be generated in the end game, if there are preplaced units of their kind.

Maybe add Elder Elementals and remove x3 elemental hit points from the end game, too.

**Comment by janne-hmp** [comment]
Done. Created new elder elementals and changed half of elementals in the elemental plane to be them.
