### ISSUE TITLE
Flint stones are too heavy

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#895]
![image](https://user-images.githubusercontent.com/16661034/79038651-a8529b00-7be3-11ea-9d24-11b09a8eb70e.png)

Should be light like other projectiles.

**Comment by janne-hmp** [comment]
Lowered the weight to 5 from 10, since they do double damage compared to stone pebbles, which weigh 2 (arrows weigh 1). However, now you are able to identify flint stones from other gray stones by their weight, but you were already able to do so by them appearing in great numbers, so that's ok.
