### ISSUE TITLE
New Items: Quiver of Infinite Arrows and Pouch of Infinite Bolts

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#90]
Use: By applying, it generates 1d10+10 arrows or bolts.
If blessed, generates +1d3 bonus.
If cursed, generates -1d3 penalty arrows or bolts.

Could have a cooldown of 310 turns, to prevent filling dungeon with arrows and bolts.

**Comment by janne-hmp** [comment]
Implemented
