### ISSUE TITLE
Did Gnoll King join my party because of magic trap or is it a bug?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#900]
![image](https://user-images.githubusercontent.com/16661034/79040425-12be0800-7bf1-11ea-8932-83a9e6007c63.png)

![image](https://user-images.githubusercontent.com/16661034/79040428-16ea2580-7bf1-11ea-939e-cd8a221c6ee9.png)

**Comment by janne-hmp** [comment]
Yes, it was the magic trap, case 19.

**Comment by TommiGustafsson-HMP** [comment]
Ok. Closed.
