### ISSUE TITLE
Balance Summoning Spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#906]
Spell Level | Monster Min | Monster Max
-1 | 0 | 1
0 | 2 | 3
1 | 4 | 5
2 | 6 | 8
3 | 9 | 11
4 | 12 | 14
5 | 15 | 18
6 | 19 | 22
7 | 23 | 26
8 | 27 | 31
9 | 32 | 36
10 | 37 | 41
11 | 42 | 47
12 | 48 | 53

**Animate Earth**
-> Summons Earth Elemental (Level 8)
-> Spell Level should be 2 (is now 4)

Other spells likewise.

**Comment by janne-hmp** [comment]
Fixed.
