### ISSUE TITLE
Flintstone and rock weight, some new ideas

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#91]
Generally rocks and flint-stones are too heavy for slinging, weighing 10. Reduce weight to 2. They are just smaller. 

Add special slingstone (maybe mithril?), dealing 1d10/1d12 damage. Weighs 2 as well. Could be found later on, in large numbers. 

Also, add Bag of Infinite Slingstones.

**Comment by TommiGustafsson-HMP** [comment]
The bag could be the Magic Vein of Infinite Mithril (or whatever). Creates 1d10+10 mithril stones with a cooldown of 310 or 150 turns, whichever is deemed better.

**Comment by TommiGustafsson-HMP** [comment]
Can stones have +X enchantment, by the way?

**Comment by janne-hmp** [comment]
Created "stone pebble", "clay pebble", "leaden sling-bullet", "iron sling-bullet" and "silver sling-bullet" so that sling has more options for ammunition. Sling-bullets can have +X, rocks not. Pebbles and sling-bullets weigh 2.
