### ISSUE TITLE
Strangulation does not show in status bar

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#911]
Not sure but:

![image](https://user-images.githubusercontent.com/16661034/79048482-030ce680-7c26-11ea-868c-abc262a359f7.png)

**Comment by TommiGustafsson-HMP** [comment]
![image](https://user-images.githubusercontent.com/16661034/79050048-191fa480-7c30-11ea-8b14-32947ae3dff2.png)

**Comment by TommiGustafsson-HMP** [comment]
Or it does but one round too late.

**Comment by janne-hmp** [comment]
Should be fixed in the latest version.

**Comment by janne-hmp** [comment]
It is fixed.
