### ISSUE TITLE
Giant skeletons leave reagents upon death

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#912]
Something maybe should be done about it?

**Comment by janne-hmp** [comment]
They should only leave bones. Maybe it was polymorphed or a random item drop, or they picked them on the way from a garden.

**Comment by TommiGustafsson-HMP** [comment]
It was skeleton warrior level 17.

**Comment by jumakituno** [comment]
🥝🌷👽🚕🚭👽📠🎃🎗️💳🍀🚑👽🚕👽🚕
