### ISSUE TITLE
Spellbook reading effects

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#92]
Reading a non-cursed spellbook should identify it already at start (no need to finish reading it). If cursed, confused, or hallucinated, something else happens than identify.

**Comment by TommiGustafsson-HMP** [comment]
Maybe one could read spellbooks titles in a shop without paying to identify them. If you read it to learn the spell, then you need to pay for it. Spellbook will disappear like a scroll, if read and the spell is learnt.

**Comment by janne-hmp** [comment]
Normal spells are now identified by looking at the book, but not reading it through. Some ancient spells you need to read the spellbook through to understand what the spell is about.
