### ISSUE TITLE
How to prevent Wizard from Casting Clerical Spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#925]
Change +% casting percentage so that it depends on **magic school skill and not role/class**.

Unskilled: 0% + 5%/Level
Basic: 60% + 10%/Level
Skilled: 120% + 15%/Level
Expert: 180% + 20%/Level
_Possibly also:_
_Master: 240% + 25%/Level
Grand Master: 300% + 30%/Level_

That would mean that at level 20, the success % from school and level are:

Unskilled: 100%
Basic: 260%
Skilled: 420%
Expert: 580%
Master: 740%
Grand Master: 900%

Spell Level difficulties should be adjusted up from -50% per level to the new system.

Also, items which grant success % to spells should have toned down to prevent cross-school spell casting. There could be items that give you additional success % to spells in the schools you can cast.

**Comment by TommiGustafsson-HMP** [comment]
Maybe -50% is ok. Or we could try -60% as well.

But items need to be adjusted somehow. Especially the +200% ring should be toned down. How about +50% to spell casting per spell school level? That is,
Unskilled: +0%
Basic: +50%
Skilled: +100%
Expert: +150%
Master: +200%
Grand Master: +250%.

All items that are not armor could be like this.

Other items, which give small spell casting bonus based on armor spell casting penalty, could be towned down to give +50% bonus to all casting maximum. Such as gloves of spell casting.

**Comment by janne-hmp** [comment]
Sounds good. But the base plus per skill level should be more than now, e.g., 100%. To make it simple, rings and items could give +X to casting certain spell schools, not multiplied by the level. E.g. ring of wizardry +100% to all wizard schools. It can be used by priests to cast wizard spells, clearly, but not for casting priest spells by anyone. If there are general spell casting items, then they are very weak (like gloves of spell casting might be).

**Comment by janne-hmp** [comment]
Or the level increase should be 5/15/20/25 per level and the plus is 100 per level.

**Comment by janne-hmp** [comment]
One moe option is 5/10/20/30 with 100 plus. This way level 2 wizard with basic school is the same as now. Wizard with skilled school is 20 better than now.

**Comment by TommiGustafsson-HMP** [comment]
Or, it can be +1 skill level to all wizard schools. How about that?

**Comment by TommiGustafsson-HMP** [comment]
So, you could be able to become Master, if you are already Expert.

**Comment by TommiGustafsson-HMP** [comment]
If we increase spell casting bonus this much (+100% per level), heavy armors should give more penalty to spell casting. Maybe double or triple what they do now.

**Comment by TommiGustafsson-HMP** [comment]
But that would prevent a cleric from casting anything in armor.

**Comment by janne-hmp** [comment]
Done. Made plate mail and gauntlet penalties a bit more severe. Dragon scale mails are -100% (gray), -60% (silver), and -30% (other).

**Comment by TommiGustafsson-HMP** [comment]
Ok. Dragon Scalemailit sopivat sitten lähinnä ei-maageille. Mutta onhan
siellä Crystal Platemail maageille.

Tommi Gustafsson
Hallituksen puheenjohtaja / Chairman of the Board
Hyvän mielen pelit ry / Sound Mind Games
+358 50 574 7667
tommi.gustafsson@hyvanmielenpelit.fi
www.hyvanmielenpelit.fi
