### ISSUE TITLE
Make Touch of Death Chaotic High Priest spell?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#926]
So that you would not need death resistance against arcane (mage) spell casters. But death resistance would be needed for chaotic priests who are expert in necromancy. Example: High Priest of Moloch in the sanctuary. High priests on the Astral Plane (usually peaceful but can be angered via conflict).

**Comment by janne-hmp** [comment]
All high priests can cast Touch of Death at the moment.

**Comment by TommiGustafsson-HMP** [comment]
Anybody else?

**Comment by janne-hmp** [comment]
Wizard of Yendor and unique spell-casting monsters.

**Comment by TommiGustafsson-HMP** [comment]
Could be limited to high priests only, so you know when to have death resistance.

**Comment by TommiGustafsson-HMP** [comment]
I think it is definitely not good game design that Wizard of Yendor gets resurrected, teleports to you, uses Touch of Death and you are dead.

**Comment by janne-hmp** [comment]
Hasn't that always been so?

**Comment by TommiGustafsson-HMP** [comment]
No, because magic resistance used to counter the spell. Now, it does not do so.

**Comment by janne-hmp** [comment]
Done. Disabled the magical version of monster Death Touch spell. Now only clerical version works, and it can be cast only by a high priest or a unique monster casting clerical spells.
