### ISSUE TITLE
Add short description to every monster

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#940]
Like:

**Cockatrice**
"Slow magical bird with petrifying touch"

This would be very useful with likes of gorgon:

**Gorgon**
"Stony bull with petrifying breath"

This could be somehow seen via '/' whatis. For example, you could click '.' for more information on a monster.

**Comment by janne-hmp** [comment]
How about when hallucinated? Or maybe it does not display anything then.

**Comment by TommiGustafsson-HMP** [comment]
Could be disabled then. No information at all. Too confused.

**Comment by janne-hmp** [comment]
Done.
