### ISSUE TITLE
Align One Ring Wraiths with new difficulty 

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#942]
Should be now ( 0.5 x char level + 0.5 x dungeon level) x difficulty modifier. So that king wraiths appear when you are level 23 on normal. A bit quicker on hard. Nazgul appear in hell and in end game.

**Comment by janne-hmp** [comment]
Done. They now appear as per one difficulty level (x 1.189) higher than normal.
