### ISSUE TITLE
New monster description could be cleaner

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#944]
![image](https://user-images.githubusercontent.com/16661034/79215921-fb7f5480-7e54-11ea-8e29-bc210fa2b630.png)

Remove "e - eye or sphere"
Remove parentheses

Could be:
A level 3 floating eye: a floating monster with paralyzing gaze defense. [seen: ,,,

**Comment by janne-hmp** [comment]
Deferred.
