### ISSUE TITLE
New Monster: Mithril Golem

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#95]
When dies, it leaves 20–40 mithril stones.
Mithril stones can be slung for 1d10/1d10 damage. Weight 2 per stone. See also #91.

If too many mithril stones are polymorphed, there is a chance of creating a mithril golem.

Mithril stones should not be gray stones, instead mithril rocks, or plain mithril stones right from the start. Maybe "shining stone" would suffice.

**Comment by janne-hmp** [comment]
Deferred. Iron golem can now drop iron sling-bullets. Stone golem drops stone pebbles (for sling) and clay golem clay pebbles (for sling).
