### ISSUE TITLE
Wizard's crowning gift is spellbook of finger of death even though he cannot cast necromancy spells anymore

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#962]
Should be changed. Spellbook of greater magic missile would be ok?

**Comment by janne-hmp** [comment]
Done. Now wizard gets a golden chest with:
- Blessed robe of the archmagi
- Blessed staff of the magi
- Blessed magic marker
- Blessed spellbook of greater magic missile
- Blessed spellbook of wish
- Blessed spellbook of one of the following: Power word kill, time stop, or black blade of disaster
