### ISSUE TITLE
Dipping a poisoned weapon into water (water fountain, sink, moat) should clear the poisoning

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#963]
The same could happen to elemental enchantments as well.

The same could happen if you are about to drown in deep water but manage to climb up.

**Comment by janne-hmp** [comment]
Done. Fire enchantment is extinguished, lightning enchantment is unaffected, and cold enchantment protects against water damage by forming an icy coating.
