### ISSUE TITLE
Review scoring system

### ISSUE THREAD

**Issue by janne-hmp** [hyvanmielenpelit/GnollHack#965]

**Comment by TommiGustafsson-HMP** [comment]
The scoring system could be

`Level * Achievements * 3^(Difficulty Level) * 2000`

Difficulty Level is -2 to 2. 0 is normal.

This works for also games that do not end in ascension.

**Comment by TommiGustafsson-HMP** [comment]
Maybe

`Level * (1 + Achievements) * 2^(Difficulty Level) * 2000`

Could be ok, since Very Easy and Easy can be pretty hard as well.

**Comment by TommiGustafsson-HMP** [comment]
And maybe we can add Artifacts giving points as well.

But money and gems do not, since we want to use them for spells and other stuff.

**Comment by TommiGustafsson-HMP** [comment]
Artifacts could have this formula:

`+ (Artifact Point Amount Total) * 2^(Difficulty Level)`

We should check that they Point Amount is big enough to make difference.

Maybe the total formula could be

```
Total Points =
Level * 15000 * 2 ^(Difficulty Level)
+ Achievements * 15000 * 2^(Difficulty Level)
+ Artifacts * 75000 * 2 ^ (Difficulty Level)
```

**Comment by TommiGustafsson-HMP** [comment]
Nethack 4 based variants have this kind of scoring system:

```
Score breakdown:
  Gold:                     0                    (    0 points)
  Experience:              24 levels             (26716 points)
  Exploration:             50 levels   (100.00%) (30000 points)
  Discoveries:            139 items    ( 55.38%) (22325 points)
  Valuables value:      98200                    (16981 points)
  Artifact value:       19500                    (14593 points)
  Variety of kills:       296 monsters ( 77.89%) (26477 points)
  Turncount:           110061 turns              (-5921 points)
  Survival:          ascended  (score multiplied by 200%)      
                                                               
  Total score:                                   262342        
```

It is roughly 10 times smaller than in normal NetHack.

**Comment by janne-hmp** [comment]
Already updated. Obsolete.
