### ISSUE TITLE
Align Elemental-Enchant-Item Spells and Wand Enchantments with Arcane Spells

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#968]
## Elemental Enchant Item Spells
**Cold-Enchant Item**
Level 5 Enchantment
Adds 12d6 cold damage enchantment

- If the item is stackable, enchants up to 5 items. Enchantment wears off with a 100% chance.
- If the item is non-stackable, enchants the item. Enchantment wears off with a 20% chance.

Material Component: Iron Ore
Castings: 3

**Lightning-Enchant Item**
Level 3 Enchantment
Adds 6d6 lightning damage enchantment

- If the item is stackable, enchants up to 5 items. Enchantment wears off with a 100% chance.
- If the item is non-stackable, enchants the item. Enchantment wears off with a 20% chance.

Material Component: Copper Ore
Castings: 7

**Fire-Enchant Item**
Level 2 Enchantment
Adds 4d6 fire damage enchantment

- If the item is stackable, enchants up to 5 items. Enchantment wears off with a 100% chance.
- If the item is non-stackable, enchants the item. Enchantment wears off with a 20% chance.

Material Component: Sulphurous Ash
Castings: 25

## Wands
The same thing happens with enchanting items with wands. The wand damages should be already aligned with arcane spells:
- Wand of fire: 4d6 damage
- Wand of lightning: 6d6 damage
- Wand of cold: 12d6 damage

**Comment by janne-hmp** [comment]
Done.
