### ISSUE TITLE
Slings

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#97]
Sling damage should be 2d4, but no strength bonus. Must be better than throwing the rock with str bonus.

New artifact sling: Sling of Slaying
- has 5% chance of instakilling the target

New artifact sling: Master Sling
- double damage (double sling damage AND double rock damage)
- double enchantment bonus to hit and to damage

**Comment by janne-hmp** [comment]
Probably obsolete.
