### ISSUE TITLE
New spells: Flash Heals

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#970]
**Minor Flash Heal**
Healing Major Cantrip
Heals 3d6
Casting Time: 0 (does not cost a turn)
Cooldown: 2
Material Component: Ginseng Root, Sporal Powder
Castings: 50

**Flash Heal**
Healing Level 2
Heals 6d6
Casting Time: 0 (does not cost a turn)
Cooldown: 2
Material Component: Ginseng Root, Sporal Powder
Castings: 20

**Extra Flash Heal**
Healing Level 4
Heals 12d6
Casting Time: 0 (does not cost a turn)
Cooldown: 2
Material Component: 2 x Ginseng Root, Sporal Powder
Castings: 15

**Greater Flash Heal**
Healing Level 6
Heals 24d6
Casting Time: 0 (does not cost a turn)
Cooldown: 2
Material Component: Healing Mushroom, Sporal Powder
Castings: 12

**Prodigious Flash Heal**
Healing Level 8
Heals 48d6
Casting Time: 0 (does not cost a turn)
Cooldown: 2
Material Component: Ginseng Root, Healing Mushroom, Sporal Powder
Castings: 6

**Full Flash Heal**
Healing Level 10
Heals all damage
Casting Time: 0 (does not cost a turn)
Cooldown: 2
Material Component: 2 x Healing Mushroom, Sporal Powder
Castings: 4

**Comment by janne-hmp** [comment]
How about making normal heal spells like that?

**Comment by janne-hmp** [comment]
Done. Changed existing healing spells to work like this (0 casting time, 2 round cooldown)
