### ISSUE TITLE
New spell type idea: Protection spells that give HP buffer for a limited time

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#973]
For example: +50% HP for 300 rounds.
Or +30 HP for 300 rounds.
This will allow a spell caster to sustain severe damage for a while, when needed.

**Comment by janne-hmp** [comment]
Shuch spells should be somewhat easily doable, but each require their own specific intrinsic / buff.

**Comment by janne-hmp** [comment]
Done. Divine endurance increase CON to 25.
