### ISSUE TITLE
New Item: Expensive Handbag

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#98]
Grants +2 Charisma when in inventory. Acts as a bag otherwise.

Female tourists have a 50% chance of having Expensive Handbag at start.

**Comment by TommiGustafsson-HMP** [comment]
That's 50% chance of starting with Expensive Handbag and 50% chance with the normal bag with bathrobe etc.

**Comment by janne-hmp** [comment]
Female starts with an expensive handbag at 100% chance. It contains the bathrobe in this case.
