### ISSUE TITLE
Add conflict resistance?

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#980]
Should monster get a wisdom based saving throw to resist conflict? And some monsters could have conflict resistance, i.e. are unaffected by conflict.

**Comment by TommiGustafsson-HMP** [comment]
A new idea was to remove permanent conflict and make it temporary with charges.

**Comment by TommiGustafsson-HMP** [comment]
@janne-hmp This could be Horn of Conflict. You blow into the horn and it causes conflict (great confusion) among your enemies.

**Comment by janne-hmp** [comment]
There is now a normal item, a horn of conflict, and an artifact the Ring of Conflict.
