### ISSUE TITLE
Ranger Skills Change

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#987]
Ranger should be half-spell caster like knight. Max Skilled, starting Unskilled.

- Remove Conjuration school (no need, now has Nature)
- Remove Movement (is somatic school and not really needed)
- Divination: max Skilled.
- Nature: Starts Unskilled, max Skilled.

So, all in all:
- Healing: Unskilled/Basic (NS)
- Divination: Unskilled/Skilled (NS)
- Abjuration: Unskilled/Basic (NS)
- Nature: Unskilled/Skilled (NS)

No starting spells. (NS= Non-somatic school.)

**Comment by janne-hmp** [comment]
Done.
