### ISSUE TITLE
Made human skull rarer 50%->15%

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#992]
Raise Skeleton Warrior
- 2 bones + 1 skull = 3 castings

Raise Skeleton Lord
- 1 black opal + 1 skull + 2 bones = 2 castings

Raise Skeleton King
- 2 black opals  + 1 skull = 1 casting

Touch of Death (Level 8 is right?)
- 10 castings

Protection from Death Magic
- 6 castings

Death Spell
- 6 castings

Create Dracolich & Mass Create Dracolich
- 1 casting

Drain Level
- 120 castings

**Comment by janne-hmp** [comment]
Done.
