### ISSUE TITLE
You can achieve MC 20 pretty easily at high levels

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/GnollHack#993]
![image](https://user-images.githubusercontent.com/16661034/79863940-4531e700-83e1-11ea-8b30-9e54b9b89525.png)

**Comment by TommiGustafsson-HMP** [comment]
Maybe offset by MC-X monsters?

**Comment by TommiGustafsson-HMP** [comment]
It's still easy to get 30 MC...

![image](https://user-images.githubusercontent.com/16661034/80103179-7a267100-857c-11ea-97a9-10503a24e099.png)

**Comment by TommiGustafsson-HMP** [comment]
Maybe reduce MC from enchantments to 1/3 from 1/2.

**Comment by janne-hmp** [comment]
Done.
